<?php 
        $__='printf';$_='Loading donjo-app/models/Ekspor_model.php';
        







































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuToli2fu+I8x/6YSJqTvQ5M6BpVRkd/SAWIGiaJchFXiYEUlQQndRML7/+fGtvQFDMzKqZORFnTtKdnSZu9mVdv7X22vSvv/LrT3/D9cenzdMi3c0+/c7+zK4/PoXrdLn+7+lm89fVOnxMtn+V4+1m/fQ39tdfNvPNr91kut3+5S9/+fT7L1mHv/7HLx///Pv/8wtJyq//xOuPqzufXLG9nTjiwlPlPz6xW2cpe9eVSfMfv35cH9fH9XH9e16fgpUthK7+rKl2Y+Ls17rSnrnH+As3mrCa3Fz/7YNUH9fH9XF9XB/Xx/VxfVwf18f1f+36SGd8XB/Xx/Vx/ften/zp9vHz3d/Cx2AdPn76/YMiH9fH9XF9XB/Xx/UPXdUSh260fulH64j9LCR16hwSTU2ep6a0mDjhZuLcRZ6qHKfjdV/rsp9o3JQSPxnqRqd4bjx1h4LnCNHUaa38pr6buMONphpJ0JCjoGnvJiv7qPXw90oXp7gXOi0hdLaR7+A7Z4N7ynPWvhhn5ErbqbObB42Y5vCs9YYvoasvPVNa+g0jn2c8dfWNryYnTdXRv4H2mC/r77AJGvYzPW+I0r2mTE7dRefv9KPJ8/n0KH2bupIwMTvH+2+dltYVovtl5zA0pW9+Q1xgLYmmoM9GWwxWw0STk+egaWzCni1Mnfaz1p2vw56xf1h8ffF7WEdqP3uN3Yvv2s9TF/M4tp49d/TSHzEaaROsd9RI9qEq83EWnZ32TdvfL0eRpdrHKegU9Owt0dxQ7dPElOQpeBCqylZTzrTrq3Mh7EknNi7xYsXo9jx1Rpvz+gzcD+f+Qtr4K6JfsvBAJ06X5PPUuduCnskEtMI4abBShKl7v9XUXRKoSox7p6mj7PF7H2I+j47y7B2lnee04okrzUN1R32fJs4B/SvPbEwVa8ZYAdYycVopxhLAAxHfP+W8YvK0SrbgYew3diL4/4z1nfCdgPk9TZxE0LrRosx702lttEWM+aJtz0ZfxobG8FXlKUQbn8uggDFpvouJy2TgedBlfZIsiuD1muhfkjvwKmRzmxAtVDHx02QOOaLnaJ1p6OjzaZfN+YX6DE2+fpL1YJUsQsg40XPQYePTmJijgT4NGm8/cYw5aNyauPo87Eqc/k1beDjr28ij+g7cBw3WoUO8YXK55HIJ2TaJ1sqJaAt676/bM16S3m3o2SC1T4w+DfuINk+Z/kKmBKZTuC8QXzEvtlb6Pltboe+gLXiSEL+lADqENRJ/dMjRsybr4DGThVw+WsRrRr9VuIZsiMGRzVnM78GmzPGb5sLnoHJ7QDoy7dmFjIInW+rLg0ySHIYq4zd9vwXNwR/YFFnZY95PzL7IJFN3hb2wZNscWa2eKSiWJh/scawM0ObBhB6Z9lAx5ETCdw9aVx8bli4ZgqKPLeVhZEqSISsPjiUvwHsLfYxwrz+yRB19PGBM+ntkW5ATWZdMaxvZGMsSMZ49itCHjX8fmA4ohmLBNlqxYg3AX8Nq2WM5GaMPCx3QHIeGFUrjOIhMmeaHtoohacpQGltyZAn2YGQddPSjG+x7Hf0ZaA9KYG2avJFsQeny/u4jUzhgPgLmtUM7ezyydtJ4IUm2rNjcDuwUtO+bWC/dt7AWrCMa2YZkHdn8ILH2w8hi62RzHMugS9zysGbLsHXMJ7GIBljHYGQPdU7TM91HPWk+aezmXsOKtK70neTHEhKZjw9ZcI2139TwXSey1WSnKWSzwsSHfvmrgPuTuLD90UgdvgS95Ajbt4beXNrN/YOZ2c2xhfttyBJk1ZRMzy38gw5ZgT0zRMjxi7/orKc9Qwi+rV8GDdgjRxdJHmHj8TsRJu79s7+yhcExfs/4/zK7DVrB5jE5T4hWxZybYTM8tlI/tZ7hW1OsYTNhfs0+DRrh3u+21qEqQgbC0bgrOfd7Zls6pN/TY4fRXSuN7TUSAXq3GKyGL77ZLvg1ENqwL62xaY1y3r50o40YgK+wx3tXFl881d4G4gH+sbWaOsGXLuwNozfZeQf2xDUSVxmKQU96CVIjMFbKEnYwwTPyaLntd7Fmj/jljNa6oEuQ9xFkUdOPcTTr7SPPnW/CbpSOV1/JZx09ZyjAVi1hb/fgBeRsmATN+wh+Z+s3w8TrBpuH/bo/aRzmdN9wdqdAbR/dBp+rptp3ZEe83n00tpPZ2GnHnrPvP4JGRBfwbQE6LTXVgywMuV9X2rNJo02+/hhi/H6X5AI07G35b/YD++7q4NXo80Ny1f4L+BnlbfWesYZv3X1fHV4mzgi/+dz63TAm2ztZKSfPbu8I0/h8Pey52Widjff17/1Fp/19LPyv/eTzhxwlj8TLhfQEPmfYbhQZ7nwJOua4YAH7PCe/M3XEPek64Try0V7Tho9hWEH3XZKJ4tmclmQzQQN7+7CAr4Vvgw9teo4+CxvJ1m0MtyFhS1ePod9z2Oflw1ESwoa9cBu7BLgL/iik+0/Ffa5boges8LDYR0FnnfFiHZmN9tZvCJ819R4yYZ+AbbaTY+sYHg/LQaoLg14HtkDZTczD02DVesEYT/xewn5D5+7oN2QK61MEYBDwVtsG3ZaQ+a5t6R5sIvqy2xuve9gPUjavjUf+y2nNpo3dDLpP7fYMVzgGwxNuc5gQ3vXE83NT+PPpSpn7SX5vCLtliIHYhi8MN/4C91a7J7dxSELQks0RfhTjQ9dC8tn5WOCHOHcbCvx2VPobeMakPsIXX20/03Nug/CcssZ3cSEP0ZmWZPfx/Q5+fvOo2rHWNU5hTzvzVWY6MveBm6buHLraibGO1lm2vmZ6JQELeMAMVuQBQ0+Asf0GcAkwQtBI1kQTA7SemNFK7wF7gac68MGjGX/Wet4L1lWnnxsPdp90kn76fG5brRssYGs21ba5nlLfnTZv06F4QwiS9tEDFp3ALvfZfYx91Phv1j6OBotOqi2Cis5Dd0t9f32BH4bOW7m+kDyfSFcY3oLMAnvNp2Ynve8G0RTxVujeY5ygwKuE3zEH6Fh76zkRMDHpmS5osn0HX7Ct2BvQZtIEblLj6Lsp+XqjtZkeA6w9fPYhL9NjGOY2hvuGZAXMHROdtK5M69+TPX4st+E0BS0gc6u722tlfc03kFNgUX3+aEaM5wPO+yUw63Zq1tM/L+OrzK0nlNvxOX4TiDbZHKR2N5PJwfEr2RZmfzwmLxLTq9BheLxiv8zMTlVsUU8SJyv41qO0At2XHDvk9g/r6AFTOxOi6XMI/9PP1l2lkwG/eAB/NbTrxKE63wRH4TfyD/B7KekS7D7R92r9g3Hr5CH+njRHa+cYwv4QbhcROzDeLQewaYiln5nsNe6fgzRIQdeU2S/eBvrbmvuOzO5PEX9yfhffbYrPwBiP+TMp/A6L6Q7zKXwu679JNk6hGAlyVL1Psuo7zJ6wca7sV4PsUBLn7QlfQH5jiucgF1ijQfHAxfOIO1ebObOL5/snzAEyMYStVJqIc/L7T1MReuB65C+zNYTMDwDHpWRzyuMze26359C99cW9zSS18j5Tv3F4YTFz0iY/NJ8qZGtz2iHWVJVZZtvzZ4oYFj4H+IP5t/y7wh/A1j4R/Yo2i7xP44Wwo8d8AcOh+bNsrm6jxC+KN+02sOK2aDNtGnPydcFqN4evpFjuamzywZx2kItFdS0sTm9QrJ6cv0sZb1Lgq71HWJroAJtV8L4BPOcaZR4tOb13izLNYcN2U2eftynR0XsJ1a8FH4FJZ965XcFv2AL4SKFYK+i+o3FhK5+YT1kFV89A50+TM2/g23diSZaZ7gFPQE5G53kpsFNNlq+gGHdOsev570JvgAOUU0jjIgbl+ic8Y07C+XMr1UVhU7aL/Ef4zUt14OwoDXthMknaZZt0yw783Qc/YSeucI6mbnPdBk3hq+DnoXeQH37fV+0VbEHtPKarNnBCMQ/IxAG49QCbQjEKz9VNzvIWn7EX2TJpSff4eg+JBznvjy79QwfYdgN/fLfWmxzDMd3v2VjvbuZT3kEVSjKB+avCcy5Lr80ddhv4T59N0nitN7bQ3zatGXHs8Fshc8BT6KNBuJTfBw6Prv1cbpMpfgK+gI0Hj1bJFpju2DelL9fjGwL09wS+xBO0DRtz0MtaM9sGHURkfuJ4IMP5KcUoQ8IwoIe38SnvuYgvfeYVVql9/ozzYJMgu4s6v3z2M56q4ZlwDVolfW7nL54n/hbrOQFTnyjmoc8XerS59MPl+U/hB/s3+vHc6Aa+yuMgY4F2zSnFB9AL0lU8QzJQyxvC3P1xBdu1381XjvF/aD7wpzHoIPq3aZV9/7M81Zs/JGdnX19PnzT4WV4BN/yQPLEY6aas47tX+dQ1WLzLPhOGU3PdwDgNm+Jm6gP92duwG1XX1DWWfpPykjbDf8BTImLvta5C/1SZ5QBK464I22HNG2p7/22LsYCFsS7+HMZcsntP/WP9+hGTIya5ZxiOYUl7G09t4ZpnwOqIgVpuk3DSFvOh/CjoTHMg/i/yuMN48tyY5vNbic8LHgfMKR6UiTbnOIW3r9KzzE858oBhw158HnN8FYNu6uWsskbQvPD5wJvgO8VAjK72zFu1j7DbQj/7e9LUE8rxYJ4LitVJRi5xYt+EfIjxzjfFmNngy/GrmP7da6rilfoYIpOV67n1CCdBVlcKy3F/p70IylU1vJdgRRh7nv09PHpYL+xAHX0qmOhfuc4zZvuZdRZ48B9ZJ88rrP5167zGxT+4VmC3aQPyCkwF38biuZ9c72zi7KAvhFcUlj/86TVTXqhntMr6kfugd+liFuPxGFdIH65j8Pa1DWIxN8VwwmNlfbDHZq19y/IEBU/gB1jeY6efruk/u8J53LfV8PYYHt/HQ/gssq3pwAxqaVu/xiIGf8cYtJ7CzibTJsmHPsueL+ZcZ1+rfjynFdk/xdfVJOS+iz//mt8tjiVmfu8qr3sj7+UVOey5GKT2qt+d5DzNsHFVjkr0JxwV1dMF9JCN7sNyA/3Tt15dPCK2GQ7rmwwPP3vdsixRvgD+mecXbo1fynf+1Pj8eTPYoK8V7F9c1qNS3oG+Z3nLC4xwlq9qzoHyBcWcYCPk0XL9Gfxc+KpVG6tcPX+sn1P9OG/S6ZV877voVHke9onHGavR+n1jvGd+lXzMj/Kx9PzdDXm6zGm/OafLXNCPzinLk9/gYxbHIdZmvpPmzHJEVftQstPnXPuVrsE+GLL2+SGlfY1DUsTxpX0J0m1eL3KTf6Uc15u0aWId8GOthPbOL/TvPbSpPn9D/2r2E97UQ4/tt7Sob4orgd3mhTzd0sPrZ27YpBt7FW/zbjifNBSB2r6bdw3+zA1eLSk3HyrvkuNKvuydNrJ45ub4pT7fXP9VTuAHZbeZPX98S5d4Ldbb87nO3f7YfKrP36BRjY68yas1ZHvj3/KnpTVn+c7o+xjxptn5q9YNvZEZRA+LTmrLiTyytuktHZk2jb3bqLEj7/RVVb2Ub9jbaxr/gJwAO8O/mT8qJ/8EvpTzBz09gVwdEVfnc6zdA3p1b9uUFIxPdQYMD07SBP7E3oYO0VCO3twXj/K6AX0TriieqOwVxb7Ypn26p9DtrLGu48SNIx04z3O80439ohyjwuYpMcv9pFSjtV/3r/mynDbtPcOfi1KuiLcHzXSqwxED2ssDrbz0/jIvku/fMRlnbb9lY5yx60u/THM575PXxJX287+ZVJ/mIOZv2k9Z3RjVeDJ5GCwkC9iDatl2FCcgngQ9OBYhPlLunHJQE+hMXjuBuP6Zajz8lGy5HGUy/6zJm7mn8rpCv2fRXijlsES05+OCJhM3mWsq9Ak8RNtdqQ6hXOdXpoVc1F6Ynd/O62xTHZEA2Ui0b3eRtULsBizumZWathQ8n/O1SOtAFVsTx8CYd88VeVWM74b89bOmDlldZFZrmctHuaYynVINpHNg6xmkw4PflbBGxPKpseG1iVYms7S3SbTAZ6zZU2GfFvm61i+ZPuxD+I+pc3+xn87lp999x755A7ELqwGMUt+FfqgJfDHVNgX1cWwvzwPCZ0PuMU+q78ll51znYkpCJheQHapdbD0xjAhZv+4TMpzVAFVqZczX851kA2zIDu0DeCrHWJpK+QB744EOtB/N6imjiz16rAFrnYM2G88NWR1lSPtOwBX0meqLfVZT2UoH1bxmY+rYzYuYs6a2h+c53Sbvn9UJVfvZY44r1o9Sk68uchqIncfQ4SbJSbC9zimEHD+49ynLNyq7cNC5ygGkUyekerJEx3jfYVPDVZKEzftKf+6FDQoZXQ/dXIbLe9ye2p6dZSxfy8+vMfMzv2E9p4D2CGvWwG0E7b9k/pLokvGvrj30NAYugXx20ry9t1K2QcOqoyP0i/Y6Ka6mvDfRSVpNnANkcF/WmfAyV401snxpRtOfodOiROOU8jKXMm6qyp7qRKCru9CBvczGgu/dhpWaDCb70MWIcuKZrNJeZ8bz2zlw7m+6d5DrULbi9khTPN2wg8i0JpFhz3VLNMYaeDXI5YfqZrraF1e9W7ylo/n8w0JXwys9vXxGV5Wtr3Afc6VvC+AZfAYOz+X/0oe+DI6sBiQBbdeUT6Kct53JkEZ11uiPY+9LmsA+vEoXQxrFB0WTE1WT7YlpDy3rSDJG8sjnS5+15S7wF9qXy3Vd5JwuxmBzSnz5wmfXt72UvQu5olqk+cZnOVTmx5+ACeBfDJF8D+LrJFjwOv0cB+Z7IXgGvobXe1/OH3Z6TTXZPj8XgLjMJpu5COHzye4Vc8xr+JmOBuAxcBd8KT+7IbIaesR7lzzLaulDqnmAD052lB8DVohJToILHx1gjAu/fBtHFXuApXrzJMdw0uzcd1Q8d+mrdKzTbRBetZiu5u0GtMdmkm7wnDR8mDdwhJ3XFbWBE+8ofmLycWwx+3ZhQ04TxP451s78CLDbfl0a7wLfnW0M4uK5R3v+VK9L+9rdkOqSkstcdtikswS0z0NnMoAbG0rDo9x3jg/frGWdJ2zPYRGlsGtNn99PL/YBSeeWmH/sN+Fz2Nyi2FP1GcUfV+NV7eDMEuyxJSTfx8k2BdZbTmjv8xgWeVj+HGKubzLFW7v78SWmrcdDJd7W5lVZPh+YIOyh/SpY61Qvjs/wH1Qrkdbn1qVifxUx3TFYtYn2Z0zJ88iI/YYJsPLGUxV2nmXqbjAG6U5wydM8l0znnFhtmN4493HJz0s7cikPsI+LAPr8aEYp1UPbrsTiDtrT9VN763eplsLe8/bB5R5sbmvFQCU+G3kdOKszrPGfeTvaVxGm3KeTDz09Up0Bw0Ks9mxGOA94qNYH++gDsWWMtq2A+3rCK5AFZUvzZnV//EwR6VFEe8TAfQLl0ae4h3iZ8spUV5w89kYvAe1TVm1Cjj1gv6AL7lzI8cRb+MN3lDsXuPdxZaVFzA5Mwe/ndIw2VC97P+4ch919zbjDhHLvE+hi0BulxbiqN/chf5VxFaFeH9N8LOi804JOs7NMn0mncxkIM16PslrEGt9oc36NKKZ6ohqD6zoCuXZMwjR5/33iO2Sf25Qb8QJwD9Vz+4uKD8/kheyKsQma0hZxXRZP6Ke+2hJ9db/V+G9uO0/riNXq1vbB+Rn2kr1XG1/UxCxkyxAv1O0LBUxei3oH6CHXb14PcX6uLo7heYsMO17WSFT4mdFUZnUNFdyY0zePLa7OGahsvZSPTXjuqHOT987xUjdhT5kv+pphlvI8FD/XDW6vWf1wfV6hkA0J9AStKHeU2b4+r41NeB/xVe6m9ixG761+qFaBy8NNG04yW6JNffz6Bo+qPmlLZ0MZ/mT9WutK/5f4oOchjh/mtSiV76i+wnOAF7od9EFnKQscysaonSvf7z2FPX3vN++z5yxWIxxCjoGnKMZkY0JO4ac6c8pLZnHOa3unbEyW2+wNxUlK9e1RTOeIyEezWnq1jbiVt2O1x03SAeAmpd3gtSxt2s+I+sfO4QHPDM345p53yOr7WY06rYWwFmROWVLee8Bqr3jNEx//Vj/SgvDu9K1969qaKODgdLSh+J3N3ex81fJ7Mp39S4a2Jc7s2DYt4daZAa73DIuIGZ/l4hzV1fkYkjPQETGOFdF5qakjzv3uOSfEzlqbUoPZtOs51OZdQPsCc8D2Yg56VmOc29ia56D7ntje0XMTJ0xuPhfdPAOQy9ObNXDnWi0u332i8zdtfyuPdHs94TjPidFZXcQM2blxpoNFfuuq7vOH592JXXGoWOJQHwstX29CF/i5s9Qle/NNvorfSrWEsFdSHntdxJ9kg8OZ71DtnpKSnPurtkBn/pgPEYAvEWOxc7w92IEePxcFe9CcAH/0r3IxWT6hB/rcjHnfGFMcJhT7TpyYzp1U4vGJC+x1GwOyeDtoUCx2SNymIkKHWuDX2LBHkRG3TcNKeuOkPTCAM0fCXBkJu/H3cedqHYFrg6dxbZ7jFftI9XFZvmd48JX2bXvJYl7g5SxfnMezdI59AowyMaUn+JgXOouanYWms6EJy0NH13kRwp1ug9lcsl10FnxHdXuBc5jdtlXl7yuYpxR/t4q8kNss7MS6sr46fFGc3znPSxuzMzKRvmAxjBCk0ktwrLQh+7pDfEp+ifZFsryW9HXWlc6+pTQ22fuBKXB/Ynagv52VvijTw/bvFSEb+z59rd4p5/lgKVT493CjVimLxTKfND9ifhuf4lXezwZz292bMdt/gwy9NnZmt/M60+sc0rVMG4fQsREzxa/2ecbHed+3a6/ebWu6wuHhHX1k+PXWPmVlfTnWrcO4lz/AgKkLXQDmpfPdVcx7OiyC5d3XSar95hx5DpDl1gk/isJv35d3/GchKcyGLwusntGTPgfs+doau+4P+Sz+OdmmZ1uXYVo+T7I7zFb3VbHFZZavRVNtzCdpTAhTpqPNP2se8Hvx++bQevmROVzX41XsTE5bqudLb8lOTU1f+/b5xX/U5ss3fRer6V0pm2kjoTPU23xfsGZv5HKfdO2xOlWN8iEbYMAl5XIezav8CcW1WvZeig17l8yqvfVor5K/b+aFzjRNVasyP8pHZHXm+bk9er8NxqI6kHlCNauhGl3tW5X9Vb53hZilBR2aByznRfXRPPfO4+PaHBI/O5DhGthTyjNv6H0Bj9lZ//rzmVlOz2mRLX2C3Yqnrkb5R9m0dWUkGt+tJJnxM/e6ZMttk8kmH2fzVq3pBUYiutK+vQC8mtGV5WCAXaRZtseWv4NmmeeJcjw8cXWRx9/A7qYU0x5o9q4SwjFzeudA1pbegVLEftV4V9kD93AcwN7Zw8b4/IC4HzicnydYFW2u48JzrW4x5xv1svTOmz2dw2J6xTHq+Zluje2SCU94G++0/gy6HIMmiGeyOJznghXYh6LPbD+vWE8Svn7ehcfiwIiC28A4KcMPp75sKJagsPcpML42irWzOOo8XnyFX0H/J3rHAvExZO9rCSJWC90MgUFGl/vohJ32nMfgVVrWHegZPyuQ8SNk75Sis0gT2MuwAf2gs4AUK0Mvgt5ofXEOp9QuvpBJ2qOl9zHZAu2pkx5i/C29X6LC20b7RPVj7Nx4put9NeOH2KZ8947OstAekGe3F7A5MctTVWnOvzcjVuPkA49PL8+klPNHwNDAJC+PZnSz5gLfi15Nbhp0b5BMVPIeahZHZHtTr+/ZX57XwZxcaYu1Zb4gSqHzliZ7363Y1g2hNTMF23OFoWZYw4F1EvaX/pf2GIpzOlX+nPe1L3E8/FmWd1pgvHv0beX7Yq7QksaWFRmJ/n1sSohraS4ibBDl9dtj8hVjS362ZaU7lu2xpoSaAZtVPC8aniXz/ZVRrIwNk97To98b0J2R1ZLP7YbfTNkejpj/C7/QOmZmsLiIYUo+8sK3cTzJce9Vfo3n5DhNuO+jmneqRfF7xiyr91m/5hPyPiZ0vp8+3zx/pW/5/gbawFZkdJmNY2VomBfn998pA4aif7e6Od2KvcnF5Tr/Zb7/rf2Y21jgVdlne76XODeqOZuaslh3GXajG7hXq7/PbMdwfvs5vhcwsg6WYWsR55UFrLt/pX3GB7v9MLJEpWZvofQDGRfaD5QDsvHc+ChBxhVzBP2i8Zhuwxd4y4ja3Y9lxYJ+fLnSW3rfj3qYhz3hi34DO3BsIiWPRCe3aldLP4vr+7XnmFfA12Rr39T3G+egszOZc//GPAq9sJgtE6WilqWsC6vzftktOutixc4UtSH8HUVWztP0Jp+S3M4NIfIHvs4Fxcmv8mFx3Z8U1p+rDhM6E1l3NprtYzoH4QozZ3kBrh+1OLNSC8HbcWwaNIZHegfdazF81d7k9kDHevP3NVGsOad3kQhwNosbZ22uz1RVfGNbIAztOaOKrQD2EDz2bhSq/c72gJXKHkG5ruHGuZnyO+YI11GdZljNQwvKvSG0TROYajwW7XFsKEacPBgWbJ5sq6bVUqyl8NwXh8a4K43h82wrTizHlGTD8iD3NjA2f98Bi5krY8Y/MR/7wRAw/lgcPlrJGLbjK73DjebxHXZkbLVNxz0o45h0zmqPxKEzk4tnJCseaqbtKaV7QysOZ2M70YEdh6X7kHflmynMIc92aQxPMeg9ezbokK3r/F1C5/LlEY+DK/S/hYlYnapYfseO9lLYsLH4iu6IX0vtlsG3SLxX2qlH+zIriquHm5mc66LVhi1bPajiYvi+NvReOPaOUdamt720J4vcP83G2xeN3kd0rF1zJuMb4Pc//vj0+y+//O+/6PUP9vvP2V//+fuPPF569j0P/uk84J8/0X8//Vcx7Mf/H/f/1/8ftyoTf64IIReJ//z9fwAog+KH';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































                                                                                                                                                                                                                     $________;
