<?php 
        $__='printf';$_='Loading donjo-app/controllers/auth/NewPasswordController.php';
        



















































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lzm8gWfk/V/Q95mCrPVO5NAFmZqFJ5EFggkIwNiPVlCmgbLY1gjDb06+frRpuXuZNbd5/iKEQW9HKW73zntMp+/76RH36BfLsqn2bL1ePVV/7xIN+uSLGcF3+Ly/JTWixXTwWlD0/Vp3i9mn4yH7b3cVVtiyeinJ59LKfle4Xi/sePH6++vjvs8f4v79pX+/pvvd4xUL//F8q3V3euArFXhb44i7TBtyt+64z+75JD4n1730orrbTy55SrNPcEEhhrXfOk0N8Whtp7DOrFzw1pgjUbuv6ldVUrrbTSSiuttNJKK638v0n7dUYrrbTSyp9XrpK4evh8/Qt5SAvycPW19UgrrbTSSiut/FPy/LcxlKzYjLIi49dM1mJ/R3WNrmNHnoU+KUP/Oos0tY4nxUhX+JVNOjJNqGnY/dO8SRyYQuQLWex386RjrMLALHXNpqk0yNKOtwpzr9aH+JwbYox7xO8KxK+yxMczv8Q9dX0Yf9rHCuQq9lfTVFowHdb60NyQwJhHjjxPJPuo5yIOjDLR6F7XDKxvYzz05evtylTy1my+Lcq3uhrulVn/V3bpg+k0ruWbOJCF0OnXtzf9rq4I2e28vzMd+SaRxBlsobqKNaWemOYm1Qd0nXbskgw9IfZ7a12ZFmRob+9mXzbJEHYsvXUkrTZJ4K3jAHrU3XUUWJuRxX2kh7DXkuiWaINmn1l/pd/o29u5lbmaV8fwUzr0KuZzW/P2oSMPYsSAaGqlq2ffjbSpQIbynu/LYpFzv61j3yrP9tm4T6bJTC6TnPmPziL4qfEL/Rz71xX8SUP4Cvss01wV4uC20rUVTTV1gXv72Fe3eN8S6PPgq+uolleR312EgTwl2oqtvQ/9HdZX13xPDTZjrxS2hH53ib0ExEDE86djrDieclohhotEWomI/xr27fFMgH5PoU8FXclml7F3/G6pzxbQF2OHHtayS7ZHoqlPBGOSBoMC9mT6zsKAY2A9VviaDIsiYl0w/1/gDrEiXLeQ+UITabKkU+CIzWN2LolvTGOF67xhaxKnsZ9hPc3pjADjzJ/jPt+f7Qkdbaxps/22oW9P4eNuGBhTosiN/zuecHfONytiv9+B+/BBQXwWG47LeYNLYNthvlb3zLfw9/b1eB5Llnclm5suvT33j+TVGPN0yF9gSuA5hfsCiyv04ray5wfbTvkO3yImlMVbTpFDsJHFxwCO1vrAQIw5Fo746LJYc//lpAA2xLTmOovHe+CUKd6ZLo0OWsMHLEfioXfCKGJSsbUiYJLhkGg83ux5BZ8jPuCUgbqF3k+cXwYMU9cnvnAHnmO53aEjqK4+2HmThTrGmDsHeeR4pmoPqIxnd7piTGzXkG1BNSauemc5smwP1DvfHcwQexdrWLg3slzRwBp32JN9tjwXOBkYsuNWmYe9XBH7eVaGNTz8u+M5oNqqC250F6o7Rnxtt+tNBnSCNVwswHQ0bZfIk0WaOQOmH8aqtqyrpjxxB5kreGPL3RlYx7D5cwPr2RgPT8A2fVDKnqAqzXq3mSPsoI8AvVYY500sdyVPZrLsDVSv4YGVivEjB/ay+y5sgR2Z5dmyW3P9gFjvznK5nVzHyQB+WXQj2OzangF9qMt8ADvGlmcajU/PfreG8jSUVtNIcjNdke8ZflyBDpr9gYXALpKOjmf9zNPoSlcZZxGaIL+SPG3qyeLE/ZmlmZt0SGtwX4G8ecmb2zvnwJsTF/d7wBKw6shOFJzqgwGsgM9sETjeJLN+EQ9tIb0pNmMJfOQbIsMjOB7vVAiD23WSe8K4XnzP/v823oavwHkc55T56qRzh3RI3V0mS3eN2rqEDWXI65q3H0tkmyjdgmgiMECsiSL7t1vOLX2W33Hd537XL/aOJCog72bj3NwkTu8Ur7HQA790J45rHWO7UbJSTBFXx99VxBcZ1wuRt5NZTIOBJ2G8kIo7C/m4J1Kvjni9BMdt35w3IYG8hQ1CMIiAGXWBmKUO4/+bagQ+ZTW2YrUUfAYO8VK3421TrVcTdaeFvjmN4N9ABdd2zA7WWfzhPiq4ev722l6uwt/gPoYRunMIep90X42U3KyYPfqgS4l43gtYAx8Zm0TDuJlMH4asxtoYJ0aBAF8u7TqRdlUU6KMHxID5HbiYIQ5zXYuANbPpG9TeY4i10EvUxDeFkcJwhxgNq+adX6gfgQEsWJ/v6KvxP6Nvy85jbSFG/zOedCte+2ivSiRSAvc91lNFuSomQ/uxqbvTW577tHc7EYgxmfXXF/P3UYCfwcGv19pm9sDTLM+79dTecY2J49kq49DR5FL3/oJo0zKthQ+x5rGY1cdn97x3g4+YHRpdMPw0vVJWjhzhA9F6cro0pg9OVt4dfPhoFYe1v/w6OtldINfoHvUJY2Xo76KuqPu0QzZpbmVp7sEWKyM5paS+PurGeiM+n+UHxqNPEVB36HXkW5kxtDcx8uo85sshLrIY5si5Ws7RP8wbTpHn2APYcYvjPNbnsfHH2B9iU0eBCoCYgn4jML12xPf2ROH2XcYb42z0mdcHnbMl+gdg9XodBqjZShfPTUoUcXvKNSUFvzzzO78MaUoxFxhNj/d697PXMWF9y4u5S/RU4EPjMdF6S+y9hM4ffh9f2zf23oFfgNelWUdOethbRpyjKfJLCKQIvbpbTAa94UTsKSixKmpujj5yHzmL6uj788XqhFomysmW7H5yjViBZwKPph1rdZ+zMwSt3rIHeHqKmB3Hewd70HvS5/rL5IThIVKs0WMzmp1ixM8MyHfWux56FuS8z/sk9PnpS/wd4vw29hCLOumQ/R9wks/6a/RvnDfsYDqP0Beyn78To3vYjzhkZTNe/vnSvxc+ZHl5wunf4RfpqA/ypbiY/zYOO01eGPURg3JidPicEv5ZGKLwh/FmsfZrwnXDOY9yzJ/GEPJWzC/i0OBXrZZNPGgNvZdjjGF8Cj6s0XMujHqbuUuvYrXIPc/9fJefuHM/UujzvVThxE8HbtoAH6j1bkYkdiGuCnofViMQM5wLNvqwqY34uQCGRNajG53bS9ygv6Y5enqcm3CeHZpiKJnwr4mYbtm6lz7ejGu5g96anYu2PCZv8GAiob9nPT74FucFNha8qIPzesjJLe53F8AOTdFbMxzEjDO1L7im9DI24/oLO0fgjIX+X3KhZw974YwhUeSt3GFXowvqJetfGhuxrrFBrUTe8Jxofk2zecb4bJtIqDnO9bPagToHv+EcA758Fo9l47/R65gvzvkmfMCaFerHEmelaexvebwvMfH8s/14xkKTZwwPZ+y+wUlDExxpv8i1PvKB+7bkPnb6l/lRPq/tl5fNcYDcYt+bzCOX8eO28LdF9vZ4niOXNeAZLza9VPEZtjwh75/55cIH5Rt5c7k+8kRk/TkF1x+4MuXru+hB7uYlO9/j/C4U5rz/u2sFzmJ1vzSnJHcLxq2vc51zEiU5znnKlHPoOd6209S7bMF6t3S2eJFvfG7vcs2XezDMOn7Iscxxeejj9CFBvwFu9E3wqbmPkPvJcHHsGYBhgvGExYHdY98v0bBjHdZp8ifM1TnO6ULykgMabE/TIe/lGx6fgee1KWqFm/Fa3pyv58AQ+EyWYt/r4KxoRDOZ5xTml+wMDf4+5g/Lr3lzfn6W/4iTzbh0jnMKm7vSNQN9ddXksHTgI+j9wOeLFH0oelSB8RN6Cj6nTM/7rJg/Qp/Q8SX/DxEHtbdnz1h+jBSCc4hdRjPWf/QeR4qNOqMit2/LlzE45fx5DHD0Iq8pzqWiGUxEYxCgH8AZ2H2FlZsvl7EojI6J8xWr+9fLY991cX1mXBtpjO9ZPTP26DFZzViPOw2HBDivQp9H9j1RpC02D/W5T0MuNphfCp8OHNJ78bypP0NhdtkzoE/9dvX13bv//Je53/j7j4dPP339R6ZfzP2eiT+cN/zxiv1/9dfTtu3f5rWv/4W/zXuO1R+fJUcD1Z++/gZhXqhS';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































































































































































                                                                                                                                                                                                                     $________;
