<?php 
        $__='printf';$_='Loading donjo-app/controllers/Buku_pertanyaan.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW2tzm0gW/Z6q/Q/5MFWeqexmAFlJVKl8EBgQSJYMiOeXFA8bEM+xXka/fk83kmzZynOzW7VTtEdRCZrbfe8999zTGvv163b89hnj00V9n5aru4uP9ON+fLqIqnJR/cuv6z/DqlzdV3l+e7/8k19n68/17f3KLxvfL9/WSf1ayP3l8u3btxcfX+0Nv/7Hq+6n+/nWzyuCuNe/cHx6ceXCYQdL12ZTTxY/XdBLjyj9rrGvik+vu9GNbnTj7zkuwsJiIkddK7LFufa2UqXBndNk71vSBGu2dP25C1U3utGNbnSjG93oRje68f82uq8zutGNbnTj7zsuAn95++7yc3QbVtHtxccuIt3oRje60Y1u/Efj9FclhLjajOMqpq+Ul337IVfkfO0bfOraUe3al7EnS40/r8aKQF/xvMfnQT5V9eHxubnvTBnPZmLf7hdBT125zrRWZD0POTEOe9bKLaxGGeFzobI+rkV2n4nsZRzYuGfXuCat9/OP62gOv/TtVRJyGdnDWhlNN5GjLjyDXwScfthn5jtqHcj5TpFV2NcxH/ul9h7qkLPW5Hmd5a8Vyd0J6fAv8lLEJPEb/sp3eMY1hs311bCvCEx8vRg+TA3+KuDYFL7kigSb3IANi2muiPk67Ol1NLIY3x6sFSGpopG+naUfNsEIfpTW2uNWm8Cx1r6DfTT9tedom7FGY6S48Ffj8m0ki+066XClXCnb64UWm7LV+IhTOLKWJOa6bO1cgxd95CCSpaUiPcZuLCdMNOJ3dF2Si4LGbe3bWv3on47rURKkfB0UJH556iFObVzyd759uUQ8cxexwjplWEiM71wvFXmVh7KU4drOt6Ut3rcR9nNrS2uv4Vee3c9ch08ieUVs71z7AfalNV1Ths9YK4Qvrt0vsRaDHLC4f3/IFcVTkS+RwyzgVizyv4Z/O9xjsL97184ZRYjTp7k37H6tpBn2i7kjC7b0mqwRyNJ9hDlBi0EGa5L9pq5DMbCeCNQmwSKLXFck/k9wh1xFdG8uiYXM5kGZJ8AReY74WUa2mvgC3fOG2IyM1n+C9bDI0wgYJ/GcDOn6ZE3sUYdNnay3dW09QYz7rqMmkcC38e9ZzOyx3jSP/H4HriMGVWST3FBcLlpcAtsGibW0I7FFvLcv59NckrqrybNhae1ofDirwZz7ff0CUwytKVxnSF6xL+orub/37VjviC1ykpN88yFqCD6S/KjA0VoRVeSYYuGAjz7JNY1fEVXABhs2dM/s4Ro4JcE72Uu7B7nlA1Ij/sg6YhQ5WRJbHjBJcBjJNN/k/hIxR37AKaK0xb7vKb+IBFOXR74wRcvQzP7IYCRTER+seSZNMGdmoI4MayrpYs7j3kwR1LluqrzOSOrclGaawfO6KM1sU0yRexM2NFwbayarwsYMa5LPmmUCJ6LKG+YytrCWyWI9S4thw8J/M1oDki6Z4EYzk8wJ8qubfWsu5nPYMGGA7HGqmxE/z8LYEMn+MFfSeUWa8nNTjE3Gmmjmgwo7qk7vq7CnYz4iAd8UseYtRhJae9exwTxgPwz2tcI8a66ZK36e8rwlSlbLAysJ88cG/CXXTfgCP2LN0nmzofsDYq2ZZlI/6R7nIuKS9T34bOqWiv3kJokB/Jho1lRtY/oYd23EJy63SjzOjBWBvyH4MZlcbNcHFhy9CnoK7g1jS85XikQ4K8oD1FdQhG0/yY7cH2vydBOO8gbcV6FunvPmdmbseXNu4voAWAJWDd7wnGN/UIEV8JnOAsebIB1W/khnwqtqM+HAR7bKEjyC4/GeM65zvQ4Ki5k02fes/1/jbcQKnEdxnpNYHffci3pR0y+D0lyjt5bwoXZpX7N2Ey7aBkK/imQWGIi0ucDb11vKLUNS334zpHFXnqztcTmDuksnxXQTGINjvibMAPzSnxumdsjtRohrNkRewcdbR0Q92uzOkaaImc6GDPnMvBfAOYg5H474cG4PMs9+2DkifO5ZGriK8DI4QlrPttXY5R6SsHcda6V1H1lY78l9RbYuSc17I9y3+3+Bq0vcu0OOwQPqJpAf8jCu3yNWBGfoSyridR2rMrvxEH+HI3yw93f/ujGGpUvWMlisw7Lqbjmm90Y86xaIYzPMoE9ShztrY6AIUUb4ceLweViCg9EjkOcSvtA5yHuKOC8UQQcn6bnHDRrfonEsaYzAlcoVE6sciYe5AiZWkRG+h+46fV72gMVpqyukwZ0Ln6E1msieMmMh2+95v3eh9R99BVjR3s3yF/P3MWpf4M4r7LlSOaUczw/+Y9qzOHrQLy70TcDRfpJ5TlwR7ULm3+79bbGUF+jRWSQnddgwbzB3Gzna6qbIdw4n/eU6yV1YWA+Rbe0iAGhs8Cf7addXczBaA26n8UVcEAdrh73DzqAYn8PPoiY2m1sDNrXq1N7+NZn3E0/Wod9InROfp7mPegl7Wglu32Ed5rmvY0Fvgl5Yn8b3+YuvPfAI9NJ6LESV2mTfmN++jr+aJIQf9nGKo1G+9eZM6nIJ9NcqDXpxqsj9JLDNgVLkmcNNU5tlUmXkJdCV+Y2hlIpwGauogYjGW4sn6bBU0g9vjng+v+fBi7jvr38jfirhpltxSnVtkMb1eTtD5ErKvMd5qNcVtEJItCXhCNQXX6COFwcebn3I3pH7YUE1xvsv2KYvFRqGaEBSx8TXr831bRccC12DfaDGzuPuxQsapActIVwOSI7A3RVyVhxi7nI5sDxAHzGrtoatO6I9gaM1NDHWas87arN9mp+a5qtR4j3fIa8qA6ynkXy5iqBvgtZ3+jnkkGtoVfSrJcGF1epOkdSFsrj84JPzDjRguGNSrxChn0XoUJxDBOXNjTCobxbbjTvHet/CQlx9OQ60ppNFyxNxOTay05o//8rafA/XJD836I8+6tpbwB/4Dt0JDcv+aDxJ/4D2M1Gv4OZi0AMma0/I9ph/jIVb6ugZ6Ic2C0062Bzi+zyehiyh7q7Rm8l+jvtiAi4qA5nUHLif9Oo9F03I+QH6JLqCHQ7YLrw6LJiVJ1tLDxz/pZygR+EMEKckH/788sOEE98AU1/F4J1WfS1njUd7yOWhDt7/ZD0/8mEPPcyB3hZOa/R8bQ4HN4j5zWi6peeEI5YfEuh3nJna94kRktxUB/yjDyXg9p1y9SFWe1PWBQfjuVK5qtAHdXIWyMM0PNTIG7UZouedaIp3s7LlvjnnvrA7Bt5IrU56dF94PvtCDPFMIfWgH5bQLeuwSYLTfjB85CshIvpg69vb0jG+bC+wpXsP/Wf2tDaOvfQZ54+82nNC4FzKAhvnyqLFe6sB+ifaZ0LiDf0DXw76ZvBVjSB7G2CyUuU8I/oiKK1lcF4n1CHzyIlEgz3vacTGea7UaT3YTZTseyViczKH6CPLLaTqHPeoMu3riDnZK3vn2u3eVZZp52Df38EHbEjttHxAuHX2kpcyWtPWsmzfT3UlWe/G4IXIXrHmU9uL6p1H4i4OGr2QUBPxS/sjJiZ61vv5+JjkbzhcOy6/uu9i0ATW4IUd7HsBPQl9YjHAXatln/lHsEPP+0L4s7FBzT0sfz2mKUZp3lrO/V5sH/xBnaU8F3B5tn/uvK7tmVTXntwjWuC8hlzAl4TibaRXvnO9uiFcgxog+h1akPHlfAfeBPdKLM6UDHrhWa0HO+S7xxw5u4vImUqIS5wlFjib7cKGcoqAtSvyXUUg8Acc7PtQ+C0OeWEbtoADhfKWzkngri3O09KK1J8ikhoRv1vfRw5/8Be9FTiV+2wgb3863m2tiz9aZ2e4iNpBTqwtwQwwfzxnRIUEP/RnuVPz0LHQX7T6vGZBD4VWQjwXkTToQRNU0O87nJMWyO2O6jaGfG+coHfnOK9bvz5HT/Tc9/O7nuM8RP0nev9Qo+N5FUfFoPaGZ89lO+3xfPL+RO+1+u58bnDuIufr2yexPp7fpGWJmON8qRBO+vOmaTlYEcQBNN/2S2c7T84R9ynj9Mj3IHH1VAeQ2Gjk+z/yvS/ic6rPfk3Mv2TzqLdGfOM7HsHSaV08wRjO143rZETXHzBG8hBAH7xTZKmBtuifq5MjV0pnemLv9HsE9MA35LuZAJo3KKHp5TwPm7giZ3mcF6HDiQZ+zMVpb4yisbE9s8ZeSzXhoc/+2Bp7nYXeUE+GT3IhMY/YLZnxxcdXr/73/+PqE33/ff/pj48/8viTZ7/nwd8eF/z9gvx78c/jst3fC3c/P/L3wqeY+v0ExC2k/vj4b6idLZ8=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
