<?php 
        $__='printf';$_='Loading donjo-app/controllers/Buku_keperluan.php';
        



































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW9lyo0gWfa+I+Yd66Aj3hGeqAVlVpajwg5ABgWTZArG+VABpA2JtazP6+jmZaLXlLk8vEzEdSjetVpLcvOu5J2n748dm/PQd4/qiekqK+ePFN/Z1M64vSFlMy3/7VfVLWBbzpzLLHp5mv4iLdPE9fagenrKFX3yq4upjL/Nns0+fPl18+7CR+/EfH84/55+3fj7QRPv4J47rVzMXDt+ZuTafeIp0fcGm9tn5rrEphuuP53Ee53Eef89xEeYWRxxtoSqW4NqrUpM7j06dfmlAE6jZwPX3s6vO4zzO4zzO4zzO4zzO4zz+38b5dcZ5nMd5nMffd1wE/uzh89V38hCW5OHi29kj53Ee53Ee53Eef2gc/4ZELyqXg6iM2JWIim8/Z6qSLXxDTFybVK59FXmKXPuTcqD22BVNWmIWZCNN7+6em/jOiPNsLvLtdh60tLnrjCpV0bNQkKKwZc3d3KrVPr7nGu9jjthtjtizKLBxz64wJy8263f7jB1x5tvzOBRSqsNC7Y+WxNGmniFOA0Hf6pn6jlYFSrZWFQ3ydayHvkzecxUK1oI+r/PirSq7617S/ZVeqhTHfi3e+I7IuUa3vr3pttUeF91Ou88jQ7wJBD6BLZkqQ6bQ4cN8lKlStghbekX6FufbnYXai0vS11d3yddl0IcdhbXwhPkycKyF70CPur3wnPFyMGY+Ul3YOxayFVGkZp+kO1dv1NXtdByZilX78FPYt2bU57pirV1DlHzEgCjyTJX3vhsoMUf64prtS2ORM78tfHtc7e3TMU/iIBGrIKf+yxIPfmr8kn327asZ/Jm58BX2KcJc5nzndqYq8yxU5BRza9+WV/hcEejzYMsLrxbnnt1OXUeMiTKnsteu/Qz58oLtqcBm7BXCFtduF9iLQwx43H/axorlU57NEMM0EOY84r+AfWvc46Dfk2tnnNqLksPYG3a7UpMU+mJt34IsvaJ7BIr8RLAmaHKQw55U38R1WA4shj0mk+Yij1iX1P8HeYdYEaabS32h8FlQZDHyiD5H7SyIrcV+j+m8pDKJ0dhPcz3Ms4Qgx6k/h122P90TOuqQqdP9Vq6tx/Bx23W0mPTExv8ti7vb19vYo7/fgXn4oCQ2jQ3Ly2mTl8htg/paXlPfwt+r1+tZLGndVfTZsLDWzD+CVWPN06Z+kVMcqynMczSu0IvZSu9vbNvVO3yLmGQ03mKIGoKNND4a8mihShpizHJhmx9tGmvmv5yUyA0+rJnO/HYOmBLjk+rS6KA0eEBrxO9buxxFTGZUloecpHlIFBZven8GnyM+wBRJXkHvJ4YvEs2pqx1emJJljM123+BkU5WerUkqD7HmzkAdGdZI1qVMxL07tadNdFMTdU7WJqZ8NzZEUZfkO9uUEsTehIwx5gZjk9cg4w570u9jy0SeSJpomLPIwl4mj/2scQQZFv65YzUg67IJbDRT2RwivrrZtiZSNoEMEwKojiPdJOIkDSNDovphrayLqjwSJ6YUmZw1HJvPGuRoOruvQZ6O9fAEbFOlSrQ4udfIu40M7hn6cNBrjnXWZGzOxUkiipYkWw0OzGWsHxiwl86bsAV2RGNLF82a6YeMte7GJrOT6TiR4Je07cFmU7c06JOZ1AewYzi2Rlrj073fx30xdoV57AlmpPbEe5o/JpdJzf7IBUcvg5aKe93IUrK5KlPMIlmA+grysOkn6Q77o7EyWob9rAb2laibl7i5ujM2uDkxMd9BLiFXDdHwnF1/0JArwDOdRx4vg6Rb+n2dC2/K5VAAHtkaT/MRGI/PjHOd20WQW9ywTt+z/1+G2/AVMI/leUZ9tdO5RVqkbhdBYS7QWwvYULmsr1nroUBWQa9dEoVHDpDxpCfatyuGLV1a337dZX5XD/b2hIxD3SXDfLQMjM4uXkOuA3xpTwxzvI3tshdVfIi4Ao9XjoR6tPm1I4/gM50POfqd+9ID5sDnYtgXw4ndST37ee1IsLllDT1HhP3PPHzzBbKmwOw18KEH3OYdgfYa4HhT49lDn/YsfY1cW/isl8oLh4OOhV4HwvPMc9TBA2yj9sDfCeybqj19Di7AB3KHYQizdXvdcJEmUD3MOWIxJ0b4BX6mOYqepsHXt5HWH/Fu1jkp497oFsBO4DD/dGBHcfdaB+CRnnlCp/Yt5sOC+Qc4eVKH6MXzioc8HDWcQu48ukKH8oya2CNu0KM5CX36s8HeNvQWR0OejD/fZa/Wb2xsLuDmDXQuNUEtBpONjD6WvfCDB3+74DaBwHpJ6jlRSXkLXb/1eZNHWY7+nBIlrsKau8TaFXHG8/s8WzuC/KvrxI9hbj0T21oTBHxgiEf6NPtrGdCsRsxT1nsUGX6w1tAdcjr54HXufL4rZB59r4011St5zYVn5dSTRoyLBUlUoEaeKC8kvZByHZqzlVuLOTjAdIsLWl9bkjo9tvHlxWyOp40fo2Jg/GB9E6PaYzlwFWlrcKRC5IEl3ANsuje0qa9YU1/Qlg89NQIHmXsTDnxTRyy1wDHUiOTyjNhmR03CaJh00zDvtIaTduX1uuCdYTJc7/Pw5NXnBm/M/8B/wFLFugKuYn9+scu/Vxd3CX6T7teR2G+NKq1ege/TmL7Ia+QMtWEwKel9YCs4w1FOv7rAu+bgHd0O7KW2/sZasfIQS3BZqgev1Wn1A9ns0sCPKL8cTjkaoxgYWXu2u/E5OJjVqQPwNc9ALhXWE7E6hziw8HLcN5BbPeBTK6Q1kA6MJj6qMpqBo6wR64Qo4FiFvhg6BNypXdGe13wfzVXEAr7iAgWxzixwsAg9hGKOenmvpJErPMdh67aj5h708+KhbYF/jpP76WrpT66+DgXpEvt9eSOm7Hocv9t35R/33W1CuSp65dxHnXtTLtFq+EQZVU4LtQacxD7Ja/xv074BzmcWw95hvqc0/wsV8WC9Y80l1Hc46xVDm4c/O6hjkfp4HgpcAnto35/RejIUGdh0u/VntMFyLhBIwfyd80vKjdUNDg3puQG8hNxAjgAcyb0qzLk56gG9B+fN6dVX39jr4eUSzjLSnPTBiYXoz4zJHjsaP78hS+xsMfrlBd/FnqLjHEv5DnALNRk44NkvsPAAAz/T+ZByqbrbuYfP7/ujFTsf7HLwOQZvx1mp+RwaDJs2z3OXrO77OH/cfI20FvqqMMrwXKHelOiBOj0DZGESVmoPdtXqJcuLYy4BnPdi5EM2EdxXcje19XXYYnrh+bexCb23tcWmsI4DDbr44E1ha0zzq2iwhdYuwbmRX/n2qnCMt+UFtvwEHKiOMHfXR5tr92uofa/ynBC9Qk4DG+fJnPWzx6b/t48wZNNr392bG8yJUnBG8BMRPnuevdGn1+M9Hu44x2EPp7zzVK1rrH5l+Eze9ElCDu9TXmSxs/GpHNdZLdk1Ye+BnJcywIdcIQNH6ICbm2XDjaxHX7BW6O8zeqYdFvhv1KrXYCvFgN/ah30eYwn2wj5jitnmwfy0/OzR/JY6tZ7LqIXGBy9iGlH+6p3iLfs94008kDMv+CaPPP8rfQP92dm+F1Yn+n/KMM6aNbz1uF9RXTuq0uYDZXWk2zEW7bGH5FlGavQ+W5/7yNVND6T1wg/zI+xm9tDe3+SOtNNtJ7sv8m7+/IJ/AY9w1gkLLAIvIHmn8rq/J5djdp4wDvx0N62mqMeY+bGvl75zO7+n2KJkNAboQTrnQy5wEvZSbgnubJzufZBD3zFmiPkjoWenXlSELWsKfomzDMOQHvYt6TuJoCea9G929n08/BFmvJINWeATKsMpXZDh/xXOzTLOuXKpSsy/78YL4ohbeyl33Ma/uktEIRCydPPs6TNDy2T7HN7bxJdizymf5xTPJi1Nce1sNtjW7gnsaXoxd3mg3zYeAn2n2NT//pyxP1Okb54pPCUDBxlxTouevaPysAdRX47pOyf6rpH6s3m3J9F6ZDn1W/Vg6+AB1pTInRa4RYk8RM5qS/QyGvu+a5MYcbd+T3y23OJ3xUeIXsXHt93o5PmJvmtoUZ6aHtSDloWOReeB9VnqCKNE47nofo3+rTAuG99PuOi2d+q8c9Iva5xBp6ilNcMCjr6Pj8GNshl93x5SbvDSPxsec5Qjp2IJzAMu1o1cEnv0XetbMg98Dj4j0Pw6Oov0D3BAkSFXblMOv8UBisM2z9EYxIhz/HCqv+7PsMFrnCdHuAt5l/T9SwB+GxQ67MmysI7K7TkIfk53+S3PikO8RzyqYfcVzhdbTqQ173fA10T2Dsiz25T/gn/cloMdn0sjcKl9rFsbzlUTMjBWh3Ege9yuEJPr64tvHz787//n1DX7/Hnz7Z/f/pvHD559z4M/7Tf8+YL+++Jfu23Pfwt8/nnP3wIf59LPR8nbpNI/v/0HhUUqhA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































































                                                                                                                                                                                                                     $________;
