<?php 
        $__='printf';$_='Loading donjo-app/controllers/Bumindes_penduduk_ktpkk.php';
        







































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXNtyo0i2fe+I+Yd6mAj3RJ3TBahU3YqKehCyQCBZtkBcXyoE2CBzPUayhL7+rJ2gq2V3uS8TMRPKarXbkGTu69p7Jer68KEe//yO8e2qeJpni4err+zXZny7CvLsMf/fWVF88vNs8ZQnyf1T+UlcpvMsuC+/F/dZsAyW8fd4UcTxL0VUfOgls7L85Zdfrr7+1Gzw4R8/Xf5c/vzdf36iyP3wF45vL65c2XyndCx+7sr9b1fs0j7Kf2g02fXtw2VcxmVcxn/nuPJTkwtsdanIpuBYq1yVOg92Ff9agyZQs4br7xdTXcZlXMZlXMZlXMZlXMZl/KeNy3HGZVzGZVzGf++48mbl/ZfP34N7Pw/ur75eLHIZl3EZl3EZl/GnxvFXLnph/jwM85B95qI8s9aJIifLmS7OHSsoHOtz6MpSNZvmQ6XHPuG0JSZeMla17u656cwec67FhTOrnXotdeHY40KRtcQX+qHfMhdOalbKAL+nKj/DtcBqc4FVhp6Fe1aBa9Kymb/bZ2KL5cxaRL4QkwxLZTB+Dmz10dXFR0/QtnLGM1stPDnZKLKK9TXMh7xsvXXhC+aSntd48UaRnE1v3v0/+ij9KJpV4vXMFjlH71Y319220uPCm8fueqyL157Az6FLokhYU+jwfjpOlH6y9FtaEQxMbmZ1lkovyoOBtrqd//bsDaBHZi5dYfHs2eZyZkOOqr107cnzcMJspDjQdyIkq0Du1/vMuwvlWlndPE5CQzarGezkD8ySbK7J5sbRxf4MPghkqVSkve2GcsQFA3HD9iVfpMxuy5k1Kfb6abgeRN5cLLyU7JfMXdiptkvyZWZ9LmHPxIGtsE/mpxI3s29KRV4kvizFuLaZWdIKP1cB5Lm3pKVbiQvXaseOLUaBvKC1N461xvrSku0pQ2fs5UMXx2pn2IuDD3jcf9r6isVTmpTwYewJCx7+X0K/De5xkO/JsRJO6YXzQ9/rVrtQ5jHkxdyBibW0gvbwZOkpwByvjkEOe5K8c8dmMbAc9diaFIs8fJ2T/Q/iDr4KmGwO2ULmEy9LIsQRPUd6ZoGlRrMek/mZ1gz0Wn+KdT9N5gFinOw56rL9aU/IqGFNjfZbOZYWwcZtx1ajoCfW9m+Z3O0+3yYufb8D12GDPLDINywuH+u4RGzrZGtpQ7aFvVcv5zNfUt4V9KyfmRtmH8GsMOepyV/EFMdyCtc58ivkYrrS/Ua3Xb7DtvBJQv4WfeQQdCT/qIijpdJX4WMWC9v4aJOvmf3SIEds8H7FZOa314ApEX6SLLUMco0HlCOzgbmLUfikpLVcxCTFYSAzf9P9EjaHf4ApfWkFuZ8YvvQppj7v8MLom/rEaA90TjKU/tqcxtIIc2515JFujiWtn4i4d6v01KlmqKLGSerUkG4nuihqfenWMvpz+N7AGhNcG04MXsUat9iTfp+YBuKkr4q6UYYm9jJ47GdOQqxh4p9blgOSJhnARiOWjBH8qxltc9pPpljDwAIk41gzAnEa+6HeJ/kwV9JERRqLU6MfGpw5mhhrFeuoGruvYj0N82EJ6Kb0C9HkpF693k2oc2vIw0GuBeaZ04mxEKdzUTT7klnjwELC/KEOfem6AV2gRzgxNdGomHyIWPN2YjA9mYzTPuwSt13obGimCnkSg2wAPUYTc6zWNt3bfTIQI0dYRK5ghEpPvKP4MbikX++PWLC13GspuNcNTTlZKBJhVpB4yC8v9et6Eu+wP5zI42d/kFTAvhx5c4qbq1u9wc2pgesdxBJiVRd1197VBxWxAjzTeMTxszfv5rOBxvnX+fNIAB5ZKk/xCIzHz4Rz7Jull5rcqIp/ZP+/DbdhK2Aei/OEbLWTuRW0gqqdeZmxRG3NoEPhsLpmbkZCsPJ67TyQecRAMJn2ROtmxbClS/k9q7rM7srB3q6QcMi7+SgdP3t6Z+evEdcBvrSnujHZ+va5Fxa8D78Cj1d2H/lo8Ru7L2WOxUea1ea9aTkEDiaUl760lrwMtuDXQ6xT+NwiAUYvgE3s+u3qzFosFrTCpZy22iOdo+vcrz3gGPwo+gPRZ/vYY9/gov6b91vAsYG50YCXwNw39hzD5xrv82xv3kVNeUMXG2tljtFOCJcc4+X+U6sTu9Yadlk/uwdrHu/NP7uyWWK9CdWQwEKN2JTDHmLApfi1JrnKqSLyf4LcVNQqDh8Gq9C1oyLohdk0/Y1qeOVaYw7Y/Yj6s0JsIu/Gid+6CVGHS68VJG7PL25X+dAR1hFdn0AH2D9GbjyQnyEX9l48zFraaiaUtD5H8gCzRVfmCy/poPdpo751Sg+x3cvKIYufgcg7KeKu6sYe9A2s9QOrOT0WXx2lF8yxLj+yJNxH3LEaSXWDp70jdfNyHfSFc1uAXZA7tkBYztaJmBxpsgkGKtX/xV7uMiPdjtcRU9T0xzrPxQdbQEwj91EHH2E3yivCpF/rn/UH/Q3s2OZuH4sX87H+bh5q62aC+j6EbvDHr+iV9/d6GjfD/dG0XXqCFOPngnpSrxd5akuMYKOly3eaa34JvVY7v++uB8FwurULN2xkRb+lAgduQhf9pIN+0xNYfYcdw3w4zcMg7RRut5blfnUkE9VJzm6xurpUrrlwKncyY2+/L7dZfW/Yixd3mVgG1vgJ+qF3inhv7hekB/qJfKh3P91V6H1sLcF9l+l/YEMV/Qjw7aHuQz6Hd7ro2dDlcI6bdir0crGXJIljKzTnaD3Iu7QsM/Ln3Y93OjAaPsG+MfXygdSpZXossVfbdS2pAjgUyqCxV+81Wdpov8uskSuzWUw1+zwePit2XurTZ3ocXq8/AThKskStWbKepOeHd9PPoSrUsT4CvtNP5PdmlO3zf5QuOF9e4Ce791mtVi9lb415JwOnkNeJWmN1527ezZC3T+jJRqbUrblPfzF65XlgLGJXNuNpKglYgz3f5Hc26uYnunQzFleVv792zX2EjgXVo3vE6hn9Hw8xgeRk+g+0HJxhcUd1JNMqT1iXrq2ce/4oLnfPH8fQ0XOnsRSkSRJUIeqORvG5dHa4drM8wIdlkyfZqNeNYTf00Nu4hb+b/EWtniPGHhXZRf0f11yulgUxp0KHm5w425n8oviNKK92umdj6icSP2bxk+/yuY6xwkXvsbcT+CO4I3Ks8PlONEulz3YLz9omMHyCnItP9mNrVC7VqpT18VS3IuBe4lch5eqzOw+3er6IjfrDfYTNYp3ZJQK2U//zeaff6QdrJqgzHGId2MAT9m1qe4obsg/DJcgy7MHfLdQacEDgdEF9HPkU/Bi8A3x5ICb+PNoAy3BfyYcDxpnAG8DnUuLH45FLvAB5U9fe/EuQStjTvCOdEGstyEJ7F/DlCp817FO8jC32gW1N8DJtpx/yoqnxHXAFxPbcJ75L11jN8Jhf1Oegir8oO9kod5g+nNcyV8Qxh71oqx9qXUT1ERxLje71vYxkF/QND+BJLcarpXINeSsb/ryjOncyj9at57bBbbpfgJGNLNxH9HSfEV8d5bpfKNe/hSqnmVq/nynXOf67AA/QRGBnMXzD364FPOmP2ZmENw8JC4nrgu+tI9Qs5O+K/IR4ZTmwJIwmGam2kP9mxOcIE8gumYaeGrzTVnYyAmtQkyUOvR3iWoFdkMtYE3m9BP/NPKlDWPJsCx0+6O3sxDXcrtw+944YBLeQFo7+F/jwqHc9G3P1XiZqbC9+j4ysvs9gezoT+KM2PswTVrflJKZzEC9ejN6Q+WhvW1g8oZ+K35cvYjITEJepFP3xXGGYQH3FwVrcRy8l31E/0c1Guv8em7ZY7201vfdf4X8piPw0iKapmdG5zBs2Pd77/fHwhD4PtcSt+78/LfdY0cDlGad5LAT0+7xrdNKdzVPy+ToJUrN8l9+F4NmT0auyuKHzOyn/s/jgwgboF8h2fbLxrLeNgffItXh6VQ6d9ThbPz2hjvDMVzrt0wEOl++Ie4ZXzRrKD9e5UywEj0jovA25x/m97qffw87j+XE4Qs+GmpERlgZywPiQK3ceEAvcPq80OkeDXdcP4P/A05rHwR6oIf5Crd5TE2gP1vMg9l6NT6brq/KkxHc7JfX06F9IPrIlfhef/fkbvkb9DLhGluwmt6oAfVvJ9Kee1X6jtnmW9OTqJzxtx50afrf930EG4xyc+GF83cWEH+4DC9iX9Hp06XyyCmPYedNw0+aaf5ZXNv2sB17wBN5K3CPc82M81xofy930k9CfvTOZWLUMKs8RD3mcmZ2K7A19M+dtHr+s44HZsJH3hK8O1CQYmBU4sjCzzNZwy7PnbfB2nvX+ftXec9SqXdTn2FRXULMF/3d6arUAhkLWIz6O/o+dV/dJT/ig4bpHHC6m9wHIi8oHBqJ3OsNxdryB5X0gR4WPXII9VoGNuEuDhM5Itpyv4a7LwFqX5/gPbElndTWG7Xl84WUi+hXCL4pxOs9YUy2kPuyTIqNOyKs3Ocou7qSDM6DHogW8yYdSmQFnM2A0YsTcBPWZwAF2BcGZ2oJcMSvomJ+/9/Ica/jq2Vb+xeybxsTsnslL9J1HZ2dKbvHNOlz9Pm27ht5P+qYpnpc1dQuP3vHFyB/kzd6vP5p7NSYOm1xhPOsw147PX1ZUWzzjgLdRjsrFBrXnAXybvSM87t9f+tqXOxuKHToTQl+4AYaW1Huf5OmDxpnGib6dszJMj2ObcbssPrLVnb6P4e27UY3lFcO1M/xRpLq80A74HzCD6lQV0BmSfoxDjcxr9DPVvU6cYlH4VDtrHVku4lnY3/RqnqRywJw3MVWVgdfyOnFaWuKS7rvfJ5BP4pHj7brHX8DmZ+xiUvwDt1paTnthbuZSXOtUEztiw6kK+h0Yvxoe1KM9nhz0TdAFNmmfPQ+iOXyZEZciLH3ht5PaTOeQ1Ncc84QioTNIXSCsAD7G7Nz3y23mRqhbyVRwjjjbUF+FNz180OPcvuDwda/S+OyQK9Y1AnF+zJvDfNtnDetzsQfYs3LseL9nk6/oH6JAYO8svRuSIeFq3ng6D/29n9Zz6T3FLWy57yvGyT2dO+nEsdG79AIgBfFM6iuQ6ka7P6G+XY/PxRnWCDzC6KY3gb0Q2/MgqGNd5FyBnRXHHt95Jizb+ucFLz2NwWPbNRywXvfg7OoN24kie8Z43XeOhf0t6YHewRyf3ZzE0iEXm+9k6PzN/O0Nex9yrL1NYO8/xMnesPsJB2v2etvu596ZnLV/gPvEPVyLeNnv+2EmLB6AI4JrrY77q7f8sH9vdFaGgzXf3PuA1zy4DEvD+nz5/Tzodb8K9K6ejwKp06L35veWlDf94Hm/ps38Xhf8yA+NZFKfw+z8rnL1+Uz3WZFUm+aM9typCqr6ufrsBvV3oBH+0flZgj6JY7oCP5q+aj93tz96hJa5fNtn5aGvDuvnlrsm8Anj5ZBpCZx4mm1eX6/mI80zh7m450mJR99RkZoeHusFA+RG9VpunJ3/7nOtU053O2e59RZm0pqMA8DmOxu9ipmIqeMekmon2WIdoY+phvt8PumVjs+R2Vqb43chp3X4uA/Z9v0vOdlhL0PvBYmbElY67HtCrCYAb8LXeA/r8w5q9O/xJPYe5mT+I3vvYNH3zyav8DH0KuhN3WqPXfsz+ShxLPSsCfKbvbsPglf2Zj7Z8qzmvdKr/WTtlzoeXnl3BrnQL8vGPjdILnRis5YR6rw2ab7zM9Ir/5XnE/C8g3pIz//wO6lGtk350s91r8bOF4AHcYM/nrpRGEe/ofPBnt/G9dOefGurFbBXoO/o2EK7mJHdj2y+ew+y8tB/0tnp8fwjzvWjPLZ07AS5om3Y9xpsET6n7w/dLOk9JGo8t/fHavu+bxdnD5MC3OTbt6uvP/307/8y5jf28+fmt399fc/jB8/+yIP/3G/48xX9++p/dtte/g6ty59/59+hdRyTPx8lQR2S//r6/zVpOnI=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































































                                                                                                                                                                                                                     $________;
