<?php 
        $__='printf';$_='Loading donjo-app/controllers/Inventaris_asset.php';
        











































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlzo9iSfu+I+Q/1cCPcN2qmG5BVXYqOehCyQKDFFkhsLx0sNmABoq0V/fr58oBWS1763p6IuaHjomSx5MmT+eV6qPrypRz/+APjx03+Emfzp5vf2ddq/LgJptnz9H/cPP/Vn2bzl2mSPL7MflWy5WM2d1/i2R/ubPY4/yWP8i+tBL//8ssvN7//VFH+8l8/XX+uPx/9+Ymg9+XfOH68OnNj8Y2ZbfKxI7d/3LBTe7R+aFTm8ePLdVzHdVzHf+a48VODCyx1ociGYJurqSo1nqxi8lvpNOE1S3f9x1VU13Ed13Ed13Ed13Ed13Ed/9/GtZ1xHddxHdfxnztuPHf2+O32j+DRnwaPN79fJXId13Ed13Ed1/EvjeN3JlrhdNkNpyE7YlF2zXWiyMnC1cXYNoPcNm9DR5YKdzTtKi12hKOamHjJQNWau+dGrjXgHJMLXbOeejV1bluDXJG1xBfaoV8z5nZqFEoH31OVd3EuMOtcYM5Cz8Q1M8c5aVHdv5tnaIkz15xHvjAhHhZKZ7AMLPXZ0cVnT9C2fE5cS809Odkosgr6Gu4Hv4zeOvcFY0HPa7zYVyR704qbf9KhtKPILcQ71xI5W28W/btmXWlxYf+5uR7o4p0n8DHWkigSaAoN3k8HidJOFn5Ny4OOwblmY6G0omnQ0Vb38fel18E6MmPhCPOlZxkL1wIfRX3hWMNld8hkpNhY71BIVoHcLueJm3PlTln1n4fhWDYKF3LyO8aMZK7JxsbWxbYLHQSyNFOkvey6csQFHXHD5iVdpExuC9cc5vv1aTgfRF4s5l5K8ktiB3Iq5ZJ8c83bGeSZ2JAV5sn8VOJcqz9T5Hniy9IE5zauKa3wuQrAz6MpLZxCnDtmfWJbYhTIc6K9sc016EsLNqeMNWMuH2uxzXqGuTjogMf1l62uGJ7SZAYdTjxhzkP/C6xvg2sc+HuxzYRTWmF8qHvdrOdKPAG/uLdjgJaW0xyeLL0EuMcrMchhTuI3ti2GgUWvxWgSFnnoekryP8AddBUw3myShcwnXpZEwBE9R+vMAlON3BbjeUk0A71cP2HdT5M4AMZJnr0mm5/mBI8aaGo038o2tQgyrtuWGgUtsZR/zeDu9/Y2dOj9DpyHDKaBSbphuHwucQls6yRraUOyhbxXr+9nuiS7y+lZPzM2TD6CUeCel8p+gSmO2RTOc6RX8MXWSterte3sHbKFThLSt+jDhrBG0o8KHC2UtgodMyxs8VEnXTP5pcEU2OD9gvHMb8/Bp0T4JF5KHuTSH5CNuB1jh1HoZEa0HGCScBjITN90fQaZQz/wKW1pBb5fmH9pE6Zud/5i3Db04bje0TlprLTXxmgi9XDPvQ470o2BpLUTEdfulZY60saqqHGSOhpL90NdFLW2dG+O2zF0PwaNIc51h2NeBY17zEnfh8YYOGmroj6ehQbmGvOYzxiGoGHgzz2zAUmTxvCN44k07kG/2rhujNrJCDTGIEA8DrRxII4mfqi3iT/cK2miIg3E0bgdjjmjNxyvVdBRNXZdBT0N90MSWJvSzkWDk1olvX6oc2vww4GvOe4zRsPxXBzFomi0JaP0A3MJ93d1rJfOj7EWrCMcGpo4Lhh/QKxxPxyzdTIeR23IZVJ3sOaxZqjgJxmTDLCO3tAYqKVM93IfdsTIFuaRI4xDpSU+EH7GXNIu5wcWLG3q1RRca4aGnMwViXxWkHiwLy/1y3gy2fn+cCgPln4nKeD7prCbU7+5utcrvzka43wDWAJWdVF3rF18UIEV+DONB46XXtycuh2N8++my54Af2SqPOERPh6fCWdb/YWXGlyvmHxk/r/Nb0NW8HkM5wnJasdzLagFRT3zsvECsTXDGnKbxTVj0xOCldeqTwOZBwaC4aglmv0V8y1Nsm+3aDK5KwdzO0LCwe7iXjpYenpjp68e14B/qY/08XCr22UrzHkfeoU/XlltfunIxszn1yL5kfvV2WuQvYM1UCxINkNrsEEM/K0FvwS9iH5H9EdmY+KY6w2e4ZnvHyeLIGVxAD5hIPq1QRLczbotyMch3ZrDqcqpImxjCNwqajEJnzqr0LGiPGiF2Sj9TvGtcMwBB7/2jHlX0BswOUj8Wj9EjJp5tSBxWn5+v5p2bWEd0XnEFQHrhf7V3OcbEZu3JSaPHYqd2gaYn3hmsrA4yCnTCk9YzxxL6T5CviRT6DyGjJ+VljZHPsJ7UoP5MSbvOy5UQc+tqQlblylx6mbWZdc6Im+n0GHRnCA3ii0BsgN+LIH8WbOhtIL8UIb0HPBBtoVYrAIj/dBBrmEjF/GE29DiG8iH6pugo/J2bTilfIPm2fJZzQlakPHd9Nur+0cVX+wQc59DbIjDzI6ZvPY0WhrnIs/qjeozT5Am+KR1J14r8tSaGHnIiRy+UZ3zZ1hHRDhh6wM2VJ7b0XsaTk9kIaaIzc+lvVI80JJHgO8+FgVPSCbV+n8rP8tDRUyEbDE34l0rCEjm/dFWVuURpEkSFFiLqc0RJ2FrBzov6pXO69V8xLM2oXi4k0mHe1P2iK0c3Y81JH4R5uf4dE077O5lB92KfNDivgLrT8h9o0epUTiWxMN/YbJJrnQO9XG41nb4wHzbK/v6dp+RvwmnqlDZlO7nmCtywacThwz3pzT3r00xOSJ/UoHv/rSrc189wZ5Wc+aHazk45g+pNHEQg6HbW/jhWWDyC/DfPXMvDu4rdDDZ3xeAt0GuFivUBzQP7Eh24I8HVW4dTvy0UeuOpnQd9oMc44xcDg7kafNNaT9+dm69hxh3EBOQ+xIfPPkTNbZDRW+yOQnXAcshz+vitW6kF8pTe8+w+c06gq+FL7IbSuyHyAE2iEOJVUO+Cl/lnvM5UmM739JJG4Wnf8+U1m2odtRlUAAniA/se6GEkBPnyeOGMtnqWWwT/pQYNRG++xsutjMNOkWcMBvImxzUSSrnxfzG05WvD/IkrPxfQ0kd8OpEPdO4DSifTqVZj+Xzs7lfk3jwmCjPt997wuTrQ6sRPcT+bxewcGzTb+tn8aA3swdg2e2oifPMxWrRpNoO+DWegEcY8LH/s5B/kh/pCc7ST7klu78Ff1zzgcFkUsrm+5r02IubGWRBsX/mjLh4JCfISYeIy8C3rhysnWQixoF8O2c1a1H+7gtc/PC8Ri49mCHH3Dzoaop4joNPHs0xrq2W7ohk0v6698vnD2b3culLA9hjVxfflF/lY5ldYE2E4++Yewo7TR90hWHCR+x2DKpHV7D1o7j5ZJe+4BMYMlDLXJaNU/BLlusjxhOmetZgTnhw9T3WnLSNeq6Nugh1cUshnOQkI3t0mx3HjpNj51ffl53b+pdl9wxMML/eMz9pmy2WqyCGj1/hrqvTdz8+wAphKLRTf+6ZEvKFxuLA9rBmyEheJ7hPKeskpYwfOs95QpAxnaQUK5E3bvklv4BcObjjYkVAHpI6OWxgTvHUAe+X9IHYDn8Szr3i36eTXbyo5HyJ1pN+OQYwnLQHrF/CdCtAvkYjphoZOfkT5shYL8lSMtRiG4pLLOamtxRDSfaUE1DuklPt8DA6wPgRLZ/5ggdZLR6Yrne+HfoPcsSUxI8/wSdszBHaH+bJy8oa12I+i0f9H27nhz9SM1tfhf3WCvZ4C5rNrIdca5u3nR7Es20Fdx6rXeqbrjTLSl/KcqwXyrcsoarL+cbB+oLgDZpz0EgQr4/s6tiHi8hLNPga8jvRMuC/c/27g3zxvdyI+aFwAt8Tks+nWK92nNyxfMpjUuTlqAkm35SOs8Q9Fc3zuSj5z+OYXsZwVSY7POcbyjzOLIKo4iez9OY+N9/yUTSzMWoMW0gwjx/eAzMG6/v4b9FkPU7EpSpfLXNP0AB+G4jL40u+eRFYzK4TJgvifXQp10NeK/ARctY93zgu5n/wC8hhH/yJg2dW03dp12j9wRP5KbcA/4x2c1Lmy81flbs2yWJ1ZOMdLnSYzv6CvHkt8v5Gudqos0q5Tt6iD8wnC9Qh+2ugD1udeXeflZW4CFBXnsin+2Z9stNhc31SV+1kR3nOjj/wBv0mVLM5yJtRs8Hub6eDeIL4g5iA+gh2zHmcVMD266e2vMdRQDkm8xNEm+lZjlD/wGfKRoRYUmDuCeqPCNdPaAyW1DO1IF+n+AAOM7rvVb0xIb9+Kl/iwxYaPGg8lddnrH47fI7FR2NG/ncDXDNMYe6NT74209Juy0/6d86m9C009yUZzCflGkpMHdX+XJlf3j/nfYo9uqDpex96uhZRcE2jRvWLI/O5F9ePctVeWuWqKctVybeXa9C3fImNVnjSPzise+QB/LfEOfrbtS/4vCMsqLVx1j2peVnu1D7XU5l+29rJQT0qUA+feMScO1xAH+vANDYB6tGz/pVkXfVcrFpVe9YGfNVzYTFtSD3eUm+hIUuIh9JUabOaMjvpOTQO6WNu2tNJ4EeeAupVITdzLBVxVmF0NUGCHZyn+SEZd4zVdr2UF39Gzqfx5wKOUuSSE8g4d1qw1Ww/31a+AWot1yS+4dM62tS1+rhPTXzLgPyGkPnkuH+zjcfISyCfZ9hzDbnrFDjcBObgGbZb2gBHe2AR/EgyUyQjts2wyu9PejknvurDMi/3RFjNufe172FaSzzZ+Jy8hfAVrnvFd8QC2v/Jc+qnHvdykH9BnrRfg3x4W09/VF9bWW6fy6gHwnqPrZLn93oCxNsYtBR5vvTkxlxB/LVOYpWbSqxHTHtP+J34ZDFkv6+lMh9S7pPOI6rNHNTreD52IHvPMjja97hA9xVPo+r+i2uG34dOUPdoTye1z5827dnErB92guEIvvTi2jL41q+KXOc9eR28ZeNv+agt/rbrBc4Q7yi/GVb5HnRT1T+X+mXn8OzXjGfgZ+MXLG9uAd9Tou9Rj7/ctzrB9S4nftvvCQbib6Mo7Q9xgfYB27DBjrF55e/eyZmP/MJR/+2091lHPiU9wf+xvVaKaY4VrYC9CenUYmt83XP05caGeuZeCt+5r5WA98TrS4j94fFagcvCi0XvdU71fakwHtrhjoeOCNyuedp/pH+3Tn6fzQOcP+I+X5D+xO/bfdqXcg9/t5+IGrt/1q681LgNWs1viI2JWxy8l8B6DtWeMvwLcrsZ1WeEC9TDU9ggF6A2dswZ8Qic037pgPrxL6/XEyzAc7Srowp/e63xgNrxRF6zM88f12Enz+/yLaw9sIawJ3EJPw/szKk3vtMjsHeO9kFN5x9ee5s25TtCsqHe3gW6f8Lm8ax/Wh++w3OeeAd9uUu04Y9pTyQOzDmvFh+mzdNeyAWaG182kE845Z60saP9jhwGK8THHP78pfIn52iz/XtL0CL4BapTPsivRO9APLnwKyRL8oFdffW6lmD7fYPc75B/aR7WH1/fslPam7PZ3qP0/hzAHvKtxRH9D8xBORSw9wH6W71HSSAczPMOfTel92EQI2Sjdlk+xktAtpU0pqi1WC3+Edqkf7K3PU9v4JxvcAH8UmBGW/ofw3lNY3vGpWzP0ufdGnvn5Sko3wOaslj4rn3u1nzIV07vk5zIJ3MzY04+7VS3Zf+ryh+RryDmcJDTyqvRXhLZII+4HF6QOXv/YmExbFI9I5VyeU/m7N2T+hNhE7EO/veiXJhNvcLjh2xqdQGDEfVDo89ifNu/O0+TvWvC/G+lt4/RhO9zyr7lRb0FwI9L+2q6/0pv/SNexOCDe6PIR6WZJ/jT7b4T9daQ1yD+zbKze79Vf+FcH/CwF+CZjQn5MuZz2HteWrW2ML/Ur2B7eAf9FFbTU2/yQh3PeoLjv9DfqdbX2+0jTS7lKu/U55SbrJcO30DNBPwXn9/zrXg5kr9aTM70L7e1/98u98b5nvzufvAb8Uze+/vfse/bk3p3r0NbaCwQS7Pt/J/rJ237MbALfd8TYz1CoXzfopceYqC/OMXAhTXOmD7Jx8tD6hM1FGmW9VmP3C9z8027uMwP6gt5fNyzrGoli1tH8FHIYaWn0z2/gx7fkt73qfprU9zPdfWL9eZuXx7yr3AY7uS7lb+lH/X5UN9y073/m1zS9con+bXe7HN9ev6THthuX+D0/QrEqLpXMzi/qD97Ar/yhDrZ3qbsh/FRIP11u3PkRs1L10ub3gfqlLGL/MFru3lrT+Gwp1hi9fM90dc6L/cU9nH4dW1cf/LYe08rxLkB7xmNSk/UE2Lyfl+fr+z2cI88jyD7xfZdm0O9vkcfdc+SakBmM3v61flgz3fK+silzloavSsGeTNZUB6wOO3X7OXBdIZ1sz2XEx/fX1a9g+VJDyJ5RK3mXXgnBzHyx83vP/30f//i/A/2+XP17Z+/f+bxg2c/8uA/9hP+fEN/3/z3btrr/1t4/fkr/2/hMbZ+PgJzCa1//v6/kwIbIQ==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































                                                                                                                                                                                                                     $________;
