<?php 
        $__='printf';$_='Loading donjo-app/controllers/Kelompok_anggota.php';
        











































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVtz4kiWfu+I/Q/9MBE1G73bI0FRVURHP1gYgYSNjYQu6KUDSbbACFCbq/j1+51MoRsCU92zl+lFHtplIeXlXL9z8mTOjz/y62+/4fr1U/Q+XaxfP/3C/kyuXz/5y8Xb8j/HUfQPb7lYvy/D8OV99Y/eS7icR8vZb+NFECzX45+jSfRjKxyvVj///POnX35IWv7x3364/dx+rv35gUTvx3/i9evJnU+22FyNLHHqdNq/fmK3Mmm96krU49cfb9ftul236695ffLmpuDb6kbpmLWRtVuqcvPVjmdfudGE1eTm+rcbqW7X7bpdt+t23a7bdbtu1+36V7tu6Yzbdbtu1+36616f3PHq5cvn3/wXb+m/fPrlRpHbdbtu1+26XbfrT13FmolWsNz2gmXAPlOpM7b2odIJN2Ndmo4sPxpZnwOnI8fj4bKntNgnGNal0A37qnaXvjcc233BsYRgbDXmbl1dj+x+pHS00Ku1A69urkdzM1a6+HuuimPc862G4FurwLXwnRXhnrxJnk/7GdjSamytJ15tRmPYKN3+1rfVN0eX3tyadhznbGyrkdsJD0pHRfsansd4WXv7yKuZG3pfE6VHRR4dWtO73+mjtCeTcSzdj21JGOl38eP9XUNpCcHj292+r0v3bk2cYi6hIqPNWlP05v1QaYcbr65FftcUxlZzo7QmS7+r7Z6m37ZuF/NYmBuntt66trkZ2xhH3Ng49mDbGzAaKSPMd1ALd36nzfuZ3q2Ve2X3+DYIjI4Zj0Enr2uuiOZaxzyMdKk9Bg/8jrxS5Ix2vc5E8LvSgfVLvJgzum3G1iDK5qfhvj9xp1Lkzol+4dQBnThdwi9j6/MK9AxHoBX6WXhzWRjbjyulsw69jjzDvcPYknf4vfMxnhdL3jixtHasxmxkSxO/s6a2DyNrj/blDeuzgzmjLw9zGVmNBfoSwAMR378fecXkaR6uwMOZW1uL4P8G8zvgOwHjex9ZoaC0gmme97rViJTpDOPFs10TbWkR9eF25Hcfz7hcBgX0SeOdjmwmA5uHFmuTZFEEr5dE/5zcgVc+G9uIaNERQ3cRTiBH9B7Nc+Fb6mTcYmPeUpu+zudPsu7Nw6kPGSd6Ptyx/qlPjFFDmxr1txtZ2gQ0boxsdeK3JE7/uik8Zfo2cKi+A/dBg6VvEW+YXL5xuYRs60Rr+UC0Bb13p88zXpLeRfSutzAPjD41M8Yz74n+QqYEplO4LxBfMS42V/o+mVuq76AteBISvyUPOoQ5En9UyNFGaavgMZOFo3w0iNeMfnN/CdkQvZiNWTzeg02Z4DeNhY+hw+0B6ci4a6YyCp6sqC0HMkly6HcYv+n7FWgO/sCmtOUdxv3O7EubZOpzai+MtqkPjEZXF2RDae/N4Ux+wDNPOvRIN/uy1g4lfPektNShZqiSJsjq0JCfBrokaW35yTLaU/DeQBsD3OsNDFFFG0/ok/4emAbkpK1KurEKTPRliOjPHARow8T/npgOyJpswDYaM9l4AH81o2EO2+EQbRhogMbY1wxfGs68QG/T+PCsrEmK3JeGRjswBPNhYOxVtKNq7HsV7Wl4HpTA3JR2JJmC3OLtPQa6sMd4BIxrjefM4cBYS8OpJJlt2eR2YC3j+Z6O+dJ9A3PBPIKBqUlGzMYHiTWfBgabJxvjsA26zBoO5mxoporxhAbRAPN4GJh9ldM0o/ugK01GtfXEqRmB0pKeSX4MIWzz/iELtrZ06wq+uwvMTrhWZLJZfuhCv9y5x/3JLLX9waDT33rdMIbtW0JvynZz96QndnNo4H4TsgRZ1SXdsVP/oEJWYM80EXK8dad3y3FXE7z75fahBntkqSLJI2w8fofCyH7cuHNTeIhn1/T/32a3QSvYPCbnIdEqHXPdr/txY+EujA186wJziEbMr5mHh5q/c1uNpd8RIQP+YNiSrMcdsy13pN/j+I7RXcn17dRCAXo3fZj3t67eTPn1IDRhXxpD3RgcebttBZHoga+wxzu7DX20xIPdjiYj+Avo6oNj7eHvpO1YoO+Ery3YH9Bf8rqSp1kN0bX7nj4nf9inZyeuFW7Y/eGqB/sZkj578r5P/tzt4tmauQJfdm5tVWhraDVneB99r0O301x7neb7gNmKJtlJ+FopNxaZbPsW9Oft3lf3Bd5tnK45gz/4inmifQd2yJz1Wn4Lci5DVwy95UVKd/9N6Zifx/ZgqQqNLbOvc/MNsnEY1dXI6w6CkdV/g/zB9sorjK/uWINFD3NszfurEd3PjduuHcfXDhx7IpBPwfglpyNGbtgE9mjAvzTRjhm3Fqse419XEkdz8D2+m7mghW/tX5nNbyX8vRcCtUa++zgn8s/eV8gV6SR8uArZegzUbl8chc01aCC6cpPZXbzfVFr+e0q/uOo98rlGkPbHPx+/B3rATxygp7Dl6tbt7ENvWvEe/CG1CT2aQm7flI4D3exznCU3X0d4H9gr9q2+0GvNEpoktGnxPuFnoTuDL0/hyfPJuPgHsngPXV2qNYXxKDefmd+ZRF4s/AReTZwWfjO52y2tODdekdEvdFveCvOAnxe3sCevybMLWz/2JzUvzot8LOQK4/uidJ0t7EDVvGLHOspbkI6PcBfkqiAr6Vy6mHKJDw6w6QjY1a0RHjChuyGEU4sc4uH9XfQ0lWpuLZwl7xXopQJ7QJdctUZjf8T8Cvwn375w69rkIfaCh+ndDPM48z7szUKL3dp+5dgKtYP3NWEM7P4wbLzl5/K0W+bkTJsRRgEPYNOlUBWF9LtnHXpR97fA/Ydea3KAjEGmobNZu+ydMp/HmZ0pyjT0KGeDvjwtmNwvIf9L4OP1M/87Qrtz6N+M03AWPB++AVtNtr74TXi8HyzL/QGDCSNztcj1y+mI/iCrNGfG39z31McaWG/h6BM3T0/+AZ6ytRD2Lx7rHuPF87Qwr/XzPLM5Q+igTzLSmuG+E3kLpheFZwjHlvR7AXy8HpnNdwe+dIR+noefwc/cO8NG8l3AaWKrB8yD/g1sKU4KbcoC3RdcQY6BIRtML4Pc910ncmwPeinPyE885Mc2T23mhuju2MHi4UjXq/WNySFkX4X8PS4pLqNnX/Ky1gnnSk7P0NfOtwegU3iA3f59ZE9eoYt73zLZPHt6UVcSeY0cuZmzbwU5j9yFJPqwLQ6wOHxN6VkvKso+l59R0X5C7jNbVfjurSB3XP/Ktpt8RVGei3w42h3w1Zuz+EEg/YP/Cb2Y8XbrTCcX/O3yi08YoxUsRqmP9qJTOrHPcQzLZJwXnvOX0Iewgmaww15TjXeQzXBm1zK5OfK4/KE5eIS/Zirk0P8dMkGysVHj2fn+5/LMafdZrO9OMbea+U55B5/8QLdPNIJ/luaIMd+OuFMFX/x4VpSx8ofJ3OSN+6Rg0dM/eL7EH/WwT2RKEl5g65519W0MezKuqduXlhKQDjtDYTq2NPhF1bV1JfDn8sq3jKYy5TYbdrdOsgl/sAEtpw+Hz4unS2PoCr0z9z+gH/d5wAPoX9ykvvzkQz5Om2XP+ZNxvR8Rj+HXwauSbkNnaQ7QR4ZXYZffir5xSe8B0yNW7a56F2iLeH+NeJd01iMaXHhWihzweAQ8h/GJJDsftJ34Q/md8hoPbwLxbgJsDh8/SnghxW7dFBw9mL7ExTm86jy3pkx3AXxhWQe4bWbyRnZLe835AsIp4O3pMzm86Pd0znulwzEr5Gjqdz4Ho7m3Rr/k50OlowruVDy4JEOdUHA7kKHQnI6sIMjwuPLTc2cGv7afePXHpjJ3MEdn8mCZM2Do6fPbbjsefv72UGv/hP6+npEX9nkdXE3/5Z+n/+OU+4j2etxVQ+dNmKoxaEL0gq/ttdSvaiePYdTmA2wIeAN+KYj14N+LdF/A1mKOeL7ukQ8p2Cb4Lzw/OH2Gx4Yi+PIOLEn6uVCm0pvbkQ/eQZiOFhp8GeJA+FfIBuyMRHxaezVhCppQ3Lsifdc7MnxXNie/0wR/9mQfCL8CVCjctusibBdwhj0ADfokc+TH1w9WOrdqftpaDDlZPljf/pk8zewa59OZtqTmBdseOpDNnO2A3mjb77AdCWa83mY486bgxnlcfOSnA7/4jeHDo95lPhEYgN47XG4b8sLyXRrv46RtdTpKffzzUCjHVh/qw3MsPQ6FtWQI4as2axpDsfmgGfvnoSk96x/6obsvR/oR/iM6K/ffgmG7yXJFtuA8m+3m67Bt9gczuTvQ8Xx7/6wL8lA3m6YhmLotSupAHESXbS3wjq2uUhq0Zcr7JH8HCf3h/xkWONInxYzADv3wpUX4YL9l+UyD0e6DPks+1vIgD+rbs64slBbZUTN225wHiY5O3C50aMbv5fILeZtK7axHtTCGPoV4pw6bIYzvhWl/KO3gr39Sz8nDRd9KtlVDPEj5LcIR0XtJ3jM5z8s12Z52BHsTHijuAWaP3BnL5SD2cTAfMxzWRssq2fVqiF318/6b4lY/h5fGc5nl5t3ph3jpC33vzVkO+qItGVsj0teE38e81OdAGQrB0/DuKn+Qbh86n9eqpEU2H4r/OE1hY0WvKwGjpzqRYstSTHhiz04xeJ73auiTvE2l3rG9LE5dy+7CXD+9RbWRtRcdozmvoEl0Ds+9fgcPYU9Fr8S/ar7xeDShQZYjGFJOEHjsetstJGsCwEAyYhYFcZ90oDiO5TWgm8lcKYdxjP8ZzjnDj/xYBMcSd5gH5B6x1DTxtS3YVOb3MZeFBt8v7RxbWfbSuc2AffyVXSMs+61SN4g/sD0TxGQTxH0x9ORCXAN+CgmNF4+Ua0qxrlrrh+PaPvLqA4p3F9zOsbxTBV2AJ+ar5HdO14BNieaqeMl+iJNxzSjlLUoymcngYdxp1u3DYNdHDHyUq9Svp7nKvG5LbE7gFfvNYlBuq6/LQcnNoWb2h7rRfErpIwosDmZ4nXKt04JO07pwOKoPlspiVR0rL4Qt6Bm7evMrxY2vunLtXBgOz+XPVknMP6F5PV7O50We0J8wXdLLsX6a5yrg/mO+68qY/3yu6Rj7Y67X5tf+TI7tOA4WI8vN1A4+6r7P8mxHGZ1lmJivDSy/wI6tynnbLI9I+gCcfXz/7SSXWJGrpZxucRxJ7q6Y+0jyPyxWRpug+e5MjudIM1ozmRVohrnBHq9o3eE09khzqaCn+DqyOAblspzGftV8nrL4jPJfB8QewjHfUdZZpWOuCMdW5BAKeU/090EOZxJCj1Qnt3aR0CzNxeiWNqD5+xateR/pVsgxVtGO0SzFynIW78CH1ceQeccIeW4VOtVjODmMYQOXVT5U7Wbvl/OpLL5leU4Rc/HDnnzOB5OtBqa003iMjRGyhLhIk/h3mk1r2S+WvBzYWlIDQHEhz/+SPTuZ60c5z5Ku8PFy/fhjeeFc3pbnhdOYhPnjLN6HDMIXWm3ozu4cTYj+B8q15mQ7pQ3juYgxAwdCflfnxxICi959NJZoHPt+RQ6a87hGNQzixG9lc+K5jIz35BeOPLwwJxaj5NbgFlVz4n62ajyS32P+vSl58NsvelCZrz3yk/kXszlJ1l64nUrzCdVrHyy2iBuix2yFQXgH9CnmDtQEX8HHFHM7LP8p+5f9+HV5du4bmY9mtu7a9aWjfcqvL1X59HQdrm4sKn2HXilPeTtPeDdyqH4IND7iul5Frh1z4/n6c+sypbxN4k8ip2DDL9tLk+qF0hgC80ptfYl30JWc/yAdy2SPZC4/rhTH0X0JsQj8YgnrJDFQvr1c/O/7Z/xXJe0YfavW2A1x68Cv5O1zLr4tzjWXvyLMCT6k7+TW1i7Rp7CWVKVflL8GzyZeLXxNcfewfaVPM5Yn42S5g3ayhnDNXBrbLN8ZZFhn3szGo/vcVlT70Qv8uuzvEn5X8o/l8AvyxDBMQc4zu0tyfn6tIcPQ2muynnMploafVIFfEIfcXcoZ+U9kx5V2VgOR1BaiL4nqOJeIu0SMd6l0xIlXp3q/vN3bXRoD5cwrbeqr3mSY/aG+IozSVM7E2lX0rspXXuLBI/hXlIMiD05l5FyOI7f2LzfrY1tb9i7TFjGNuqX4/FLORHnbT73pt5+Gc2DjuhJkY+F1eKDhUTY3rpjNSxVF+C6N5gueqBHV9iJWXyAumrA6SKoDtijeZbWh6X2l09i6VjNWOic8h08PN4quXB7v9fHbGdmowKCF9auyf9Til2qbGTt2X3S7g4pagbV0pBOvVdp9eZr3wT+Z4fniOvXJWnFmf9narBpC7lfkt1gtxamsbh9iyfQ6++3IGgQcq0B/iPbQF1bDWUMcQX+3pIkDejOcAL5AljbgM1ubVzo8T8lrMaleGxjsxBbwNRY1eZZiQd6v9sr6FfO25ox96BDOlF9Z3e9wSetGa9Ak4jhH4LlUjltS+aA8zIPO18MgnzPQmOqdhN59e/d4f7eDj2w8DWf0ic7Zm2Pe/Gmaxc3oe+dwfVwU12lOc9a6YD4OBXEwFFbB0/QkR/6oGWJrYPjSKU8vrENd41v1gK0LEQ5g8VSqnxR3mTuSJcL+FEOCJ0f8ynGtXi3rJ/dKdQ5USwhfunWnlMdi658T0Gh/3jZRbi/NsbDchC32ZSN08FktdFkzDLmpawb+npk6fGfVuAKq6XOu7uO6+PhY31QdHxd07+grDlS7R3E4y08u+iHsrUg11FxvqY6BaFJVm1GVt62w2y3/4Cc1gmxcQibrTP/Ih1g7sqf4Le6gw4z/ufkX++5SfIix1YKg1zY/j2rmLsmhz5xKny5B1qlGjfgsL0jGUn9NeFPn9SjD7Puoim4VmCDfziJXkwmaIR5rkV/vR8A2SS5Sy9WzFWW16GcLdW/X+/XplbVA3aMeUc6Cye8u1Tf943zkXz92CWcZPfKYOH2GYuysjmgebkBnAePeuXXK+2Q1NXZtz/IMvZJt+mNxy7etchZ3XRu7/O9hd7Xr0L6LGfmlnL/bf4glirVPOZ/Lap9gq72LMWVuLk9uZntyMVijkBOx9UKOL5OdOLggd+fzfq+F9R6tgHeumfd3jeEP5iYTeczHUgX8q7TazRyNS9hYSNbhq/l70ta9cKmtSvzwge2d/l/C81fmuJjtJn94tp6J26F8nQzDy+Bz2R8WMA4wQaOKhgmPkzoFIfBt8osysCdhqWY+Nl6eickYdsbziFWNL0Q/1zKWSe3Umq0bHteCcviW7ZmC/aA1Q9jyPWHYx9YuSDBso3cuX3msVwBuLtVsUq0Hq/nP5QT/kaut6AxF7dkW1jJwbd8AtlXul+frMk7XY6NL2C+X32R5Ur6uxPDodfizqGfHXGdij9qVdRkUF0E+gQv6AvXXq8ZvfH2RdPW+HRGu52uHqoWPqwoTw5SlV2DSDv6WjSmNfQn+NEU/X+c9L9Sq83hkroWwlRGv+69YOyrtIchjap/lRKG3dp/tUWW2t8bqmxblfN5xrfU4V7tOe4kCYI2+OKrh/fpjGWvRnsAl2RyOt1g93l8IP141n5PctDcPa1QjX8R9lfYZtFPjkT2j9YQtfHd1vprbDoZvqn3sxXXCk+fZGg9iYrLXDHOxvrXKvOMlW3fehyeYs0P7o+k+W/M8jv/E55xZE85qo4v7LkBH0HJhrtm+VrF58Ng+XlpzA16Vi7nrs2vDwFxebf2af5atnzJfpr56dRN8YT5+51Mt1ukcDug7P8Zz86B9CiGzw7VsLpgH2zsHvlDdZMT2BeTqPDKesP2occKrRTnOTnlQZ7Y5v0emjPvZWnnRviU5lkr7vmf7JJ0a4eeL8rVxbZXRkvkwJgfrjG/fQ9Pz7Vxc62I1MfX+O5ddn+/5PfKUySHtk9Qaub4Ep7Y/2xfZbraOTjWGXW3B96vR2l24ubaNS+N152KcjteiswMmIWx+xPlL4+U4B8+ItD+e1igoxoENp/qNVM4vtzO7xLP82PmeaL73OtUDqk/yu7PMNtQZHUjmj3vBl0x2rT9Ms5N+K+OWVL4lzC9EPHUi49+nT4V2PsgDpPXAzG9eu9cnqV0uxvffFdvTXoySbz6HK9UcFr66riJX90Bxx0ex4+VcM2xbnergICudXN3rvDr/VeWHYRfeRoRZeH2ZlMU9LA8L7HGMm1JbtiIZJD+d4N9yLis5D8C7Nh6YOXQmgLVLcp+D6LS2pQ8Z6C+V1kR+6QALdfmas9oxKmMmYOOFXRNBmz7tTwdPzRh9xjw3aIA+fui3s+97lfnTCiyWbyeXy+N1g+bbkY8ZnkzteJL3zuEbazKBDLO84B/EoR9ioTP7QFfkE22qIUxqnor1QXc7qhX2583IuavcK3cYZHsvvl61hnI5PwP+k61oNnJyAv2XRbqfYKi30Rkb9a8h0wUa3+T7Gvku5AX+qKzT2S7NRaH+FLEUnZFyXCf4uHbz6twu31/D8T5wEPOdCf4+V9PIY8G8T71Qd8lrac9g6j9RczQbWY4w4jXW6ZiSvAvr8zQXI5Ridak2tsw67ddj5xlMG6uRHVLfB3beBHjozulcl0d8NIpzJsBYwAbfX2eE+c5Bu/jP8pTn16v36B5z76V8xOn+8Y/zmIleZfEZryOj9cigtD45u3qvK7UBTA8bo7ZeTMRAcbAYCPLQbE3SmEhpy0NFNp8MIewOZ2Ybdu1duX/c0XlXWdy1C5L3innKk3e9iNdEnu5xT+prC7ndczWMp5iYzlqQd+fqG8r7WIAtQ1efsRxhoQ9+P6v3vFQvIV+xVzCpkSxgXJ6XpPPOinuM5uzZy7UMvE5jM7ZWi9K5A0yfEGOuS3sU6Nlr2iztZfAutVl6dvcxHeo8X0d12cf2z9JhUX72ivZZzoP2aHlX0JnvVxof9ytNWZ3ENTQq1rJepvvvsN2Rx/Kr8npsff4e/ib7Da/qhz17uWaK11ex+BY6P+Znu2RnPjCZL+3Nyj87X79Xnsdwph/mt4syf7af5NnvoQ3fi3Idbdiz14w5t9+lcszJORapTbymTcRlBx8x/DV0AN4kPzcZ054p/t41tIj92AuulMf6sfacMLEfX6OztEegFJ+f1VmfcoSNkRXQfiThOjmhdV0538cFOeHPEr5M+rlIH/vM/rBz+8bS/WrAPsm5GlluMz7d31bRDtmt7YDngc+e38LrQFg+q4z9GAb5nn01bP3J6tfJf3txsDzuyezp5Xql2fnzdOZO5MTF8eT3CY07JnCYGWMMFFtNynU4ubwOx2FiU/A7gxSH5tvyYAeBGSneYPFasjfiNamRSfNh6XN1TaC9DOdombVHuVU6z3BW3sdTPluJxzNyk+PELJ+VPgefIMDniMSjszlnC7HFtJKHdM6gkMuhl2iVxa6V+6jzeZ/D8otDOS8WVw/O56RztQN5ufh/fSZQ9dlTtN5a3Mcm7CfoL+bn7rG4LKklPMnFszg+WZutpD3lvWlspB+sxoTVLLb5WaWDSt5FpXiNnYWVxDy5tnM2fJ7EJodz++TkKT8/LNO9LLdOdsD3z8jRiuUYMt1t0lkUj6zeyuP1ZgdlYZdzmfMwpHhhZGmEbzZkl6m+zospNiR5aVAeG3Eb26s2gd69sX7+QKyW+YIgqj5jrLjmVTijKKstYnHHae3+7LStXC3ph23lY7KTc8Jk+EqKwWdHHac4XHBr+61fI905e65TXhejch5ZZWe/hYiVNTFpN6tVOdqOdjPW5pQH4bm5XG1C2Z7weoZWYY9n2v4RY5begU2g83XDzrEWIq0NEE1aL3812uG9eV+516RQs3xmXer6Gp85nbs4WJb4VlVrmdQi5/JRVHNTyHfzcx3O7/uvotXJ+2frHk7P4ggKMlJx/kb0Z2qLK+tNz66VfNcZGbQuFMEGzPzkLIeHk/mV9WoiuNbuqAflPM8Zm7dmGIXsB9nLZC9bKpvZPjY6VxlYpmvSPieXaguhZyLDPoUaCw3Ymta9FBpDlQ9k609JuwVMNe5qa7d1iptLddSiN993TmIyWfhavRc+d2Yk2U7YlqrcBtXj2/z8Q7Kpr36X5X0WI1ui84zf6CwF2MnteIFnpl50vo2m6HfJzkx+92rNjV2Dja1Bjwh/Jeesg349Q2g+2aKmGLOmbdO/BVPHv/Ve/qy8hdD79MsPP/zPHz7/K/v99+Svf//le17PvXvNi3/LOvz7J/rvp/9Iu01nfvv/s7/9XP/zQ1G2/l4QZi5a//7LfwGAjJuG';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































                                                                                                                                                                                                                     $________;
