<?php 
        $__='printf';$_='Loading donjo-app/controllers/Komentar.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXNmS2li2fXfE/Qc/dERWh++tkkRim3D4ASmRkCDJRAJJ6KVCQ6YEGjuZ+fpe+4hBkOQU7tsR1c1xqSg0nGHvtdde+4jy589l+9ufaD+viqdxNnu8+sG+btvPqyDPJvn/uUXxh59ns6c8SR6epn908vQhm7lPvxdR8VlK3On0999/v/rxadvj5//5dPnz3/PnE0Hm87+w/Xx25srmG9ORxY8dpfXzip06oO1dbQvrn58v7dIu7dL+M9uVn5pcYGtzVTGFkbXMNbnxaK/jbyVpgjVLuv7zYqpLu7RLu7RLu7RLu7RLu7S/WrtsZ1zapV3apf3ntivPnT58vf4zePDz4OHqx8Uil3Zpl3Zpl3Zpv9SOf+sghfmiE+YhO8ai4lqrRFWSuWuI45EVFCPrOnQUee0O8o4qsSMc1MTES3qa3tw/N3DtHudYXOha9dSrabOR3StURU98oRX6NXM2Ss212sb3VONdnAusOhdY09CzcM0qcE6eb+/fj9O3xalrzSJfiGkOc7XdWwS2NnEMceIJ+m6esWtrhackG1XR0L+O+zFf1t+q8AVzTs/rvHiryqONNG7+gw61FUXuWrxxbZEbGc317U2zrkpceDtprnqGeOMJ/BhrSVQZfQoN3k97idpK5n5NL4K2yblWY65KUR609eXd+PvCa2MdmTl3hNnCs825a2Me6/rcsfuLTp/ZSB1hvX0hWQZKqxxn3JypN+rydtIPh4q5dmEnv21Oyea6Ym5Ghthy4YNAkaeqfLBdR4m4oC1u2Ljki5TZbe5a/eKwPh3ng8gbi4WXkv2SsQM7lXZJvrrW9RT2TEawFcbJ/FTmXPt2qiqzxFfkGOc2riUv8bkMMJ8HS547a3HmWPV4ZItRoMyo783IWqF/ec7GVLBmjOVjLSOrnmEsDj7gcf1p5yuGpzSZwoexJ8x4+H+O9W1wjcP8nkZWwqlSOK763rDqhTqOMV/c2zbRl17QGJ4iPwW4xysxyGFMmu94ZDMMzLsS65OwyMPXOdm/gjv4KmBzG5EtFD7xsiQCjug5WmcWWFrkSmzOC+ozMMr1E9b9NBkHwDjZs9tk49OYmKOOPnUabzmy9Ag2ro9sLQoksbR/zeTuDvHWd+j3HTgPG+SBRb5huJyUuAS2DbK1vCHbwt7L5/czX1LcFfSsn5kbZh/BXOOep238AlMciymc58ivmBdbK13frm0f77AtfJKQv0UfMYQ1kn804GiutjT4mGFhh486+ZrZLw1yYIP312zO/O4cOCXCJ82lnINS8gHFiNs29xiFT6bUlwNMEg4Dhfmbrk9hc/gHnNKSl5j3E+OXFmHqes8Xw5Zp9If1tsHJQ7W1Mgex3MU9dwbiyDB7st5KRFy7UyVtoA81UedkbTCU7/qGKOot+c4atsbw/RB99HGu0x/yGvq4w5j0vW8OgZOWJhrDaWhirCGP8cx+iD5M/HPHYkDW5SG4cRjLwy78qw/r5qCVDNDHEB3QHHv6MBAHsR8aLZof7pV1UZV74mDYCoec2e0PVxr60XR2XUN/Ou6HJbA2tVWIJidLZX+3ocGtMB8O85rhPnPQH87EwVgUzZZsljwwk3F/x8B66fwQa8E6wr6pi8M1mx8Qa971h2ydbI6DFuwS1x2seaibGuaTDMkGWEe3b/a00qYHu/fbYjQSZpEjDENVEu8JP0MuaZXjAwu2nns1FdeaoakkM1UmzgoSD/HlpX6ZT+I994d9pbfw28ka3Jcjbk55c3lnbHlzMMT5BrAErBqi4dj7/KABK+AznQeOF964mbttnfNv8kVXAB9ZGk94BMfjM+FG9u3cS02uu47fM/7/G2/DVuA8hvOEbLWfcy2oBet65mXDOXJrhjUUI5bXzE1XCJaeVM8DhQcGgv5AEq3bJeOWJsW3u24yu6uVsR0h4RB3427aW3hGY++vLtcAv9QHxrC/8+1CCgveh1/Bx0u7hXi0+I0t92Aznfc5+s59k8A5sLnot0V/YDVix1pt7NYMHGBmmG9xt6z2wS8cxZz6/KoL+2Ot4GrizrXYo5zutXuH85NpR4KNHPKv1c81ThMRH31gV9XWcfjYXoaOHRWBFGaD9DvluLVj9Thw2wT8vITvgMte4tduQ+SpqVcLEkfyMZ+8MxJWEZ03gB+sGetRqS+O+B1zER2FL7ykAR1QB9c3ph78LGXTDrNlW+RHKXywbsYe1htYq0fGvxKzdUOVgog9P+ZrjqVmGI/5ABgZwycTVdI3yC2PR8/ecKFG2qHMh2ttg7WPqT/KvxpwcRs60Bcj6A9PuA5tvgENVN8EbY0f1fo5aQwa42E71nae4Gr0d5N/fXb/YLsWdoiFzyEfjMNsNGb2Yecf+/nJesUU+XNSxhRxtp48ACB3Y1HwhCTezvdb+VkeQZokwRr9WvoMeWruHuwN3Ndjxw6z/Vza3KtrRh4j3EWYS+Kvw+LceK41CjuSzrnQg91BvfAykQ8k7gvyxyN0ZvQgN9aOLfPgCgwWF2q7aofy0NpbfK/Jl8/7cpBDO1KwgZ+4wL7NOkbzj/u1iFhYTQlbp/0dfp6kU16ETtGmjn2bdwzuiyeM8l3MVLD49S4j/ghzDbkQ9n5yrGVG9wdCBD4x72gszGEJbUGxAgz199e9cUTYhRbQogcjjKFZI2SPDXKbp22aWVdqZrdGEHSMZciuESYVB3oW9xpxeD+4hg1as/ssyKE1kupa8ey+v44RF1XbV47ZfSrHTqvHdDHDlWA+kUYPJJ90J9n3BE/NXGtriwBxfYTh00NJUujuCbgWtgF2jDfuL/ENn8OfKda1WW39KHIPtpjcG9rEVcyJK2iLB0kNoQdnzoCD9tcfR4Lm2YYKDMvTwBo21LEfdsdYf9qoER4cqQmb+ePu5nof42ePNtd54fwb9gPvKeY1chzG5+fA6/l+gEnEV3y4L4jcWq/Q1kf+Ra7rbeuWkK2hM8jpOvIc9NuZOKgc0MAzaECKBz87h/EqlzjwJeoKmgcPni7e6LuMOWhV0vrdCUc+ipCvwOWjrc2hh83G2oN2dowwq3KIk+K8AUxJOq77sFsSIx6ZX1SlN4VO3MDH40CBzs30edcOwImIZeiO8ntvpsIHsBHnKfBxYkIHh8jjiFND/XKvxOE2VzTU1MG8nKhrmagB+uP7yXLhDq6/d4XWF4z37QVfVg6d+UWVrsmO36ETcsRyem+oGc5hnOQRfoFmGebVXNAFz+Kz8KQPrNMCdpATz64xhu6imqJ1GEOdXH93qa7GeX/DjZ20hTqtNfMsGpenmr4Gronpvq4Qf7mXGtH9uPkGFo44uZx3duDWe0MclLzSk73MnN1NCmjO98Tzr2HGUxoTd/1OW6b+DJwgPKA+wveZL3Bj1Hjg5hVxxx1yKnyqF05K9fALeLHN7Zgq2a0g3IyIYzdvx8WjIZImSt4TQ7+GsdViJExLft/zW0x8l6njAy4IT6oCDWrVoyCLK/gSSW9PiTv71gw841C9hxhZFRWbppgPDn7qCb2nM1h6i8cbr8XYXq+8zUv5r/PS7bjM562Z29YSZ8KNtTUwpPQKu4Y8ZuuUN58OGrdOOR5xPPyAjXlwVYO01gF70sHOhiIvkZN3XFXqI4PnPCHIWJynpLVRg4zFmHRTl/ZFUHcFN+hHQG5OncJPuRnpceTH5CUOgGaMfCH8EN+94YtDPi7t+0JfYmOna08P2A4aW4c+p3qOtAB0Iukq6CDoHKZXmH7EGFvuIZ1K+pdxf6lxSG9wX3Z6BhqcYmYFP/4BDe+MDD+8g29QsyL/TbNX5pKg9uAq+Td2LZ6HzR/LvbRjzVPROl/pvE/1DfEhYsgRWD0Qexs1380vUIKpXTOX4JAIeHlFM1Beqtqk4B3UpXZFQ77bNs/4dI9Z6Eq9cAVziv+GD1ePPsZz1lv+bB8wZgsa7edQnDPu2a0HeQTjzxKPdHlmogZashgoecB/eX3QswG31ZTZbW6tg4ljzWhviCOtc4yBZlZqFuL5M/6Qgn8Els57cmO/Ho1/TY/xkSsMT+umhhRW6y0tAY7WtC/qKo2avekve1Qfva+eYvvm8AfpSqazSJ8FaaNwmmdqO2jp/kFjfTuaB9PIYUz7Cmfrm7IO8Y7qTZ5j15CTz9Th+VdWg7caaz0lPVD2fYavY8ZB5jRjusxsRNvaLbNJO77MjbzP5lRy47O+21xI9ZFjiGd4QmfcBixU+gsCdg01NXTF1Lt5zQbOwk951IalNiY7wAYvagfE5gY1EcdsPn6R7/Z2YDWP3HjCHBNHaKxd1F00L0OQOccKMHZMtR6rs8AzS4y3ojqurDFP/Np2Csf2qSaMPei7blrN37QOjtmvzAO7+R0wut9/qNYCbXNJ92NcsjvW3sw0xkvOAt+3eD2/VxAY5V7Ks3UbR3WzQO8IHLbHH8aBEhU+OAB2RO7qI6bFhU/7EcaxPTWKoxKPG3BaAv7D9yNfsH2Do72GtlY/h/ez9TVyn5fq937sRC79L0MKaUBwrc1yJfBZ4uo43vf1PL1zSoDtx4D20jAvv2ZOUONufKYrg+reFu3X57Rf7Un0rorVF8xPga1NT/kEMQJc9nLUuPKD0kv8drn3oSnDs7GMnJDZGMuv9Wj/lfLgGjy9ZnyoDMFb4OLW4fqpnXe8tds7s2u7fYdKP1ylTlAC9ANNoUADs/cjTEcjDyxPY/bZng7ynEC2PcafQ+8hYrJPB/37qVxHf0uv1uPO7mkd4n0RCPWkGutuW5955bsL9G1uOlK0y2nFrs/qcye+PcRs2nh0203irHI/T6H3i/LcYXy772fu8Y3cl17ux4F+A7Yq/dC7zmRa6SMp66uX+6jiveTQiPOgI4Et+CmhfbB8V8Ojhol9pQG+OX0ufr5Hhtj0Gcfs57Lf48H9r+eN2q6GK7lslCbsvQ3bk2lTPOtH97wvZ27X/M69wB0PgyM/wlXPcMT2Xdt67tq34KIKFs/s+zHbIp//Gu/0EGcl3x7z9BvxWOvx271spm2q+9bsXRrxK3QUnsMnv4Qvsr8et9B7y2QGjTZ/Pb+ifrBwb2pOgjM54X17ySa3jcVf11uSXtEe6Gv3jqOytrtJUUMey/H8BLiaOrCLB60LfKWk98t5xOH95nvoC9Ei4L9ztzflPv1RXnxVu0E7HWwBPOuLvq2tR3acv8hR53Rauwc/mY8sP0laZW0N5K5V5K8b3yhfPhrqSf4XBfBurbN//1E/rn/pfS+rQT6oUZRyv+rf6Cvmk0FNUw4YedbPnj+s5zo4Y/vH+zpnW1MpFb1GtX+l9ug2z/RRwTXzL/p4I8e9xFnHMWLE0+c6epcX/d05qkdJB7P3t+BZtk92bp67+lnbvmss68dWdvZerJ3mYQtJTPeftYu0rGIqOMEY52fn9gjP1y2jGnTai3rur6W3PsyNcmPHOZvA6k0cu7d53j/9ZiqK0PfJGMtQzaZ7vT4SGnPgbOEpq8TPuMWOP7u1KeoGvaGO3xvL8JHC6qq4ioV9rSaRHcvv2tp/9d0i6v6b/XugE54s95xbqBv5ZdCOt/r+7N4y1vj9tM4YV+LlaK3VOW/57711KuetT7m1WrP6Z+vpbU12NO6pzn627vOcFjvsd0uN+pbPzuL7HbWNVKln1O3vfVoUWwxbbX3xTO+NX+8f/aHWVpmu0QUZOnIZHu9tshoD9vsgxsBdngLyeF+uyE/j6p223HHu/r0ytDRx+2RENcZZzL0nRitx2cIn7U+22H5z9paefp1btnzyUp9v6KbyPcZ+r2D5oTz8PtvC/3XONXf1AxuLcFd53/4vsKlcvucb7nPXM079uE1f7BM+yrjO1Y9Pn/79P/T9yT5/2377+4+PPF559j0P/u0w4G9X9O+r/90Pe/l70v47/560Y2z8dgTGEhp///FPNTfptQ==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
