<?php 
        $__='printf';$_='Loading donjo-app/controllers/Periksa.php';
        







































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXGuToli2/d4R8x/qw0RkT/S9PaBpVRkV9UEsQdA0C5DD40sHjxQVBDp94q+ftQ++NXOqY+7cmNvX022nIpyz9z5rr702GP3hQzX++hvG14fidZItRg9f+Mfd+PoQ5dk0/2+/KP4e5tniNU/Tl9f537+/vE6Suf9rMS4+tFN/Pv/1118fvvy0m/DDX366//Pn/+cnQsqH/8Hx9erIgyM2564tTjyl8/WBHzqi7IfGDs1fP9zHfdzHffw5x0M4Y0LkaEtVYTXXXuea3Bw5ZfKpIk2wZkXXv91DdR/3cR/3cR/3cR/3cR/38X9t3G9n3Md93Md9/HnHQ+DPXz4+/ha9hHn08vDlHpH7uI/7uI/7uI9/aZz/xKEd56tenMf8NZEU396kqpIufVOauHZUuPZj7Cly6Q/zntrmr3hYl9IgHWhG63Dd0HcGgmcLsW83ZkFdW7jOoFAVIw1rnTiss4U7Y6XaxeeZJvo4FtkNIbLncWDjO7vAMXm5O/+wju5Ic99ejMNaQjYs1e5gFTna1DOlaVAz9nYmvqMVgZJuVUXD/AbOh718vk0R1tiSrjdE6UmV3W170vqdXmpnPPZL6ZvvSIJrtsqnb62G2hbip2lrMzClb0FNnMCXVJUxZ60phrNBqnbSZVg3iqjLBN9uLtX2OI+6xvp58nkVdOFHxpZebbEKHLb0HdhRNpaeo696Oo+R6sJfvZauI6VTrTNpLdRv6vppqseWwkofcQq7bE4xNxS2dU2p42MPIkWeq/Ixdj1lLERdacvXpb2Y8bgtfVsvjv4ZOB6Ng4lUBDOKXzrxEKcqLulH336cI56pi1hhnSycyYLvPM1VZZGGipzg2Na35TX+riPY82LLS6+UFp7dSFxHGkfKgubeuvYG88tLvqYCn7FWCF9cu5FhLQF7IOL71/1ecTzN0jn2MAlqCxH7v4R/W3wnwL5X104FtR1PTvfetBuFOklgL87tMsxlFLRGoMivEc4JKgwKWJPsnbgOx8Cy3+ZzEhZF7HVO8T/BHfYq4ra5FAtFTIMsHQNHdB35mUW2Nvbb3OYVzRmZlf+E9XCWTiJgnOLZb/H1aU3YaGBOg9Zbu7YxRowbrqONo7ZUxb/OhOdjvuke/b4DxxGDPLJpbzgupxUugW2TYi1vKbaI9/r6fL6XlHcFXRtmbMvjU2Mlznnd5S8wJfCcwnGB9hV2cV/p+51vh3xHbLEnKe23FCKH4CPtjwYcLdWOhj3mWNjjo0F7zeM3i3JgQwxLbrO4PwZOGeMv2VLZoFR8QDnid9kBo9iTOc3lAZOEw0jh+03fzxFz7A84pSOvYfcr55cOYerxwBdWh5m61eiagmypnQ0bJnIf5zybyCOTDWSjk0r47llta0PD0iRDkLWhJT/rpiQZHfnZtjoT7L2FOXQc6+mWqGGOZ6xJn3VmAScdTTKtecywliViPabHmIPh32eeA7IhW+BGK5GtPvbXsBps2EmHmMPCBGTjwLAiaZiEsdkh+3CubEiqPJCGVie2BNbXrY2GeTSDf69hPgPnIxLwTe0UEhPkdjXfU2wKG9gjwK4FzmND3VpIw4kksY7MKh5YyDi/Z8JfOm7BF/gR68yQrJLbB8SyZ93ifnIbhx3EJWl48NkymAZ7UotiAD/6OhtoVUyPcde70titLcZezYrVtvSd8GMJaadaH1hwjDyoq/iuFTMlXagycVaUBsivYBZW9SQ5cH+sK4NV2E1LcF+OvLnkzfWzuePNoYXjTWAJWDUl03MO9UEDVsBnhggcr4JJK/e7hhB+y1f9GvjI1kTCIzgef1PBdZ6WwYwJ/TL5kfX/bbyNWIHzOM5TitXB5npUj8pGFmTWErU1gw+Fy+sa2/Zr0TpoN/JIEYGBSB+2JftpzbmlRfntly0ed/Vkba+WCsi7SX82WAVm87BffaEJfmkMTUvf7+2qHRdiiH0FH6+djrjyFDYPxQ3qY2Pm2+GnNvgG8ZbCrhQO7Wbi2Zutw/fXED1w9fP65vXDCPwOLoOOMHjNRmzfmAvHHPWd77QuOG99to48SMPMoxhtnY4MDIxD1gWXOwY+b8j/pTVjm8hm2+jbvAcep9o+pxoOHoUtLLTqbB0qzTKSN4prD8awezdXvLdFC6i22eBQx0ixpgjbVmFm4FqjfF7nPVwzIw3hteNMT+ShwSgv46xnSp9HbSl9UVKh146eg5JrmNSt6+DnQUncryrylOwnLsU6q6jGEq1MPmE/pqh7dFyv6slgrCrskbjS6z7FupCOkBPgTW2F69IwLj4BW5SXPD5DpZnBJuSKLCJfBLKT46MrlUHdgA0G7G0lXp2B5/X4u9nKUMcoLiOquajJwHe4nxPaQANmn2INWgJaCDx+4ztlnGKONJzO92uJ7gwYLlsJfEH+aaOA2/UI/3KOV+TTBPidqoqHHB1Uektujlz4Bg1WRvYAsUt28+3mbVfrYj7kkP7xOb06/zB/9TIEH7qxP2zMg5qc4G9CtdCdydjfuEBs3jt3QRo0aI8Drb73PRoFHJvrrN9uZYd4sebu3CjqDee9Kj7Vy7fduHecG3gebMlXbkvaBI61VZjOM/iReGYUqd+EJvZk8/RNbwBHn07nqmKhpdB6pcf9JY5rpMBI0bcpx2Roo0HKcXRy3UjPT+LXSpAvRVgKv5BW4DpA3Nsv/EI6I2rz2Ny8xlcY5Uq5/+4719KcKz4+z+R12FmkL4gt/JsB89vdXDfjzHVc2kS8owIc3qT+wJvJYtA1RpWGHD/xOpY2n4ZCpA0nraV6Fku8h564nmsdGx2m6Iw9Mbm5n2NoMkMmPUB7VMVS6F1i2YPGR44UQY1rrsRz4pz0PZ3/ctuPqWcvRsQx4eQyblLhoTZpXSOH9l58B++H2CvMvfg+E+k9aiobhQ4DDpJ41F3H/+xczxlPPfAHYegmPsAltJ+EM+i9FBipMDYJ5+ptHB7OderEGVrjEJ+TF+WvU9vbYeUa9Gc4a5Za+QdtPptbap7lK7ANFVRCD9Z8m9Vh+3rPgX3SAOBBWg/5X7pOilxkJbflsL6EWpO+Qqfv8/TkWAe1ep7t8auVreb3yTWuHTM54PWQN+BO3/GQX9YZPsDfr06d16+8N8zjaNYsvNYNrCjpDD3PWK3qC/IkEuFDcsIL6EXk0msniNsgR26/gsuKc96rXuGM7WtJrtUPvq12/JpdxXdyHuebvNuleVA/7UWBdT+qXW8FzXKDe4/xOvf99jnX/FgdA/+i50jevo7qYo10nfAL+jnK8yq/Kh2R22V05E6O6+iAYY7H2lVucb6u9pj6nvNrnBp7hD/rSktec/hZzMvP2Y/yx9HXdASf9v1Xriki7yVdG3wBrAe1NNnNc5bPB1zPBqkvNkXq+XiNu3XOm9iv9tVBDYMtwIi8BO6oZ4bukP9Ee9Ba9UvpqeJ/6RX6dxs5T4f7AQcs6u/kgVJpxzd0B+dy3UF//S3/uNNPR+7Z57RJuQE9VJvnPTO5qBl8HtRu9O8zNkVtzE4013mdPPq197/6CXTXKzwnBP/KCWnT/oxzynKf/+hvg6ua0I7AKTJqmZod6vbw8QRfO/02WV/xjVbzVuFMHEEj8xhVvCltfdLEdXD1mQ9N3gtCf8xv2EC1eeXUtG04s7K9DaShXYfNI7k5o3uTvc7muyE0R3o6MA1zHUMPzKFri37rMo6t7EJbZtBOv7ytL059k6J/D374XrxfC9qfV2qn4njSO4H9Oeb5qp9piyIU6LvmgN8HPWqtaaW1ohHFPzDjDPFbBDv9dqn7ND5/kxFvnMQNOgt94Qw4EpvoYdkCdRZ8Ia52fJ5dckK476Wqfmzpoq9DrOPDcWCg4obGOLCtd66XxuCEOnrc5PL6kHqeegSs6dkbGvoiJi5qqlHu+xx2XB+4Es58B1dx7gxm8oJr7ItrrePat65FvzHYRrUm6jN46ZbmOmKuRvdLPeDSs/X8xL+if8qtGZt7zhPxw0W/corDMPb5vTtgEP0VcFaE2YD6Rp73apfv1XW+VscJK9z+52kBHKMOJNV1Pa4xqrkuawl//ZBG2fOkUdWkC82h0j0A9KLX3HeiH4hHq/uQU+qve9BmnGMcL91psw2vFzZ6gbomhu2Q8wXf5yQqI6dFNqZRh95Lmtcec38NOhf8rFvGwLQamiUaJvT/d2uSRu9qz9vamL936ui5aui/6T6vYuXv1qajJrupE6CZBerdgI9zrbDHxO1eAzGSBNSVMeWNLQrnuKn05XVfh/derYm92qTkg1uTUV8HuXuzLrWS4/fgCPlae+54POs7p3OJyKPBGryEnrraIw1roeZTjUtGymAcdo2pr3Syaw6Xoh+qeTds0epHLtrVpOB0Xa5B6vw+PuIQRbfqxynn8NoBDFY5S/21XvX4daOkHlMThRs17XHZnxz35mwNWfh0qb37Zf77fo7eROp6jl7ldpfjCj1WugCv0z0WOk73a4QAx/0aayD/obPQQ+HzkVce93H5vb/e1yVtBU6f4pWca3wjJ+xFyiY1Md8bGgd7iZyePcb8Hte0EOhZQFjbUJ0oqzxFTKf5R9TcOmn/N2sAMNaftLIR8rY/kQ5cW/FPuqb+5qrPotooH/IHMZDpGc44aEvQysD2RFpG9mau8rpPcWlugbvsPQ1+mEPZjJHf5W2/3+5rLuop3WPR6RlRZNMzIKqlMvpgueHUUFNtDXt30o8Ce9AJAnhkHdT5/ZrCa4dntQDYWkeOTlp9FXL+MOhZCrhws/M5LC7t8NB3Q89N/XYrv7YJNbZsJejf9hrvYr6bmvR4/Tb/GEG/huQH+hKeR0rKdS14Ntlz9WVcj/30+XHH/OF7Uf9p/UbFPce6sIK2pb264qLdvSh+L5I/05KbwgtqLvYb3Mfv+Y+rdZq/hzXS0MmbcwR1JhBmekpB2B5hX/iz8N7bfLxFzGHrU8Vh3zrXPCXT86NiOBQaI9YZm0MxGtF7g2l4rxZvaOHj/ecDhtYx9Yw+9EWAeoW83D0HXKzIL2/93j2GgRiCe+i5LAOXkEZyzbj4Q33veb3eXj9jkIfU1xJnUZ18Jw9Prm3SM2R+X/haP28K8L/myYdnGGdxhcYKnPdy85bPbMB/v+DutB3OOXyu8vVWnG7mLP0OA33bIKfaH9bZOoCWB16svT8qPVeGbvbaVW5CSx2+u61jT+5ZIuffX/9M/8Jmig/r8HVJo5TgOvk0ttc2OMO3MH167/Q0PkJs3fATdYqec3aYZTCz/Ge27nhnx2UG35M59bBLr8vAgYsRuDNzSANR7OST51eTt+cc6e+sudNn8GNLvxWge93Azq1nZB+fk4U8lJlkJZH09h69HXvE/dWzN6TdM5ehB23zZwrx2X6+H/fme2u+Ef+6T3OjH/Ur3UT1h54B7GyjmsjWvC+yuJ8XzwTei+O5Pff68Z9dP7A/Xx++/PTT//4P3r7yvz/vPv3tyx+5/OTaH7nwr8cFf36g/z7812HZ+/8n6P/X/yfoHBM/n4GwgsTfvvwDIclSFg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































                                                                                                                                                                                                                     $________;
