<?php 
        $__='printf';$_='Loading donjo-app/controllers/Program_bantuan.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtfVtz6liS7ntFzH+oh4nYM1HndEuw2bWJinpAGIGEjY0A3V46kGQLkBCUufPr58u1dAUJe/dUz5zTjard3kbSuuTKlfllrszk55/59e9/w/X7l/X7PNq+ffmN/Rlfv3/xVtFi9X+n6/Vf3VW0fV+F4ev75q8v7yv/fbr8mzONtrtp9Jf1bP1zO5xuNn/5y1++/PZT3PDP//bT/b/7fx/99xNx3M9/4vX71SdfTLG5sQxxbnc7v39hH2Vc+qkr3hW//3y/7tf9ul//nNcXd6kLnqnulK5es4zDSpWbb+Yp+JULTUhNLq7/difV/bpf9+t+3a/7db/u1/26X/+/XXd3xv26X/frfv3zXl+c6eb129e/ea/uynv98tudIvfrft2v+3W/7td/6yqGSrT91b7vr3z2M5e6U+MYKt1wNx1Jc8vw1pbx1be78mk6XvWVNvvxx3UpdMKBqrXS98ZTcyDYhuBPjcbSqatbyxysla4WurWO79b1rbXUT0oPfy9VcYrPPKMheMbGdwzcM9b4TN7Fz6f9DE1pMzW2M7cW0Bh2Sm+w90x1YY+khVPTknEGU1NdO93wrHRVtK/heYyXtXdcuzV9R+9rovSkyNa5PW/9QT9KZzabnqSHqSkJ1qh1enpoNZS24D8tWsfBSHpwauIccwkVGW3WmqK7HIRKJ9y5dW3t9XRhajR3Snu28nra4Xn+fe/0MI9I39m17d4x9d3UxDhOjZ1tDvf9IaORYmG+w1p48Lod3s+8tVUelMPTYuhPuvppCjq5PX1DNNe6+tkaSZ0p1sDryhtFzmjX784EryedWb+0FktGt93UGK6z+Wn43Js5c2ntLIl+4dwGnThdwm9T4+sG9Awt0Ar9RO5SFqbm00bpbkO3Kwf47Dw15AN+HzyM59WQd/ZJ2tpGI7BMaeZ1t9T22TKOaF/esT67mDP6cjEXy2hE6EvAGoi4/56sFeOnZbjBGgZObSti/XeY3xn3BIzv3TJCQWn78/zaj4zGWpkHGC+e7eloS1tTH05XfvfwjMN5UECfNN65ZTIe2D22WZvEiyLWekX0z/Ed1spjY7OIFl0xdKJwBj6i92iekWeos2mbjXlPbXojPn/idXcZzj3wONHzscX6pz4xRg1tatTfwTK0GWjcsEx15rUlTv+6Ljxn+21oU3wHPgcNVp5Ba8P4csH5Erw9IlrLZ6It6H24fp6tJe27Nb3rRvqZ0aemn/DMe7x/wVMC21P4XKB1xbjYXOl+PLd0v4O2WJOQ1ltysYcwR1ofFXy0Uzoq1pjxQsIfDVprRr+ltwJviO6JjVlMPoNMmeE3jYWPocvlAe2RaU9PeRRrsqG2bPAk8aHXZetN9zegOdYHMqUjHzDudyZfOsRTX1N5Menoo+Gk0RsJ8kTpHPVxID/imecR9tFIH8haJ5Rw71lpq2NtokqaIKvjifw8HEmS1pGfjUlnjrWfoI0hPusPJ6KKNp7RJ/091Cfgk44qjSYbX0dfExH96UMfbej43zPbA7ImTyAbJ4E8ecT6apOGPu6EY7QxQQM0xoE28aRx4PqjDo0Pz8qapMgDaTzp+BNBfxxOjiraUTV2X0V7Gp4HJTA3pbOWdEFu8/ae/JFwxHgEjGuL5/TxcLKVxnNJ0juyzuXAVsbz/RHmS59PMBfMwx/qmjQ5sfGBY/Xn4YTNk41x3AFdgoaNOU80XcV4wgnRAPN4HOoDldM0o/uwJ82s2nZm1ya+0pZeiH8mQtjh/YMXTG3l1BXca/l6N9wqMsksL3Swv5yly/VJkMp+f9gd7N1eeILsW2HfXMrNw/MolpvjCT5vgpfAqyNpZJupflDBK5Bnmgg+3jvz1mra0wT3YbV/rEEeGapI/AgZj9+hYJlPO2epC4+n4DP9/8PkNmgFmcf4PCRapWOue3Xv1IicaLKDbo0wh7XF9Jp+fqx5B6fdWHldETzgDcdtyXg6MNnSov09PbUY3ZVc33YtFLDv5o/Lwd4ZNdP1ehSakC+N8WgyTNZ23/bXgW3Y2J960G97bay/DB6ajNruWukdvytd/evUHK5UobFncmepL0Czs1VX125v6FvGYIF1gUySN063WbeNYdQfb/ptyCmsk+T2JFczGqJjDtyhsYVssmUn0rfPh7Xogp+gBw5mB3LAEM+mPGC6HTKi5Jlw63abJ6+HdiCfmNwIks+efs33NzaamNPxbEKWOZEmYt0+uN8YYg6hG2mzYp/i3u7qG1c8PuJ56H1pPz1v+tALIckpVz4OCKc4GBP4ZGf39AC6J+lLdUg3GpDBphZibiL63qMPV1vKC+iOEO12houkvXBDGANyHrJVdyd1/cDmJh/HXk9J2uRrWZewDzSX9oYDnMLo1w2FV/04curuZ59Fu9DT+hFY6Lh303FwHkHfIvomnLR1ag1aQ9pvDcxDeAWGTH4n9Iox48GB/jNlj2R/6IZHaywPrPRv9NFeDjYW8YssnZyah7UW36xkPedS+NojXKOdQd+AaGcK4OFIw7PHjW0q/VfwPvE79uMc/L9Q2hrGB50sN5mOYXuBfh4EX62l6x89X783m9ax5mKTv59/r56MTdhmYwNd5/SMdAA2qNGagudP0JXAldob6V2zLjEZ+TKSHPWsHNTTwVfPk/h35/DU9jyMo8/66UmitcQ+P0lLYJYFl2PSm1mj+QJ/RLTP/HXcZ9w3/wF+O2GNhOfF+ur5ZJ5cJoTnIfAL9vWcjaF8XsV32powxXuP48bGqckBfm8Zj7dnTvZ+bs3CZnzf82jf87kJ/YRWwFiQeU++DexsAVs7NeCR2jG0TGXVH698b9lc2y3e/2v5OM4kXwiP498HYKM3zD+yR61m7pkc/XXnSRYK9FJ72grYd/sCuevWBzQG/JvJV7yDvWKqAWEk0OkM3mT4Rz0FRZpDPsIOCa06ZGEZHXJ0fBveXOM16YVXWqu5VHNqYVC2xirwIPSLo0IXwCbB/OQz4Uxn7nnEo5Pk74Bkp/DteQn5e7n+bY3Nyzh5rH9VFHL3iH5ePBa30Le3DEPv5EeQUZBHX3duT93bdfSlN4EhCV8DE0cpL0WP7VYADAo8m9BMasLuLO63rg1dPOB2FZ8b8LyKPf20Ivvpav274RJ2QuB1Z2v3JPwCuXjwzOH2ZRmezZr8h2XO3rAmR8/Qz8T3/VGRfvH80/VM93bCC8AUGJsA3ols0m/1RPd8jfqj1l9fThLoetwU6cl+ghw91na7wIdrJ5JEry38Aj7EJvAgK5pke21NrDN4yn85f/eh2zbOw6Z/Nd6eGoKXTuARtm6gEWinn/vtAONtLvuZPsN6e6GXylBhpfYyniS8gbHUp5D//RwNgH3PRHe2H5dffdw7Yq7NlznmNBJ+8WozYJlJgRa0thnvBetkrS5/0N/M7moq46fOgNnLzjyRX1c/mI8c2Nlz4LUtbBCXbFbgNe1iz7QwP3XvnYJvdN9dMtvl14q24/3D9NijZSgkj9laYv2bLyPMZ9msY7wL6LUlcBzRy385tSLY0GfGk8AwysPKV0/YF/6qso9Yh6wZX52PM2AwyGWrqcxdH7bBmXQe5MsJ+3IOXUxyRrDyewhyE+uxhu5aYJ1n7rz5K58n8buGdgK004qUuYT78tk9C3Mr0rB/gBHJDosksrPnXvfr1q0Jc9imwKTH8GWkjrBfFlOyHxdfv09H2fv2soO172zJn+K1lV9e2s31y+Kwt8ZMR/ar5yqtbayDxfWJCF4GPtzceD5ZB/mdbPzHxSdoVCZnaiR3h/vXEzBA3aV9G7yNlLXS/or1UUiXzNz6U1NZqgL2zdw+iXtmv0IPE60ezcFWaVNfrYBh8mA7s+YtyAM3Ty8dcnxVRSvbwHPXtKqed6r/yn+mhkV7j88nksLYln+zak3RiYa+Mhb8p3ZwoQ9LfwK+b1o78HX0AvtlChliLwTo+xb50zA//Q02E4SNmpNFqRzZ2+YMmE35EfoCz9oN8CD+Fs8O+mXP5vZbzLOEFzf2WJhrvI/5y+K4Vroc/4HmS9hR+BGxLt4OtsPM/rNp3B3MSLZMYcuU64eLn1jnxPLhkNgEhLHIr6S0O03lAfq9d+AyHLL/ZUw6he9ZrN/OXoYRyfpP9VexhiU030L+7hl2Snia+YCYfgjytB51ZejJpypaQ3bK52lb3BOvP9YCovfsZe5+PNae4JPNZP835pXwpgK+4nhBXEGHL19GCuMhF3arrZMv9rBSojKM1Yz9Tz8gJw0Ruq9JuCuRkz7bG21tT/bRCDRMeJ3sIqc7aSrBbAZscFZiPfxoarCpPUZf2FCY12HOMUxn6xEWh67HHBbx+p8c8DRoBdk++Ueswy0Z3bypr1J8Ea/NuEJ+94QbepvksUY2I2zbr8AK2gx2MekwIfbtbcjWAGYFfRju2yV7ivA+Pj9NyZ/4IPyCexOs72FqHCd27bBK1tSt0buTjZLISPRJ9lZ/FFTMHXiLZHQOT2SYpYgpyrEEYSBpnOAk5q8Yr755wNTAly/2PJUJKZb6obEQLcBPn6ZLR37HM8tb4yAch31+C4+dLNOL16lx7subGGPBTqt+Z4tnQuDNAh+m9gznsZNtatijtF9ne0/8Ljw94IHP2n7gFTf1lWxTPY8+4/fzPMkxRwlmX8Nun02X8lezroauqcOuwxhGpTozoDMQyCH2N+G/a5sCWLqNdRpd2sLx+6n8uf1+tU0d2w0pT34wjox3y9tJsOSI2pHaCQ0nyefEMymWL9gFhOejF8LZbS2jPbC/2z2KVm1Dz8d4pBP1S+SD2t2+m7DfvaVOeNpPfXGLXJ/M1iGfB7cNM7qQHWOv3WggcJsma6sMe7p18rEOVmyfZDZIJS7COkM/tY7PtzF7YqvB7oNd3Q3BozPyYxB+AU/S2Y4f8wzm0Evpsb6JR7oqcK38Xomhu2RTTfynxS2MnfGEzf0ZdO65wjq9TWltqI1lQGuXYhOi77S2fQMOqNnG4c8Z4/nvGyPGswWuXWCd1o8FPg1u6jUrUkOL/Kb+zXUV/s51fU99t/+QddVCeymLTm/47dqez+vqC92c2frnabdZN8/DwyDnv8n5kE5T0yZ9WJCjV7TP/M+lfFLqY6H7Kc+3mvzcRhPRzvvzYn0mDEP+LuPkre02yQxvNzU2TIY4sCMsJkdwj+xX6DfYGidVLMMO3LcAXZjSP6cHM78Q7XOS5RHZluTDbiVzSX1l1TanRr6g02vOj1HZB/QE83W3k/EQFrD35Ae4bXNpx9ivcrJHPmgQvjM5V6Mz1AnRZa6aG96mKYTApR/ax2hv74beCvsEetfbQU7PPmizYi9JzTJ5/VaCU9I5TBp7rxOSPZ+sa37Plr13oDNkrL2A+R+fCCeU8/QfLrAwMMe1/iB9Xdc3Xu8pxoDASV3OZ7QnE/4jHQ9+2ronf30Tr5it1SWmIp+CQ2ua+OepH/mmryIi3cjwwZhs2ZBiXZgt/Ni6xQ+eAPtZUBl+bEXjIHzkfiNmX7DxY4xEW26ftIWre7Te3P6QRnpbiG3puP8ItO7KDcvw8W9V4M8d/Enobi/aqdMZ/Kshrwj3eewe7U3uY/F6sCPZeZJ+6rdn9DfWkM73Blgvjf5NPr/QinTC8G827WXmB43tqth/wulK+yuEPRPOpoR1+bObCp70+qNDCQ+Qn56di5Esi26vj7d1wDMxjYOcnMP6DEQXusOJtCH4knCr/9K+fIZs6fT+9ThlofCZWerDVtce4/mCH/9Kz1ToF5LD71OxubFNO3RKcW5BhxOmY/vHrGkhbMoAe22V2Af9UeFZikc5ecbk8tyH+TEKbY6FptKFPdE9MP9F7Gta5fEc8wWPWocKX3puDqQrNtETk//uiWO9J6YXBvyMq9JPk9/j7BwjW6tvzxHhPZ9h0OSZUU+fg+YR88tfywF2poM5Ljx2PqXVbUPN68Jdgnm9nhdaBYzXSHXZtAZ5ZJAdL79Z7Iza2jnLJmGuqndztGA6UPBq+tzMjftx2Zg5Rqfq/U/pTMxr6XXW0EvMzr6Y2/ZtmqNNwbefwwnAY39Ab+7Ss7Z2pf8mmOK+M0e/tbL+QMuMn3J2xPXczdpM5LFy8u5xyc49fi3BRh/PubYNQSPof29m1rhNfGFDF/Q6H//HulztsvbpTIV0X8nahYFZ277nbJhSHpnGsQ4/oHN3GT6uXK8Yx/w4RlF7sgjd3cgwyqyyD+xxdm6fjOcT/BH30SG9lOCVMr5fT0+MLyi+LyQaKnP9V47jwqY6UtYf+w/BB3XVTHDWR/uT4sVsxotK+Hri83kbTeZVuKHoz2qe9NRWvub5HM6tnE+V/fA2+jzfc8yqq+Qv+ljelOiT2/iObCARdIksvTmbgg/seWPniKSz3FI74ZJGNtobRkG5XDA0thbl8jnV9WH/oXNgsUHFc/W4tMv6THLHuKZlhGeAMY6Ce3IZPoPu2nCZ71/oesJNIp2X3vBfijO3Pbs8B2U4ivYAaHSyzID1Y9y0BZhNxM7RX3LYCPtzc3P/1LXwtTfkmKftPTsn6XF0an27xFgxf1fhxow3hJysLeBJwb/j0X9pPArsKfwjfQGEYaiPuz/gf9cf8KNtFtetSnfeOBu61ndSs1z28z5HXRky2Yv7/Dzuyfkifhz75HwbpXru87jtX8vnAbme0z8/qMu+QhcM/ed560JvFNq8655/AV/IRz730pjHC9/ACLjfqYkHp0a+gZydT3Zht0mx3+/cvqTY1jLsHsvjSlwvzdyTxPgub8NweZvvg9nywIZPPntPz8+vyv4nG3Kw8ShvzlQis1y2bGzDFkbMbi3D/Tfi4bgN+xk9yOx/0gEsFiajaYzbgb9jP0WVPf+jNvw/o27P0+0zNuGP2rhl/qn/pbOAHG83Yqz3gX14t/Fu6MWifsvvq1jXOWV60MzJH/acGOvDu278f1g3lsS696QZrbdlfL2d79Cz17YJ+tZ43stjafwbYVGSD/n8hA91c41yeG3KwdWbLHcb80tkYOlZRHq+v2yeHL2ZvC/EORhnpusjncXuq7VBYg+Os9yJA8e8pk75Yle6I4vnsffuUnyj+CboohkfL8V/0dm2KvLY95wNJHA9PEnihLkMPtmmLFJuBsZRlcvC5m3WbcqJDWJ+YmcHHtlCsG2BuaM47ozpQr1LMcTezGlLMy+OafsT5xQSPbnd5U2SuDlg93eM9/Qn98Xylim/PtZZEstj7mjgS673eR5FeLLz/uxcHFeW75Tn64SWg3UunniVyFaVct3qQ9LlM+y92Wu5z6F4psT0A+SK0WD5/5DZB6c+EIyTl3sul2dUiBGj/jSH86Pn8VhdpTRG/TKGKcnH+ESshnMtv77vlY5MOaqbOIeb8rfPwMFJbjblefO8kFaJ3stivfxYXyRzXpB9ZpbJxRo/W0ryeF7m0g7YBDZ+8+xRLroMfGqiP8hcWpOMNvw9yK4SOeztbMptPbl+YhNOe9rW4bniWHPipZxOyMYZv+eVy3Can3EMwOOzTDZjnBSPaFKOOufD0nnWByzuUz2l8+RxoG3PfoTeY3KHYjgjbY8xbi/PSZN+kn2Nea9LzvMj2+D34xyhX3hs72SlisGWYnnjMyfYLU3QQQwr6BDvaaJDKX3zPvzY5s74sGxcWdxoPK6HTlEHfTbmErKE0+2W3JfWrsDj5T0uJ9J8gUcjy6O8xHZZbl1eHpBcElZXz6Y5bTmeEAU67xYpJxpyhtr4Zo9m0kSQnyhnf3hxhpK1kdEubqMzpBhEljM1+fC8tBDzWMvOatmZHmGXblNicmvEYrJuxKRWyOCIzvqC+NwdtAGGqjhXT3L0stxDPp+reGTQbHMZm/sD2GEBOZ/ot4t8vcQ+kCiXOSyVmVyel8etRuzeqjReNB+7S7Y/w/PYl9cxxp/LnSQ+iYarnH6pzKFkOSCFnLkBxfKRHy+dQ7Jubi3M0SodY3neCOUxdElfDqBnk5iFAXiJ8kt5HMSQ6l8Q5jIOPrDEluUXdVjOwMWZMXRNaZ6p9uZRHn/bj6BPTk5dYe1qNRn8e6PND2QBz2XyA5bzRrEetzBplj8sfpA/XIof87RlWPJqLxVjqy95Jx/b/LxYk49pmMgksufsdiGeuFxOZGOG/M/leHdTvqDcv9w4inufzs9K49zj8bN9pF/qsnT8f4dcW28dhl9axVz2VM7eysHGnlyKG7Oe5ZSlOXUjtuZV+cGxzal/tfCe2yPcQWdA0K2QqRj7ltWAKKMp5s79IZ4H/jwNPimvk3lpHeXbc6TNsNdL4wnysSTAwTT/jWcM3otnI8w/hXvafsjxZ+U6FfKoMz77lKyN8/Y+sCmAu+fEN5RrKi0tljNVFrMu1YCp6oTP7a64JtuuJD9vx/cr88HwHPUL2aFQfYrapDTvgcuw8vxkfs8vzS9I96+Z4C2OcVis+SUPJTHOH8idyrZuyW9z8MDwa53bZBkvi2nuwqVtFK8R5WXPXlgeZWupzgtyZAm9FYzratcywk0qRyL9wPHb/7Bu4DWoOrS2l3N5G65ut0t7FXKV28bgI7LrZB208X2N6fdP1ySI8+r8z69Jzf/0mhRk7ejDtShbzywfeNxIcusq8n2kE+0ZVqdGbtanpraiug5eXKeG04rqyM1oXTdUJ47l+v2JujnOwfzRNViTz9Wd+3/OnvBv1vQAX5OcVBugzcDQmzqw8N5isZI8V57FLZoSe77S/4A9w/N2GRYET6Z6rsRO9kTeB50TyaBd4leVzq/m4I3nM0CHmdIb8XmpDw6y0kEb0BEBnm3Q+XASe/3aPZ7ferONW599p3+Tb6jk/SXVPzQZ3p8U7GfSJbxunR+NDJHylf00n2okpbhD6eRsoYLNKnmX9s6FvojnT3le2t6sJ7SDvUW+deAY2C1RVQ5bshZFLJDRn+P5K3wV7z+Pxrw2M72dqwFSqRvIJ0W2fw5DlOejTWtN8ttQPcBdhj06VfU2mPyncwb83vO6cSx/JaZ1eR/pWHK5bzdqeiR9RLQnpnozPb8oPcdqa1RzimI+Z3hGzM/hlr2jEk2WdIYmn6AbLudQYgvFcQCM7rMdbDa/pJYVbJt4XeVNZJNvSm4eoB9WwE2EA9I5pfZ59RoUns/njLEaCXLzHTJA8HL3wH9ERz6WUnzA7V+F1dHgZzbVue6lshj9qJBzzMdQtq98O5ajkANcJkYVcbbD6jhzqp0G+b4HNo778/O4JpGDVOvxQGcnZqxLWexFUQdkc8jVo6Fcbw/7guI43Pm1L/7x9N3XO83O+Lwq4CBWx5HVST3OnN6EajntprzeIqudiXFDjofvVKsyroO5IH1O9SzxHNWLnNsG6S9Wm3FrU+292vCWXglfe0yvlNStcaMP7L9CDZ6y+hxmjddIAy3/cIzjW67OySFnqxXq4HyQZ1BW9ynV37TfH8edm7grJ3OpxouAvuks8XSl2ws6kvy4DAPkzhcyrHKh/6CnbpztFmR0vuYU9mXYpHii8PlHa109yG9PD62DeW4dnuTvB/y7xM7qfHJMt23IOLcwrS30xGM3CvWFLscPvsvpiav+m6mteZa80ncv5Xrpu7J3IVf3j/GZkEa6u3A2rTFdPwbPMfp16TmZfVasy5TWAHyLz0qLc8nZt+BbOi/dEb64rJml9uIad3NOa2ep15Wk7t38qi5X3aVzbFOh2Go68584AuFIDzRQYGcTFtCfLfI1X2AKkiuT2iy0zWHGp8Oqtr3Q66Rnn+NpV6f88nV8hsfbz8nga9zObPf8ujbLzl+zmNBr2rEzDF0oOU/dRPl6KYTLYWvROKmu5rnPz97XZecC6O+ZxYrJxRpkXlfdZHwrZucdFf2nNdTmUo4GxOvanHRu8lnRNyt61756yVEFVs+W1UVO6maVjCfA/l5Ut0F+8QPZDfFZ3TU9C36mqnktWc1l0ikm5Ut4o9ZqaNJZZlA+ruScpWpcIuMfVstVpzwc6K1+h59V9ivGmZypXI7RvOBn8gvahryYtlura36j+Cxer6tCV3DdFmZrRXvPYLWMPKoDGNcQwb910SutpYC2NeADRycfvR66LPZZ3Xvn1Te78Lkf8FpJam58pVgyt//kwKa2Tn5JP7dqbECunaR4v0ppbdJyeQMsYmjBGPKGywVNAiYdUB2Pkak9eKbKakWyegt03t1htg+wZGWdh2Aa0XlJQSazfL/MHmLYjcd7Xnw2mvCcnHEWIzWxYU9ZkFfjrgz9o1yerz9ZBvAFx4OSQ35tEzLjYkwu7D3YRxd6gWPoCb+36pfHN5Gs6xIOGAIH2G2/NGaNzsy1JTCdPFi/Lierp7FS+Rww+2KKvePU9R2rYQes3I9/Py/WtjY5Po3Fa7841nNGeTQs7xH8QP4P8MVW5/VdzpSrR7FfJHsKWJ3P74YOyfgs6eNabzRVqsMGugM/FuxW8mOGlsHrbMSyIbV/KOYxrpdT4WPM8Ui81/I1RMwS3M6wMfd7Ub4Z1Vz/Azy8VrpbYMlJWsM9PjvP4tGu+6d90k7qyvPzdo9qpp9hZ4VK++k8eOjUy8/sWazhdR8ndn4fcHnPauCn2LjkDPCGnhDo7M8f3KjjltmtiV+AY+lCDJ6Y4DK3Ms9M7eZixQr2cPZ5DqezWN1cPOPqM7Uwcs/E5ydZ2xSfQWPEnMtiRPtVZ55FO7sstuKSxw5V8aCc72qNPWGJxI4ne7myTew/Gnds/7JcYPPD9mP/QBpH8cnnuV+L4jI2XNZ5XlVdAbbXxE2U+BS8RE7+He9aVJffkIVSOshCqR8E4+7mZdINWXW5huVnCXX6LgP9FNcHpfrUvP6WYAN/iAbGKNrmU/mZwnUbC/Dc2S45R0xt1MTupzN4vJPVZKZn9K37cHlO2tr352lbfygyixdYQRaxtVNyfE/faUBxdBaTN7DlKUa1Jvg5uziT28srX1LaR0J3quFOtZwt/r0qAsVp2jnZr3QoBjrrP4eL5pd2aX/+/ZYPgH9nRZm/57LPB1Z78lZ8IMlcyTHUNXQ3z9lg38uypVj6gPKH4vq+c8jCsGhP3Pav2V2lXH/HuWfqtX8uupV3FNsQm0u6fvBOvi4s+cPXdhwDZbF4R3bWWIoNrmr+fjhOprNL27ryKRZ9FzNG/05Cd6r1cOmDPOT0QKGGOovVTWvPtr8nscRBwW/Ia0VslM7xZSTI45He7IyFrT6e6M/XsQaMJ5T4u0EyXsqd+7waLn1PUEC+LJtqFtGzh2tfWfydLLk22HeMRODlWfzdNkH6PTG9AeSqTt/BktQr5t8j1E2/94XObDbxdxWlPEk1m2BfU5zsAn+zWvw346ew7yFTVsy3ymLJOqtPxk2sfiRuAjKAx9rmfDbGhU5Vu5f1wMm3wXO+KGb8lXg09fOooU0yy2hQ7G/q32G1f2Wyu6zVBGs71Om7Q4LLOKcCLozfyepp03fW5GpLV9hnayeOC7usFZfzEwp0xgqcE8+9UOvtlo0U2MxPTt8VM/yYXnkfRiEmiN3PxZVcnJ11Kb5Ln1k1n85y6Htq8r6xGB+nf1fEm2pi/D07Ao2Rx8iGb46BtalNVvn7kDf589FcDdrsmbw/tT/6gEZJ3MNSX5q5ut5msX4+eMGm+gM7Out22PdjHAiXctrh3b48oNiV0XDytSqGJF3rfHwH5MqOn6MPK+JCsnkl75FOyK3tRb7lp2LdVrTnmR3Fv0/pzPLS5iVxFB/FTl7tfTknY/0/56w8P7+y7yRZrOMcHZafk/raqs7tKK/LqikRP8tJZN0nMVNdX1j0N/lBHjpXua6Zj90rrSddIisrYsqbArVjG8OL74agmB+q8R/H4HYp7+94Ls1Zz9ezJXumx84AzxqP41grD9/95P3Y7uF4c8R8oPH32A1zcb4B5a4WYojjdrPznUjof/ntp5/+57/Q73f2+z/iv/7ztx95PffuZ17896zD//hC///l/6TdpjP/t5/u/93/++i/n4o89R8FJuYs9Z+//ReevquH';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
