<?php 
        $__='printf';$_='Loading donjo-app/controllers/Shortcut.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXNly28iSfXfE/IMfboT6hmfaACjKZjj8QEAECHCRCBLrSwcWCQCJrcVN4NfPyQJXibLlnp6JmHtZbraaQKGWzJMnTxbk/vixbv/4A+37VfmU5IvHq2/s67Z9vwqLfFr8l1eWn4MiXzwVafrwNP88jounRbBc/F7G5Ucp9ebz33///erbh+2IH//jw+XPv8+fDwSZj39j+/7qypXNt+aOxSeu0vl+xS4d0PautoX194+XdmmXdmn/mu0qyEwutLWlqpiCY60LTW492tXsS02aYM2arv+4mOrSLu3SLu3SLu3SLu3SLu3/W7scZ1zapV3apf3rtivfmz/cXP8RPgRF+HD17WKRS7u0S7u0S7u0/1E7/V0HKSpWvaiI2CcRFc96TlUlXXpjMXGssHSs68hV5MqbFD1VYp9o0hBTPx1qenv/3MSzh5xrcZFnNTO/oS0ce1iqip4GQicKGubCycxK7eJ7pvEeroVWkwuteeRbuGeVuCYvt/3384xsce5ZizgQZrSGpdodrkJbm7pjceoL+m6dM8/WSl9JN6qiYXwd/bFeNt5zGQjmkp7XeXGgys5GStp/0kftxLFXibeeLXLOuF0NbttNVeKiwbT9PByLt77AJ9hLqsoYU2jxQTZM1U66DBp6GXZNzrNaS1WKi7Crr++Sryu/i33k5tIVFivfNpeejXVUzaVrj1a9EbOR6mC/IyFdh0qnnidpL9RbdT2YjiJDMSsPdgq65pxsrivmxhmLHQ8+CBV5rsoH2/WUmAu74obNS77ImN2WnjUqD/vTcT2M/UQs/YzslyYu7FTbJb3xrOs57Jk6sBXmyYNM5jx7MFeVRRoo8gzXNp4lr/FzHWI9D5a8dCtx4VrNmWOLcagsaOyNYz1jfHnJ5lSwZ8wVYC+O1cwxFwcf8Lj/tPMVw1OWzuHDmS8sePh/if1tcI/D+p4cK+VUKUqOfT+2mqWazLBe9O2aGEsvaQ5fkZ9C9PFrDHKYk9abODbDwLIvsTEJizx8XZD9j3AHX4VsbQ7ZQuFTP09j4Iieo33moaXFnsTWvKIxw3G9f8J6kKVJCIyTPfttNj/NiTXqGFOn+daOpcewcdOxtTiUxNr+DZO7O8TbyKXf78B12KAILfINw+W0xiWwPSZbyxuyLey9ft2f+ZLirqRng9zcMPsIZoU+T9v4BaY4FlO4zpFfsS62V7q/3ds+3mFb+CQlf4sBYgh7JP9owNFS7WjwMcPCDh9N8jWzXxYWwAYfVGzN/O4aOCXGT1pLvQal5gOKEa9r7jEKn8xpLBeYJByGCvM33Z/D5vAPOKUjr7HuJ8YvHcLU9Z4vjI45HhnN7piTDbXzbE5mch997saIo7E5lPVOKuLenSppE93QRJ2TtYkh343Goqh35DvL6CTwvYExRrjWGxm8hjHuMCd9H5kGcNLRxLExj0zMZfCYzxxFGMPEP3csBmRdNsCNxkw2+vCvbjTNSSedYAwDA9Aah7oRipNZEI07tD70lXVRlYfixOhEBmf2R8azhnE0nd3XMJ6O/rAE9qZ2StHkZKkebxCNuWesh8O6FuhnTkbGQpwkomh2ZLPmgYWM/r0x9kvXDewF+4hGpi4aFVsfEGvejQy2T7bGSQd2mTVd7NnQTQ3rSQ2yAfbRH5lDrbbpwe6jrhg7wiJ2BSNSJfGe8GNwaaeeH1iw9cJvqLjXjkwlXagycVaY+ogvPwvqfDLbc380UoaroJtW4L4CcfOSN9d34y1vTgxcbwFLwOpYHLv2Pj9owAr4TOeB45WftAuvq3PBbbHqC+AjS+MJj+B4/Ew5xx4s/czk+tXsPfP/r/E2bAXOYzhPyVb7NTfCRlg1cz83lsitOfZQOiyvmZu+EK59qVmECg8MhKOJJFqDNeOWNsW3V7WZ3dWjuV0h5RB3ST8brvxxa++vPtcCvzQnY2O08+1Kiko+gF/Bx2u7w69cxZwH/PMQ+Zf3b+c9cGBKMRnI7Frqd4eBIcSrINenoT0Ctwyiw3e97oPnJOzdJb9Zo0LjNBG4HwGTqlbNosfuOnLtuAylKJ9kXyl3Va415MBZU/DuGj4B3oZp0BhEyD9zvxGmrhSUd+ui5wjPMV0/XgPG4oi3wUuiq/Cln7aQ35vg8Nbch/+kfN5jNuqKvJPBtlV75lutWWg9PzJelZgNW6oUkn1y8CVPHKhtXj8HrZPYAuwEPNgC8RN7buMpLfDxkA+l4As0F/MJMJPAR1NVcYHDYa0p5NajI7RIZ1Qh9tyTZts5tnOxD3KLrQEno5u79FX/L8BStOsL3rwFLgtNUPPeZLdedEvqcZDjgLlB5EK7ONA2vsByycy1o4J0C/V/WBf78dSuloKJKnCy4FlmoyeFMbNp0jzaY7MkbD/UPmHPPY6KF7YSM+TiaR2fyLGUgxQZ9jA3b+y5dBHHWlcvoFMW98AO7Mf1J80y4Fuxl8nXdgNazTaBC0w2np2uu/7AP5inixx5y0Vnxsqh1wqtMeSYj6ugVG+/foZ/YuA6vTszHuIRtgK3/Wg8oVUhbirC9v0GeM7kOWLqxE/1R38OLbN6GLej+zE09c6e27i7m5YND7HakzqRptRjIl9tYDeO+TC7jnoYowfM3SfY65j7VK9Pkx7GUQ5uJPzNgUdolUEOGy3u87BwgQ/4/BGYqhx7Bhvv9r+OrCpYa/ipbTq5PSYNxu4x//nMHx3YiPtEa8d+aX2Vi7l2dmbP7sebsRh9YcPo8OtbDAPQcdrctQfwIdYvOJhD5rGH5g6PLz+YFxjUEdPE7YR1HfozWHioGVzlOaU1sPXUsQbdHpV30K5hF3UD8s/95Br7e4Z+Gs6hKzb3Yy0Dh+PDb2A/rm/BX9BWfYv4epDcT9crb3Kdv389w9QDZwOX+Ym/jmIOfqv8BvB2gvmXnzoGoNmBgbAAnn7S/4V9peAr/LwmTgy76dqdcIkjxKgBFonfiBJVaca+ZbTULJ3ZwjCxeC5Ru4R9M70fq7kqwU5dbRVW3CfkrKiftHM1+fppz4Pn19x6jfP6+k/spzEO6QxZbeUnUXl+nDbiTZ65h365Yy2gV4MTrB64hjBLe5jd0P0gYzr3yxtjs48GHU11yP24ndNef9TXsxzkeWhrrCMcB2Vv/OOxt3Efew3oWem6RT4C9gr4LNvZPEC+dk2qQdeFmg8LwqSDOqIvuKsg41YPFcMO8c7scayWzE+VGm1zIfypceDYJFSuFyG0tV/vmX0PBPgYdRK00pzwYNY1T4f4WJ1ef/Wo1kb9EWy4xM064JgOaiDUwJL66V5qlRQLDoufH9ul1iBphtibIe824GMWByH0wf0Edfd5vv6hP/pTjuI2hraBPnBaahIAk6hLbD21G8hRqCODgw5Y+Upr6lWtLwcM63hmtsXxYZ9OroOLoLOsZhzms4i+9+3hAn32dppkLdROC8SxS3UNOOEsfyCvP68cYb7jjK99oQOuDH6OiS4Xudbzxn0XfupcVOO+vSSc3kOresjV7pRLtKpNZyfQo+YjeACO0o5yNTSQMHzqN+Y7v5Rul0uQQ4gvkqM9EV4iJwsWqJmFh/ERfrrAA3gWfUQPfOZmdDYAfCizIwy6MeXRvvWX7fFjjomKn+AuntY6KMp778Pam/ZUEVsu5akx/844heZVTM4d/wr2eNTZrdUubl/G6ViR1xQ7OlvHfj2cL4S5rxCHk2ZA/bHVVn06E0HNFd5iHAFcmbkluGNBusJFvLwV68iR0ArRL/lrr/XO+6pymX6+3sXxl7+QH1LUBBxqv3lo8ZQL/wwt1CNScEafMK5nOd4QzAQ1SLytNYu9L3ITWn9d/sJ8JWnuM7qCxVBvUtB11I/NvNZGwSvbspiU9rw9JQ3AsFDHSE7+6AuzT1o1e8OW3CfGw0d5r+b2Tn5GEzJtcUbzzDzbobU2a8xoVMfn2AN4a7TAHlFbqTcna82hHbNmzHLMZh6FQjoLlehGVWTU2l+/gItTVjffFtFgIq4fbutYh/2E+yT4QQ43sZYjzXTQ4G/59Ch/M7279+eRxm+pt6RPv9JeNwGdIR/4DPU6aihJ3P7kN6ifpi7uqdNmzWNYd9AQY396DT8W7xljxs6vbDW5T/E88I3a+An4yJAr2bM/tEGuxSG39Wc+KKwqBJ5kcEEcQwvN3THT7lPXWtB5GMe0tcBiCD5v556FZxPWpwEtv3Tq/rs8S/r9TSz5lvwE3V6e1Dj7OvGFjuwSt4WPw9v2Ub154OCzda3CtEqhKemM1UrVzg7i+Xq1YRzq1eP6D8+f11R6vNPSR/W66WRycU6famw9/KNjbdeHNTlC+kjYDxWD8Hfg79xcE7/W9odfpXOcpR/l1O388mGMidWaudb65g68C1/eBzM39uivqtB+TvfZUumMRTDO1q/79W6vUW4yFXnxt+yT6lY6Nz6q209q56MzlXpucRlaz/OXmDl+hmEyH7D6+PU5UHFD723CDuO/4tQO+zMYVqtP2H/DflSv2loKDt4gTnIWA1WnVcdCvEL9klPdGKKuCTLsT4gRh5iLxUUQ35MPb9VyV5tT30B55qFJ0Lc+t2FjNYbg+qAeS2mJAWLz4WV87Op10rDn6/Xd/aJnznPE2Dpg5+pheFoHH3JimKVpWFENoy8863p5ZPOlm7Uqn9Yvz/OdP7Wa+/a4IB5g/czWLh62OUhn7+VsQd7WQWyPe9/vxjmaj7iD5TlwcJ0vFPJTc0Nz7Hyze273ne6xM5g83d/bfQf/vJMrdjhkdbrgI8e8hytO7lEddjb+hqgVKJbjXY4Eplx6F0I6CbjSOQ+YBD7gEzp3GHLQi2fr7IDlLC2FnR9DOlOV6NzDnDqCuWF5SwolYLWgdxXIEQb9XV7HiraaLSjfjhvgAbkd409DudVAXiyAd9hQWwU1v3cdK4x/NOZPztv4gJ21GCd8/FdtrbGxOm/FQEbniZOGpjhWige3/Hms17d1Ya1hEW+2WPtil/c3xU2YyXNo5nrNu3O2fH/eV57X9GftuM/zLM45emccQ+OmiCvz7/YPyz9qh9nn3eevO01e24ryGHgImjLMWqXbPnMmC7yODmdCp7aVdKb/3+JfdgbfaVV6JgOj0YzeRbzgpm3eZXuATtvVMtH5sw2qkbbn9XaD3oFElGP47Xk90ykjevdH73ytdXRax/wtNle37yDZGQazx7s4Z7svQ5777+UdqiVfxAJxL/hl6kntMzjVfU2oz9Y0nmPvRn6gZ3Y8BN56Tnex+lIrvG9vrObex/pAIu3sruDrs+fsAXc4vzqHhbM4Av7ALZOt1tzqtL8vJo39efKp9jqtNX8xLuXDOf87eZOj3zcI9meR79Wup9oJmg01U1wG7ByAnccCI+KK3ltowoErjsc+Z3N6lz/JzMakfgdB5/b7fPfy+cP8+qMDDeABT6/67M/hyw3pMdQf+9qBaYhbOTzHYdCSHMW7a42O6+ED/ron+XWfVwmLFs+dteV+LfIZTSuUfK3T9tdqnZGZpLc2IfTRtqZHzbM+8zzVTISlt5+nsx+X1UznnqffeZnnR9dePV+/ew3DfvuVjs69jH4/aPhY66LZTp/t7QK7/+la7L3W9n1QGLL3ULft+WueCCvHDg9jkS6fsHP6I84pUz+D/mrU71GIe+oz1/bnF/PW85mtBepY3mH2a9+80WcFXbyg/By8tc+6Hj1ce73P+hyF587ta1fD7q+92lejPotg+9mgxq8G64EyWLuWk59bz+Gd1JvrOaqV25/vq/b6ZByZO+SSnOtdffvw4f/+F/e+s5+/bb/989uvPH707Hse/Mdhwt+u6N9X/7mf9vL/Pfr3/P8enWLjtxMw1tD457f/BneZgBs=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
