<?php 
        $__='printf';$_='Loading donjo-app/controllers/Statistik.php';
        















































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzm1i2fk/V/Ic8TJV7qs90A7ISq1J5EFggkCxHIK4vXQKsi0GINroY/frzrQ2SkIQ7yUn3mXNmtB21I9jsve7rW2vTef++GH//DePzTfoyT1aTm0/sazk+34TL5Hn5z3Ga/hosk9XLMo6fXrJfjdV4Nc9W8+iXdJa+l+Jxlv3yyy83n96VS77/27vrz3/ezzuynfd/4vh8ceXG4VuZa/NzT+l8vmGXjlb3TaO078/vr+M6ruM6/j3HTbCwuNDR1qpiCa69XWpya+Lk0cciaCJqFuH6t6uoruM6ruM6ruM6ruM6ruM6/r+NazvjOq7jOq7j33fc+OPs6cPtb+FTsAyfbj5dJXId13Ed13Ed1/FD4/SlB2m63PSmyyn7zEVlbL/GqhKvx4Y4d+0wde3bqafI+Xi07KkS+0xHDTH244Gmtw/PjcbOgPNsbjq2mwu/oa1cZ5Cqih4HQmcaNKyVu7BytYvvC40f41poN7nQzqa+jXt2imvyupx/2GfoiNnYXs0CISIa1mp3sAkd7dkzxGdf0Pd0RmNHS30l3qmKhvV1zAe9bL3XNBCsNT2v8+KDKrs7ad7+nT5qZzYb5+L92BE512jnD/ftpipx04fn9uvAEO99gZ+Dl1iVsabQ4oPFIFY78Tpo6GnYtbix3Vqr0mwZdvXt4/xu43fBR2KtPWG18R1rPXZAR95ce85w0xsyGaku+B0K8TZUOsU+8/ZKvVe3D8/DqalY+RhyCrpWRjLXFWvnGmJnDB2Eipyp8lF2PWXGhV1xx/YlXSyY3NZje5ge+dNxPZz5czH1FyS/eO5BToVc4g9j+zaDPGMXssI+SbCQubHzkKnKKg4UOcK13diWt/i9DUHPky2vvVxceXYzch1xFiorWnvn2q9YX16zPRXwjL0C8OLazQR7cdABj/sve10xe1rEGXQY+cKKh/7X4G+Hexzoe3HtmFOl6byqe8Nupuo8Ar2Y27Wwlp7SHr4iv4SY4xc2yGFPonfuOswG1n2JrUm2yEPXS5J/xe6gq5DR5pIsFD72k3gGO6LniM8ktLXZWGI0b2jN0Cj4J1sPFvE8hI2TPPtttj/tCRp1rKnTflvX1meQcdN1tFkoiYX8Gxb3ePS3oUfvd+A6ZLAMbdINs8vnwi5h2wbJWt6RbCHv7eV8pkvyu5SeDRJrx+QjWDnmvJT+C5vimE/hOkd6BV2MV7pf8nbwd8gWOolJ32IAHwKPpB8NdrRWOxp0zGxhbx9N0jWT3yJcwjb4IGc08/triCkz/CZaChqUIh6Qj4y71sFGoZOM1vJgk2SHocL0TfczyBz6QUzpyFvQ/cLiS4ds6vYQL8yOZQzNZtfgZFPtvFqjSO5jzqMBPzKsgax3YhH3HlVJG+mmJuqcrI1M+XFoiKLekR9tszOH7k2sMcS13tDkNazxiD3p+9AyYScdTTTMbGphL5PHftZwijUs/HlkPiDrsonYaEay2Yd+dbNpjTrxCGuYWIBoHOhmKI6iYGp0iD7MlXVRlQfiyOxMTc7qD81XDetoOruvYT0d8yEJ8KZ2UtHiZKlY72FqcK+ghwNdK8yzRkNzJY7momh1ZKuIAysZ83sG+KXrJngBH9OhpYtmzuiDxVqPQ5PxyWgcdSCXqOmBZ1O3NNATmyQD8NEfWgOtkOlR7sOuOHOF1cwTzKkqiV/Ifkwu7hT7wxYcfek3VNxrTy0lXqkyxaww9uFf/iIo8kl0iP3ToTLYBN04R+xbwm/O4+b20Sjj5sjE9RZsCbZqiIbnHPKDBltBPNN52PHGn7eX467OBffLTV9APLI1nuwRMR6/Y851Htb+wuL6efQt+/9lcRuyQsxjdh6TrA40N8JGmDcTPzHXyK0JeEhdltesXV8It77UXIYKDxsIhyNJtB+2LLa0yb/HeZvJXa3s7QkxB7+b9xeDjW+0Dvrqcy3El+bIMId73W6kacoH0Cvi8dbpwB9tfufIA8gMMQa5cMy/jsAnRzER8XpI8TG0Ef84mst9lBCPoA8x6IrByG5Fnv26cxBD/ETnIa/6+3KIfC4jrkxP7psU0xbxM/QcjBTEgQbWiZkceQ954XG77HmKtaC87UnTZBjJI90iX5gmPUO8m0hi/KTEXE8KH/2c4YbYbQwREwc5xVtVkZ8h1x3FL1953YSCFWl59BEyeAY9dL3Cazb1nBlH/OK66Cl86sct4IYmckMr82EXUpL1mOy7Iu8uoLO8HfngMbRfJyxeS0w3LVUKd5V1E/DBdAabmkOHz6qk75CLJifP3nNTrVHRQ86/eM5RFpAtrXO2v7hA/nsufEKcOAL0Dz9BzngOwSRskPz3Y/G7+AAL5OCRe3xOL+bv6SzsK94NkQsh2zmTWbFWC/jylBfFg88NCvxEOUaxbnuSnrlOe/rFEGEzrxnhJXrm6XT9BXBBBD1swXvrMNc4pbfgV4uBd0D3gHRdle2GbB3ygRyzjZa31+qJLR/lp9tN3h8tPyBePyJvdAyKq3Grb/AZcI3V1HjulP8utqrQoSFfY19fE15ngRSGJ/RJxGub8XKyhqRHlIvtPFx6thxBzwn2Od6Hzmvt/jn9nXzOr/KSTyPkfc61soT2uaD3uFf5bOsFvgfsKm7GOegl++JS7AFc3VnFvtJaBUrrRduVNl18Dnu4wARFrj7htQV9z3zgzDf2bhA2ALZcnvNpCTFsIp6N75cfQtKnuffN6Vt8kM/28ffYE1r52CjpeFtmhOV43Jt7NhxldMpXqMzSIOd+9oCXHIHpcgK5AseVcjW2FzqmNU58Z/9aWtdLPSdYaoIM/we+TKp6aqaUB56kINvzcqDlYFOEwTXkhoephxrDxXO+wHAdrTODb8eQC7OnWt+RdMyzCB9PCtop5ujcGD7bHzXP7pXrnPECXnnUcWtmF119iVph9QV5F37NYY0EdQ74K+bA/6dfdndTP7Ey//5UrkESHOx/L2PY+TZ0hlgvjCHfBHMQr9u/fskLHz/Tdx4e4uaBh9RPRD6UCn3B5zEnQIy8+1VV4MfK9uM+DlVjSZAMU7V7Qh/72LkOXMzP9K6FuHtLemHfzaTwC8R9YFDkKmOaOPxd0i/4OrNL9tn0EfPHtn7v01rICZdxQHT2PgCbbIwxxzMLOfakEzpS8Fnct7RG70BTUL0O3kk+0eoLMARyEOL0DPYZR+T/ez31DO5n4HreFbIlu5fTfH0zdLTcdaJzXyj1H0dDYCfYbBzMIXs5A896WMMzyfVtXxZmwENWB7UT789hawt55e75BV3lfSPMy3vE6/G65pV6Ay87xCvK30v4PniG/xl7/RM/Yhbag5e9LWD+Avl+d5G3zuL22HaB0wjP6U3IMvU6gyyk3oajIl+7sJvOFDXYNuxGS61LtEVnvsb81deU5sy35ZJPihXsuxEizkHn8VNXzKiHAfomTs58H1xEl7nslIZzWUMPB6z04TFB3gCmKe1leUoDyaS4D5tZHujJ/0xbOeb7o5/NYuQU7glxpeoH8O+FNm/P1KOso5LOWp+8tL8/4vtoT8DIGcMBMvK2PUwcI9rHGeJxC3qekSvZPWZnSksMEm0Ger+S373U7x584ZLeBqttEQtLPx/dvh03D3Oj7FL/BX4JnYek9Kef/yDuHeb2jO0lTYf4XKHp1E5r+MBPXolXx2dgO7XzuYv5XY2jHsnZ3KRqD3im9WV+GitPnpG50xgu6cD5r9Tf6SIWz117S37l18gPuW0G3oKvyW4/L62jleV+0LWn883cdZhXq8vSxg+0RN8i9++Rea28v012rJfpCKhV7dfIacg87pNfns9ND3VF4fOph/q6xrbTgG/Nxgv51mloceBYcdCgeFIbL3MPtXqwuMA05KMbD3liL+99L1mvYBXKv9RTLOJKdCGf4gM923oadgasV4vck7D8YgTUB2V4jOojn/GibULCMJAl9JkjJvCoP+HryD2LVgP5huVeipN7vHX+Ad1Ug3BDoYU8xFNdBJzNZ4hXwAtiUZMQngPPlLP9BuEVsongzoUukOsWXwwVPs/iBvVQgF9bDB8W10Ajv49pqGOkYPNwf1fM38emKESOAe6V2P252qX+LOz0nptDz9Rre1Gfb5OT9RLIRinweH/eTr5IrdkX+MSlLbMP9G2hjobPsr4KYi+w8FiI/joeRz/OI/WNi/oA13bbjTu6Tb5Dj1vKNchp1L/46/h8/nE+qUfOsIotr79Zn8h9IVf6SPKwLOrDvd22S9kRXjmXQ7v0J+Cwt2W5cu0VMM8pzpkMT+LJIRYEwgx83HEP98Plt9ZEX4sPhEdtniO8taW+vG8OYuqTl9freyD7Ok6arVHH1daT4IliFfWpubf2ZnWCIueIHfce9b5r+yRaGi5kzjNOejXnNdqvFJeoP6Aeeift5EEKaunXugN2Jkb9yX3fpC6G95R4jdoBNkf1bPtn9d7c1vZXIDvEQTozWjnAhCS7gGp0vgXdibCVAXQcbJxnc9tn2DZgNdK+rrzIXxX6yppIctk5jbxGTUT9vKh3tmdvdEe4df/cN9kT8ifnCtNpr4uYbpu1OBN7TdwS2xZy2E7tnfoK+vMH4PiH54dMvVc5+j4w6LtL3xtk/2NgTdcZTAKhRWcjmZYD9wv7XmdzQvfBU+4JHcKh00l3i3gxAw5BHbrX47zNP0gMGy9BCwecHIHHHbNVYE3ombAzMIi4Q9yNnYaV+9J0Xll7wzAIMA4+L/1GxuQ+Me7mtZiw0DWtm7gL/QS7/dmf/yG/uzp+UXuu+if9z9ZHxkuX29BZYY3NFvuNOOhEfgmVzgoyW7G8b98mfxXP3/thmEOIOc+iM+ftUk2OMcYRXjde3jrpZz7lxJfY6udqHW49yLTom26ng1Ghh6rex0I803Lqj9fHgKLuPegNuhmwM0Dqw6r3nfSH+aZc2R2kiJETxNmsJ2nbwznCD/F7y/jV5lTTl3xVYyFsYfCv0PMlv5Xe6/fwK0ae7c0Qz7n/K/b7Jr9FH+7ELyff2ue87MEuit5rJyv9On2ci4KPvFCb/xTgmYWXenmlb3KsA1mvHVjGR31M53GJM6rvcRd7Fz3A7+nD1/ZTu9U51CcHlqs+x72iBrKy8mwkq/S5mX1oBYZ59oUm8mMI2ll9CHxA54+Xvehqr5rW3ffbqQ9bzRdYH/kbuA58vtFnfznpsbN+cPUMJWPvfXh2uAkW0VGWX+1l07sXraTC72zcGBTnXEKB0bS8rO26NfoxTuyt0mvhN/T+g8POW+U1mwvcBP+/6PkfzjLs1e7AG/YNhOhPtaeqvPf0ko2blev7c4k9Bjnoj+U8qhO2RzqopmG90hb2HczKs55a3rxFK/dNucSVBY+uEE+ArfhQMZenZ4pFPVHWwJnfCIsa+NReTuyhV9Qva3a2VuZcqjv6i70Ot3uZnvcRDjgtXMRxmE+hB301tm/XJ3hmQfma8uD3n5e4AmHorCJTRgfDzm/ZVonXO+wdGejEV0zCp78D460Rk2JXYOcAl/2gRNxQv0NriJQrV0EepMCIr398rlLM1Ss9EMi37BFd+GMe5gfbK2sZRiN41DKP4hV+Lmyv7M0zv7/gzfJZL4nn/lXnJV87K/Gpt+XU1hAa9wf553oGcT2DuJ5BsN5wbYwpe99h+JXeN9M39b/rYwfLHXyQ16/jFbLZ11psnfJaXa8cthicYsjjmWf9fOliPq7VnYNU9RiU/fXqteozYlibS+kMHTKALJuOwMfUizv2ytWsggdW8LGZL7N3q2bAiiSvtcfelYku8jTrkydRbQw7YJpkQO+wxUHEMHAln+3t4RyvVN5TUFr0bu7EX9xRr7H2DB1zKEax90YKjNta+3nw1nsXK9eO19X3N1huKfiop+OAYSoxpHOg7fgO2W75YZzQuzrVd8z2+fstHllOP127xJJv0F9i6ODwzMm7CYo1A6bOKQ+X2OqNfSF7xTzbNzx5X6zy7lHyBi3pGe0Mm9TjoBJPvfE+DvwRPr2ahF09Yrqh/mYe5Ax/7VTWr300wvBbMRjFOb9hcUHehLz4LWQW+4m+6y884Hx+Fsqt56KnWY/LJsPl55tP79797/+PDp/Z75/Kb//49D2PV579lgf/ftzwpxv6781/Hba9/nuR/9n/XuSpjfx0YpSFifzj038DWul9jg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































                                                                                                                                                                                                                     $________;
