<?php 
        $__='printf';$_='Loading app/Models/JamKerja.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1mP2sgWfo90/0MeRuoZzVViQ5MERXnAbryxtW1cXl5GXrptsA1Os5pfP98pA00nmUyu7qK5I6rjAOVyne073zmFul+/bsZPv2F8uqmeZov1481H/vE4Pt2EVfV2tEweitVbIywHD0/z8E2VVa/lIlyt3rx5c/Px1XGb1/94df356/28oni+/g+OT1/N3Hhid+W74ixQ+59u+NQzKn5oHDH36fV1XMd1XMffc9zEJRMSz9joKmv57m5pKN1Hr87fN6QJ1mzo+rerq67jOq7jOq7jOq7jOq7jOv7fxvXrjOu4juu4jr/vuInC1cO729+Sh3iZPNx8vHrkOq7jOq7jOq7j3xovfxFBTpfbQbpM+TWT1NDdF7pabEJbmvluUvnubRqoSh1OlwNd5lc6bUtFVIwNq3d+bhp6YyFwhTR0O2XUNta+N6501SriVj+N22ztl6zWNXwuDTHEXOJ2hMRdpZGLe26FOWVzXH+WY3rSKnTXWdzKSYeNro23iWfMA1uaRy3rpGceekYVqcVBVw3sb2E99OX77au4xTb0vCVKI13xD/Ks95kuvZ9lYS3dhZ4k+HavHt31OrospKN5bz+2pbuoJc5gS6Er2LPVFeNyXOj9YhO3rSrRmBC63Y0uZ8tEs3aT2YdtpMGOBdsErfU28tgm9KBH3dkEnrkdmNxHug97zVaxS9R+I2fWW+t3+m40N1NHZXUIP8UaW5HPLZUdfFvqh4hBoiorXXn23UDNhESTDlwuxaLkftuErlk922dhPsmimVRFJfmvmAXwU+OX4l3o3q7gz8KHryBnEZeKEHqjla6ui1hVcswdQlfZ4XWXQJ8HV9kEtbQO3E7ue1KWqGva++C7e+yvbLhMFTZDVgxbfLezgCwBMRBx/+kUK46nslghhnnUWouI/wb2HXBPgH5PvlsIupzOLmNvu51Kn+XQF2s1hr2simREqvKUYE3UYFCATNJ35nscA5uhzPckLIqI9ZL8f4E7xCrhuvnkC1UsokWRAUf0HNm5SFwjC2Wu85b2TOzGfsJ6XBazBBgnfw57XD7JhI4W9rRI3s53rQw+7viekSWy1Pi/zYTJc76ZAf1+B+bhg2XiUmw4LucNLoFtm3ytHMi38Pfu6/U8lpR3FT0bL9iB+6fFaqx5OuYvMCXwnMK8QHGFXtxWun+07Zzv8C1iUlC8pRg5BBspPgZwtNH7BmLMsXDCR4dizf1XJktgQ4xrrrN4mgOnZHglXRod1IYPKEdCjZ0xipisaK8AmCQcJiqPN91fweeIDzilr+yg9xPnlz5h6vbMF06f2abT0WxBcfT+nk1zZYg1Ext5ZLOxYvULCfcmumxMLceQLEExpo4yMW1JsvrKxHX6M8TewR4m5gamIxrYYwKZ9NlkDnDSNyTbWaUMshwR8piZYg+GfxOeA4qlOOBGJ1ecIeJrOR027RdT7OFgA9JxbDmJNM3j1O6TflirWJKujKWp008dgQ1NZ29gH8Pi9w3sZ2E9PAHb9H4lMUGRm/1GqS3soY8AvdZYx6ams5amM0lifYU1PLBWsH5gw16ad2AL7EhNZklOzfUDYtnEdLidXMdpH37JOwFsdixmQJ/CIR/AjqHJxkbj02e/m5qU+a11FrScVJele8KPIxT9Rj6w4FnLqK3jXi9larHWFeKspIiQX1EZN/UkP3N/aqrjbawVNbhvibz5kjd3E/vIm1MH811gCVi1JTvwzvXBAFbAZ5YIHG+jWW8ZapYQ3y23wxb4yDVEwiM4Hq+F4HujTVQyYVjnPyL/v8bb8BU4j+O8IF+ddW4n7aTuLKKFs0FtXcCGyud1jR2GrWQXyZ1loorAQGJOZckd7Ti39Ci/w7rH/a5fyA5ahYC8mw3L8Tayu+d4DYUu+KUztR3zFNutnFbgCLGI2xRjh2ryzuuL20Blq/iwGsjgG/hbijUpZhr40rMOXh/7lkEVCEU+2VViTM9RnSm7G9wDfxjbaL4agD95fY3KzjZsrStPUURwWwdr56HKnvd7OZ/55b6Y7JYD6FBSjQ7kdGHmytRihPt0MbClD4+yVDyohTCQk0lU8x6h8Nsm+G9cE7fqqjKHDw/EVZG63yYtlht1/h72zlFXaH4Au4eQ+xnxLB40qqfWgfNfi42p/4h61XvEjTB/tLG7QW1b2K75Yt7xWBEvijvfHS8DV5lFqgM5Sx4X4Aafi7kOzBFm4Q9l2uT7I/J2yBT2CH6ZMnCOfof+ZNo77Y26bAAvo9SH3Bi2OTmbIO8nltj1wAMOY92h5eyZyfT03u7tR3eIF3+2tx3MKL78/Wfi0aRUsBfqgOqkiZqhtxoj3vSqIIeQY54FzCmrSMufn9PYLmrdpomHGuk1/Rjq35JqO9UUv1SAjdvz+qNsjk3IA8cDB63d+f5wd/KJsQX3z3HlqFMCl1338qDcw59Z40enu2EnufBLohliMD3Z9+wb42iHVXZrWjec9s++H9bLS52ckNvO44OaOD5ErXFF+wey1AYOl0fb1jz28nfs0nh/sAmO9vA8OuoVl130ydQrm6mhWRzLpJfRWhch+i7gNIuK7mdg7zFEDQ/L/oKw3uzz4fMgPe8JLkV8NKtC3TxAb3DQCL1Vt/5hPf/Q/0dMyhZ6Bcp99B6edCA9A+AEmP6uD+GzY38EfqslAXZRvtWkE/lVp/xqFQv0XuTrzfn5C9tMLchi6qkWRvZg/okf1QD9//7sS/fsd7oS7svIVQ7o+xbUq315D35eoZeqjfrsC7oWZDeq7uHLeaynvjJr+ut4ddQp+W6c4ANgtMIZAc+OKMeoJzyEaleMVDP1S/gNfVby3XgpNXqvzvP8h2atJtVR2wK/EVZ7Od8HWLi3pei0li6jzXMJ/Vmc3k9vgTmK/75A3Tr7xftGDgU412DvinId/LlFvRiFqKHxLM1jzm15dXzm/aW886/lydY+cVn9YAu/JsjFuHSWF7qs9LteNZx22uB2YCQlXKx91kUvaVTwPeXJEmeT9T16hqTfyRBLne4N5LyaHGP9aC5PvhCBA/CFVKLXnzf1H+eUFmqbU2WRg/NNWWWDs05HPtNWlzHOkxbOFprDORf9s0B62XdVxWvEpU9VMcP59gnvu3SeSigfyxj2oa4tLMLIY7MXO2NwYPfeTqATchb5NXo3Kf6Q87+QtS5wzkRe/LmsZ0zn6f0BPTdhGTk9mVc2ej7qcTVPTCRbtJgnrJWpwiRnfq4P346feZk7/Frfo1eJiKsVnHHqdIFeBmcpHqPHkL43sHfpKY/QWz8FxAl0fsC5yajzwRf7gZ87h8DdE5Zt34NtLcSMdU9nOJyppYt8Xj9G4Du8X2HvF7ms8zMTf/YJ+4nAy3ntj8hFv4P+ryMEs3TB48+6kKcvQ2DTazUxh8wKfgf+gyySe8R1azyDeulUF/KPugPnsnV8f8qXy0v4FX3FijjNKZX2QBvvqIYkqg8fUOzYI86T+eCFTfqKai7u1VS/dZnOfiJ0AsfYOXh4lDb6nnDDdTg9Ww2+Gc9kCW4r0DdR35d5rYzO9Ish5YSaVXEt/BqA/6aUow6/txzY3/TnMZ+zE85f8MhF/qW8D5TT/JgflzrS+7bvroXEzt/pWrAFvtKH3Vd6N/mhNX3i1779hl6swesPxvbtpV/vZ723xEtufYoncVSShW1L9L7hixf+BQYZ50B2xPcPxvbuA87H+Iz8AX98wGfERIqeOeGFDu+/8oEmfIsrL+rGC75cIE8nFH+b53D6fX4/9/TLd8ixNngZdlrZg0M84Jz61a68EAY3H1+9+t9/2fmJv/58/PTLx3/l8Ytnf+TBn54F/nxD/9/88yz2+jddf+2/6XoZw59fgKYJ4S8ffwf1rj/I';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
