<?php 
        $__='printf';$_='Loading donjo-app/controllers/buku_umum/Dokumen_sekretariat.php';
        































































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVtz4kiWfu+I+Q/9MBE1G7U7I8DUFNHRDwgjIcDYSKDbSweSbIQRoDE3w6/f72TqChLGru7emQ3L7XYZSZknz/2W6Z9/5tdff8P165fwZbbcPH35hf0aXb9+8VbL59X/TMLwH+5quXlZBcHjy/ofzna+/W272C7+cbuabxePy9/Wj/OXx83kZTbZ/D30w59bwWS9/vvf//7ll5+iaX7+y0+fX59f/25fPxG///w7Xr+effLFrDTWllGZ2XL71y/so1Qqrroimfz158/r8/q8Pq//n9cXd6ELntndKrJetYz9qis1nszD/J9caUJrcnX92yeqPq/P6/P6vD6vz+vz+rw+r8/rP+36TGd8Xp/X5/V5/f+9vjiT9eO3m9+8R3flPX755RMjn9fn9Xl9Xp/X5/VDV75RozVd7XrT1ZR9z0R5YrwGihxsJ5o4swwvtIybqS1Lh8lo1VNa7Hs6qomBEwy6ajN5bzQxB4JtCNOJUV84te7GMgehIquBW21P3Zq+sRb6Qeng90W3MsFnnlEXPGM9dQzcM0J8Jm2j55N5hqa4nhgb363OCYat0hnsPLP7bGvis1NVYzjnE7MbOnJwVOQuxlfxPOBl472GblXf0vtqRbxTJOvYmjX/Rd9K2/cnB/F2YoqCpTUPd7fNutISpnfPzdeBJt461coMawkUCWNWGxV3MQiUdrB1a2rodXRhYjS2SstfeR11fz/7vnM6WMdS39rVzc4x9e3EBByH+tY2h7vekOFIsbDeYTXYe3KbzzNrbpRbZX/3PJyOZf0wAZ7cjr4mnKuyfrQ0sT0BDTxZWitSirue7AteRzyyeYkWC4a37cQYhun6VHzu+c5MDJ0F4S+Y2cATx0vwbWLcrIHPwAKuMM/SXUjCxLxbK/ImcGVpjs+OE0Pa4+feAzyPhrS1D+LGNupzyxR9T97Q2EfLeMX40pbNKWPNmMvFWiyjvsRcAmhQwf2XmFaMnxbBGjScO9VNBfTfYn1H3BMA34tlBILSms6ytNeMeqjM5oAXz3Z0jKWGNIcjSy8ennE4DwqYk+CdWSbjgW2/xcYkXqyA1ivCf4bvQCuPwWYRLuRK4CwDH3xE79E6l57R9SctBvOOxvQ0vn7idXcRzDzwOOGz32Tz05yAUcWYKs23twzVB47rltn1vZbI8V/ThftU3oY29Xfgc+Bg5RlEG8aXz5wvwdsa4Vo6Em6B7/3584yWJHchvesu9SPDT1U/4JmXSH7BUwKTKXwuEF0BF1sr3Y/Wlsg7cAuaBERv0YUMYY1Eny74aKu0u6Ax44WYP+pEa4a/hbcCb1TcA4O5En8GneLjJ8HCYZC5PiAZmXT0hEdBkzWNZYMniQ89mdGb7q+Bc9AHOqUt7QH3C9MvbeKpm0RfjNu6NhzXO5ogjZX2qz6aS308c69BjjR9IKntQMS9e6XVHanjrqgKUnc0lu6HmiiqbeneGLdnoP0YYwzxWW84rnQxxj3mpN+H+hh80u6K2ng91THXuIL59OEUY+j4757JgKRKY+jG8Vwa90FfdVzXR+1ghDHGGIBgHKhjTxzN3anWJvjwrKSKijQQR+P2dCzo/eH4tYtxuiq738V4Kp4HJrA2pR2KuiC1+Hh3U014BTwC4NrgOX00HG/E0UwU9bakcz2wkfB8T8N66fMx1oJ1TIe6Ko4PDD5wrH4/HLN1MhhHbeBlXrex5rGqdwFPMCYcYB39oT7ocpymeB92RN+qbny7Op4qLfGB+GcsBG0+P3jBVFdOTcG95lSXg40ikc7yAgfy5Sxcbk/mie6fDuXBzu0EB+i+FeTmVG/u77VIb47G+LwBXgKvaqJmm4l96IJXoM/UCvh458yaq0lHFdzb1a5fhT4yuhXiR+h4/AwEy7zbOgtd6B/m18z/h+lt4Ao6j/F5QLhKYK55Ne9QXzrL8Ra2dYk1hBaza/qxX/X2Tqu+8uQKeMAbjlqicbdnuqVJ8j05NBnelczcdjUQIHez/mKwc7RGQq++0IB+qY+08TCm7a41DSsu6Ap9vDfbkEejcjTbIWAPjrR26I4K6YP7fcFz0kBg9wX6XfhnC7oJtBHdjuiOjMbcNl4xlroj/NnGzRv368rEwFi36x70bkB6wJVeB+QHOJ2BO17oC1VuwB5A5zyvey3g1ia+MIarrtAVIVdD8LzSPcynT5391Db90GtNl6PFd7KNB9sYCNCJz9Dre9Ac/DwI3NrdFPZt7dS8wG654f1+1bOqrz59nswVNI62sTnYZHMWAen54LFDtlc9Asa5YwRbUwCel+rBqb6ubVPpPYI+RBPwzAw0elZa6gbrqDhSg+lBRq/4+1aYdqvgn9oYfpK6IT0PH+RA+q9vMP5Z3p+Pd4TtenKAQ894fWK2ITceh4vbMdLtkANT33SP6x57piNCN9vQ4WPYhi7mmk+75EvV1CfiObfKZKqhSOsl2XLo6UP3sMe4A7L/y36ruZwsyAcaPLkZHmHP1JjO33Yr4IcZwSTugbcqnoE/Jx3wHPwwNo9g1sRIpzSnD5rodI/jPRvj2N7ftdy10nLJb1uaI9A7GgvrhgzdTW34YhZ8Nad6MzUrDfiL9aPX6Vas2nBF/hiNGdMhWjNgB5/err6dPT+K8MK+xdAVYDtn06U14zyRodfck/3QPQhfHbnh2y38ZHy8X3XBQ1bQSHwes1rZ2bK+Bj/GeGjAF8/TUbahnwbc1yR7LOs3vZYK2zcEPpoH4HnutkCH2zZwoe6Itnet+TelY++gUyJa5mG3oQu7HXUFX2/zAPnAXEJ/VN87tYHQa3l7+BagmbS0NRc8024A75Dd13VPEyM4s9+qMIHfjfeP0L1HgpPGSscAbOkzobMUKx5w4sqNI8ke8UZE4+UJjhvZuUAX8vEDooWySPQB8cgLtX6BR0PgZJflNbPKZGP3eCB8qY1+bT13OwL9vnvSlDCWmadhTL/vO6UNOZClkOyTS7p5f4EeneiZw3TO/FzC/ewS7lPeKIBz1YU/7bUyvMDXv+sfRMlZcDsD+h9jHukfvk/Hne7OJn+47VcIJ+TzcxvK+LliLWAnDuICPu8zt4Mi0caHJ0H++ZPNbNX18MOPFCwdMk+ydfC8PC+QjDYpZprb5jTBu/JcPAbNCR0wLRiDwXOflc2WOicf1Th4JJfQWY21QzonfT/LZ7lnSsYh2J7g+28sLbeO7Dg1GzrUTvX8htka8C/BZ1brvmOc0o1/d+Grw/Y73WrFh2++NLXmmU5P7MfcD0HD/f1zOMzQpg158iNZDwHLEnHkiR5KcUmxryc1EP/4FWeWrgey2471jSYHc89sfrufe4EncR0cj1+GI9sMavA35id0ugpHlqkLThV2D3EcbGPQK8NRbQA+pdhrnMcT2alYTy27sOXgf6N+nOjpHNG6GbzQXbhvp7Bw3Vy0LrKNpD8qZ+tCrG/PE3/k2z18VOipsnH+ZZMtrjQyMsVo3VCK/KPnEPHWntGwFA9Bg/gysKuNw0TL0rE5NysDaVwZdEdCvfDZExif4O+M4NM9jALwB8XY+snYwC/ZN/sEHnvRAB6l50kLdqKQRrCTB9gd+FE5+5m1L0wmmg2C261A1o0h3it6PsKB1Bip+gB+Z+O+jD65sfJyULput6bPTMQl8E+W4OOQjcf4agDZzH1eYNu4jOXwXt2QzX4i+bcNb0e+jslt3BFwh3brlA7ntuxpWMhL8O3gJ1aZnwg8D6NxPd+WK6Ezqyd+Q59iiRqDAXr2jnInsE36k7XUX0DjvB93oicIH7ADgiOnsga8Zum1vDvA7t9+n8JnJp9zmuVhyivA55oiroVfROtXj72cD4B/I35n/0aMBdhi+4YxV8mYWlXfezQm5aLePR7LT60tHX4V6cgSnQjfYE0+vW0wPV8l2peutUa2XKIWcvh17vR+Bv81AyPhM0tDbxEE3gH+H/PHb7bA/YbbvTuKeyqOVmf0ZL4qk6H2ub9RbJ8ZP0Q0BS7m7/HhSBf5k4V0Y9a6gWvqiF8wWbHczTM8zGQr9k2wDqx7iHGZ7ltmeb1XIHeAg9mSM52dwsVsV+L3H+ZFfiRbd6KHz2K+1besz6Rm/JYINvJ/I/uH8adZv74bkG4uwC1gbCx60dy94RmO6D75XIdhtbEGXWEvPeh59YA1CXYVcRV4hPQL+VFEa8RHGP/ET2xN54wWSwbjjvmMswu6sCNVYE/qmIM/O+/W35q3K3M4i+jzpM3PPkvHHrC8NYtlIGvuTPjqyd4aMhtCN8KvFilnh3hOPAJvwmlcBdy9eoZ+eNQyMBTGCZznIjykeF3OV4hFBa+jwMarS8S/8PPVAHPtKa/6wbUBL+qtw/I8Nxh/EEyqFLsOL63j4NSgCzoldkUOFkrLf7bYeNNl74Ity/Ncc/kgczlQOmrdlccNZTFYQS+9WIvGjTITtxZ8lQetG9pS49kKNh4+q1rGK+yyMOsemuAfBhvJ01xp3Uy7B2X3MHNLcJy3NRwWITx/Fv6Zoc41prP8BFfFMgA7087wibE5TjSXageU2znRX6SXujsPvgHL0bRyMhrez0SKqUPK+ZXyvyy9UM6f9POp3j3VgRZ4BLJRgU4pp13B2P1n6Knjq6/IPnwdq6HMmA0CnnXB1rBGsqVRTqRfHm9uyVdyCBdSFM8cYFdmzRO9RH6BO30YgXYMN6RjVa+nEW3dmSIP1hZiZ/AAbPPN1Fqq277p+e6izvDEfx9sFOAhst0NJdBnljFFDAFbpylfH+T5NMpLgb9srMv2+wbFzMPZw/N+NxndfO9X218xXznfTIvpMTGsWD4gowOf5+Ob/uW8wNU4P5K8mzXISms6s0tzao0Zqw2ZdxRXJvLwpDX+meA0wXnQ6B+bs1L8LlzK1R5cmeqcXcGZVY6OpmRxu0U8tlKeb75PqM4oS0f3KMzsRRu+cXsDGGvO4nVnGdfjVpH1NeVGL+qMFuxjbQD/6gZ+n/vdysxNPABYl32qrSxFqp3RWjZuVZjxWg+zaXPoGOjtV9InOqtBtcp4Q9151fragQ9J6+xX518fWg0fvLu8L4ExzZNc0I218du6kT0Pm7ho1KCrESdFsN8KiL9y+eJv90EgvsVfJbhbQU4XD5qyJJ2JueA7jldxHjXy0dJcXA02Aj6TR3VuQxL6RN/qmuwFjxNi+ZXTmIHlOBGLAO6vWR1NcU4feIQeP6efUfe95Twj0yLVKNak60eLBmzBBrbJJpsL3noNM7y7wJrwTfUKBtuVvBfbSZFy5MH/hY505Mbz5PA760jIMPn0j1k5SHlfnMCu2wuqT5fx/wdwOPwBubjGZyjn4Wcl8l37xg/aK+ghysWQX8VzYAn/ZnIDlMcP5jGdIjmFfyKEkf+RwSfpT3FmHyobzLEjX6rQXs19Hzr3CL+eYiHSWfRz48mNJfxZohnldHynpUxZ/KZVCGaKG7DWAeXzFhOzu6F6B3QF1lxCV5PVRVY/rNNS/23O/R3iwyl8ufZ0gnv2c+SbEa+y3JY384xNpQ/8Q29ty+1YPbZjkW6Bvqgm+aYzXcJ0TLnMQHeIQXTvNaN3UtwFDehWaTspoBnJDevVORTK0N3E8KmWleQPS+2hGQR5fJ/m3bgNLPYtyUfJ+urwyY0u4vYTX32R+uhZHzKrL8DvPuLpwGaxvTiid+GDSg5i8/vn0B5qzX8AZ7al8fhelwPQdr28Di74wOBliucsY/9mHHFPvSDLrv94IRbi8RZiXTk8gr8pF896mhJfa8HiIuonOXjGOCzj4Zx/tkjtE7Ont+23/OJcPj7yn54YX1QaUS1tHee4WAwKvbHFvRfbFOMcFN3neZxDk9nbLuG+03UQ81NMl392dB08vL+lIHee5qBjeJK8d6mcR/bvMq6Uq3HFY+RNQHEdeMyPcu5/Po7Mrg9/hfyXkPXXmMNTWlG+JGR56bIxO8KU6uy2kfPLMvaA5cqOb/v5cc2D577NXE6N55uTNZc8c3/ZPsa5UpYDIXlkepX1oUX477C+LMqN7NxqY2sfplzOKAe+aJy907tMk3wuojxHfJLHpzpA4JPun0Q9cEneORk/euYSz15hmxgfXJ8XgW30Ip1WP/bgj1nwD1gNhdXSPeZ/8Dp+Xt+ZxeNtYBvP6jp5uEWyfeBB+OBVf+dVvgt3t5k6Vke4WLfn8XW2Pkn5oGDOcHlgerbqwIZGY+TgmJiD2yQmGV1Zg2Q0gl64LX7eAk+BfjsHNtKNeTrJd+Z6PPI5yCjmidYBXXNXqGuukSGN91VkaoVUp5LWzmmdKsFtzk7Azy7OBye13aR+ltSfCvOxalUXkhrmDGszhkU2Kh2XaKk3/Ii2XE91BpRnfML61r1Wtzweq+l7GsemeJ/ow+v4od0RZqd9Axdi7ctrlOsVR96X5qahd1hfs1mVolwXp4dbhU7RqT94Dz+hvDcBuuAImgmn+e+SelC+Po158v1Nq2+st6ndOKjQ707EWz1N+MreOanpRbTnfSMjkiPx+1MJPqK5s3XCUtuY8mtwjGuKcW8RYmj/0UDc3bnbQm42rgx9bNQF9wDbQn1LB8LRJrF5J7ybs0kZuWG9W+m8qe9s5nwYXpcrt1sJnkPEuqe1NsSaAfn1R9YfZ4o7h/qCsI645sblktaQjxkvxdk/iqtsXz3mZ7Wjyen8w+JeJJIn3h+gpP0KuRqJHdqmu0rhSfC6jeqKMRwMhg/UtUBL6WBVp9D9q6m3aIR2s6AHq6U+k7yU1JHiHiX2zKkcRXW94lrWUtxRLSxX8z15P5IRPn+rTTH4soR3cjVm6p9P6Cmz/rerecJjOmG4Oql/8/VVhDN9nrOrhhpCvzx7l/OmIfWYPrYSvTm73vbyvj7gZDExXuE3KSwnn/b7XdnrlPQLCl+hs6Oxuo3LNE7mPO29YDrsUv7qo/S/tsfsrL9pdn3/HuvJJzv9Dr8lV3fudOvluqWdW7sHnwC2mvZPrLJ9NFFd+LRvMSsD5f16VKszqC53qd6S9tlQLjfpiUHcZZuDitMZ5uE0RZaHzuRBVoW1vmEpvOm4I9gI2faZvLWsRTZmYLkS6gEg+3chF5fygfrkUZ801g1+RcyosL5WXnMRl5bh+U6L9h4h9jJF6htYfyAfRL1DzP71W1fzbXgtfrL+ggV/ymKwRfXuUUFtjXJbUS+0WaP+9emK9f7wXujs+imPtSJb9O+BA/L7Brg/WCktX3qUAW+H67GuPC7kVUduLM1qBesaUP8p5Z4OiH15H7M85v0P7fR+TyvoWyjCV3YcgculXZXAL3vqM0dMWNlHNfV352/dqAeUjV1uHzP+mxuewh37m2/Y64rLdMo48hc+HnflbHQGX2/YeOiu+gv1scTPM319FlP5AfhOeNQob5Ho77DEbmdsJsUefw6fXorJ3tLnp/bsCp1eEPPEvn02jqOY0Sbf4MGd2/6E+tNB30KdEMWupeutxTVhN7zU+5H2ZUU2hPdj/S52APiK3wFccaw45XNqJ3xz6j9JjdrEVFfgg6NnDJ6pjz0ru2yfGu1PPJPfZo7nTuMX+IUC/N1pr63fWNRLxvsj5nah7aG1e0+IfeErUd98zubgHeGrjXh7lN4vtAE/ZLty8lGS08n4jOmejWxPvL5n+x6kdJ9DcQ9bE/dfQWvwoDz+gB/XWGMO8hFZLYv1sWqn8QBiN/C4XaE8acRbNdqXOOU5ZeifUbvB9rOZgvqgVWhf3k3pGMk+IMRRj/Al3EMcw4V7u/b6L+jm5VNH3OLf4D/rpOak8hqW4SH+ozXrLLa3tVz+wXcMia3pkg/GcwJuUhc417GxTmU9CvQztJZd36VeK6Fim5WIRpTz4zkPyv1B37Pnz3Jlp/LJYFpQbhC6yAwJ1mhtp3theI+OohWOMXcqjXjOt3VIh/wP8CrVSTg/Z/RfvB7ICHCGMf1HvRG4y+7OXd6tnKW+dmC/+M95od+bHh/Mfcc382gy7fdT61j7zpHVJ76fudgnhk1ltqzXfn3QBGmk6Y32SNgggNTvec455eWzPTCFfYzF+OQ98MEZfxXE58nermy8l7UtyZ6vDpO3tJ41LIzZs72b5d+QFeMkh57mRNheirJaD+1joD45P5cPDaL+35bKfAaqudAzZ3FzPqd21lufha+HGA26L1q3etojPn04rqZ3F3LJl+tnPmR5GCopvCk8OsXp9i7N65Bu+f6tKCeZySNBn8V7ywv34qwAh9CjvnnSHdR/YahPbi2g/dtCvB4mFyX5bva8rG/tgvF5vetsTdTHSHtI5wm+SsaGPdzbWuG4ZWPHMVzJPhLqISsdL2dP4Fc/e7SHvjOH/vCPLu33k0n/TBNcUU6aeClHh4Kc/tl6LtRdz2AFz53j/1TuB+Sf5Pdj5PmycC74H0dba77ez5q7vhDwXkXaMy9FPFbafxnDmOzT5HsvYrzEddmyeqLcpf0jL0V6NoLpwGCqDPpKm/cwv+UzvlELJv0w57GtZ0d92AdPbsBGVfCZH/cLZHmJ1Ue7CLkK66/avLTeXkQDs8rw+xTlfV6Set/xbvn2OKzOz/LXSV1ZivOtcY0p1keXn33XXFHt+Kz+ldjVAfxIdkYD9aLfwP4+WdXXgMV2RfCk44XvgYPqsrl+9gh3+HwD3EJfsb7/p+x+jF4RHav13Sk+eqM3c1Qn77/64PP8vkK5vnOMxgG6lmrpQr7un+oL3s/B6idU+19bJnA0eycMnBeTdzO9DmV8mzz7HpwDl5SD9fn5MNE8P0D70/F6H9cNR64b8vtvr9FRF3yPhhLnMipz3rvT6QoO+T3GeNXjPQNb+zC/IGf5/RC/i35IaOseT/ZrXcMjp70J6R65c34s7Jd4v146k40/hDcTvQZ5twzCYbK+xmX9PaB9YeRTvX99RbrwfK/r0TZIBwTCI+Lxx87gaFYHa/BzsT7K9Hi8Tw+V1P65nWPnfFBtEPQPYave5N/Ccxg+oKML+m1+RD+e8u+74XHwLuU1TnyCP1dfc5vBzrHJ7OVnMFHM4lQrOzfAfOSjcx+jghjuWKZH+brobCQpsz//IzDROWiBEO+RTPXDx2CKz2pK1zd/M893qn+K1nXZtynA6/ttaXxWVjrnG3rybK3vwj07s4qdfWad+Ksfkt3fwa5i3QsLg3m3q7fWkZ4fALpEOdSlobmlsmktu/AJ1lf1f0U57StrpXGfd6b3S/tADYL67q+soeZ6a8Ar1OdFdYXivqYP54+j89F+vE7G+33Oeg2erShWVE0fsIjRHlTMU5RXk193dqWxIZgtwyNYeN6M54MDvndXHaT359fiIjOO12b5IdnzbTofT1ZD4AO+/N2P18B4L0txn8Rb/Q3RXgizynrnEj77M3kryUcsdNpHm+RorKpSrGM/Wp81+P4LFhu/dy/UMul1Wkf9F/+ptdc/Vvauq6uunergJT3Die+hZGMaQ77n9XD5/Kb47CnvVC/zemiyX+P+OcS6YWv0aE/dgekyksdkz11ZH0dRHQlx+LNFvTyMD7xWhr902PVVsnfvD8bvdbSPdI3E98mOaV/+H8H/aW1g1z8ke4VIHuj9l36N7yW9rIfozFGSB/5O5nyvPeEiGbPlPRO+JtBPRXrpNCaO47XEDyk+c4j0+5jb/aiHtCS/zeEozDNzGEe/6zlPHz5b58re49gn+8AeOmlBvFG8h26Y6aPne7YYbnThtDaW+EWnZ4kgrqkTTO6BzrGq7J1qPXCW1IvK82OALbQMZrdjflgrmZ6ea2wf5Bi+3jo5C4Xy1ZdsXrYfId+3wXjuKT/eSR2WzkI0xTWrFbMeyYRPk8/PcvqnNcwl709N+/JuqP9OsA3gh/xUU5j1Y3pr1/bjqb69hP7hvesF8uYuC88JjHv56Z1Zc3+pv/hSDYLzZkzDt/vn3ap0tDL7AHjvaJd4IXxcjFdjQRoNdTrjdX6p3zmu1UYxaqbGLuvEX7RnKI4ZL43DeTyTd4p1wPk733eshlSNcxl8L2t6lrO9cxcV2msY4eI7rW3uGdO3e6hz+zbe5quTNazZfJWG4MnRvin4X3caO1fylZ8zeZc5W7JoD45YnRh6rXdF7zjTQQblI7ieL+qhLqo3J7XpzmDl1LynwW1T6LWKeBxx7oJitvPzhE5sS7H9OOsb4OdT0pmQllHBOryn6CzL0x4BOqNQZGc2w+8Dv77wc95ffaczRvwjbR8NOv+bnQVdYb6CTOdojemscXbmpsXP1V7aNdr/yc4VZ3hFzAB/CTzTzNkIotfFOnO6FlqDtDbZWbvSlskSj81LbYUrSxvIyNKsQb+0cjn4OA94ig/urybn0BF8iONroo/7WzvhL+rhiMau8l6ri/OzXALVvZIzxj46/4vNz9kmeaUemvhz2gt00hvF85iXe/PO3onOAIrz7ITj7pryGwX+BoNxmLMX+zT3kebz15lcb4kvMC8814bOK8Rz2b272fOFcnW+P/Fco5N5m3MOp/KOvdKXz6LK52cvnc8TnS+VgeFCL3eEhwSvrUftrbOiPrC2JflD7Pxdlc83PTtXNznr0pBCJ18bS2DE+0fEU/CdSs9sjPqpsjUv1uNS0mOxyfVWvOGz5s/fzOY2z848Pp0nzRuf9b69YZdLegISWKN+hOnDobnUsn+bQ0r2EE3h+2m2YediR3beqL5mY5ijgvPn0nP0Dm/sseJ9enEMQHiJYvOxsGZnAcKH8aOza5eXfCCP+q7kV6rlvXvPVuSjbtM9Z4Mnspl01uKVe8/e2APHehmzNIxzMdm9mlN+bgTsMeVIFi7lbwLEHkKaF3fDPxwHUQ4NdvFAPUL5+uOVeyhZz1tWDr07VkOhcyLTPuM/nJ6ZnAL1pG69lvtD+ej+YfWv+P3eTIzOURLjcztYPhfwky/O/rbGBPrYqVK+PO6zrid72/gZ+mwsOtt/z/x3TSSeY7nsTK/zVEM8wXLF8PPpLHKbzhphY0sbJe1v3iZ5ocIxIZPp3OzvMoAeG4X1tZFOCfb2sPy+Kzf2ntlMxu9fOv+a/a0d+G8sdlGfcn3mt804V0Jy8NqP59aSe7DtYoWfXd68GHvSOddDg/4Wz37Ke19TWrC/S8R7f3z4lUe7YC9tSd6jAz5opz3KapjrWT7x+c/zlfUdnfNoa3zfvLMcszNF2FlTTKeoTxRXZs5pWDOfpqRnN9rHFOtL2ktM8nD5jLVMDuz83Yt78uH/AcZ2Sr+C3vx12Xna/AygRsE54t+jMxS4Txf33Rb0WPOxTTGIbFOGH66Oa6K/DwC6J3mri/tK47WQb8r/HgL1GBlRj34UFxXqd8SAsY5DvF+9a+3La2z8mcq9ts/p07QHN8S6fv31yy8//fTn/8GvX9nPv0W//dcv73k98+41L/41nfBvX+j/X/47mTZZ+V9++vz6/Pp3+/opz8N/ywkNZ+H/+uV/AbGjRRk=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































































































































                                                                                                                                                                                                                     $________;
